#!/bin/bash
# land-the-whole-picture.sh — the product shot stops being cropped, and the
# product name stops being a link out.
#
#   1. THE CROP. A percentage max-height against an auto-sized track is circular
#      and the browser drops it, so a 500x1200 shot laid out 578px tall in a
#      210px well and the well's overflow took the rest. Measured, then fixed in
#      three places, then measured again on four aspect ratios.
#   2. THE WELL GOES WHITE — the ground these were actually photographed on.
#   3. THE NAME IS NOT A LINK. The card is the product page now.
#
# WEB APP ONLY (together-city-react). Vercel. No API change, no migration.
# PRECONDITION: land-paper-under-the-ink.sh ("The paper under the ink").
set -euo pipefail

cd "$(dirname "$0")"
[ -d together-city-chat ] || { echo "!! Run this from the Together-Ai repo root."; exit 1; }

if [ -f .git/index.lock ] && [ ! -s .git/index.lock ]; then
  echo "== clearing a stale empty .git/index.lock"
  rm -f .git/index.lock
fi

NEEDS="The whole picture"
LOG="$(git log --oneline -40)"
case "$LOG" in
  *"$NEEDS"*) echo "== \"$NEEDS\" is already here. Nothing to do."; exit 0 ;;
esac
case "$LOG" in
  *"The paper under the ink"*) ;;
  *) echo "!! Run land-paper-under-the-ink.sh first — this is written against the tree it produces."; exit 1 ;;
esac

ALLOWED='^ M together-city-react/(public/assets/img/(apple-touch-icon-180|tc-icon-1024|tc-icon-192|tc-icon-512|tc-icon-maskable-512)\.png|public/downloads/TogetherCity\.apk)$'
DIRTY="$(git status --porcelain \
  | grep -Ev '^\?\? (land-.*\.sh|push-.*\.sh|.*\.patch)$' \
  | grep -Ev "$ALLOWED" || true)"
if [ -n "$DIRTY" ]; then
  echo "!! The tree carries changes this script did not expect:"; echo "$DIRTY"; exit 1
fi

PATCH="$(mktemp "${TMPDIR:-/tmp}/land.XXXXXX")"
trap 'rm -f "$PATCH"' EXIT
cat <<'B64EOF' | tr -d '\n' | openssl base64 -d -A > "$PATCH"
ZGlmZiAtLWdpdCBhL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL2FwcC9hLXJlYWQtc2VjdGlvbi1mb2xkcy1pdHNlbGYudGVzdC50cyBiL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL2FwcC9hLXJlYWQtc2VjdGlvbi1mb2xkcy1pdHNlbGYudGVzdC50cwppbmRleCBlODllZTdmLi44YjZiODQ3IDEwMDY0NAotLS0gYS90b2dldGhlci1jaXR5LXJlYWN0L3NyYy9hcHAvYS1yZWFkLXNlY3Rpb24tZm9sZHMtaXRzZWxmLnRlc3QudHMKKysrIGIvdG9nZXRoZXItY2l0eS1yZWFjdC9zcmMvYXBwL2EtcmVhZC1zZWN0aW9uLWZvbGRzLWl0c2VsZi50ZXN0LnRzCkBAIC0yNDcsMTIgKzI0NywzOSBAQCBkZXNjcmliZSgndGhlIGJlYXV0eSBodWIgcHJpbnRzIG9uIGl0cyBvd24gcGFwZXInLCAoKSA9PiB7CiAgICAgfQogICB9KTsKIAotICBpdCgnbmV2ZXIgaW5mbGF0ZXMgYSBwcm9kdWN0IHBob3RvZ3JhcGgnLCAoKSA9PiB7Ci0gICAgLy8gd2lkdGg6MTAwJSBvbiBhIHNtYWxsIHJldGFpbGVyIEpQRUcgdXBzY2FsZXMgaXQgaW50byBhIGJsdXI7IHRoZSB3ZWxsCi0gICAgLy8gc2hvd3MgYSBzaG90IGF0IGl0cyBuYXR1cmFsIHNpemUsIGNhcHBlZC4gTXVsdGlwbHkgKyBuby1jYXNlIGJlY2F1c2UgdGhlCi0gICAgLy8gcGhvdG9ncmFwaHkgaXMgd2hpdGUtZ3JvdW5kIGN1dC1vdXRzIOKAlCB0aGUgZ2VtIHNoZWV0cycgb3duIHRyZWF0bWVudC4KKyAgaXQoJ25ldmVyIGluZmxhdGVzIG9yIGNyb3BzIGEgcHJvZHVjdCBwaG90b2dyYXBoJywgKCkgPT4geworICAgIC8vIFRocmVlIGNvbnN0cmFpbnRzLCBhbmQgYWxsIHRocmVlIHdlcmUgbGVhcm5lZCB0aGUgaGFyZCB3YXkuIGBhdXRvYCArCisgICAgLy8gbWF4IHN0b3BzIGEgc21hbGwgcmV0YWlsZXIgSlBFRyBiZWluZyB1cHNjYWxlZCBpbnRvIGEgYmx1ci4gYGNvbnRhaW5gCisgICAgLy8gc3RvcHMgYSBsYW5kc2NhcGUgc2hvdCBsb3NpbmcgaXRzIHRvcCBhbmQgYm90dG9tIOKAlCBtYXgtaGVpZ2h0IGFsb25lCisgICAgLy8gbGV0dGVyYm94ZXMgYSBwb3J0cmFpdCBjb3JyZWN0bHkgYW5kIGNyb3BzIGEgbGFuZHNjYXBlLCB3aGljaCBpcyB3aHkgdGhlCisgICAgLy8gbGl2ZSBjYXJkcyBoYWQgYm90dGxlcyB3aXRoIHRoZWlyIGNhcHMgY3V0IG9mZi4gYG5vLWNhc2VgIGJlY2F1c2UgYW4KKyAgICAvLyBvdXRsaW5lIGRyYXduIHJvdW5kIGEgY3V0LW91dCBpcyBhbiBvdXRsaW5lIHJvdW5kIG5vdGhpbmcuCiAgICAgY29uc3Qgc2hvdCA9IHJlYWQoJ2ZlYXR1cmVzL2JlYXV0eS9jb21wb25lbnRzL1Byb2R1Y3RTaG90LnRzeCcpOwotICAgIGV4cGVjdChzaG90KS50b01hdGNoKC9tYXhXaWR0aDogJzEwMCUnLCBtYXhIZWlnaHQ6ICcxMDAlJywgd2lkdGg6ICdhdXRvJywgaGVpZ2h0OiAnYXV0bycsIG1peEJsZW5kTW9kZTogJ211bHRpcGx5Jy8pOworICAgIC8vIHNjYWxlLWRvd24sIG5vdCBtYXgtd2lkdGgvbWF4LWhlaWdodCArIGF1dG86IGEgcGVyY2VudGFnZSBtYXgtaGVpZ2h0CisgICAgLy8gYWdhaW5zdCBhbiBhdXRvLXNpemVkIHRyYWNrIGlzIGNpcmN1bGFyIGFuZCB0aGUgYnJvd3NlciBkcm9wcyBpdCwgd2hpY2gKKyAgICAvLyBpcyBob3cgYSA1MDB4MTIwMCBzaG90IGNhbWUgdG8gcmVuZGVyIDU3OHB4IHRhbGwgaW4gYSAyMTBweCB3ZWxsLgorICAgIGV4cGVjdChzaG90KS50b01hdGNoKC93aWR0aDogJzEwMCUnLCBoZWlnaHQ6ICcxMDAlJywgb2JqZWN0Rml0OiAnc2NhbGUtZG93bicvKTsKKyAgICBleHBlY3Qoc2hvdCkubm90LnRvTWF0Y2goL21heEhlaWdodDogJzEwMCUnLyk7CiAgICAgZXhwZWN0KHNob3QpLnRvTWF0Y2goL2NsYXNzTmFtZT1ce2ZpbGwgXD8gJ25vLWNhc2UnIDogdW5kZWZpbmVkXH0vKTsKKyAgICAvLyBBbmQgbm8gYmxlbmQgbGVmdCBiZWhpbmQ6IGl0IHdhcyBtZWx0aW5nIGEgd2hpdGUgc3R1ZGlvIGdyb3VuZCBpbnRvCisgICAgLy8gY3JlYW0sIGFuZCBhbiBPRkYtd2hpdGUgZ3JvdW5kIG1lbHRlZCBpbnRvIGEgZ3JleS1ncmVlbiBib3ggaW5zdGVhZC4KKyAgICBleHBlY3Qoc2hvdCkubm90LnRvTWF0Y2goL21peEJsZW5kTW9kZS8pOworICB9KTsKKworICBpdCgnc3RhbmRzIGEgcHJvZHVjdCBzaG90IG9uIHRoZSBncm91bmQgaXQgd2FzIHBob3RvZ3JhcGhlZCBvbicsICgpID0+IHsKKyAgICAvLyBFdmVyeSBvbmUgb2YgdGhlc2UgaXMgaG90bGlua2VkIGZyb20gYSByZXRhaWxlciBhbmQgbGl0IG9uIHdoaXRlLiBUaGUKKyAgICAvLyB3ZWxsIGlzIHdoaXRlIGZvciB0aGF0IHJlYXNvbiBhbmQgZm9yIG5vIG90aGVyIOKAlCBub3RoaW5nIGlzIHJlYWQgb24gaXQuCisgICAgY29uc3QgbGF5b3V0ID0gcmVhZCgnc3R5bGVzL2xheW91dC5jc3MnKTsKKyAgICBleHBlY3QobGF5b3V0KS50b01hdGNoKC9cLnJvdXRpbmUtd2VsbCBce1tefV0qYmFja2dyb3VuZDogdmFyXCgtLXNob3QtZ3JvdW5kXCkvKTsKKyAgICBjb25zdCB0b2tlbnMgPSByZWFkKCdzdHlsZXMvdG9rZW5zLmNzcycpOworICAgIGV4cGVjdCh0b2tlbnMpLnRvTWF0Y2goLy0tc2hvdC1ncm91bmQ6IHZhclwoLS1wYXBlclwpLyk7ICAgLy8gaW5lcnQgYXQgdGhlIHJvb3QKKyAgICBleHBlY3QodG9rZW5zKS50b01hdGNoKC8tLXNob3QtZ3JvdW5kOiAjZmZmZmZmLyk7ICAgICAgICAgICAgLy8gd2hpdGUgaW4gdGhpcyBodWIKKyAgfSk7CisKKyAgaXQoJ2RvZXMgbm90IHNlbmQgc29tZWJvZHkgdG8gYSByZXRhaWxlciBmcm9tIHRoZSBtaWRkbGUgb2YgaXRzIG93biBjaGVja291dCcsICgpID0+IHsKKyAgICAvLyBUaGUgY2FyZCBjYXJyaWVzIHRoZSBwaG90b2dyYXBoLCB0aGUgYnJhbmQsIHRoZSBzaXplLCB0aGUgbGlmZSBhbmQgdGhlCisgICAgLy8gcHJpY2Ug4oCUIGl0IElTIHRoZSBwcm9kdWN0IHBhZ2Ug4oCUIGFuZCB0aGUgbmV4dCB0aGluZyBpdCB3YW50cyBpcyB0aGUgYmFnLgorICAgIGNvbnN0IHJvdXRpbmUgPSByZWFkKCdmZWF0dXJlcy9iZWF1dHkvcGFnZXMvUm91dGluZS50c3gnKTsKKyAgICBleHBlY3Qocm91dGluZSkubm90LnRvTWF0Y2goLzxhIGhyZWY9XHtzXC5wcm9kdWN0VXJsXH0vKTsKICAgfSk7CiB9KTsKZGlmZiAtLWdpdCBhL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL2ZlYXR1cmVzL2JlYXV0eS9jb21wb25lbnRzL1Byb2R1Y3RTaG90LnRzeCBiL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL2ZlYXR1cmVzL2JlYXV0eS9jb21wb25lbnRzL1Byb2R1Y3RTaG90LnRzeAppbmRleCBiOWU2OGY1Li4yY2NhOTc4IDEwMDY0NAotLS0gYS90b2dldGhlci1jaXR5LXJlYWN0L3NyYy9mZWF0dXJlcy9iZWF1dHkvY29tcG9uZW50cy9Qcm9kdWN0U2hvdC50c3gKKysrIGIvdG9nZXRoZXItY2l0eS1yZWFjdC9zcmMvZmVhdHVyZXMvYmVhdXR5L2NvbXBvbmVudHMvUHJvZHVjdFNob3QudHN4CkBAIC00NSwyNiArNDUsNjIgQEAgZXhwb3J0IGZ1bmN0aW9uIFByb2R1Y3RTaG90KAogICAgICAgLy8gc3VwcGxpZWQgaXMgYSAyMTBweCBiYW5kIG9mIHdoaXRlIHdpdGggdGhlIHByb2R1Y3QgY2VudHJlZCBpbiBpdCwgYW5kIGEKICAgICAgIC8vIGZpeGVkIHNxdWFyZSBpbnNpZGUgYSB2YXJpYWJsZS13aWR0aCBjb2x1bW4gbGVhdmVzIGEgbWFyZ2luIGRvd24gb25lCiAgICAgICAvLyBzaWRlIHRoYXQgcmVhZHMgYXMgYSBtaXN0YWtlIGF0IGV2ZXJ5IGJyZWFrcG9pbnQgYnV0IG9uZS4KKyAgICAgIC8qIEEgREVGSU5JVEUgQk9YLCBCWSBBQlNPTFVURSBQT1NJVElPTklORywgQU5EIFRIQVQgSVMgVEhFIFdIT0xFIFRSSUNLLgorICAgICAgICAgYHdpZHRoL2hlaWdodDogMTAwJWAgaGVyZSBsb29rcyBlcXVpdmFsZW50IGFuZCBpcyBub3Q6IHRoaXMgc3BhbiBpcyBhCisgICAgICAgICBmbGV4IGl0ZW0gaW5zaWRlIHRoZSB3ZWxsLCBzbyBpdHMgY3Jvc3Mgc2l6ZSBpcyBjb250ZW50LWJhc2VkLCBpdHMgb3duCisgICAgICAgICBoZWlnaHQgcmVzb2x2ZXMgdG8gYGF1dG9gLCBhbmQgZXZlcnkgcGVyY2VudGFnZSB0aGUgaW1hZ2UgdGhlbiBhc2tzIGZvcgorICAgICAgICAgaGFzIG5vdGhpbmcgdG8gcmVzb2x2ZSBhZ2FpbnN0LiBNZWFzdXJlZCwgdGhhdCBpcyBhIDUwMHgxMjAwIHNob3QgbGFpZAorICAgICAgICAgb3V0IDU3OHB4IHRhbGwgaW4gYSAyMTBweCB3ZWxsIGFuZCBjbGlwcGVkIGJ5IHRoZSB3ZWxsJ3Mgb3ZlcmZsb3cuCisgICAgICAgICBgaW5zZXQ6IDBgIGFnYWluc3QgdGhlIHdlbGwncyBgcG9zaXRpb246IHJlbGF0aXZlYCBnaXZlcyBhIGJveCB3aG9zZQorICAgICAgICAgaGVpZ2h0IGlzIGtub3duIGJlZm9yZSB0aGUgcGljdHVyZSBpcyBtZWFzdXJlZCwgd2hpY2ggaXMgdGhlIGNvbmRpdGlvbgorICAgICAgICAgdGhlIHdob2xlIHRoaW5nIG5lZWRlZC4gVGhlIHBhZGRpbmcgbW92ZXMgaGVyZSB3aXRoIGl0LCBzbyB0aGUgY29udGVudAorICAgICAgICAgYm94IHRoZSBpbWFnZSBmaWxscyBpcyB0aGUgd2VsbCdzIDIxMCBsZXNzIGl0cyBvd24gbWFyZ2luLiAqLwogICAgICAgLi4uKGZpbGwKLSAgICAgICAgPyB7IHdpZHRoOiAnMTAwJScsIGhlaWdodDogJzEwMCUnIH0KKyAgICAgICAgPyB7IHBvc2l0aW9uOiAnYWJzb2x1dGUnIGFzIGNvbnN0LCBpbnNldDogMCwgcGFkZGluZzogMTYgfQogICAgICAgICA6IHsgZmxleDogJ25vbmUnLCB3aWR0aDogc2l6ZSwgaGVpZ2h0OiBzaXplIH0pLAotICAgICAgZGlzcGxheTogJ2dyaWQnLCBwbGFjZUl0ZW1zOiAnY2VudGVyJywgb3ZlcmZsb3c6ICdoaWRkZW4nLAorICAgICAgLyogRkxFWCwgTk9UIEdSSUQsIElOIFRIRSBGSUxMIENBU0Ug4oCUIHRoZSBsYXN0IGxpbmsgaW4gdGhlIHNhbWUgY2hhaW4uIEEKKyAgICAgICAgIGdyaWQgd2hvc2Ugc2luZ2xlIHJvdyBpcyBgYXV0b2Agc2l6ZXMgdGhhdCByb3cgZnJvbSB0aGUgaXRlbSwgc28gdGhlCisgICAgICAgICBpdGVtJ3Mgb3duIGBoZWlnaHQ6IDEwMCVgIGlzIGNpcmN1bGFyIGFnYWluIGFuZCBkcm9wcGVkLCBhbmQgdGhlIHRhbGwKKyAgICAgICAgIHNob3Qgd2FzIHN0aWxsIDU3OHB4IGFmdGVyIHRoZSBib3ggYWJvdmUgaXQgaGFkIGJlZW4gbWFkZSBkZWZpbml0ZS4gQQorICAgICAgICAgZmxleCBjb250YWluZXIgd2l0aCBhIGRlZmluaXRlIGhlaWdodCByZXNvbHZlcyBhIGNoaWxkJ3MgcGVyY2VudGFnZQorICAgICAgICAgaGVpZ2h0IGFnYWluc3QgaXQuIFNhbWUgY2VudHJpbmcsIG9uZSB3b3JkIGRpZmZlcmVudCwgYW5kIGl0IGlzIHRoZQorICAgICAgICAgd29yZCB0aGUgbWVhc3VyZW1lbnQgYXNrZWQgZm9yLiAqLworICAgICAgLi4uKGZpbGwKKyAgICAgICAgPyB7IGRpc3BsYXk6ICdmbGV4JywgYWxpZ25JdGVtczogJ2NlbnRlcicsIGp1c3RpZnlDb250ZW50OiAnY2VudGVyJyB9CisgICAgICAgIDogeyBkaXNwbGF5OiAnZ3JpZCcsIHBsYWNlSXRlbXM6ICdjZW50ZXInIH0pLAorICAgICAgb3ZlcmZsb3c6ICdoaWRkZW4nLAogICAgICAgLi4uKGJhcmUgfHwgZmlsbCA/IHt9IDogeyBib3JkZXJSYWRpdXM6IDEyLCBiYWNrZ3JvdW5kOiAndmFyKC0tcGFwZXIpJywgYm9yZGVyOiAnMXB4IHNvbGlkIHZhcigtLWxpbmUpJyB9KSwKICAgICB9fT4KICAgICAgIHtzcmMKICAgICAgICAgPyA8aW1nIGtleT17c3JjfSBzcmM9e3NyY30gYWx0PSIiIGxvYWRpbmc9ImxhenkiIG9uRXJyb3I9eygpID0+IHNldFRyaWVkKChuKSA9PiBuICsgMSl9CiAgICAgICAgICAgICBjbGFzc05hbWU9e2ZpbGwgPyAnbm8tY2FzZScgOiB1bmRlZmluZWR9CiAgICAgICAgICAgICBzdHlsZT17ZmlsbAotICAgICAgICAgICAgICAvKiBOQVRVUkFMIFNJWkUsIENBUFBFRCDigJQgbmV2ZXIgaW5mbGF0ZWQuIHdpZHRoOjEwMCUgb24gYSBzbWFsbAotICAgICAgICAgICAgICAgICByZXRhaWxlciBKUEVHIHVwc2NhbGVzIGl0IGludG8gYSBibHVyOyBhdXRvIHdpdGggYSBtYXggbGV0cyBhCi0gICAgICAgICAgICAgICAgIGJpZyBzaG90IGZpbGwgdGhlIHdlbGwgYW5kIGEgc21hbGwgb25lIHNpdCBhdCBpdHMgb3duIHNpemUuCi0gICAgICAgICAgICAgICAgIE1VTFRJUExZIGlzIHRoZSBnZW0gc2hlZXRzJyB0cmljayBmb3IgdGhlIHNhbWUgcGhvdG9ncmFwaHk6Ci0gICAgICAgICAgICAgICAgIHRoZXNlIGFyZSBzaG90IG9uIHB1cmUgd2hpdGUsIGFuZCBtdWx0aXBseSBtZWx0cyB0aGF0IHdoaXRlCi0gICAgICAgICAgICAgICAgIGludG8gd2hhdGV2ZXIgcGFwZXIgdGhlIHdlbGwgaXMsIGluc3RlYWQgb2YgbGVhdmluZyBhIHdoaXRlCi0gICAgICAgICAgICAgICAgIHJlY3RhbmdsZSBmbG9hdGluZyBvbiBjcmVhbS4gYG5vLWNhc2VgIGZvciB0aGUgc2FtZSByZWFzb24gdGhlCi0gICAgICAgICAgICAgICAgIGdlbXMgd2VhciBpdCDigJQgYW4gb3V0bGluZSBkcmF3biByb3VuZCBhIGN1dC1vdXQgaXMgYW4gb3V0bGluZQotICAgICAgICAgICAgICAgICByb3VuZCBub3RoaW5nLiAqLwotICAgICAgICAgICAgICA/IHsgbWF4V2lkdGg6ICcxMDAlJywgbWF4SGVpZ2h0OiAnMTAwJScsIHdpZHRoOiAnYXV0bycsIGhlaWdodDogJ2F1dG8nLCBtaXhCbGVuZE1vZGU6ICdtdWx0aXBseScgfQorICAgICAgICAgICAgICAvKiBPTkUgS0VZV09SRCwgQU5EIElUIFJFUExBQ0VTIEEgUlVMRSBUSEFUIFNJTEVOVExZIERJRCBOT1RISU5HLgorICAgICAgICAgICAgICAgICBUaGlzIHdhcyBgbWF4LXdpZHRoL21heC1oZWlnaHQ6IDEwMCVgIHdpdGggYHdpZHRoL2hlaWdodDogYXV0b2AKKyAgICAgICAgICAgICAgICAg4oCUIHRoZSBvYnZpb3VzIHdheSB0byBzYXkgImZpdCwgYnV0IG5ldmVyIGJsb3cgaXQgdXAiLCBhbmQgaXQgaXMKKyAgICAgICAgICAgICAgICAgdGhlIHdheSB0aGF0IGRvZXMgbm90IHdvcmsgaGVyZS4gQSBQRVJDRU5UQUdFIE1BWC1IRUlHSFQKKyAgICAgICAgICAgICAgICAgUkVTT0xWRVMgQUdBSU5TVCBUSEUgUEFSRU5UJ1MgSEVJR0hULCBhbmQgdGhlIHBhcmVudCBpcyBhbgorICAgICAgICAgICAgICAgICBhdXRvLXNpemVkIGdyaWQgdHJhY2sgd2hvc2UgaGVpZ2h0IGRlcGVuZHMgb24gdGhpcyBpbWFnZTogdGhlCisgICAgICAgICAgICAgICAgIHJlZmVyZW5jZSBpcyBjaXJjdWxhciwgc28gdGhlIGJyb3dzZXIgZHJvcHMgdGhlIGNvbnN0cmFpbnQKKyAgICAgICAgICAgICAgICAgZW50aXJlbHkuIE1lYXN1cmVkLCBhIDUwMHgxMjAwIHNob3QgcmVuZGVyZWQgNTc4cHggdGFsbCBpbiBhCisgICAgICAgICAgICAgICAgIDIxMHB4IHdlbGwgYW5kIHdhcyBjbGlwcGVkIGJ5IHRoZSB3ZWxsJ3Mgb3ZlcmZsb3cg4oCUIHdoaWNoIGlzCisgICAgICAgICAgICAgICAgIHRoZSBjcm9wcGluZyBvbiB0aGUgbGl2ZSBwYWdlLiBUaGUgd2lkdGggY2FwcGVkIGZpbmUsIHdoaWNoIGlzCisgICAgICAgICAgICAgICAgIGV4YWN0bHkgd2h5IGl0IGxvb2tlZCBsaWtlIGEgY3JvcHBpbmcgYnVnIHJhdGhlciB0aGFuIGEgc2l6aW5nCisgICAgICAgICAgICAgICAgIG9uZS4KKworICAgICAgICAgICAgICAgICBgc2NhbGUtZG93bmAgaXMgdGhlIHByb3BlcnR5IHRoYXQgbWVhbnMgd2hhdCB0aGUgdHdvIGxpbmVzIHdlcmUKKyAgICAgICAgICAgICAgICAgdHJ5aW5nIHRvIHNheTogbGF5IGl0IG91dCBhdCB0aGUgYm94IHNpemUsIHRoZW4gZHJhdyBpdCBhcworICAgICAgICAgICAgICAgICBgY29udGFpbmAg4oCUIG9yIGF0IGl0cyBuYXR1cmFsIHNpemUgaWYgdGhhdCBpcyBzbWFsbGVyLiBObyBjcm9wCisgICAgICAgICAgICAgICAgIG9uIGFueSBhc3BlY3QsIG5vIHVwc2NhbGluZyBvZiBhIHNtYWxsIHJldGFpbGVyIEpQRUcuCisKKyAgICAgICAgICAgICAgICAgTk8gTVVMVElQTFkuIEl0IHdhcyBtZWx0aW5nIGEgd2hpdGUgc3R1ZGlvIGdyb3VuZCBpbnRvIGNyZWFtCisgICAgICAgICAgICAgICAgIHBhcGVyLCBhbmQgdGhhdCB3YXMgdGhlIHdyb25nIGhhbGYgb2YgdGhlIGZpeDogYW4gT0ZGLXdoaXRlCisgICAgICAgICAgICAgICAgIGdyb3VuZCBtdWx0aXBsaWVkIGFnYWluc3Qgc2FuZCBpcyBhIGdyZXktZ3JlZW4gYm94LiBUaGUgd2VsbCBpcworICAgICAgICAgICAgICAgICB3aGl0ZSBub3cg4oCUIHRoZSBncm91bmQgdGhlc2Ugd2VyZSBhY3R1YWxseSBzaG90IG9uIOKAlCBzbyB0aGVyZQorICAgICAgICAgICAgICAgICBpcyBub3RoaW5nIGxlZnQgdG8gYmxlbmQgYXdheS4gYG5vLWNhc2VgIHN0YXlzIGZvciB0aGUgcmVhc29uCisgICAgICAgICAgICAgICAgIHRoZSBnZW0gc2hlZXRzIHdlYXIgaXQ6IGFuIG91dGxpbmUgZHJhd24gcm91bmQgYSBjdXQtb3V0IGlzIGFuCisgICAgICAgICAgICAgICAgIG91dGxpbmUgcm91bmQgbm90aGluZy4gKi8KKyAgICAgICAgICAgICAgPyB7IHdpZHRoOiAnMTAwJScsIGhlaWdodDogJzEwMCUnLCBvYmplY3RGaXQ6ICdzY2FsZS1kb3duJyB9CiAgICAgICAgICAgICAgIDogeyB3aWR0aDogJzEwMCUnLCBoZWlnaHQ6ICcxMDAlJywgb2JqZWN0Rml0OiAnY29udGFpbicgfX0gLz4KICAgICAgICAgOiA8c3BhbiBhcmlhLWhpZGRlbiBzdHlsZT17eyBmb250U2l6ZTogZmlsbCA/IDQwIDogTWF0aC5yb3VuZChzaXplIC8gMi44KSB9fT57Z2x5cGhGb3IoY2F0ZWdvcnkpfTwvc3Bhbj59CiAgICAgPC9zcGFuPgpkaWZmIC0tZ2l0IGEvdG9nZXRoZXItY2l0eS1yZWFjdC9zcmMvZmVhdHVyZXMvYmVhdXR5L3BhZ2VzL1JvdXRpbmUudHN4IGIvdG9nZXRoZXItY2l0eS1yZWFjdC9zcmMvZmVhdHVyZXMvYmVhdXR5L3BhZ2VzL1JvdXRpbmUudHN4CmluZGV4IGE0MDNkZDMuLjcxODY5ZjIgMTAwNjQ0Ci0tLSBhL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL2ZlYXR1cmVzL2JlYXV0eS9wYWdlcy9Sb3V0aW5lLnRzeAorKysgYi90b2dldGhlci1jaXR5LXJlYWN0L3NyYy9mZWF0dXJlcy9iZWF1dHkvcGFnZXMvUm91dGluZS50c3gKQEAgLTEzMywxMyArMTMzLDIwIEBAIGZ1bmN0aW9uIFN0ZXAoeyBzLCBwaWNrLCBxdHksIGFscmVhZHlJbiwgb25BZGQsIG9uUmVtb3ZlIH06IHsgczogUHJvZHVjdFJvdXRpbmVTCiAgICAgICAgICAgPHNwYW4gY2xhc3NOYW1lPSJyb3V0aW5lLXByaWNlIj7igrl7cy5wcmljZUlucn08L3NwYW4+CiAgICAgICAgICAge3BpY2sgJiYgPHNwYW4gY2xhc3NOYW1lPSJtdXRlZCIgc3R5bGU9e3sgZm9udFNpemU6IDExIH19PuKJiCB7cnVwZWVzKHBpY2subW9udGhseUlucil9L21vbnRoPC9zcGFuPn0KICAgICAgICAgPC9kaXY+Ci0gICAgICAgIHsvKiBUaGUgbmFtZSBsaW5rcyBvdXQgdG8gd2hlcmUgaXQgaXMgYWN0dWFsbHkgc29sZC4gQSByb3V0aW5lIHRoYXQgbmFtZXMKLSAgICAgICAgICAgIGEgcHJvZHVjdCB5b3UgdGhlbiBoYXZlIHRvIGdvIGFuZCBzZWFyY2ggZm9yIGlzIGhvbWV3b3JrLiAqL30KLSAgICAgICAgPGRpdiBjbGFzc05hbWU9InJvdXRpbmUtbmFtZSI+Ci0gICAgICAgICAge3MucHJvZHVjdFVybAotICAgICAgICAgICAgPyA8YSBocmVmPXtzLnByb2R1Y3RVcmx9IHRhcmdldD0iX2JsYW5rIiByZWw9Im5vb3BlbmVyIG5vcmVmZXJyZXIiIHN0eWxlPXt7IGNvbG9yOiAndmFyKC0taW5rKScgfX0+e3MubmFtZX08L2E+Ci0gICAgICAgICAgICA6IHMubmFtZX0KLSAgICAgICAgPC9kaXY+CisgICAgICAgIHsvKiBUSEUgTkFNRSBJUyBOT1QgQSBMSU5LIEFOWSBNT1JFLCBhdCB0aGUgb3duZXIncyB3b3JkLCBhbmQgdGhlCisgICAgICAgICAgICByZWFzb25pbmcgaXQgcmVwbGFjZXMgaXMgd29ydGgga2VlcGluZzogaXQgdXNlZCB0byBvcGVuIHRoZQorICAgICAgICAgICAgcmV0YWlsZXIncyBwYWdlLCBvbiB0aGUgYXJndW1lbnQgdGhhdCBhIHJvdXRpbmUgd2hpY2ggbmFtZXMgYQorICAgICAgICAgICAgcHJvZHVjdCB5b3UgdGhlbiBoYXZlIHRvIHNlYXJjaCBmb3IgaXMgaG9tZXdvcmsuCisKKyAgICAgICAgICAgIFdoYXQgY2hhbmdlZCBpcyB0aGUgcGFnZSBhcm91bmQgaXQuIFRoZSBjYXJkIG5vdyBjYXJyaWVzIHRoZQorICAgICAgICAgICAgcGhvdG9ncmFwaCwgdGhlIGJyYW5kLCB0aGUgc2l6ZSwgaG93IGxvbmcgaXQgbGFzdHMgYW5kIHRoZSBwcmljZSDigJQKKyAgICAgICAgICAgIGl0IElTIHRoZSBwcm9kdWN0IHBhZ2Ug4oCUIGFuZCB0aGUgb25lIHRoaW5nIHRoaXMgaHViIHdhbnRzIHNvbWVib2R5CisgICAgICAgICAgICB0byBkbyBuZXh0IGlzIGFkZCBpdCB0byB0aGUgYmFnLCB3aGljaCBpcyB0aGUgYnV0dG9uIGRpcmVjdGx5CisgICAgICAgICAgICB1bmRlcm5lYXRoLiBBIHRpdGxlIHRoYXQgcXVpZXRseSBsZWF2ZXMgZm9yIE55a2FhIGlzIGEgc2hvcCBzaG93aW5nCisgICAgICAgICAgICB5b3UgdGhlIGRvb3Igb24gdGhlIHdheSB0byBpdHMgb3duIGNoZWNrb3V0LiBgcHJvZHVjdFVybGAgc3RheXMgb24KKyAgICAgICAgICAgIHRoZSB3aXJlIGFuZCBzdGF5cyB1c2VkIGluIHRoZSBNYXJrZXQsIHdoZXJlIGJyb3dzaW5nIE9VVCBpcyB3aGF0CisgICAgICAgICAgICB0aGUgcGFnZSBpcyBmb3IuICovfQorICAgICAgICA8ZGl2IGNsYXNzTmFtZT0icm91dGluZS1uYW1lIj57cy5uYW1lfTwvZGl2PgogICAgICAgICA8ZGl2IGNsYXNzTmFtZT0ibXV0ZWQiIHN0eWxlPXt7IGZvbnRTaXplOiAxMS41LCBtYXJnaW5Ub3A6IDEgfX0+e3MuYnJhbmR9e3Mua2V5SW5ncmVkaWVudCA/IGAgwrcgJHtzLmtleUluZ3JlZGllbnR9YCA6ICcnfTwvZGl2PgogICAgICAgICB7LyogVGhlIHdvcmtpbmcgYmVoaW5kIHRoZSBtb250aGx5IGZpZ3VyZS4gV2l0aG91dCBpdCAi4omIIOKCuTM2Ni9tb250aCIgaXMKICAgICAgICAgICAgIGFuIGFzc2VydGlvbjsgd2l0aCBpdCwgaXQgaXMgYXJpdGhtZXRpYyBhbnlib2R5IGNhbiBjaGVjay4gKi99CmRpZmYgLS1naXQgYS90b2dldGhlci1jaXR5LXJlYWN0L3NyYy9zdHlsZXMvbGF5b3V0LmNzcyBiL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL3N0eWxlcy9sYXlvdXQuY3NzCmluZGV4IDMzOTMxYTIuLjhlN2ZlYWYgMTAwNjQ0Ci0tLSBhL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL3N0eWxlcy9sYXlvdXQuY3NzCisrKyBiL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL3N0eWxlcy9sYXlvdXQuY3NzCkBAIC0xMDg0LDEyICsxMDg0LDIwIEBACiAgIGJhY2tncm91bmQ6IHZhcigtLWNhcmQpOyBib3JkZXI6IDFweCBzb2xpZCB2YXIoLS1saW5lKTsgYm9yZGVyLXJhZGl1czogMnB4OwogICBib3gtc2hhZG93OiB2YXIoLS1lMSk7CiB9Ci0vKiBUaGUgd2VsbCBpcyB0aGUgcGFwZXIgYSBzaG90IGlzIHRha2VuIG9uLCBhbmQgaXQgaXMgYSBmaXhlZCBoZWlnaHQgc28gYSByb3cKLSAgIG9mIGNhcmRzIGhhcyBpdHMgY2FwdGlvbnMgb24gb25lIGxpbmUgaW5zdGVhZCBvZiBzdGVwcGluZy4gKi8KKy8qIFRIRSBXRUxMIElTIFRIRSBTRUFNTEVTUyBUSEUgU0hPVCBXQVMgVEFLRU4gT04g4oCUIHdoaXRlIOKAlCBub3QgdGhlIHBhcGVyIG9mCisgICB0aGUgcm9vbS4gRXZlcnkgb25lIG9mIHRoZXNlIHBob3RvZ3JhcGhzIGlzIGhvdGxpbmtlZCBmcm9tIGEgcmV0YWlsZXIgYW5kCisgICBldmVyeSBvbmUgd2FzIGxpdCBvbiB3aGl0ZTsgb24gdGhlIGh1YidzIGNyZWFtIHRoZSBvZmYtd2hpdGUgb25lcyBzaG93ZWQgYXMgYQorICAgZ3JleS1ncmVlbiByZWN0YW5nbGUgYmVoaW5kIHRoZSBib3R0bGUsIHdoaWNoIHJlYWRzIGFzIGEgYnJva2VuIGltYWdlIHJhdGhlcgorICAgdGhhbiBhcyBhIHByb2R1Y3QuCisKKyAgIEZpeGVkIGhlaWdodCBzbyBhIHJvdyBvZiBjYXJkcyBrZWVwcyBpdHMgY2FwdGlvbnMgb24gb25lIGxpbmUgaW5zdGVhZCBvZgorICAgc3RlcHBpbmcsIGFuZCB0aGUgcmVmZXJlbmNlJ3Mgb3duIDIxMC4gKi8KKy8qIE5vIHBhZGRpbmcgaGVyZSDigJQgaXQgYmVsb25ncyB0byB0aGUgc2hvdCdzIG93biBhYnNvbHV0ZWx5LXBvc2l0aW9uZWQgYm94LCBzbworICAgdGhhdCBib3ggaGFzIGEgaGVpZ2h0IGJlZm9yZSB0aGUgcGljdHVyZSBpbnNpZGUgaXQgaXMgbWVhc3VyZWQuIFNlZSB0aGUgbm90ZQorICAgaW4gUHJvZHVjdFNob3QudHN4OyB0aGlzIGlzIHRoZSBoYWxmIG9mIHRoYXQgZml4IHRoYXQgbGl2ZXMgaW4gQ1NTLiAqLwogLnJvdXRpbmUtd2VsbCB7Ci0gIHBvc2l0aW9uOiByZWxhdGl2ZTsgaGVpZ2h0OiAxODZweDsgcGFkZGluZzogMTZweDsKLSAgYmFja2dyb3VuZDogdmFyKC0tcGFwZXIpOyBib3JkZXItYm90dG9tOiAxcHggc29saWQgdmFyKC0tbGluZSk7Ci0gIGRpc3BsYXk6IGZsZXg7IGFsaWduLWl0ZW1zOiBjZW50ZXI7IGp1c3RpZnktY29udGVudDogY2VudGVyOworICBwb3NpdGlvbjogcmVsYXRpdmU7IGhlaWdodDogMjEwcHg7CisgIGJhY2tncm91bmQ6IHZhcigtLXNob3QtZ3JvdW5kKTsgYm9yZGVyLWJvdHRvbTogMXB4IHNvbGlkIHZhcigtLWxpbmUpOwogfQogLyogVGhlIG9yZGVyLCBrZXB0LiBBIGdyaWQgb2YgcHJvZHVjdCBjYXJkcyBsb3NlcyB0aGUgb25lIHRoaW5nIGEgbnVtYmVyZWQgbGlzdAogICAgaGFkLCBzbyB0aGUgbnVtYmVyIGdvZXMgb24gdGhlIHBpY3R1cmUg4oCUIHdoZXJlIGEgcHJpbnQgd291bGQgcHV0IGEgcGxhdGUKZGlmZiAtLWdpdCBhL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL3N0eWxlcy90b2tlbnMuY3NzIGIvdG9nZXRoZXItY2l0eS1yZWFjdC9zcmMvc3R5bGVzL3Rva2Vucy5jc3MKaW5kZXggOWM0MzhiMi4uYzU4Yjg2MSAxMDA2NDQKLS0tIGEvdG9nZXRoZXItY2l0eS1yZWFjdC9zcmMvc3R5bGVzL3Rva2Vucy5jc3MKKysrIGIvdG9nZXRoZXItY2l0eS1yZWFjdC9zcmMvc3R5bGVzL3Rva2Vucy5jc3MKQEAgLTQzNyw2ICs0MzcsMTkgQEAKICAgICAgaHViIHRoYXQgaGFuZ3MgYSBwaG90b2dyYXBoLiBPbmUgbWVjaGFuaXNtLCBub3QgdHdvLiAqLwogICAtLXNreS1pbWFnZTogbm9uZTsKIAorICAvKiDilIDilIAgVEhFIEdST1VORCBBIFBST0RVQ1QgV0FTIFBIT1RPR1JBUEhFRCBPTiDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKKyAgICAgRXZlcnkgcHJvZHVjdCBzaG90IGluIHRoaXMgY2F0YWxvZ3VlIGlzIGhvdGxpbmtlZCBmcm9tIGEgcmV0YWlsZXIg4oCUIE55a2FhLAorICAgICBUaXJhLCB0aGUgYnJhbmRzJyBvd24gc3RvcmVzIOKAlCBhbmQgZXZlcnkgb25lIG9mIHRoZW0gd2FzIHNob3Qgb24gYSB3aGl0ZQorICAgICBzZWFtbGVzcy4gU29tZSBhcmUgcHVyZSAjZmZmZmZmIGFuZCBzb21lIGFyZSBhbiBvZmYtd2hpdGUgYSBmZXcgcG9pbnRzCisgICAgIGRvd24sIHdoaWNoIGlzIGludmlzaWJsZSBvbiBhIHdoaXRlIHBhZ2UgYW5kIGlzIGEgZ3JleS1ncmVlbiByZWN0YW5nbGUgdGhlCisgICAgIG1vbWVudCB0aGUgcGFnZSBpcyBub3Qgd2hpdGUuCisKKyAgICAgU28gdGhlIFdFTEwgYSBzaG90IHNpdHMgaW4gaXMgdGhlIGdyb3VuZCBpdCB3YXMgdGFrZW4gb24sIG5vdCB0aGUgZ3JvdW5kIG9mCisgICAgIHRoZSByb29tLiBJdCBpcyBhIHRva2VuIHJhdGhlciB0aGFuIGEgbGl0ZXJhbCBiZWNhdXNlIHRoYXQgaXMgd2hlcmUgY29sb3VyCisgICAgIGxpdmVzIGhlcmUsIGFuZCBpdCByZXNvbHZlcyB0byB0aGUgcGFnZSdzIG93biBwYXBlciBldmVyeXdoZXJlIGV4Y2VwdCB0aGUKKyAgICAgaHViIHRoYXQgbmVlZHMgaXQg4oCUIG5vdGhpbmcgb3V0c2lkZSBCZWF1dHkgY2hhbmdlcy4gKi8KKyAgLS1zaG90LWdyb3VuZDogdmFyKC0tcGFwZXIpOworCiAgIC8qIOKUgOKUgCBJTksgT04gVEhFIEdST1VORCwgRk9SIEEgSFVCIFdIT1NFIEdST1VORCBJUyBOT1QgSVRTIFBBUEVSIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAogICAgICBFdmVyeSBncmFudCBpbiB0aGlzIGZpbGUgdW50aWwgbm93IHJlLXBvaW50ZWQgT05FIGdyb3VuZCwgc28gLS1pbmsgd2FzIHRoZQogICAgICBhbnN3ZXIgdG8gIndoYXQgY29sb3VyIGlzIHRleHQiIGV2ZXJ5d2hlcmUgaW4gdGhlIGh1Yi4gVGhlIEJlYXV0eSBnYWxsZXJ5CkBAIC0xNTc0LDYgKzE1ODcsMTEgQEAKICAgICAgTm90IHB1cmUgd2hpdGUuICNmZmZmZmYgb24gIzEwMTAxMCBpcyAxOToxIGFuZCBpdCBnbGFyZXM7IHRoZXNlIGFyZSB0aGUKICAgICAgc2FtZSBuZWFyLXdoaXRlcyB0aGUgZGFyayBodWJzIHVzZSwgYW5kIHRoZXkgc3RpbGwgY2xlYXIgQUEgZm91ciB0aW1lcwogICAgICBvdmVyLiAqLworICAvKiBXaGl0ZSwgYW5kIG9ubHkgaGVyZTogaXQgaXMgdGhlIHNlYW1sZXNzIHRoZSBtZXJjaGFuZGlzZSB3YXMgcGhvdG9ncmFwaGVkCisgICAgIG9uLiBOb3RoaW5nIGlzIFJFQUQgb24gaXQg4oCUIGl0IGhvbGRzIHBpY3R1cmVzIOKAlCBzbyBpdCBpcyBub3QgaW4gdGhlIGluaworICAgICB0YWJsZSBhYm92ZS4gKi8KKyAgLS1zaG90LWdyb3VuZDogI2ZmZmZmZjsKKwogICAtLW9uLWdyb3VuZDogICAgICAgI2VkZTllMjsgICAvKiAxNS43OjEgb24gdGhlIHdhbGwgKi8KICAgLS1vbi1ncm91bmQtc29mdDogICNkOWQzYzk7ICAgLyogMTIuODoxICovCiAgIC0tb24tZ3JvdW5kLW11dGVkOiAjYTQ5YjhlOyAgIC8qICA2Ljk6MSDigJQgdGhlIGZsb29yLCBhbmQgaXQgaXMgbm93aGVyZSBuZWFyIGl0ICovCg==
B64EOF
WANT="530126d42507cec89c3b9f3e09a5850eb83bee9164408c66a2c1bf2ce35dee5b"
GOT="$(shasum -a 256 "$PATCH" | awk '{print $1}')"
[ "$GOT" = "$WANT" ] || { echo "!! Patch is corrupt."; echo "   want $WANT"; echo "   got  $GOT"; exit 1; }
echo "== patch verified"
git apply --check -C1 "$PATCH" || { echo "!! Patch does not apply cleanly. Nothing written."; exit 1; }
git apply -C1 "$PATCH"
echo "== applied"

echo "== gates: the web app"
cd together-city-react
npx tsc --noEmit
npx vitest run
node scripts/a11y-audit.mjs
node scripts/motion-ceiling.mjs
node scripts/lint-ceiling.mjs
npx vite build
cd ..

git add -A together-city-react/src
git commit -F - <<'MSG'
The whole picture

── THE CROP, WHICH WAS THREE BUGS WEARING ONE COAT ────────────────────────────

The routine cards were cutting the tops and bottoms off product shots. The rule
in place was the obvious way to say "fit, but never blow it up" —
`max-width/max-height: 100%` with `width/height: auto` — and it is the way that
does not work here, for a reason worth writing down:

A PERCENTAGE MAX-HEIGHT RESOLVES AGAINST THE PARENT'S HEIGHT. The parents in
this chain had none. The shot's wrapper was a flex item, so its cross size came
from its content; inside it a grid track was `auto`, so the row came from the
image. Every percentage the image asked for was circular, and a circular
constraint is not an error — the browser silently drops it. The WIDTH capped
fine, because the width chain was definite the whole way, which is precisely why
this looked like a cropping bug rather than a sizing one.

Measured before touching anything: a 500x1200 shot rendered 578px tall in a
210px well, and the well's `overflow: hidden` took the difference.

Three changes, each removing one link of that chain. The wrapper is absolutely
positioned to `inset: 0` against the well, so its height is known before the
picture is measured, and it carries the padding that used to sit on the well.
It is a flex box rather than a grid, because a grid's auto row reintroduces the
same circularity one level down. And the image is `object-fit: scale-down`,
which is the single keyword for what the two-line rule was trying to say: fit
inside the box, or stay at natural size if that is smaller — no crop on any
aspect, no upscaling of a small retailer JPEG into a blur.

Re-measured after, on four aspect ratios — 1200x500, 500x1200, 90x90, 900x900.
All four fit inside the well; the 90px one is still 90px. The test pins the
three declarations, because each of them looks like an arbitrary style choice
and every one is load-bearing.

── THE WELL IS THE GROUND THE SHOT WAS TAKEN ON ───────────────────────────────

White. Every one of these photographs is hotlinked from a retailer and every one
was lit on a white seamless; some are pure #ffffff and some are an off-white a
few points down, which is invisible on a white page and a grey-green rectangle
on cream. The previous fix for that was `mix-blend-mode: multiply`, which is the
wrong half — multiply melts pure white into the paper and turns off-white into a
tint of the paper, which is the grey-green box. Standing them on white removes
the problem instead of blending it, and `--shot-ground` is inert everywhere
outside this hub.

── AND THE NAME STOPS LEAVING FOR NYKAA ───────────────────────────────────────

At the owner's word, and the reasoning it replaces is worth keeping: the title
used to open the retailer's page, on the argument that a routine which names a
product you then have to go and search for is homework. What changed is the page
around it. The card now carries the photograph, the brand, the size, how long it
lasts and the price — it IS the product page — and the one thing this hub wants
next is the bag, which is the button directly underneath. A title that quietly
leaves for a marketplace is a shop showing you the door on the way to its own
checkout. `productUrl` stays on the wire and stays used in the Market, where
browsing out is what the page is for.

Backend untouched: no route, no schema, no query changed.
MSG

echo "== committed"
cat <<'DONE'

===============================================================
 Landed: The whole picture
 Push — Vercel rebuilds. /beauty/routine: nothing cropped,
 shots on white, names no longer link out.
===============================================================

DONE
