#!/bin/bash
# land-archive-is-not-versioned.sh — the archive stops hiding every letter
# written before the last change to the brief.
#
# THE ARCHIVE SHIPPED EMPTY. Both pages render, both requests succeed, and both
# lists are legitimately empty on an account with a month of letters in it,
# because the history query read through the reading-version prefix and v6 is
# one day old. This is the fix and the test that fails without it.
#
# BACKEND ONLY (together-city-chat). Railway, not Vercel.
set -euo pipefail

cd "$(dirname "$0")"
[ -d together-city-chat ] || { echo "!! Run this from the Together-Ai repo root."; exit 1; }

if [ -f .git/index.lock ] && [ ! -s .git/index.lock ]; then
  echo "== clearing a stale empty .git/index.lock"
  rm -f .git/index.lock
fi

NEEDS="A letter that was sent was sent"
LOG="$(git log --oneline -40)"
case "$LOG" in
  *"$NEEDS"*) echo "== \"$NEEDS\" is already here. Nothing to do."; exit 0 ;;
esac
case "$LOG" in
  *"A month is kept as long as a month is remembered"*) ;;
  *) echo "!! Run land-monthly-history.sh first — this is written against the tree it produces."; exit 1 ;;
esac

ALLOWED='^ M together-city-react/(public/assets/img/(apple-touch-icon-180|tc-icon-1024|tc-icon-192|tc-icon-512|tc-icon-maskable-512)\.png|public/downloads/TogetherCity\.apk)$'
DIRTY="$(git status --porcelain \
  | grep -Ev '^\?\? (land-.*\.sh|push-.*\.sh|.*\.patch)$' \
  | grep -Ev "$ALLOWED" || true)"
if [ -n "$DIRTY" ]; then
  echo "!! The tree carries changes this script did not expect:"; echo "$DIRTY"; exit 1
fi

PATCH="$(mktemp "${TMPDIR:-/tmp}/land.XXXXXX")"
trap 'rm -f "$PATCH"' EXIT
cat <<'B64EOF' | tr -d '\n' | openssl base64 -d -A > "$PATCH"
ZGlmZiAtLWdpdCBhL3RvZ2V0aGVyLWNpdHktY2hhdC9zcmMvYXN0cm9sb2d5L2FzdHJvbG9neS5zZXJ2aWNlLnRzIGIvdG9nZXRoZXItY2l0eS1jaGF0L3NyYy9hc3Ryb2xvZ3kvYXN0cm9sb2d5LnNlcnZpY2UudHMKaW5kZXggNmFmMTczOC4uMjhmZjFhYyAxMDA2NDQKLS0tIGEvdG9nZXRoZXItY2l0eS1jaGF0L3NyYy9hc3Ryb2xvZ3kvYXN0cm9sb2d5LnNlcnZpY2UudHMKKysrIGIvdG9nZXRoZXItY2l0eS1jaGF0L3NyYy9hc3Ryb2xvZ3kvYXN0cm9sb2d5LnNlcnZpY2UudHMKQEAgLTM0NiwyMCArMzQ2LDU0IEBAIGV4cG9ydCBjbGFzcyBBc3Ryb2xvZ3lTZXJ2aWNlIHsKICAgICogYW5kIHN0b3BwaW5nIHRoZSBuZXh0IGxldHRlciBmcm9tIHJlcGVhdGluZyB0aGUgbGFzdCBvbmUuIFRoZSBzZWNvbmQgaXMgd2h5CiAgICAqIHRoaXMgcmVhZHMgdGhlIGJvZGllcyByYXRoZXIgdGhhbiBhIHN1bW1hcnkg4oCUIGxldHRlclByb2JsZW1zKCkgY29tcGFyZXMKICAgICogZml2ZS13b3JkIHJ1bnMsIGFuZCBpdCBjYW4gb25seSBkbyB0aGF0IGFnYWluc3QgdGhlIHJlYWwgdGV4dC4KKyAgICoKKyAgICogSVQgRE9FUyBOT1QgRklMVEVSIEJZIFJFQURJTkdfVkVSLCBBTkQgVEhBVCBJUyBUSEUgUE9JTlQgT0YgVEhJUyBNRVRIT0QuCisgICAqCisgICAqIEl0IHVzZWQgdG86IGBwZXJpb2Q6IHsgc3RhcnRzV2l0aDogJ3Y2OicgfWAuIFRoZSB2ZXJzaW9uIHByZWZpeCBpcyBhIENBQ0hFCisgICAqIGtleSDigJQgaXQgZXhpc3RzIHNvIGEgY2hhbmdlIHRvIHRoZSBicmllZiBkb2VzIG5vdCBsZWF2ZSBldmVyeWJvZHkgcmVhZGluZworICAgKiB5ZXN0ZXJkYXkncyBjYWNoZWQgbGV0dGVyIHVudGlsIHRoZWlyIG93biBtaWRuaWdodC4gUmVhZGluZyBISVNUT1JZIHRocm91Z2gKKyAgICogaXQgbWFkZSBldmVyeSBsZXR0ZXIgd3JpdHRlbiBiZWZvcmUgdGhlIGxhc3QgYnVtcCB2YW5pc2gsIGFuZCB0aGUgZWZmZWN0IGlzCisgICAqIHRvdGFsIHJhdGhlciB0aGFuIHBhcnRpYWw6IHY1IGJlY2FtZSB2NiBvbmUgZXZlbmluZywgYW5kIHRoZSBuZXh0IG1vcm5pbmcKKyAgICogdGhlIGFyY2hpdmUgd2FzIGVtcHR5IG9uIGFuIGFjY291bnQgd2l0aCBhIG1vbnRoIG9mIGxldHRlcnMgYmVoaW5kIGl0LiBUaGF0CisgICAqIGlzIHRoZSBvbmUgdGhpbmcgYW4gYXJjaGl2ZSBtdXN0IG5vdCBkby4KKyAgICoKKyAgICogQSBsZXR0ZXIgdGhhdCB3YXMgc2VudCB3YXMgc2VudC4gSXQgaXMgdGhlaXJzLCBpbiB0aGUgd29yZHMgaXQgd2FzIHdyaXR0ZW4KKyAgICogaW4sIHdoYXRldmVyIGJyaWVmIHdhcyBjdXJyZW50IHRoYXQgZGF5IOKAlCB3aGljaCBpcyBhbHNvIHdoeSBgdGl0bGVgIGlzCisgICAqIG9wdGlvbmFsIHRoZSB3aG9sZSB3YXkgb3V0IHRvIHRoZSBhcGkgdHlwZTogbGV0dGVycyBvbGRlciB0aGFuIHRpdGxlcyBsaXN0CisgICAqIGFzIHRoZWlyIGRhdGUgYW5kIHJlYWQgcGVyZmVjdGx5IHdlbGwuCisgICAqCisgICAqIE9SREVSRUQgQlkgY3JlYXRlZEF0LCBOT1QgQlkgcGVyaW9kLiBPbmNlIHZlcnNpb25zIG1peCwgYHBlcmlvZGAgc29ydHMKKyAgICogYHY2OjIwMjYtMDItMDFgIGFib3ZlIGB2NToyMDI2LTA4LTAxYCDigJQgZXZlcnkgY3VycmVudC12ZXJzaW9uIGxldHRlciBpbiBvbmUKKyAgICogYmxvY2sgYW5kIHRoZSBvbGRlciBvbmVzIHVuZGVybmVhdGgsIHdoaWNoIGlzIG5vdCBhIGNocm9ub2xvZ3kuIFRoZSByb3cgaXMKKyAgICogd3JpdHRlbiBvbiB0aGUgZGF5IHRoZSBsZXR0ZXIgaXMgZm9yLCBzbyBjcmVhdGVkQXQgSVMgdGhhdCBkYXksIGFuZCBpdCBoYXMKKyAgICogYW4gaW5kZXguIFRoZSBmaW5hbCBzb3J0IGlzIG9uIHRoZSBsZXR0ZXIncyBvd24gYGRhdGVgLCB3aGljaCBpcyB0aGUgdmFsdWUKKyAgICogdGhlIGFyY2hpdmUgcHJpbnRzLCBzbyB3aGF0IGlzIHNob3duIGFuZCB3aGF0IGl0IGlzIG9yZGVyZWQgYnkgY2Fubm90IGRyaWZ0CisgICAqIGFwYXJ0LgorICAgKgorICAgKiBBTkQgT05FIFJPVyBQRVIgREFURS4gQSBidW1wIGluIHRoZSBtaWRkbGUgb2YgYSBkYXkgbGVhdmVzIGB2NToyMDI2LTA4LTEwYAorICAgKiBhbmQgYHY2OjIwMjYtMDgtMTBgIGJvdGggb24gZGlzaywgYW5kIGJvdGggYXJlIHJlYWwg4oCUIG9uZSB3YXMgc2VudCwgdGhlbgorICAgKiB0aGUgb3RoZXIgd2FzLiBUaGUgbmV3ZXN0IHdpbnMsIGJlY2F1c2UgaXQgaXMgdGhlIG9uZSB0aGF0IHdhcyBvbiBzY3JlZW4uCisgICAqIFRoZSBvdmVyLWZldGNoIGlzIHdoYXQgbWFrZXMgcm9vbSBmb3IgdGhlIHBhaXJzIHRoYXQgY29sbGFwc2UuCiAgICAqLwogICBwcml2YXRlIGFzeW5jIHJlY2VudExldHRlcnModXNlcklkOiBzdHJpbmcsIGtpbmQ6ICdkYWlseScgfCAnbW9udGhseScsIHRha2U6IG51bWJlcik6IFByb21pc2U8RGF0ZWRMZXR0ZXJbXT4gewogICAgIGNvbnN0IHJvd3MgPSAoYXdhaXQgc3dhbGxvdyh0aGlzLmRiLmFzdHJvUmVhZGluZy5maW5kTWFueSh7Ci0gICAgICB3aGVyZTogeyB1c2VySWQsIGtpbmQsIHBlcmlvZDogeyBzdGFydHNXaXRoOiBgJHtBc3Ryb2xvZ3lTZXJ2aWNlLlJFQURJTkdfVkVSfTpgIH0gfSwKLSAgICAgIG9yZGVyQnk6IHsgcGVyaW9kOiAnZGVzYycgfSwgdGFrZSwKLSAgICB9KSwgYGFzdHJvOiAke2tpbmR9IGhpc3RvcnkgcmVhZGAsIHsgdXNlcklkIH0pKSA/PyAoW10gYXMgQXJyYXk8eyBwZXJpb2Q6IHN0cmluZzsgcmVhZGluZ0pzb246IHN0cmluZyB9Pik7CisgICAgICB3aGVyZTogeyB1c2VySWQsIGtpbmQgfSwKKyAgICAgIG9yZGVyQnk6IHsgY3JlYXRlZEF0OiAnZGVzYycgfSwgdGFrZTogdGFrZSAqIDIsCisgICAgfSksIGBhc3RybzogJHtraW5kfSBoaXN0b3J5IHJlYWRgLCB7IHVzZXJJZCB9KSkgPz8gKFtdIGFzIEFycmF5PHsgcmVhZGluZ0pzb246IHN0cmluZyB9Pik7CiAgICAgY29uc3Qgb3V0OiBEYXRlZExldHRlcltdID0gW107CisgICAgY29uc3Qgc2VlbiA9IG5ldyBTZXQ8c3RyaW5nPigpOwogICAgIGZvciAoY29uc3QgciBvZiByb3dzKSB7CiAgICAgICB0cnkgewogICAgICAgICBjb25zdCBwYXJzZWQgPSBKU09OLnBhcnNlKHIucmVhZGluZ0pzb24pIGFzIERhdGVkTGV0dGVyOwotICAgICAgICBpZiAocGFyc2VkPy5ib2R5KSBvdXQucHVzaChwYXJzZWQpOworICAgICAgICAvLyBBIHJvdyBmcm9tIGJlZm9yZSBsZXR0ZXJzIGV4aXN0ZWQgcGFyc2VzIGZpbmUgYW5kIGhhcyBubyBib2R5LiBUaGVyZQorICAgICAgICAvLyBpcyBub3RoaW5nIGluIGl0IHRvIHNob3cgYW5kIG5vdGhpbmcgdG8ga2VlcCB0aGUgd3JpdGVyIGZyb20KKyAgICAgICAgLy8gcmVwZWF0aW5nLCBzbyBpdCBpcyBub3QgYSBsZXR0ZXIgZm9yIGVpdGhlciBvZiB0aGlzIG1ldGhvZCdzIGpvYnMuCisgICAgICAgIGlmICghcGFyc2VkPy5ib2R5IHx8ICFwYXJzZWQ/LmRhdGUgfHwgc2Vlbi5oYXMocGFyc2VkLmRhdGUpKSBjb250aW51ZTsKKyAgICAgICAgc2Vlbi5hZGQocGFyc2VkLmRhdGUpOworICAgICAgICBvdXQucHVzaChwYXJzZWQpOwogICAgICAgfSBjYXRjaCB7IC8qIGEgcm93IHRoYXQgd2lsbCBub3QgcGFyc2UgaXMgYSByb3cgd2UgY2Fubm90IHNob3cgKi8gfQogICAgIH0KLSAgICByZXR1cm4gb3V0OworICAgIHJldHVybiBvdXQuc29ydCgoYSwgYikgPT4gYi5kYXRlLmxvY2FsZUNvbXBhcmUoYS5kYXRlKSkuc2xpY2UoMCwgdGFrZSk7CiAgIH0KIAogICAvKioKZGlmZiAtLWdpdCBhL3RvZ2V0aGVyLWNpdHktY2hhdC9zcmMvYXN0cm9sb2d5L2xldHRlci1hcmNoaXZlLnNwZWMudHMgYi90b2dldGhlci1jaXR5LWNoYXQvc3JjL2FzdHJvbG9neS9sZXR0ZXItYXJjaGl2ZS5zcGVjLnRzCm5ldyBmaWxlIG1vZGUgMTAwNjQ0CmluZGV4IDAwMDAwMDAuLmRlZDYxMTYKLS0tIC9kZXYvbnVsbAorKysgYi90b2dldGhlci1jaXR5LWNoYXQvc3JjL2FzdHJvbG9neS9sZXR0ZXItYXJjaGl2ZS5zcGVjLnRzCkBAIC0wLDAgKzEsMTIyIEBACitpbXBvcnQgeyBBc3Ryb2xvZ3lTZXJ2aWNlIH0gZnJvbSAnLi9hc3Ryb2xvZ3kuc2VydmljZSc7CisKKy8qKgorICogQW4gYXJjaGl2ZSB0aGF0IGhpZGVzIGxldHRlcnMgaXMgbm90IGFuIGFyY2hpdmUuCisgKgorICogVEhFIERFRkVDVCBUSElTIEZJTEUgRVhJU1RTIEZPUi4gYHJlY2VudExldHRlcnMoKWAgcmVhZCB0aGUgc2F2ZWQgbGV0dGVycworICogdGhyb3VnaCBgcGVyaW9kOiB7IHN0YXJ0c1dpdGg6ICd2NjonIH1gLiBUaGUgdmVyc2lvbiBwcmVmaXggaXMgYSBDQUNIRSBrZXkg4oCUCisgKiBpdCBleGlzdHMgc28gdGhhdCBjaGFuZ2luZyB0aGUgYnJpZWYgZG9lcyBub3QgbGVhdmUgZXZlcnlib2R5IHJlYWRpbmcKKyAqIHllc3RlcmRheSdzIGNhY2hlZCBsZXR0ZXIgdW50aWwgdGhlaXIgb3duIG1pZG5pZ2h0LiBSZWFkaW5nIEhJU1RPUlkgdGhyb3VnaAorICogaXQgbWVhbnQgdGhhdCB0aGUgbW9tZW50IHY1IGJlY2FtZSB2NiwgZXZlcnkgbGV0dGVyIGEgY2l0aXplbiBoYWQgZXZlciBiZWVuCisgKiBzZW50IGRpc2FwcGVhcmVkIGZyb20gdGhlaXIgb3duIGFyY2hpdmUsIG9uIGJvdGggcGFnZXMsIGF0IG9uY2UuIFRoZSBhcmNoaXZlCisgKiBzaGlwcGVkIGFuZCB0aGUgb3duZXIgbG9va2VkIGF0IGFuIGVtcHR5IHBhZ2Ugd2l0aCBhIG1vbnRoIG9mIGxldHRlcnMgYmVoaW5kCisgKiBpdC4KKyAqCisgKiBJdCBpcyB0aGUgd29yc3Qgc2hhcGUgYSBidWcgY2FuIGhhdmU6IHRoZSBwYWdlIHJlbmRlcnMsIHRoZSByZXF1ZXN0IHN1Y2NlZWRzLAorICogdGhlIGxpc3QgaXMgbGVnaXRpbWF0ZWx5IGVtcHR5LCBhbmQgbm90aGluZyBhbnl3aGVyZSByZXBvcnRzIGEgcHJvYmxlbS4gSXQKKyAqIHNob3dzIHVwIG9ubHkgYXMgYW4gYWJzZW5jZSwgYW5kIGl0IHdvdWxkIGNvbWUgYmFjayBhdCB0aGUgbmV4dCBidW1wIHVubGVzcworICogc29tZXRoaW5nIGZhaWxzIGZpcnN0LiBUaGF0IGlzIHdoYXQgdGhlc2UgYXJlLgorICoKKyAqIFRoZXkgZHJpdmUgdGhlIHR3byBwdWJsaWMgaGlzdG9yeSBtZXRob2RzIHJhdGhlciB0aGFuIHRoZSBwcml2YXRlIGhlbHBlciwgc28KKyAqIHRoZXkgYWxzbyBicmVhayBpZiBlaXRoZXIgcGFnZSBpcyBldmVyIHdpcmVkIHRvIHNvbWV0aGluZyBlbHNlLgorICovCisKK2NvbnN0IGxldHRlciA9IChkYXRlOiBzdHJpbmcsIG92ZXI6IFJlY29yZDxzdHJpbmcsIHVua25vd24+ID0ge30pID0+IEpTT04uc3RyaW5naWZ5KHsKKyAgZGF0ZSwgdGl0bGU6ICdBIFRpdGxlIE9mIFRoZSBSaWdodCBMZW5ndGgnLCBzYWx1dGF0aW9uOiAnRGVhciBTb21lbiwnLAorICBib2R5OiBgVGhlIGxldHRlciBmb3IgJHtkYXRlfS5gLCBzaWduT2ZmOiAnV2l0aCBjYXJlLCcsIHdvcmRzOiA1LCAuLi5vdmVyLAorfSk7CisKKy8qKiBgY3JlYXRlZEF0YCBpcyB3aGF0IHRoZSBxdWVyeSBvcmRlcnMgYnksIHNvIHRoZSBmaXh0dXJlcyBjYXJyeSBhIHJlYWwgb25lLiAqLworY29uc3Qgcm93ID0gKHBlcmlvZDogc3RyaW5nLCBkYXRlOiBzdHJpbmcsIG1hZGVBdDogc3RyaW5nLCBqc29uID0gbGV0dGVyKGRhdGUpKSA9PgorICAoeyBwZXJpb2QsIHJlYWRpbmdKc29uOiBqc29uLCBjcmVhdGVkQXQ6IG5ldyBEYXRlKG1hZGVBdCkgfSk7CisKKy8qKgorICogVGhlIGZha2Ugb2JleXMgdGhlIGBvcmRlckJ5YCBpdCBpcyBoYW5kZWQsIGFuZCB0aGUgYHN0YXJ0c1dpdGhgIGlmIHRoZXJlIGlzCisgKiBvbmUuIEEgbW9jayB0aGF0IHF1aWV0bHkgcmV0dXJucyByb3dzIGluIHRoZSBvcmRlciB0aGUgdGVzdCBsaXN0ZWQgdGhlbQorICogY2Fubm90IGZhaWwgb24gYSB3cm9uZyBxdWVyeSDigJQgaXQgd291bGQgYWdyZWUgd2l0aCBhbnkgaW1wbGVtZW50YXRpb24sIHdoaWNoCisgKiBpcyBleGFjdGx5IGhvdyB0aGlzIGRlZmVjdCBzdXJ2aXZlZCBoYXZpbmcgdGVzdHMgYXJvdW5kIGl0LgorICovCitmdW5jdGlvbiBzdmMocm93czogQXJyYXk8eyBwZXJpb2Q6IHN0cmluZzsgcmVhZGluZ0pzb246IHN0cmluZzsgY3JlYXRlZEF0OiBEYXRlIH0+KSB7CisgIGNvbnN0IGFza2VkOiBBcnJheTx7IHdoZXJlOiBSZWNvcmQ8c3RyaW5nLCB1bmtub3duPjsgb3JkZXJCeTogdW5rbm93bjsgdGFrZTogbnVtYmVyIH0+ID0gW107CisgIGNvbnN0IHByaXNtYSA9IHsKKyAgICBhc3Ryb1JlYWRpbmc6IHsKKyAgICAgIGZpbmRNYW55OiAoYTogeyB3aGVyZTogeyBwZXJpb2Q/OiB7IHN0YXJ0c1dpdGg/OiBzdHJpbmcgfSB9OyBvcmRlckJ5OiBSZWNvcmQ8c3RyaW5nLCBzdHJpbmc+OyB0YWtlOiBudW1iZXIgfSkgPT4geworICAgICAgICBhc2tlZC5wdXNoKGEgYXMgbmV2ZXIpOworICAgICAgICBjb25zdCBwcmVmaXggPSBhLndoZXJlLnBlcmlvZD8uc3RhcnRzV2l0aDsKKyAgICAgICAgY29uc3Qga2VwdCA9IHByZWZpeCA/IHJvd3MuZmlsdGVyKChyKSA9PiByLnBlcmlvZC5zdGFydHNXaXRoKHByZWZpeCkpIDogWy4uLnJvd3NdOworICAgICAgICBjb25zdCBieSA9IE9iamVjdC5rZXlzKGEub3JkZXJCeSlbMF07CisgICAgICAgIGtlcHQuc29ydCgoeCwgeSkgPT4gKGJ5ID09PSAncGVyaW9kJworICAgICAgICAgID8geS5wZXJpb2QubG9jYWxlQ29tcGFyZSh4LnBlcmlvZCkKKyAgICAgICAgICA6IHkuY3JlYXRlZEF0LmdldFRpbWUoKSAtIHguY3JlYXRlZEF0LmdldFRpbWUoKSkpOworICAgICAgICByZXR1cm4gUHJvbWlzZS5yZXNvbHZlKGtlcHQuc2xpY2UoMCwgYS50YWtlKSk7CisgICAgICB9LAorICAgIH0sCisgIH07CisgIHJldHVybiB7IHM6IG5ldyBBc3Ryb2xvZ3lTZXJ2aWNlKHByaXNtYSBhcyBuZXZlciwgbnVsbCBhcyBuZXZlciwgbnVsbCBhcyBuZXZlciwgbnVsbCBhcyBuZXZlciksIGFza2VkIH07Cit9CisKK2Rlc2NyaWJlKCd0aGUgbGV0dGVycyBzb21lYm9keSBoYXMgYmVlbiBzZW50JywgKCkgPT4geworICBpdCgnZG9lcyBub3QgZmlsdGVyIHRoZW0gYnkgdGhlIHZlcnNpb24gb2YgdGhlIGJyaWVmIHRoYXQgd3JvdGUgdGhlbScsIGFzeW5jICgpID0+IHsKKyAgICBjb25zdCB7IHMsIGFza2VkIH0gPSBzdmMoWworICAgICAgcm93KCd2NjoyMDI2LTA4LTExJywgJzIwMjYtMDgtMTEnLCAnMjAyNi0wOC0xMVQwNDowMDowMFonKSwKKyAgICAgIHJvdygndjU6MjAyNi0wOC0wOScsICcyMDI2LTA4LTA5JywgJzIwMjYtMDgtMDlUMDQ6MDA6MDBaJyksCisgICAgICByb3coJzIwMjYtMDgtMDcnLCAnMjAyNi0wOC0wNycsICcyMDI2LTA4LTA3VDA0OjAwOjAwWicpLCAvLyBvbGRlciB0aGFuIHRoZSBwcmVmaXggaXRzZWxmCisgICAgXSk7CisgICAgZXhwZWN0KChhd2FpdCBzLmRhaWx5SGlzdG9yeSgndTEnKSkubWFwKChsKSA9PiBsLmRhdGUpKQorICAgICAgLnRvRXF1YWwoWycyMDI2LTA4LTExJywgJzIwMjYtMDgtMDknLCAnMjAyNi0wOC0wNyddKTsKKyAgICAvLyBBc3NlcnRlZCBvbiB0aGUgUVVFUlkgYXMgd2VsbCwgYmVjYXVzZSBhIGBzdGFydHNXaXRoYCBwdXQgYmFjayBoZXJlIHdvdWxkCisgICAgLy8gc3RpbGwgcGFzcyB0aGUgbGluZSBhYm92ZSBvbiBmaXh0dXJlcyB0aGF0IGFsbCBoYXBwZW4gdG8gYmUgY3VycmVudC4KKyAgICBleHBlY3QoYXNrZWRbMF0ud2hlcmUpLnRvRXF1YWwoeyB1c2VySWQ6ICd1MScsIGtpbmQ6ICdkYWlseScgfSk7CisgIH0pOworCisgIGl0KCdvcmRlcnMgYnkgd2hlbiB0aGUgbGV0dGVyIHdhcyB3cml0dGVuLCBub3QgYnkgdGhlIHBlcmlvZCBzdHJpbmcnLCBhc3luYyAoKSA9PiB7CisgICAgLy8gYHBlcmlvZGAgc29ydHMgZXZlcnkgdjYgYWJvdmUgZXZlcnkgdjU6IEZlYnJ1YXJ5IG9mIHRoaXMgdmVyc2lvbiB3b3VsZAorICAgIC8vIHN0YW5kIGFib3ZlIEF1Z3VzdCBvZiB0aGUgbGFzdCBvbmUuCisgICAgY29uc3QgeyBzIH0gPSBzdmMoWworICAgICAgcm93KCd2NjoyMDI2LTAyJywgJzIwMjYtMDInLCAnMjAyNi0wMi0wMVQwNDowMDowMFonKSwKKyAgICAgIHJvdygndjU6MjAyNi0wOCcsICcyMDI2LTA4JywgJzIwMjYtMDgtMDFUMDQ6MDA6MDBaJyksCisgICAgXSk7CisgICAgZXhwZWN0KChhd2FpdCBzLm1vbnRobHlIaXN0b3J5KCd1MScpKS5tYXAoKGwpID0+IGwuZGF0ZSkpLnRvRXF1YWwoWycyMDI2LTA4JywgJzIwMjYtMDInXSk7CisgIH0pOworCisgIGl0KCdzaG93cyBvbmUgbGV0dGVyIHBlciBkYXRlIHdoZW4gYSBidW1wIGxlZnQgdHdvIHJvd3MgZm9yIG9uZSBkYXknLCBhc3luYyAoKSA9PiB7CisgICAgY29uc3QgeyBzIH0gPSBzdmMoWworICAgICAgcm93KCd2NToyMDI2LTA4LTEwJywgJzIwMjYtMDgtMTAnLCAnMjAyNi0wOC0xMFQwMzowMDowMFonLCBsZXR0ZXIoJzIwMjYtMDgtMTAnLCB7IGJvZHk6ICdUaGUgbG9uZyBvbmUuJyB9KSksCisgICAgICByb3coJ3Y2OjIwMjYtMDgtMTAnLCAnMjAyNi0wOC0xMCcsICcyMDI2LTA4LTEwVDIzOjAwOjAwWicsIGxldHRlcignMjAyNi0wOC0xMCcsIHsgYm9keTogJ1RoZSBzaG9ydCBvbmUuJyB9KSksCisgICAgXSk7CisgICAgLy8gQm90aCB3ZXJlIHJlYWxseSBzZW50LiBUaGUgb25lIHRoYXQgd2FzIG9uIHNjcmVlbiBsYXN0IGlzIHRoZSBvbmUga2VwdC4KKyAgICBleHBlY3QoKGF3YWl0IHMuZGFpbHlIaXN0b3J5KCd1MScpKS5tYXAoKGwpID0+IFtsLmRhdGUsIGwuYm9keV0pKQorICAgICAgLnRvRXF1YWwoW1snMjAyNi0wOC0xMCcsICdUaGUgc2hvcnQgb25lLiddXSk7CisgIH0pOworCisgIGl0KCdrZWVwcyBhIGxldHRlciB0aGF0IGhhcyBubyB0aXRsZSwgYmVjYXVzZSBpdCBwcmVkYXRlcyB0aXRsZXMnLCBhc3luYyAoKSA9PiB7CisgICAgY29uc3QgeyBzIH0gPSBzdmMoWworICAgICAgcm93KCd2NToyMDI2LTA4LTAyJywgJzIwMjYtMDgtMDInLCAnMjAyNi0wOC0wMlQwNDowMDowMFonLCBsZXR0ZXIoJzIwMjYtMDgtMDInLCB7IHRpdGxlOiB1bmRlZmluZWQgfSkpLAorICAgIF0pOworICAgIGNvbnN0IG91dCA9IGF3YWl0IHMuZGFpbHlIaXN0b3J5KCd1MScpOworICAgIGV4cGVjdChbb3V0Lmxlbmd0aCwgb3V0WzBdLnRpdGxlLCBvdXRbMF0uYm9keV0pLnRvRXF1YWwoWzEsIHVuZGVmaW5lZCwgJ1RoZSBsZXR0ZXIgZm9yIDIwMjYtMDgtMDIuJ10pOworICB9KTsKKworICBpdCgnZHJvcHMgYSByb3cgdGhhdCBpcyBub3QgYSBsZXR0ZXIgYXQgYWxsLCByYXRoZXIgdGhhbiBsaXN0aW5nIGFuIGVtcHR5IG9uZScsIGFzeW5jICgpID0+IHsKKyAgICBjb25zdCB7IHMgfSA9IHN2YyhbCisgICAgICByb3coJzIwMjYtMDctMzAnLCAnMjAyNi0wNy0zMCcsICcyMDI2LTA3LTMwVDA0OjAwOjAwWicsIEpTT04uc3RyaW5naWZ5KHsgc2VjdGlvbnM6IFtdLCBsdWNreTogeyBudW1iZXI6IDcgfSB9KSksCisgICAgICByb3coJzIwMjYtMDctMjknLCAnMjAyNi0wNy0yOScsICcyMDI2LTA3LTI5VDA0OjAwOjAwWicsICdub3QganNvbiBhdCBhbGwnKSwKKyAgICAgIHJvdygndjY6MjAyNi0wOC0xMScsICcyMDI2LTA4LTExJywgJzIwMjYtMDgtMTFUMDQ6MDA6MDBaJyksCisgICAgXSk7CisgICAgZXhwZWN0KChhd2FpdCBzLmRhaWx5SGlzdG9yeSgndTEnKSkubWFwKChsKSA9PiBsLmRhdGUpKS50b0VxdWFsKFsnMjAyNi0wOC0xMSddKTsKKyAgfSk7CisKKyAgaXQoJ292ZXItZmV0Y2hlcywgc28gYSBjb2xsYXBzZWQgcGFpciBjb3N0cyBhIHJvdyByYXRoZXIgdGhhbiBhIGRheScsIGFzeW5jICgpID0+IHsKKyAgICBjb25zdCB7IHMsIGFza2VkIH0gPSBzdmMoW10pOworICAgIGF3YWl0IHMuZGFpbHlIaXN0b3J5KCd1MScpOworICAgIGF3YWl0IHMubW9udGhseUhpc3RvcnkoJ3UxJyk7CisgICAgLy8gVGhpcnR5IGRheXMgYW5kIHR3ZW50eS1mb3VyIG1vbnRocyBhcmUgdGhlIHByb21pc2VzIHRoZSBwYWdlcyBtYWtlLgorICAgIGV4cGVjdChbYXNrZWRbMF0udGFrZSwgYXNrZWRbMV0udGFrZV0pLnRvRXF1YWwoWzYwLCA0OF0pOworICB9KTsKKworICBpdCgnaXMgYW4gZW1wdHkgbGlzdCwgbm90IGEgZmFpbHVyZSwgd2hlbiB0aGUgdGFibGUgY2Fubm90IGJlIHJlYWQnLCBhc3luYyAoKSA9PiB7CisgICAgY29uc3QgcHJpc21hID0geyBhc3Ryb1JlYWRpbmc6IHsgZmluZE1hbnk6ICgpID0+IFByb21pc2UucmVqZWN0KG5ldyBFcnJvcignbm8gc3VjaCB0YWJsZScpKSB9IH07CisgICAgY29uc3QgcyA9IG5ldyBBc3Ryb2xvZ3lTZXJ2aWNlKHByaXNtYSBhcyBuZXZlciwgbnVsbCBhcyBuZXZlciwgbnVsbCBhcyBuZXZlciwgbnVsbCBhcyBuZXZlcik7CisgICAgZXhwZWN0KGF3YWl0IHMuZGFpbHlIaXN0b3J5KCd1MScpKS50b0VxdWFsKFtdKTsKKyAgfSk7Cit9KTsK
B64EOF
WANT="8481554633f0d0a3b431f0b6aeebc1533b654bb8f7f62d4e00f031c1413d5d30"
GOT="$(shasum -a 256 "$PATCH" | awk '{print $1}')"
[ "$GOT" = "$WANT" ] || { echo "!! Patch is corrupt."; echo "   want $WANT"; echo "   got  $GOT"; exit 1; }
echo "== patch verified"
git apply --check -C1 "$PATCH" || { echo "!! Patch does not apply cleanly. Nothing written."; exit 1; }
git apply -C1 "$PATCH"
echo "== applied"

cd together-city-chat
npx tsc --noEmit
# JEST, NOT VITEST. This backend runs jest; the react app is the vitest one.
npx jest src/astrology
cd ..

git add together-city-chat/src/astrology/astrology.service.ts \
        together-city-chat/src/astrology/letter-archive.spec.ts
git commit -F - <<'MSG'
A letter that was sent was sent

The archive shipped this morning and it was empty. Not broken — empty. Both
pages rendered, both requests succeeded, both lists were correctly zero-length
on an account with a month of letters behind it, and nothing anywhere reported
a problem.

THE HISTORY QUERY WAS READING THROUGH A CACHE KEY. `recentLetters()` filtered
on `period: { startsWith: 'v6:' }`. That prefix exists for one reason: when the
brief changes, a cached letter written to the old brief must not keep being
served until midnight. It is about WHAT TO WRITE NEXT. Using it to decide what
somebody is allowed to see means that the instant v5 became v6 — last night —
every letter this city had ever sent stopped existing as far as its owner was
concerned. Monthly was total: exactly one v6 monthly letter exists, this
month's, and the page filters out the one it is already showing.

So the version comes out of the read. A letter that was sent was sent. It is
theirs, in the words it was written in, whatever brief was current that day.
The api type has said so since the archive was designed — `title` is optional
precisely because letters older than titles are still letters — and the row in
the list already degrades to the date alone.

ORDERED BY createdAt NOW, NOT BY period. This is not tidying; it is what makes
mixing versions safe. `period` sorts `v6:2026-02` above `v5:2026-08`, so
February of this version would stand above August of the last one — every
current letter in one block with the older ones underneath, which is not a
chronology at all. The row is written on the day its letter is for, so
createdAt IS that day, and `@@index([userId, kind, createdAt])` already exists
for it. The final sort is on the letter's own `date`, which is the value the
page prints, so what is shown and what it is ordered by cannot drift apart.

ONE ROW PER DATE, because last night produced pairs. A bump mid-day leaves
`v5:2026-08-10` and `v6:2026-08-10` both on disk and both real — one was sent,
then the other was. The newest wins, since it is the one that was on screen.
The query over-fetches 2× so that a collapsed pair costs a row rather than a
day.

Rows that predate letters entirely — the sectioned readings, with `lucky` and
`theme` and no `body` — were already dropped by the parse guard and still are.
That guard is why removing the version filter does not surface eleven-section
horoscopes in a list of letters.

THE TEST FILE IS THE REAL DELIVERABLE HERE. This defect has the worst shape a
defect can have: no error, no log line, no failing request — an absence, which
looks exactly like a citizen who has no history yet. It would have come back at
the next bump. letter-archive.spec.ts drives the two public history methods and
fails on four counts against the code as it was.

Its fake obeys the `orderBy` and the `startsWith` it is handed, and that is
deliberate: a mock that returns rows in the order the test happened to list
them agrees with every implementation, which is how a query bug survives having
tests around it.

tsc clean, the astrology jest suite green — fourteen spec files, 146 tests.

MSG
echo "== committed"

echo
echo "==============================================================="
echo " Landed: $NEEDS"
echo " The archive shows every letter, not just this version's."
echo " Railway. Push, wait for the API to redeploy, then reload."
echo "==============================================================="
