#!/bin/bash
# land-routine-cards.sh — the routine step becomes the owner's catalogue card.
#
# THIS IS THE HALF OF land-gallery-wall.sh THAT NEVER LANDED, AND WHY. That
# script was rebuilt with the routine cards inside it but kept its commit name,
# and its own already-done check keys on the name — so on a machine that had
# already run the earlier build it said "nothing to do" and exited. The wall,
# the budget removal and the bag fix are live; the cards are not. This script
# is only the cards, under a name of its own.
#
# WEB APP ONLY (together-city-react). Vercel. No API change, no migration.
# PRECONDITION: land-gallery-wall.sh ("Prints on a dark wall").
set -euo pipefail

cd "$(dirname "$0")"
[ -d together-city-chat ] || { echo "!! Run this from the Together-Ai repo root."; exit 1; }

if [ -f .git/index.lock ] && [ ! -s .git/index.lock ]; then
  echo "== clearing a stale empty .git/index.lock"
  rm -f .git/index.lock
fi

NEEDS="The photograph is the identifier"
LOG="$(git log --oneline -40)"
case "$LOG" in
  *"$NEEDS"*) echo "== \"$NEEDS\" is already here. Nothing to do."; exit 0 ;;
esac
case "$LOG" in
  *"Prints on a dark wall"*) ;;
  *) echo "!! Run land-gallery-wall.sh first — this is written against the tree it produces."; exit 1 ;;
esac

ALLOWED='^ M together-city-react/(public/assets/img/(apple-touch-icon-180|tc-icon-1024|tc-icon-192|tc-icon-512|tc-icon-maskable-512)\.png|public/downloads/TogetherCity\.apk)$'
DIRTY="$(git status --porcelain \
  | grep -Ev '^\?\? (land-.*\.sh|push-.*\.sh|.*\.patch)$' \
  | grep -Ev "$ALLOWED" || true)"
if [ -n "$DIRTY" ]; then
  echo "!! The tree carries changes this script did not expect:"; echo "$DIRTY"; exit 1
fi

PATCH="$(mktemp "${TMPDIR:-/tmp}/land.XXXXXX")"
trap 'rm -f "$PATCH"' EXIT
cat <<'B64EOF' | tr -d '\n' | openssl base64 -d -A > "$PATCH"
ZGlmZiAtLWdpdCBhL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL2ZlYXR1cmVzL2JlYXV0eS9jb21wb25lbnRzL1Byb2R1Y3RTaG90LnRzeCBiL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL2ZlYXR1cmVzL2JlYXV0eS9jb21wb25lbnRzL1Byb2R1Y3RTaG90LnRzeAppbmRleCAwM2ZiOWY2Li4yZjE3Yjk5IDEwMDY0NAotLS0gYS90b2dldGhlci1jaXR5LXJlYWN0L3NyYy9mZWF0dXJlcy9iZWF1dHkvY29tcG9uZW50cy9Qcm9kdWN0U2hvdC50c3gKKysrIGIvdG9nZXRoZXItY2l0eS1yZWFjdC9zcmMvZmVhdHVyZXMvYmVhdXR5L2NvbXBvbmVudHMvUHJvZHVjdFNob3QudHN4CkBAIC0yOSw4ICsyOSw4IEBAIGNvbnN0IEdMWVBIOiBBcnJheTxbUmVnRXhwLCBzdHJpbmddPiA9IFsKIGV4cG9ydCBjb25zdCBnbHlwaEZvciA9IChjYXRlZ29yeTogc3RyaW5nKSA9PiBHTFlQSC5maW5kKChbbV0pID0+IG0udGVzdChjYXRlZ29yeSkpPy5bMV0gPz8gJ/Cfp7QnOwogCiBleHBvcnQgZnVuY3Rpb24gUHJvZHVjdFNob3QoCi0gIHsgaW1hZ2UsIGltYWdlQWx0LCBjYXRlZ29yeSwgc2l6ZSA9IDYyLCBiYXJlID0gZmFsc2UgfToKLSAgeyBpbWFnZT86IHN0cmluZzsgaW1hZ2VBbHQ/OiBzdHJpbmc7IGNhdGVnb3J5OiBzdHJpbmc7IHNpemU/OiBudW1iZXI7IGJhcmU/OiBib29sZWFuIH0sCisgIHsgaW1hZ2UsIGltYWdlQWx0LCBjYXRlZ29yeSwgc2l6ZSA9IDYyLCBiYXJlID0gZmFsc2UsIGZpbGwgPSBmYWxzZSB9OgorICB7IGltYWdlPzogc3RyaW5nOyBpbWFnZUFsdD86IHN0cmluZzsgY2F0ZWdvcnk6IHN0cmluZzsgc2l6ZT86IG51bWJlcjsgYmFyZT86IGJvb2xlYW47IGZpbGw/OiBib29sZWFuIH0sCiApIHsKICAgY29uc3Qgc291cmNlcyA9IFtpbWFnZSwgaW1hZ2VBbHRdLmZpbHRlcihCb29sZWFuKSBhcyBzdHJpbmdbXTsKICAgY29uc3QgW3RyaWVkLCBzZXRUcmllZF0gPSB1c2VTdGF0ZSgwKTsKQEAgLTQwLDEzICs0MCwyMSBAQCBleHBvcnQgZnVuY3Rpb24gUHJvZHVjdFNob3QoCiAgIC8vIHZlcnNpb24gaXMgdGhlIHNtYWxsIG9uZSB0aGF0IHNpdHMgaW4gYSByb3cgYmVzaWRlIHRleHQuCiAgIHJldHVybiAoCiAgICAgPHNwYW4gc3R5bGU9e3sKLSAgICAgIGZsZXg6ICdub25lJywgd2lkdGg6IHNpemUsIGhlaWdodDogc2l6ZSwgZGlzcGxheTogJ2dyaWQnLCBwbGFjZUl0ZW1zOiAnY2VudGVyJywgb3ZlcmZsb3c6ICdoaWRkZW4nLAotICAgICAgLi4uKGJhcmUgPyB7fSA6IHsgYm9yZGVyUmFkaXVzOiAxMiwgYmFja2dyb3VuZDogJ3ZhcigtLXBhcGVyKScsIGJvcmRlcjogJzFweCBzb2xpZCB2YXIoLS1saW5lKScgfSksCisgICAgICAvLyBgZmlsbGAgaXMgdGhlIHJvdXRpbmUgY2FyZCdzIHdlbGw6IHRoZSBwaWN0dXJlIHRha2VzIHRoZSB3aG9sZSBwYW5lbCBpdAorICAgICAgLy8gaXMgZ2l2ZW4gcmF0aGVyIHRoYW4gYSBzcXVhcmUgb2YgYSBzdGF0ZWQgc2l6ZS4gVGhlIHJlZmVyZW5jZSB0aGUgb3duZXIKKyAgICAgIC8vIHN1cHBsaWVkIGlzIGEgMjEwcHggYmFuZCBvZiB3aGl0ZSB3aXRoIHRoZSBwcm9kdWN0IGNlbnRyZWQgaW4gaXQsIGFuZCBhCisgICAgICAvLyBmaXhlZCBzcXVhcmUgaW5zaWRlIGEgdmFyaWFibGUtd2lkdGggY29sdW1uIGxlYXZlcyBhIG1hcmdpbiBkb3duIG9uZQorICAgICAgLy8gc2lkZSB0aGF0IHJlYWRzIGFzIGEgbWlzdGFrZSBhdCBldmVyeSBicmVha3BvaW50IGJ1dCBvbmUuCisgICAgICAuLi4oZmlsbAorICAgICAgICA/IHsgd2lkdGg6ICcxMDAlJywgaGVpZ2h0OiAnMTAwJScgfQorICAgICAgICA6IHsgZmxleDogJ25vbmUnLCB3aWR0aDogc2l6ZSwgaGVpZ2h0OiBzaXplIH0pLAorICAgICAgZGlzcGxheTogJ2dyaWQnLCBwbGFjZUl0ZW1zOiAnY2VudGVyJywgb3ZlcmZsb3c6ICdoaWRkZW4nLAorICAgICAgLi4uKGJhcmUgfHwgZmlsbCA/IHt9IDogeyBib3JkZXJSYWRpdXM6IDEyLCBiYWNrZ3JvdW5kOiAndmFyKC0tcGFwZXIpJywgYm9yZGVyOiAnMXB4IHNvbGlkIHZhcigtLWxpbmUpJyB9KSwKICAgICB9fT4KICAgICAgIHtzcmMKICAgICAgICAgPyA8aW1nIGtleT17c3JjfSBzcmM9e3NyY30gYWx0PSIiIGxvYWRpbmc9ImxhenkiIG9uRXJyb3I9eygpID0+IHNldFRyaWVkKChuKSA9PiBuICsgMSl9CiAgICAgICAgICAgICBzdHlsZT17eyB3aWR0aDogJzEwMCUnLCBoZWlnaHQ6ICcxMDAlJywgb2JqZWN0Rml0OiAnY29udGFpbicgfX0gLz4KLSAgICAgICAgOiA8c3BhbiBhcmlhLWhpZGRlbiBzdHlsZT17eyBmb250U2l6ZTogTWF0aC5yb3VuZChzaXplIC8gMi44KSB9fT57Z2x5cGhGb3IoY2F0ZWdvcnkpfTwvc3Bhbj59CisgICAgICAgIDogPHNwYW4gYXJpYS1oaWRkZW4gc3R5bGU9e3sgZm9udFNpemU6IGZpbGwgPyA0MCA6IE1hdGgucm91bmQoc2l6ZSAvIDIuOCkgfX0+e2dseXBoRm9yKGNhdGVnb3J5KX08L3NwYW4+fQogICAgIDwvc3Bhbj4KICAgKTsKIH0KZGlmZiAtLWdpdCBhL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL2ZlYXR1cmVzL2JlYXV0eS9wYWdlcy9Sb3V0aW5lLnRzeCBiL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL2ZlYXR1cmVzL2JlYXV0eS9wYWdlcy9Sb3V0aW5lLnRzeAppbmRleCAyMzk4NWIzLi5hNDAzZGQzIDEwMDY0NAotLS0gYS90b2dldGhlci1jaXR5LXJlYWN0L3NyYy9mZWF0dXJlcy9iZWF1dHkvcGFnZXMvUm91dGluZS50c3gKKysrIGIvdG9nZXRoZXItY2l0eS1yZWFjdC9zcmMvZmVhdHVyZXMvYmVhdXR5L3BhZ2VzL1JvdXRpbmUudHN4CkBAIC05OSwxNyArOTksMjAgQEAgY29uc3QgVElFUl9MQUJFTDogUmVjb3JkPFJvdXRpbmVUaWVyLCBzdHJpbmc+ID0gewogICovCiBmdW5jdGlvbiBTdGVwKHsgcywgcGljaywgcXR5LCBhbHJlYWR5SW4sIG9uQWRkLCBvblJlbW92ZSB9OiB7IHM6IFByb2R1Y3RSb3V0aW5lU3RlcDsgcGljaz86IFJvdXRpbmVQaWNrOyBxdHk6IG51bWJlcjsgYWxyZWFkeUluPzogc3RyaW5nOyBvbkFkZDogKCkgPT4gdm9pZDsgb25SZW1vdmU6ICgpID0+IHZvaWQgfSkgewogICByZXR1cm4gKAotICAgIDxsaSBzdHlsZT17eyBkaXNwbGF5OiAnZmxleCcsIGdhcDogMTMsIHBhZGRpbmc6ICcxNXB4IDAnLCBib3JkZXJUb3A6ICcxcHggc29saWQgdmFyKC0tbGluZSknIH19PgotICAgICAgPHNwYW4gYXJpYS1oaWRkZW4KLSAgICAgICAgc3R5bGU9e3sgZmxleDogJ25vbmUnLCB3aWR0aDogMjYsIGhlaWdodDogMjYsIGJvcmRlclJhZGl1czogJzUwJScsIGRpc3BsYXk6ICdncmlkJywgcGxhY2VJdGVtczogJ2NlbnRlcicsCi0gICAgICAgICAgYmFja2dyb3VuZDogJ3ZhcigtLWFjY2VudC1zb2Z0KScsIGNvbG9yOiAndmFyKC0tYWNjZW50LWluayknLCBmb250U2l6ZTogMTIsIGZvbnRXZWlnaHQ6IDgwMCB9fT4KLSAgICAgICAge3Mub3JkZXJ9Ci0gICAgICA8L3NwYW4+Ci0KLSAgICAgIDxQcm9kdWN0U2hvdCBpbWFnZT17cy5pbWFnZX0gaW1hZ2VBbHQ9e3MuaW1hZ2VBbHR9IGNhdGVnb3J5PXtzLmNhdGVnb3J5fSBzaXplPXs2Mn0gLz4KKyAgICA8bGkgY2xhc3NOYW1lPSJyb3V0aW5lLWNhcmQiPgorICAgICAgey8qIFRIRSBQSUNUVVJFIEZJUlNULCBBTkQgQklHLiBUaGUgb3duZXIncyBjYXRhbG9ndWUgc2hlZXQgaXMgYSB3ZWxsIG9mCisgICAgICAgICAgcGFwZXIgd2l0aCB0aGUgcHJvZHVjdCBwaG90b2dyYXBoZWQgaW4gaXQgYW5kIGV2ZXJ5dGhpbmcgZWxzZSB3cml0dGVuCisgICAgICAgICAgdW5kZXJuZWF0aCwgYW5kIG9uIGEgcGFnZSB3aG9zZSBqb2IgaXMgImdvIGFuZCBidXkgdGhlc2UgZWlnaHQgdGhpbmdzIgorICAgICAgICAgIHRoZSBwaG90b2dyYXBoIGlzIHRoZSBpZGVudGlmaWVyIOKAlCBpdCBpcyB3aGF0IHNvbWVib2R5IG1hdGNoZXMgYWdhaW5zdAorICAgICAgICAgIGEgc2hlbGYuIEF0IDYyIHNxdWFyZSBpdCB0b2xkIHlvdSBhIGJvdHRsZSBmcm9tIGEgdHViZSBhbmQgbm90aGluZworICAgICAgICAgIGVsc2UuIEV2ZXJ5IGZhY3QgdGhlIG9sZCByb3cgY2FycmllZCBpcyBzdGlsbCBoZXJlLCBiZWxvdy4gKi99CisgICAgICA8ZGl2IGNsYXNzTmFtZT0icm91dGluZS13ZWxsIj4KKyAgICAgICAgPHNwYW4gYXJpYS1oaWRkZW4gY2xhc3NOYW1lPSJyb3V0aW5lLW51bSI+e3Mub3JkZXJ9PC9zcGFuPgorICAgICAgICA8UHJvZHVjdFNob3QgaW1hZ2U9e3MuaW1hZ2V9IGltYWdlQWx0PXtzLmltYWdlQWx0fSBjYXRlZ29yeT17cy5jYXRlZ29yeX0gZmlsbCAvPgorICAgICAgPC9kaXY+CiAKLSAgICAgIDxkaXYgc3R5bGU9e3sgZmxleDogMSwgbWluV2lkdGg6IDAgfX0+Ci0gICAgICAgIDxkaXYgc3R5bGU9e3sgZGlzcGxheTogJ2ZsZXgnLCBhbGlnbkl0ZW1zOiAnYmFzZWxpbmUnLCBnYXA6IDgsIGZsZXhXcmFwOiAnd3JhcCcgfX0+CisgICAgICA8ZGl2IGNsYXNzTmFtZT0icm91dGluZS1ib2R5Ij4KKyAgICAgICAgPGRpdiBjbGFzc05hbWU9InJvdXRpbmUtdG9wIj4KICAgICAgICAgICA8c3BhbiBjbGFzc05hbWU9Im11dGVkIiBzdHlsZT17eyBmb250U2l6ZTogMTAsIGZvbnRXZWlnaHQ6IDgwMCwgdGV4dFRyYW5zZm9ybTogJ3VwcGVyY2FzZScsIGxldHRlclNwYWNpbmc6ICcuMDdlbScgfX0+e3Muc3RlcH08L3NwYW4+CiAgICAgICAgICAgey8qIFdIWSBUSElTIFNURVAgSVMgSEVSRSwgaW4gb25lIHdvcmQuIFRoZSBwbGFuIHNvcnRzIGV2ZXJ5dGhpbmcgaW50bwogICAgICAgICAgICAgICB0aHJlZSB0aWVycyBhbmQgYWN0cyBvbiB0aGVtIOKAlCBlc3NlbnRpYWxzIGdvIGluIGZpcnN0IGFuZCBhcmUgbmV2ZXIKQEAgLTEyNCwyMSArMTI3LDE4IEBAIGZ1bmN0aW9uIFN0ZXAoeyBzLCBwaWNrLCBxdHksIGFscmVhZHlJbiwgb25BZGQsIG9uUmVtb3ZlIH06IHsgczogUHJvZHVjdFJvdXRpbmVTCiAgICAgICAgICAgICAgIHtUSUVSX0xBQkVMW3BpY2sudGllcl19CiAgICAgICAgICAgICA8L3NwYW4+CiAgICAgICAgICAgKX0KLSAgICAgICAgICA8c3BhbiBzdHlsZT17eyBtYXJnaW5MZWZ0OiAnYXV0bycsIHRleHRBbGlnbjogJ3JpZ2h0JyB9fT4KLSAgICAgICAgICAgIDxzcGFuIHN0eWxlPXt7IGZvbnRTaXplOiAxMy41LCBjb2xvcjogJ3ZhcigtLWluayknLCBmb250V2VpZ2h0OiA3MDAgfX0+4oK5e3MucHJpY2VJbnJ9PC9zcGFuPgotICAgICAgICAgICAge3BpY2sgJiYgKAotICAgICAgICAgICAgICA8c3BhbiBjbGFzc05hbWU9Im11dGVkIiBzdHlsZT17eyBkaXNwbGF5OiAnYmxvY2snLCBmb250U2l6ZTogMTEsIG1hcmdpblRvcDogMSB9fT4KLSAgICAgICAgICAgICAgICDiiYgge3J1cGVlcyhwaWNrLm1vbnRobHlJbnIpfS9tb250aAotICAgICAgICAgICAgICA8L3NwYW4+Ci0gICAgICAgICAgICApfQotICAgICAgICAgIDwvc3Bhbj4KKyAgICAgICAgPC9kaXY+CisKKyAgICAgICAgPGRpdiBzdHlsZT17eyBkaXNwbGF5OiAnZmxleCcsIGFsaWduSXRlbXM6ICdiYXNlbGluZScsIGdhcDogOCwgZmxleFdyYXA6ICd3cmFwJyB9fT4KKyAgICAgICAgICA8c3BhbiBjbGFzc05hbWU9InJvdXRpbmUtcHJpY2UiPuKCuXtzLnByaWNlSW5yfTwvc3Bhbj4KKyAgICAgICAgICB7cGljayAmJiA8c3BhbiBjbGFzc05hbWU9Im11dGVkIiBzdHlsZT17eyBmb250U2l6ZTogMTEgfX0+4omIIHtydXBlZXMocGljay5tb250aGx5SW5yKX0vbW9udGg8L3NwYW4+fQogICAgICAgICA8L2Rpdj4KICAgICAgICAgey8qIFRoZSBuYW1lIGxpbmtzIG91dCB0byB3aGVyZSBpdCBpcyBhY3R1YWxseSBzb2xkLiBBIHJvdXRpbmUgdGhhdCBuYW1lcwogICAgICAgICAgICAgYSBwcm9kdWN0IHlvdSB0aGVuIGhhdmUgdG8gZ28gYW5kIHNlYXJjaCBmb3IgaXMgaG9tZXdvcmsuICovfQotICAgICAgICA8ZGl2IHN0eWxlPXt7IG1hcmdpblRvcDogMSB9fT4KKyAgICAgICAgPGRpdiBjbGFzc05hbWU9InJvdXRpbmUtbmFtZSI+CiAgICAgICAgICAge3MucHJvZHVjdFVybAotICAgICAgICAgICAgPyA8YSBocmVmPXtzLnByb2R1Y3RVcmx9IHRhcmdldD0iX2JsYW5rIiByZWw9Im5vb3BlbmVyIG5vcmVmZXJyZXIiIHN0eWxlPXt7IGZvbnRTaXplOiAxNCwgZm9udFdlaWdodDogNzAwLCBjb2xvcjogJ3ZhcigtLWluayknIH19PntzLm5hbWV9PC9hPgotICAgICAgICAgICAgOiA8c3Ryb25nIHN0eWxlPXt7IGZvbnRTaXplOiAxNCB9fT57cy5uYW1lfTwvc3Ryb25nPn0KKyAgICAgICAgICAgID8gPGEgaHJlZj17cy5wcm9kdWN0VXJsfSB0YXJnZXQ9Il9ibGFuayIgcmVsPSJub29wZW5lciBub3JlZmVycmVyIiBzdHlsZT17eyBjb2xvcjogJ3ZhcigtLWluayknIH19PntzLm5hbWV9PC9hPgorICAgICAgICAgICAgOiBzLm5hbWV9CiAgICAgICAgIDwvZGl2PgogICAgICAgICA8ZGl2IGNsYXNzTmFtZT0ibXV0ZWQiIHN0eWxlPXt7IGZvbnRTaXplOiAxMS41LCBtYXJnaW5Ub3A6IDEgfX0+e3MuYnJhbmR9e3Mua2V5SW5ncmVkaWVudCA/IGAgwrcgJHtzLmtleUluZ3JlZGllbnR9YCA6ICcnfTwvZGl2PgogICAgICAgICB7LyogVGhlIHdvcmtpbmcgYmVoaW5kIHRoZSBtb250aGx5IGZpZ3VyZS4gV2l0aG91dCBpdCAi4omIIOKCuTM2Ni9tb250aCIgaXMKQEAgLTE1OSw3ICsxNTksNyBAQCBmdW5jdGlvbiBTdGVwKHsgcywgcGljaywgcXR5LCBhbHJlYWR5SW4sIG9uQWRkLCBvblJlbW92ZSB9OiB7IHM6IFByb2R1Y3RSb3V0aW5lUwogICAgICAgICAgIDwvdWw+CiAgICAgICAgICl9CiAKLSAgICAgICAgPGRpdiBzdHlsZT17eyBtYXJnaW5Ub3A6IDkgfX0+CisgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJyb3V0aW5lLWZvb3QiPgogICAgICAgICAgIHthbHJlYWR5SW4gPyAoCiAgICAgICAgICAgICA8c3BhbiBjbGFzc05hbWU9Im11dGVkIiBzdHlsZT17eyBmb250U2l6ZTogMTEuNSwgZGlzcGxheTogJ2lubGluZS1mbGV4JywgYWxpZ25JdGVtczogJ2NlbnRlcicsIGdhcDogNiB9fT4KICAgICAgICAgICAgICAgPHNwYW4gYXJpYS1oaWRkZW4+4oaRPC9zcGFuPgpAQCAtMjEzLDcgKzIxMyw3IEBAIGZ1bmN0aW9uIEJhbmQoCiAgICAgICAgICAgTm90aGluZyBoZXJlIHlldCDigJQgYXMgeW91ciBwcm9maWxlIGZpbGxzIGluLCBzdGVwcyBhcHBlYXIuCiAgICAgICAgIDwvcD4KICAgICAgICkgOiAoCi0gICAgICAgIDx1bCBzdHlsZT17eyBsaXN0U3R5bGU6ICdub25lJywgcGFkZGluZzogMCwgbWFyZ2luOiAnOHB4IDAgMCcgfX0+CisgICAgICAgIDx1bCBjbGFzc05hbWU9InJvdXRpbmUtZ3JpZCIgc3R5bGU9e3sgbGlzdFN0eWxlOiAnbm9uZScsIHBhZGRpbmc6IDAgfX0+CiAgICAgICAgICAge3Iuc3RlcHMubWFwKChzKSA9PiAoCiAgICAgICAgICAgICA8U3RlcCBrZXk9e3MucHJvZHVjdElkfSBzPXtzfSBwaWNrPXtwaWNrcy5nZXQocy5wcm9kdWN0SWQpfSBxdHk9e2JhZ2dlZC5xdHlPZihzLnByb2R1Y3RJZCl9CiAgICAgICAgICAgICAgIGFscmVhZHlJbj17c2Vlbi5nZXQocy5wcm9kdWN0SWQpID09PSByLnRpdGxlID8gdW5kZWZpbmVkIDogc2Vlbi5nZXQocy5wcm9kdWN0SWQpfQpAQCAtMjcyLDcgKzI3Miw3IEBAIGZ1bmN0aW9uIEJ1ZGdldENhcmQoCiAgIGNvbnN0IGFzayA9IHNob3J0ID8gKGMubWluaW11bUluciBhcyBudW1iZXIpIDogaWRlYWwgPyAoYy5pZGVhbEluciBhcyBudW1iZXIpIDogbnVsbDsKIAogICByZXR1cm4gKAotICAgIDxzZWN0aW9uIGNsYXNzTmFtZT0iY2FyZCIgc3R5bGU9e3sgbWFyZ2luOiAwLCBtaW5XaWR0aDogMCB9fT4KKyAgICA8c2VjdGlvbiBjbGFzc05hbWU9ImJlYXV0eS1zaGVldCIgc3R5bGU9e3sgbWFyZ2luOiAwLCBtaW5XaWR0aDogMCB9fT4KICAgICAgIDxkaXYgc3R5bGU9e3sgZGlzcGxheTogJ2ZsZXgnLCBhbGlnbkl0ZW1zOiAnYmFzZWxpbmUnLCBnYXA6IDgsIGZsZXhXcmFwOiAnd3JhcCcgfX0+CiAgICAgICAgIDxoMyBzdHlsZT17eyBmb250U2l6ZTogMTMsIG1hcmdpbjogMCwgdGV4dFRyYW5zZm9ybTogJ3VwcGVyY2FzZScsIGxldHRlclNwYWNpbmc6ICcuMTJlbScgfX0+e21ldGEubGFiZWx9PC9oMz4KICAgICAgICAgPHNwYW4gY2xhc3NOYW1lPSJtdXRlZCIgc3R5bGU9e3sgZm9udFNpemU6IDExIH19PntjLnBpY2tzLmxlbmd0aH0gcHJvZHVjdHtjLnBpY2tzLmxlbmd0aCA9PT0gMSA/ICcnIDogJ3MnfTwvc3Bhbj4KQEAgLTY3NCwxNyArNjc0LDE3IEBAIGV4cG9ydCBmdW5jdGlvbiBSb3V0aW5lKCkgewogICAgICAgICAgIHsvKiBBTSBhbmQgUE0gYWJyZWFzdCwgYXMgaW4gdGhlIHJlZmVyZW5jZTsgdGhlIGRpdmlkZXIgYmV0d2VlbiB0aGVtIGlzCiAgICAgICAgICAgICAgIHRoZSBvbmx5IHJ1bGUgb24gdGhlIHBhZ2UgYW5kIGl0IGlzIHdoYXQgbWFrZXMgdGhlbSByZWFkIGFzIHR3bwogICAgICAgICAgICAgICBoYWx2ZXMgb2Ygb25lIGRheSByYXRoZXIgdGhhbiB0d28gbGlzdHMuICovfQotICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJjYXJkIHJvdXRpbmUtZGF5IiBzdHlsZT17eyBtYXJnaW5Cb3R0b206IDE0IH19PgorICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJiZWF1dHktc2hlZXQgcm91dGluZS1kYXkiPgogICAgICAgICAgICAge2RheS5tYXAoKHIpID0+IDxCYW5kIGtleT17ci50aW1lT2ZEYXl9IHI9e3J9IHBpY2tzPXtwaWNrc30gYmFnZ2VkPXtiYWdnZWR9IHNlZW49e2ZpcnN0U2Vlbn0gLz4pfQogICAgICAgICAgIDwvZGl2PgogCiAgICAgICAgICAge3Jlc3QuZmlsdGVyKChyKSA9PiByLnN0ZXBzLmxlbmd0aCA+IDApLm1hcCgocikgPT4gKAotICAgICAgICAgICAgPGRpdiBrZXk9e3IudGltZU9mRGF5fSBjbGFzc05hbWU9ImNhcmQiIHN0eWxlPXt7IG1hcmdpbkJvdHRvbTogMTQgfX0+CisgICAgICAgICAgICA8ZGl2IGtleT17ci50aW1lT2ZEYXl9IGNsYXNzTmFtZT0iYmVhdXR5LXNoZWV0Ij4KICAgICAgICAgICAgICAgPEJhbmQgcj17cn0gcGlja3M9e3BpY2tzfSBiYWdnZWQ9e2JhZ2dlZH0gc2Vlbj17Zmlyc3RTZWVufSAvPgogICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgKSl9CiAKLSAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0icm91dGluZS1hc3N1cmUgY2FyZCIgc3R5bGU9e3sgbWFyZ2luQm90dG9tOiAxNCB9fT4KKyAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0icm91dGluZS1hc3N1cmUgYmVhdXR5LXNoZWV0Ij4KICAgICAgICAgICAgIHtBU1NVUkFOQ0VTLm1hcCgoW21hcmssIHRleHRdKSA9PiAoCiAgICAgICAgICAgICAgIDxkaXYga2V5PXt0ZXh0fSBzdHlsZT17eyBkaXNwbGF5OiAnZmxleCcsIGdhcDogOSwgYWxpZ25JdGVtczogJ2NlbnRlcicgfX0+CiAgICAgICAgICAgICAgICAgPHNwYW4gYXJpYS1oaWRkZW4gc3R5bGU9e3sgZm9udFNpemU6IDE1LCBjb2xvcjogJ3ZhcigtLWFjY2VudC1pbmspJyB9fT57bWFya308L3NwYW4+CmRpZmYgLS1naXQgYS90b2dldGhlci1jaXR5LXJlYWN0L3NyYy9zdHlsZXMvbGF5b3V0LmNzcyBiL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL3N0eWxlcy9sYXlvdXQuY3NzCmluZGV4IGI1YTg4NTYuLjMzOTMxYTIgMTAwNjQ0Ci0tLSBhL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL3N0eWxlcy9sYXlvdXQuY3NzCisrKyBiL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL3N0eWxlcy9sYXlvdXQuY3NzCkBAIC0xMDU5LDMgKzEwNTksNDkgQEAKICAgICAgb24gdG9wIG9mIHRoZSBsaXN0IGl0IHN1bW1hcmlzZXMuICovCiAgIC5nZW0tc3VtbWFyeSB7IHBvc2l0aW9uOiBzdGF0aWM7IH0KIH0KKworCisvKiDilZDilZAgVEhFIFJPVVRJTkUgQ0FSRCDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZAKKyAgIFRoZSBvd25lcidzIGNhdGFsb2d1ZSBzaGVldCwgYXBwbGllZCB0byBhIHN0ZXA6IGEgdGFsbCB3ZWxsIHdpdGggdGhlIHByb2R1Y3QKKyAgIHBob3RvZ3JhcGhlZCBpbiBpdCwgYW5kIGV2ZXJ5dGhpbmcgZWxzZSB1bmRlcm5lYXRoLgorCisgICBXSFkgVEhFIFBJQ1RVUkUgR09UIEJJR0dFUi4gSXQgd2FzIDYyIHNxdWFyZSBpbiBhIHJvdyBiZXNpZGUgZm91ciBsaW5lcyBvZgorICAgdGV4dCDigJQgZW5vdWdoIHRvIHRlbGwgYSBib3R0bGUgZnJvbSBhIHR1YmUgYW5kIG5vdCBlbm91Z2ggdG8gdGVsbCBvbmUgd2hpdGUKKyAgIGJvdHRsZSBmcm9tIGFub3RoZXIuIE9uIGEgcGFnZSB3aG9zZSBqb2IgaXMgImdvIGFuZCBidXkgdGhlc2UgZWlnaHQgdGhpbmdzIiwKKyAgIHRoZSBwaG90b2dyYXBoIElTIHRoZSBpZGVudGlmaWVyOiBpdCBpcyB3aGF0IHNvbWVib2R5IG1hdGNoZXMgYWdhaW5zdCBhIHNoZWxmCisgICBvciBhIHNlYXJjaCByZXN1bHQuIFRoZSB0ZXh0IGlzIHdoYXQgdGhleSByZWFkIG9uY2UuCisKKyAgIFRIRSBMQVlPVVQgRElEIE5PVCBDSEFOR0UuIE1vcm5pbmcgYW5kIGV2ZW5pbmcgc3RpbGwgc2l0IHNpZGUgYnkgc2lkZSwgdGhlCisgICBzdGVwcyBhcmUgc3RpbGwgaW4gb3JkZXIsIGFuZCBldmVyeSBmYWN0IHRoZSByb3cgY2FycmllZCBpcyBzdGlsbCBvbiB0aGUgY2FyZAorICAg4oCUIHRoZSB0aWVyLCB0aGUgcHJpY2UsIHRoZSBtb250aGx5IGNvc3QsIHRoZSBwYWNrIHNpemUsIHRoZSBpbnN0cnVjdGlvbiwgdGhlCisgICBmcmVxdWVuY3ksIHRoZSB3YXJuaW5ncy4gT25seSB0aGUgc2hhcGUgbW92ZWQuICAgICAgICAgICAgICAgICAgICAgICAgICAgICovCisucm91dGluZS1ncmlkIHsKKyAgZGlzcGxheTogZ3JpZDsgZ3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiByZXBlYXQoYXV0by1maWxsLCBtaW5tYXgoMjI2cHgsIDFmcikpOworICBnYXA6IDE0cHg7IG1hcmdpbi10b3A6IDEwcHg7Cit9Cisucm91dGluZS1jYXJkIHsKKyAgZGlzcGxheTogZmxleDsgZmxleC1kaXJlY3Rpb246IGNvbHVtbjsgb3ZlcmZsb3c6IGhpZGRlbjsKKyAgYmFja2dyb3VuZDogdmFyKC0tY2FyZCk7IGJvcmRlcjogMXB4IHNvbGlkIHZhcigtLWxpbmUpOyBib3JkZXItcmFkaXVzOiAycHg7CisgIGJveC1zaGFkb3c6IHZhcigtLWUxKTsKK30KKy8qIFRoZSB3ZWxsIGlzIHRoZSBwYXBlciBhIHNob3QgaXMgdGFrZW4gb24sIGFuZCBpdCBpcyBhIGZpeGVkIGhlaWdodCBzbyBhIHJvdworICAgb2YgY2FyZHMgaGFzIGl0cyBjYXB0aW9ucyBvbiBvbmUgbGluZSBpbnN0ZWFkIG9mIHN0ZXBwaW5nLiAqLworLnJvdXRpbmUtd2VsbCB7CisgIHBvc2l0aW9uOiByZWxhdGl2ZTsgaGVpZ2h0OiAxODZweDsgcGFkZGluZzogMTZweDsKKyAgYmFja2dyb3VuZDogdmFyKC0tcGFwZXIpOyBib3JkZXItYm90dG9tOiAxcHggc29saWQgdmFyKC0tbGluZSk7CisgIGRpc3BsYXk6IGZsZXg7IGFsaWduLWl0ZW1zOiBjZW50ZXI7IGp1c3RpZnktY29udGVudDogY2VudGVyOworfQorLyogVGhlIG9yZGVyLCBrZXB0LiBBIGdyaWQgb2YgcHJvZHVjdCBjYXJkcyBsb3NlcyB0aGUgb25lIHRoaW5nIGEgbnVtYmVyZWQgbGlzdAorICAgaGFkLCBzbyB0aGUgbnVtYmVyIGdvZXMgb24gdGhlIHBpY3R1cmUg4oCUIHdoZXJlIGEgcHJpbnQgd291bGQgcHV0IGEgcGxhdGUKKyAgIG51bWJlciDigJQgcmF0aGVyIHRoYW4gYmVpbmcgZHJvcHBlZCBhcyBkZWNvcmF0aW9uLiAqLworLnJvdXRpbmUtbnVtIHsKKyAgcG9zaXRpb246IGFic29sdXRlOyB0b3A6IDEwcHg7IGxlZnQ6IDEwcHg7IHdpZHRoOiAyM3B4OyBoZWlnaHQ6IDIzcHg7CisgIGJvcmRlci1yYWRpdXM6IDUwJTsgZGlzcGxheTogZ3JpZDsgcGxhY2UtaXRlbXM6IGNlbnRlcjsKKyAgYmFja2dyb3VuZDogdmFyKC0tY2FyZCk7IGJveC1zaGFkb3c6IHZhcigtLWUxKTsKKyAgZm9udC1zaXplOiAxMXB4OyBmb250LXdlaWdodDogODAwOworfQorLnJvdXRpbmUtYm9keSB7IHBhZGRpbmc6IDEzcHggMTVweCAxNXB4OyBkaXNwbGF5OiBmbGV4OyBmbGV4LWRpcmVjdGlvbjogY29sdW1uOyBnYXA6IDdweDsgZmxleDogMTsgfQorLnJvdXRpbmUtdG9wIHsgZGlzcGxheTogZmxleDsgYWxpZ24taXRlbXM6IGNlbnRlcjsganVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuOyBnYXA6IDhweDsgfQorLnJvdXRpbmUtbmFtZSB7IGZvbnQtc2l6ZTogMTQuNXB4OyBsaW5lLWhlaWdodDogMS4zNTsgZm9udC13ZWlnaHQ6IDcwMDsgbWFyZ2luOiAwOyB9Cisucm91dGluZS1wcmljZSB7IGZvbnQtc2l6ZTogMTdweDsgZm9udC13ZWlnaHQ6IDgwMDsgbGV0dGVyLXNwYWNpbmc6IC0uMDFlbTsgfQorLnJvdXRpbmUtZm9vdCB7IG1hcmdpbi10b3A6IGF1dG87IHBhZGRpbmctdG9wOiAxMHB4OyB9Cg==
B64EOF
WANT="07324f3a06ef5d4fd52e88715a28c99d017137262508e2007654dd0c34736e0b"
GOT="$(shasum -a 256 "$PATCH" | awk '{print $1}')"
[ "$GOT" = "$WANT" ] || { echo "!! Patch is corrupt."; echo "   want $WANT"; echo "   got  $GOT"; exit 1; }
echo "== patch verified"
git apply --check -C1 "$PATCH" || { echo "!! Patch does not apply cleanly. Nothing written."; exit 1; }
git apply -C1 "$PATCH"
echo "== applied"

echo "== gates: the web app"
cd together-city-react
npx tsc --noEmit
npx vitest run
node scripts/a11y-audit.mjs
node scripts/motion-ceiling.mjs
node scripts/lint-ceiling.mjs
npx vite build
cd ..

git add together-city-react/src/features/beauty/pages/Routine.tsx \
        together-city-react/src/features/beauty/components/ProductShot.tsx \
        together-city-react/src/styles/layout.css
git commit -F - <<'MSG'
The photograph is the identifier

The routine step becomes the owner's catalogue card: a tall well with the
product photographed in it, and everything else written underneath.

WHY THE PICTURE GOT BIGGER. It was 62px square in a row beside four lines of
text — enough to tell a bottle from a tube and not enough to tell one white
bottle from another. On a page whose whole job is "go and buy these eight
things", the photograph IS the identifier: it is what somebody matches against
a shelf or a search result. The text is what they read once.

THE LAYOUT DID NOT CHANGE, and that was the instruction. Morning and evening
still sit side by side, the steps are still in order, and every fact the row
carried is still on the card — the step, the tier, the price, the monthly cost,
the pack size, how long it lasts, the instruction, the frequency, the warnings,
the quantity control. Only the shape moved. A band is a small grid inside its
own column: two cards abreast at desk width, one on a phone.

The order badge went onto the picture rather than being dropped. A grid of
product cards loses the one thing a numbered list had, and a routine whose
steps are not visibly in order is a catalogue.

The band containers move from the city's rounded card onto the hub's own cream
sheet, so the routine page is one material with the profile page.

── AND WHY THIS IS A SEPARATE COMMIT ──────────────────────────────────────────

These cards were rebuilt INTO land-gallery-wall.sh after a copy of that script
had already landed, under the same commit name — and the script's own
idempotency check keys on the name, so the second build exited "nothing to do"
on every machine that had run the first. A guard that cannot tell two builds
apart is a guard that silently drops the difference between them. The rule that
follows: a land script's patch is frozen the moment its name has been run
anywhere; anything more gets a new name.

Backend untouched: no route, no schema, no query changed.
MSG

echo "== committed"
cat <<'DONE'

===============================================================
 Landed: The photograph is the identifier
 Push — Vercel rebuilds. /beauty/routine: each step is a card,
 big photograph on top, two abreast per band at desk width.
===============================================================

DONE
