#!/bin/bash
# land-paper-under-the-ink.sh — three visible defects on the live routine page,
# and the missing half of an earlier script, in one cut.
#
#   1. THE GHOST TEXT. Product names and prices on the routine cards render in
#      the WALL's near-white ink on cream paper. The step cards and the sheets
#      never joined the ink-restore list in relief.css. They join it, and a test
#      now reads the list.
#   2. THE FLOATING CHECKOUT comes off the viewport and becomes the last block
#      of the page, phone and desk alike.
#   3. THE IMAGE SCALE. A product photograph shows at its natural size, capped —
#      never inflated into a blur — and its white studio ground melts into the
#      well (multiply + no-case, the gem sheets' own treatment).
#
# WHY YOUR TREE WAS MISSING THE CHECKOUT FIX ALREADY: land-gallery-wall.sh was
# rebuilt twice under one commit name, you ran the first build, and every later
# build then said "nothing to do". This patch was therefore built against YOUR
# tree — the exact bytes staged off this machine tonight — not against the tree
# the rebuilt scripts assumed.
#
# WEB APP ONLY (together-city-react). Vercel. No API change, no migration.
# PRECONDITION: land-routine-cards.sh ("The photograph is the identifier").
set -euo pipefail

cd "$(dirname "$0")"
[ -d together-city-chat ] || { echo "!! Run this from the Together-Ai repo root."; exit 1; }

if [ -f .git/index.lock ] && [ ! -s .git/index.lock ]; then
  echo "== clearing a stale empty .git/index.lock"
  rm -f .git/index.lock
fi

NEEDS="The paper under the ink"
LOG="$(git log --oneline -40)"
case "$LOG" in
  *"$NEEDS"*) echo "== \"$NEEDS\" is already here. Nothing to do."; exit 0 ;;
esac
case "$LOG" in
  *"The photograph is the identifier"*) ;;
  *) echo "!! Run land-routine-cards.sh first — this is written against the tree it produces."; exit 1 ;;
esac

ALLOWED='^ M together-city-react/(public/assets/img/(apple-touch-icon-180|tc-icon-1024|tc-icon-192|tc-icon-512|tc-icon-maskable-512)\.png|public/downloads/TogetherCity\.apk)$'
DIRTY="$(git status --porcelain \
  | grep -Ev '^\?\? (land-.*\.sh|push-.*\.sh|.*\.patch)$' \
  | grep -Ev "$ALLOWED" || true)"
if [ -n "$DIRTY" ]; then
  echo "!! The tree carries changes this script did not expect:"; echo "$DIRTY"; exit 1
fi

PATCH="$(mktemp "${TMPDIR:-/tmp}/land.XXXXXX")"
trap 'rm -f "$PATCH"' EXIT
cat <<'B64EOF' | tr -d '\n' | openssl base64 -d -A > "$PATCH"
ZGlmZiAtLWdpdCBhL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL2FwcC9hLXJlYWQtc2VjdGlvbi1mb2xkcy1pdHNlbGYudGVzdC50cyBiL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL2FwcC9hLXJlYWQtc2VjdGlvbi1mb2xkcy1pdHNlbGYudGVzdC50cwppbmRleCA2YTUxNDdkLi5lODllZTdmIDEwMDY0NAotLS0gYS90b2dldGhlci1jaXR5LXJlYWN0L3NyYy9hcHAvYS1yZWFkLXNlY3Rpb24tZm9sZHMtaXRzZWxmLnRlc3QudHMKKysrIGIvdG9nZXRoZXItY2l0eS1yZWFjdC9zcmMvYXBwL2EtcmVhZC1zZWN0aW9uLWZvbGRzLWl0c2VsZi50ZXN0LnRzCkBAIC0xOTMsMyArMTkzLDY2IEBAIGRlc2NyaWJlKCd0aGUgYmVhdXR5IGRpc3BsYXkgZmFjZScsICgpID0+IHsKICAgICBleHBlY3QobGF5b3V0KS50b01hdGNoKC9cLmJlYXV0eS1wbGF0ZSBcLmJlYXV0eS1kaXNwbGF5IFx7W159XSpmb250LXNpemUvKTsKICAgfSk7CiB9KTsKKworLyoqCisgKiBUSFJFRSBTVVJGQUNFUyBJTiBUSElTIEhVQiBBTkQgTk8gRk9VUlRILgorICoKKyAqIEEgcGxhdGUgZm9yIHRoZSBmb3VyIGNoYXB0ZXJzIHRoZSBvd25lciBkcmV3LCBhIGxlYWYgZm9yIHRoZSBjb250ZW50cyBvZiBvbmUsCisgKiBhbmQgYSBzaGVldCBmb3IgZXZlcnl0aGluZyB0aGF0IGlzIHNpbXBseSBjb250ZW50IOKAlCB0aGUgcHJvZ3Jlc3Mgc3RyaXAsIHRoZQorICogZGF0ZWQgaGlzdG9yeSwgdGhlIGJpb21hcmtlciBwYW5lbCwgdGhlIGJhZydzIHJ1bm5pbmcgdG90YWwuIFRoZSBjaXR5J3MKKyAqIG9yZGluYXJ5IHJvdW5kZWQgYC5jYXJkYCBpcyB0aGUgdGhpbmcgdGhleSByZXBsYWNlOiBuZXh0IHRvIGEgc2V0IG9mIHByaW50cworICogaXQgaXMgdGhlIG9uZSBvYmplY3Qgb24gdGhlIHBhZ2UgdGhhdCBjYW1lIGZyb20gYW5vdGhlciBkZXNpZ24sIGFuZCBpdCBjb21lcworICogYmFjayB0aGUgbW9tZW50IHNvbWVib2R5IGFkZHMgYSBzZWN0aW9uLCBiZWNhdXNlIGA8ZGl2IGNsYXNzTmFtZT0iY2FyZCI+YCBpcworICogd2hhdCBldmVyeSBvdGhlciBwYWdlIGluIHRoaXMgYXBwbGljYXRpb24gY29ycmVjdGx5IHVzZXMuCisgKgorICogVEhFIEJBRyBCQVIgSVMgSEVSRSBGT1IgQSBESUZGRVJFTlQgUkVBU09OLiBJdCB3YXMgYHBvc2l0aW9uOiBzdGlja3lgIGFuZAorICogcm9kZSB1cCB0aGUgcm91dGluZSBzaGVldCBjb3ZlcmluZyB0aGUgc3RlcHMgc29tZWJvZHkgd2FzIHJlYWRpbmcg4oCUIGEgc3VtbWFyeQorICogb2Ygd2hhdCBpcyBpbiB0aGUgYmFnIHBhcmtlZCBhY3Jvc3MgdGhlIHByb2R1Y3RzIHRoZXkgd2VyZSBkZWNpZGluZyB3aGV0aGVyCisgKiB0byBwdXQgaW4gaXQuIEl0IGlzIHRoZSBsYXN0IGJsb2NrIG9mIHRoZSBwYWdlIG5vdzogeW91IHJlYWNoIGl0IGJ5IGdldHRpbmcKKyAqIHRvIHRoZSBlbmQsIHdoaWNoIGlzIGFsc28gd2hlbiB5b3UgaGF2ZSBmaW5pc2hlZCBkZWNpZGluZy4KKyAqLworZGVzY3JpYmUoJ3RoZSBiZWF1dHkgaHViIHByaW50cyBvbiBpdHMgb3duIHBhcGVyJywgKCkgPT4geworICBjb25zdCBwcm9maWxlID0gcmVhZCgnZmVhdHVyZXMvYmVhdXR5L3BhZ2VzL1Byb2ZpbGUudHN4Jyk7CisgIGNvbnN0IGJhciA9IHJlYWQoJ2ZlYXR1cmVzL2JlYXV0eS9jb21wb25lbnRzL0JlYXV0eUJhZ0Jhci50c3gnKTsKKworICBpdCgnZ2l2ZXMgdGhlIHByb2dyZXNzLCBoaXN0b3J5IGFuZCBiaW9tYXJrZXIgcGFuZWxzIHRoZSBzaGVldCcsICgpID0+IHsKKyAgICBleHBlY3QoWy4uLnByb2ZpbGUubWF0Y2hBbGwoL2NsYXNzTmFtZT0iYmVhdXR5LXNoZWV0Ii9nKV0ubGVuZ3RoKS50b0JlR3JlYXRlclRoYW5PckVxdWFsKDQpOworICB9KTsKKworICBpdCgnbGVhdmVzIG5vIGVtb2ppIGhlYWRpbmcgb24gYSBiZWF1dHkgc3VyZmFjZScsICgpID0+IHsKKyAgICAvLyDwn5OIIPCfl5PvuI8g8J+puCBoZWFkZWQgdGhlIHRocmVlIHBhbmVscyBhYm92ZS4gVGhlIPCfqbggdGhhdCBzdGF5cyBpcyBhIE1BUktFUgorICAgIC8vIGluc2lkZSBhIGNoaXAg4oCUIGl0IG1lYW5zICJ5b3VyIGxhYnMgc3VwcG9ydCB0aGlzIG9uZSIgYW5kIGlzIGRvaW5nIHdvcmsKKyAgICAvLyBubyB3b3JkIGRvZXMgaW4gdGhhdCB3aWR0aC4KKyAgICBjb25zdCBjb2RlID0gcHJvZmlsZS5yZXBsYWNlKC9cL1wqW1xzXFNdKj9cKlwvL2csICcgJykucmVwbGFjZSgvKF58W146XSlcL1wvLiokL2dtLCAnJDEgJyk7CisgICAgZm9yIChjb25zdCBlIG9mIFsn8J+TiCcsICfwn5eT77iPJ10pIGV4cGVjdChjb2RlKS5ub3QudG9Db250YWluKGUpOworICAgIGV4cGVjdChjb2RlKS5ub3QudG9NYXRjaCgvZXllYnJvd1tePl0qPvCfqbgvKTsKKyAgfSk7CisKKyAgaXQoJ2RvZXMgbm90IHN0aWNrIHRoZSBiYWcgdG8gdGhlIHZpZXdwb3J0JywgKCkgPT4geworICAgIGV4cGVjdChiYXIpLm5vdC50b01hdGNoKC9wb3NpdGlvbjogJ3N0aWNreScvKTsKKyAgICBleHBlY3QoYmFyKS50b01hdGNoKC9jbGFzc05hbWU9ImJlYXV0eS1zaGVldCIvKTsKKyAgfSk7CisKKyAgaXQoJ3JlZ2lzdGVycyBldmVyeSBsaXQgc3VyZmFjZSB3aXRoIHRoZSB3YWxsIGluay1yZXN0b3JlIGxpc3QnLCAoKSA9PiB7CisgICAgLy8gVGhlIHdhbGwgcmUtcG9pbnRzIC0taW5rIHRvIG5lYXItd2hpdGUgYnkgaW5oZXJpdGFuY2U7IGV2ZXJ5IGNsYXNzIHRoYXQKKyAgICAvLyBwYWludHMgY3JlYW0gbXVzdCBwdXQgdGhlIHBhcGVyJ3MgaW5rIGJhY2sgaW4gcmVsaWVmLmNzcy4gVGhlIHN0ZXAgY2FyZHMKKyAgICAvLyBhbmQgdGhlIHNoZWV0cyBib3RoIHNoaXBwZWQgd2l0aG91dCBkb2luZyBzbywgYW5kIGJvdGggd2VudCBvdXQgd2l0aAorICAgIC8vIG5lYXItd2hpdGUgcHJvZHVjdCBuYW1lcyBvbiBjcmVhbSDigJQgaW52aXNpYmxlIGluIHJldmlldyBiZWNhdXNlIGV2ZXJ5CisgICAgLy8gbG9jYWwgaGFybmVzcyByZXN0b3JlZCB0aGUgaW5rIGJ5IGhhbmQuIEEgc3VyZmFjZSBjbGFzcyBtaXNzaW5nIGZyb20KKyAgICAvLyB0aGlzIGxpc3QgaXMgdGhhdCBidWcgYWdhaW4uCisgICAgY29uc3QgcmVsaWVmID0gcmVhZCgnc3R5bGVzL3JlbGllZi5jc3MnKTsKKyAgICBjb25zdCBsaXN0ID0gcmVsaWVmLnNsaWNlKHJlbGllZi5pbmRleE9mKCdbZGF0YS1odWI9ImJlYXV0eSJdIC5jYXJkLCcpKTsKKyAgICBmb3IgKGNvbnN0IGNscyBvZiBbJy5iZWF1dHktcGxhdGUnLCAnLmJlYXV0eS1zaGVldCcsICcuYmVhdXR5LWxlYWYtb3BlbicsICcucm91dGluZS1jYXJkJ10pIHsKKyAgICAgIGV4cGVjdChsaXN0LnNsaWNlKDAsIGxpc3QuaW5kZXhPZigneycpKSkudG9Db250YWluKGBbZGF0YS1odWI9ImJlYXV0eSJdICR7Y2xzfWApOworICAgIH0KKyAgfSk7CisKKyAgaXQoJ25ldmVyIGluZmxhdGVzIGEgcHJvZHVjdCBwaG90b2dyYXBoJywgKCkgPT4geworICAgIC8vIHdpZHRoOjEwMCUgb24gYSBzbWFsbCByZXRhaWxlciBKUEVHIHVwc2NhbGVzIGl0IGludG8gYSBibHVyOyB0aGUgd2VsbAorICAgIC8vIHNob3dzIGEgc2hvdCBhdCBpdHMgbmF0dXJhbCBzaXplLCBjYXBwZWQuIE11bHRpcGx5ICsgbm8tY2FzZSBiZWNhdXNlIHRoZQorICAgIC8vIHBob3RvZ3JhcGh5IGlzIHdoaXRlLWdyb3VuZCBjdXQtb3V0cyDigJQgdGhlIGdlbSBzaGVldHMnIG93biB0cmVhdG1lbnQuCisgICAgY29uc3Qgc2hvdCA9IHJlYWQoJ2ZlYXR1cmVzL2JlYXV0eS9jb21wb25lbnRzL1Byb2R1Y3RTaG90LnRzeCcpOworICAgIGV4cGVjdChzaG90KS50b01hdGNoKC9tYXhXaWR0aDogJzEwMCUnLCBtYXhIZWlnaHQ6ICcxMDAlJywgd2lkdGg6ICdhdXRvJywgaGVpZ2h0OiAnYXV0bycsIG1peEJsZW5kTW9kZTogJ211bHRpcGx5Jy8pOworICAgIGV4cGVjdChzaG90KS50b01hdGNoKC9jbGFzc05hbWU9XHtmaWxsIFw/ICduby1jYXNlJyA6IHVuZGVmaW5lZFx9Lyk7CisgIH0pOworfSk7CmRpZmYgLS1naXQgYS90b2dldGhlci1jaXR5LXJlYWN0L3NyYy9mZWF0dXJlcy9iZWF1dHkvY29tcG9uZW50cy9CZWF1dHlCYWdCYXIudHN4IGIvdG9nZXRoZXItY2l0eS1yZWFjdC9zcmMvZmVhdHVyZXMvYmVhdXR5L2NvbXBvbmVudHMvQmVhdXR5QmFnQmFyLnRzeAppbmRleCA3MDk5Mjk1Li5mNWVmYzg4IDEwMDY0NAotLS0gYS90b2dldGhlci1jaXR5LXJlYWN0L3NyYy9mZWF0dXJlcy9iZWF1dHkvY29tcG9uZW50cy9CZWF1dHlCYWdCYXIudHN4CisrKyBiL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL2ZlYXR1cmVzL2JlYXV0eS9jb21wb25lbnRzL0JlYXV0eUJhZ0Jhci50c3gKQEAgLTExLDYgKzExLDE2IEBAIGltcG9ydCB7IHVzZUJlYXV0eUJhZyB9IGZyb20gJy4uL2FwaSc7CiAgKiBpdGVtcyDCtyDigrk2LDAwOSIgb24gdGhlIG90aGVyIGFuZCBib3RoIHdlcmUgdHJ1ZSwgaW4gdGhlIHNlbnNlIHRoYXQgbmVpdGhlcgogICogd2FzLiBGb2xsb3dpbmcgYSBsaW5rIGVtcHRpZWQgd2hpY2hldmVyIG9uZSB0aGV5IHdlcmUgbm90IGxvb2tpbmcgYXQuCiAgKgorICogSVQgU0lUUyBBVCBUSEUgRk9PVCBPRiBUSEUgUEFHRSwgTk9UIE9OIFRPUCBPRiBJVC4gSXQgd2FzIGBwb3NpdGlvbjogc3RpY2t5YAorICogd2l0aCBhIGhlYXZ5IGRyb3Agc2hhZG93LCBzbyBvbiB0aGUgcm91dGluZSBzaGVldCBpdCByb2RlIHVwIHRoZSBzY3JlZW4KKyAqIGNvdmVyaW5nIHRoZSB2ZXJ5IHN0ZXBzIHNvbWVib2R5IHdhcyByZWFkaW5nIOKAlCB0aGUgc3VtbWFyeSBvZiB3aGF0IGlzIGluIHRoZQorICogYmFnIHBhcmtlZCBhY3Jvc3MgdGhlIHByb2R1Y3RzIHRoZXkgd2VyZSBkZWNpZGluZyB3aGV0aGVyIHRvIHB1dCBpbiBpdC4gQQorICogcnVubmluZyB0b3RhbCBpcyB3b3J0aCBzaG93aW5nOyBpdCBpcyBub3Qgd29ydGggYSBwZXJtYW5lbnQgc3RyaXAgb2YgdGhlCisgKiB2aWV3cG9ydCBvbiBhIHBhZ2Ugd2hvc2Ugd2hvbGUgam9iIGlzIGEgbGlzdCB5b3Ugc2Nyb2xsLgorICoKKyAqIFNvIGl0IGlzIHRoZSBsYXN0IGJsb2NrIG9mIHRoZSBwYWdlLiBZb3UgcmVhY2ggaXQgYnkgZ2V0dGluZyB0byB0aGUgZW5kLAorICogd2hpY2ggaXMgYWxzbyB3aGVuIHlvdSBoYXZlIGZpbmlzaGVkIGRlY2lkaW5nLgorICoKICAqIEFORCBDSEVDS09VVCBJUyBBIExJTkssIE5PVCBBIFBBWU1FTlQgU0hFRVQuIEl0IHVzZWQgdG8gb3BlbiB0aGUgd2FsbGV0CiAgKiBkaXJlY3RseSBvdmVyIHdoYXRldmVyIHBhZ2UgeW91IHdlcmUgb24sIHdoaWNoIGFza3Mgc29tZWJvZHkgdG8gcGF5IGZvciBhCiAgKiBsaXN0IHN1bW1hcmlzZWQgaW4gb25lIGdyZXkgbGluZSBvZiBydW5uaW5nIHRleHQuIEl0IGdvZXMgdG8gTXkgT3JkZXJzIG5vdyDigJQKQEAgLTI1LDkgKzM1LDggQEAgZXhwb3J0IGZ1bmN0aW9uIEJlYXV0eUJhZ0JhcigpIHsKICAgaWYgKCFkYXRhIHx8IGRhdGEuY291bnQgPT09IDApIHJldHVybiBudWxsOwogCiAgIHJldHVybiAoCi0gICAgPGRpdiBjbGFzc05hbWU9ImNhcmQiIHN0eWxlPXt7Ci0gICAgICBwb3NpdGlvbjogJ3N0aWNreScsIGJvdHRvbTogMTYsIG1hcmdpblRvcDogMTgsIGRpc3BsYXk6ICdmbGV4JywgYWxpZ25JdGVtczogJ2NlbnRlcicsCi0gICAgICBnYXA6IDE0LCBmbGV4V3JhcDogJ3dyYXAnLCBib3hTaGFkb3c6ICcwIDhweCAzMHB4IHJnYmEoMCwwLDAsLjEyKScsCisgICAgPGRpdiBjbGFzc05hbWU9ImJlYXV0eS1zaGVldCIgc3R5bGU9e3sKKyAgICAgIG1hcmdpblRvcDogMjIsIGRpc3BsYXk6ICdmbGV4JywgYWxpZ25JdGVtczogJ2NlbnRlcicsIGdhcDogMTQsIGZsZXhXcmFwOiAnd3JhcCcsCiAgICAgfX0+CiAgICAgICA8ZGl2IHN0eWxlPXt7IG1pbldpZHRoOiAwIH19PgogICAgICAgICA8ZGl2IHN0eWxlPXt7IGZvbnRXZWlnaHQ6IDcwMCwgZm9udFNpemU6IDE1IH19PgpkaWZmIC0tZ2l0IGEvdG9nZXRoZXItY2l0eS1yZWFjdC9zcmMvZmVhdHVyZXMvYmVhdXR5L2NvbXBvbmVudHMvUHJvZHVjdFNob3QudHN4IGIvdG9nZXRoZXItY2l0eS1yZWFjdC9zcmMvZmVhdHVyZXMvYmVhdXR5L2NvbXBvbmVudHMvUHJvZHVjdFNob3QudHN4CmluZGV4IDJmMTdiOTkuLmI5ZTY4ZjUgMTAwNjQ0Ci0tLSBhL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL2ZlYXR1cmVzL2JlYXV0eS9jb21wb25lbnRzL1Byb2R1Y3RTaG90LnRzeAorKysgYi90b2dldGhlci1jaXR5LXJlYWN0L3NyYy9mZWF0dXJlcy9iZWF1dHkvY29tcG9uZW50cy9Qcm9kdWN0U2hvdC50c3gKQEAgLTUzLDcgKzUzLDE5IEBAIGV4cG9ydCBmdW5jdGlvbiBQcm9kdWN0U2hvdCgKICAgICB9fT4KICAgICAgIHtzcmMKICAgICAgICAgPyA8aW1nIGtleT17c3JjfSBzcmM9e3NyY30gYWx0PSIiIGxvYWRpbmc9ImxhenkiIG9uRXJyb3I9eygpID0+IHNldFRyaWVkKChuKSA9PiBuICsgMSl9Ci0gICAgICAgICAgICBzdHlsZT17eyB3aWR0aDogJzEwMCUnLCBoZWlnaHQ6ICcxMDAlJywgb2JqZWN0Rml0OiAnY29udGFpbicgfX0gLz4KKyAgICAgICAgICAgIGNsYXNzTmFtZT17ZmlsbCA/ICduby1jYXNlJyA6IHVuZGVmaW5lZH0KKyAgICAgICAgICAgIHN0eWxlPXtmaWxsCisgICAgICAgICAgICAgIC8qIE5BVFVSQUwgU0laRSwgQ0FQUEVEIOKAlCBuZXZlciBpbmZsYXRlZC4gd2lkdGg6MTAwJSBvbiBhIHNtYWxsCisgICAgICAgICAgICAgICAgIHJldGFpbGVyIEpQRUcgdXBzY2FsZXMgaXQgaW50byBhIGJsdXI7IGF1dG8gd2l0aCBhIG1heCBsZXRzIGEKKyAgICAgICAgICAgICAgICAgYmlnIHNob3QgZmlsbCB0aGUgd2VsbCBhbmQgYSBzbWFsbCBvbmUgc2l0IGF0IGl0cyBvd24gc2l6ZS4KKyAgICAgICAgICAgICAgICAgTVVMVElQTFkgaXMgdGhlIGdlbSBzaGVldHMnIHRyaWNrIGZvciB0aGUgc2FtZSBwaG90b2dyYXBoeToKKyAgICAgICAgICAgICAgICAgdGhlc2UgYXJlIHNob3Qgb24gcHVyZSB3aGl0ZSwgYW5kIG11bHRpcGx5IG1lbHRzIHRoYXQgd2hpdGUKKyAgICAgICAgICAgICAgICAgaW50byB3aGF0ZXZlciBwYXBlciB0aGUgd2VsbCBpcywgaW5zdGVhZCBvZiBsZWF2aW5nIGEgd2hpdGUKKyAgICAgICAgICAgICAgICAgcmVjdGFuZ2xlIGZsb2F0aW5nIG9uIGNyZWFtLiBgbm8tY2FzZWAgZm9yIHRoZSBzYW1lIHJlYXNvbiB0aGUKKyAgICAgICAgICAgICAgICAgZ2VtcyB3ZWFyIGl0IOKAlCBhbiBvdXRsaW5lIGRyYXduIHJvdW5kIGEgY3V0LW91dCBpcyBhbiBvdXRsaW5lCisgICAgICAgICAgICAgICAgIHJvdW5kIG5vdGhpbmcuICovCisgICAgICAgICAgICAgID8geyBtYXhXaWR0aDogJzEwMCUnLCBtYXhIZWlnaHQ6ICcxMDAlJywgd2lkdGg6ICdhdXRvJywgaGVpZ2h0OiAnYXV0bycsIG1peEJsZW5kTW9kZTogJ211bHRpcGx5JyB9CisgICAgICAgICAgICAgIDogeyB3aWR0aDogJzEwMCUnLCBoZWlnaHQ6ICcxMDAlJywgb2JqZWN0Rml0OiAnY29udGFpbicgfX0gLz4KICAgICAgICAgOiA8c3BhbiBhcmlhLWhpZGRlbiBzdHlsZT17eyBmb250U2l6ZTogZmlsbCA/IDQwIDogTWF0aC5yb3VuZChzaXplIC8gMi44KSB9fT57Z2x5cGhGb3IoY2F0ZWdvcnkpfTwvc3Bhbj59CiAgICAgPC9zcGFuPgogICApOwpkaWZmIC0tZ2l0IGEvdG9nZXRoZXItY2l0eS1yZWFjdC9zcmMvZmVhdHVyZXMvYmVhdXR5L3BhZ2VzL1Byb2ZpbGUudHN4IGIvdG9nZXRoZXItY2l0eS1yZWFjdC9zcmMvZmVhdHVyZXMvYmVhdXR5L3BhZ2VzL1Byb2ZpbGUudHN4CmluZGV4IDQxYWMwMWIuLjM5MzY1YTMgMTAwNjQ0Ci0tLSBhL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL2ZlYXR1cmVzL2JlYXV0eS9wYWdlcy9Qcm9maWxlLnRzeAorKysgYi90b2dldGhlci1jaXR5LXJlYWN0L3NyYy9mZWF0dXJlcy9iZWF1dHkvcGFnZXMvUHJvZmlsZS50c3gKQEAgLTMxLDggKzMxLDEyIEBAIGZ1bmN0aW9uIFNraW5IYWlyVGltZWxpbmUoKSB7CiAgIGNvbnN0IGVudHJpZXMgPSBbLi4uZC5lbnRyaWVzXS5yZXZlcnNlKCk7IC8vIG5ld2VzdCBmaXJzdAogICBjb25zdCBmbXQgPSAoaXNvOiBzdHJpbmcpID0+IG5ldyBEYXRlKGlzbykudG9Mb2NhbGVEYXRlU3RyaW5nKCdlbi1JTicsIHsgZGF5OiAnbnVtZXJpYycsIG1vbnRoOiAnc2hvcnQnLCB5ZWFyOiAnbnVtZXJpYycgfSk7CiAgIHJldHVybiAoCi0gICAgPGRpdiBjbGFzc05hbWU9ImNhcmQiIHN0eWxlPXt7IG1hcmdpblRvcDogMTQgfX0+Ci0gICAgICA8ZGl2IGNsYXNzTmFtZT0iZXllYnJvdyI+8J+Xk++4jyBTa2luICZhbXA7IGhhaXIgdGltZWxpbmU8L2Rpdj4KKyAgICA8ZGl2IGNsYXNzTmFtZT0iYmVhdXR5LXNoZWV0Ij4KKyAgICAgIDxkaXYgY2xhc3NOYW1lPSJiZWF1dHktcnVsZSI+CisgICAgICAgIDxzcGFuPlNraW4gJmFtcDsgaGFpciB0aW1lbGluZTwvc3Bhbj4KKyAgICAgICAgPHNwYW4gLz4KKyAgICAgICAgPHNwYW4+e2VudHJpZXMubGVuZ3RofSBhc3Nlc3NtZW50e2VudHJpZXMubGVuZ3RoID09PSAxID8gJycgOiAncyd9PC9zcGFuPgorICAgICAgPC9kaXY+CiAKICAgICAgIHtkLmZvbGxvd1VwRHVlICYmICgKICAgICAgICAgPGRpdiBzdHlsZT17eyBkaXNwbGF5OiAnZmxleCcsIGFsaWduSXRlbXM6ICdjZW50ZXInLCBnYXA6IDEwLCBmbGV4V3JhcDogJ3dyYXAnLCBtYXJnaW5Ub3A6IDgsIHBhZGRpbmc6ICcxMXB4IDE0cHgnLCBiYWNrZ3JvdW5kOiAndmFyKC0td2Fybi1zb2Z0KScsIGJvcmRlcjogJzFweCBzb2xpZCB2YXIoLS13YXJuLWxpbmUpJywgYm9yZGVyUmFkaXVzOiAxMiwgZm9udFNpemU6IDEyLjUgfX0+CkBAIC0xMTQsOCArMTE4LDggQEAgZnVuY3Rpb24gQmlvbWFya2VyQ29ycmVsYXRpb24oKSB7CiAgIGNvbnN0IGQgPSBxLmRhdGE7CiAgIGlmICghZC5oYXNQYW5lbCkgewogICAgIHJldHVybiAoCi0gICAgICA8ZGl2IGNsYXNzTmFtZT0iY2FyZCIgc3R5bGU9e3sgbWFyZ2luVG9wOiAxNCB9fT4KLSAgICAgICAgPGRpdiBjbGFzc05hbWU9ImV5ZWJyb3ciPvCfqbggQmlvbWFya2VyIGNvcnJlbGF0aW9uPC9kaXY+CisgICAgICA8ZGl2IGNsYXNzTmFtZT0iYmVhdXR5LXNoZWV0Ij4KKyAgICAgICAgPGRpdiBjbGFzc05hbWU9ImJlYXV0eS1ydWxlIj48c3Bhbj5CaW9tYXJrZXIgY29ycmVsYXRpb248L3NwYW4+PHNwYW4gLz48c3BhbiAvPjwvZGl2PgogICAgICAgICA8cCBjbGFzc05hbWU9Im11dGVkIiBzdHlsZT17eyBmb250U2l6ZTogMTMsIG1hcmdpbjogJzZweCAwIDAnLCBsaW5lSGVpZ2h0OiAxLjU1IH19PgogICAgICAgICAgIEFkZCBhIGJsb29kIHRlc3QgaW4gdGhlIDxMaW5rIHRvPSIvbWVkaWNhbC9ibG9vZCIgc3R5bGU9e3sgY29sb3I6ICd2YXIoLS1hY2NlbnQtaW5rKScsIGZvbnRXZWlnaHQ6IDYwMCB9fT5NZWRpY2FsIEh1YjwvTGluaz4gYW5kIHdlJ2xsIGxpbmsgbWFya2VycyBsaWtlIGZlcnJpdGluLCB2aXRhbWluIEQsIEhiQTFjIGFuZCBDUlAgdG8geW91ciBza2luICYgaGFpciBoZXJlIOKAlCBmb3IgZXhhbXBsZSwgbG93IGZlcnJpdGluIOKGkiBpbmNyZWFzZWQgc2hlZGRpbmcsIG9yIHJhaXNlZCBIYkExYyDihpIgZ2x5Y2F0aW9uIGFuZCBsb3NzIG9mIGZpcm1uZXNzLgogICAgICAgICA8L3A+CkBAIC0xMjMsMTAgKzEyNywxMSBAQCBmdW5jdGlvbiBCaW9tYXJrZXJDb3JyZWxhdGlvbigpIHsKICAgICApOwogICB9CiAgIHJldHVybiAoCi0gICAgPGRpdiBjbGFzc05hbWU9ImNhcmQiIHN0eWxlPXt7IG1hcmdpblRvcDogMTQgfX0+Ci0gICAgICA8ZGl2IHN0eWxlPXt7IGRpc3BsYXk6ICdmbGV4JywgYWxpZ25JdGVtczogJ2Jhc2VsaW5lJywganVzdGlmeUNvbnRlbnQ6ICdzcGFjZS1iZXR3ZWVuJywgZ2FwOiA4LCBmbGV4V3JhcDogJ3dyYXAnIH19PgotICAgICAgICA8ZGl2IGNsYXNzTmFtZT0iZXllYnJvdyIgc3R5bGU9e3sgbWFyZ2luOiAwIH19PvCfqbggQmlvbWFya2VyIGNvcnJlbGF0aW9uPC9kaXY+Ci0gICAgICAgIHtkLnRha2VuT24gJiYgPHNwYW4gY2xhc3NOYW1lPSJtdXRlZCIgc3R5bGU9e3sgZm9udFNpemU6IDExLjUgfX0+ZnJvbSB5b3VyIHBhbmVsIMK3IHtkLnRha2VuT259PC9zcGFuPn0KKyAgICA8ZGl2IGNsYXNzTmFtZT0iYmVhdXR5LXNoZWV0Ij4KKyAgICAgIDxkaXYgY2xhc3NOYW1lPSJiZWF1dHktcnVsZSI+CisgICAgICAgIDxzcGFuPkJpb21hcmtlciBjb3JyZWxhdGlvbjwvc3Bhbj4KKyAgICAgICAgPHNwYW4gLz4KKyAgICAgICAgPHNwYW4+e2QudGFrZW5PbiA/IGBGcm9tIHlvdXIgcGFuZWwgwrcgJHtkLnRha2VuT259YCA6ICcnfTwvc3Bhbj4KICAgICAgIDwvZGl2PgogICAgICAge2QuaW5zaWdodHMubGVuZ3RoID09PSAwID8gKAogICAgICAgICA8cCBzdHlsZT17eyBmb250U2l6ZTogMTMsIG1hcmdpblRvcDogOCwgY29sb3I6ICd2YXIoLS1vay1pbmspJyB9fT7inJMgTm8gYmlvbWFya2VyIGZsYWdzIGFyZSBhZmZlY3RpbmcgeW91ciBza2luIG9yIGhhaXIgcmlnaHQgbm93IOKAlCBhIGdvb2QgZm91bmRhdGlvbi48L3A+CkBAIC0zNzUsMTAgKzM4MCwxNiBAQCBmdW5jdGlvbiBQcm9ncmVzc1ZpZXcoeyBlbnRyaWVzIH06IHsgZW50cmllczogQmVhdXR5UHJvZ3Jlc3NFbnRyeVtdIH0pIHsKICAgICA8L2Rpdj4KICAgKTsKICAgcmV0dXJuICgKLSAgICA8ZGl2IGNsYXNzTmFtZT0iY2FyZCIgc3R5bGU9e3sgbWFyZ2luQm90dG9tOiAxNCB9fT4KLSAgICAgIDxkaXYgc3R5bGU9e3sgZGlzcGxheTogJ2ZsZXgnLCBhbGlnbkl0ZW1zOiAnYmFzZWxpbmUnLCBnYXA6IDgsIGZsZXhXcmFwOiAnd3JhcCcgfX0+Ci0gICAgICAgIDxoMyBzdHlsZT17eyBmb250U2l6ZTogMTYsIG1hcmdpbjogMCB9fT7wn5OIIFByb2dyZXNzIHRpbWVsaW5lPC9oMz4KLSAgICAgICAgPHNwYW4gY2xhc3NOYW1lPSJtdXRlZCIgc3R5bGU9e3sgZm9udFNpemU6IDExLjUgfX0+e3NvcnRlZC5sZW5ndGh9IGNoZWNrLWlue3NvcnRlZC5sZW5ndGggPT09IDEgPyAnJyA6ICdzJ30gwrcgcmUtdXBsb2FkIHdlZWtseSB0byB0cmFjazwvc3Bhbj4KKyAgICA8ZGl2IGNsYXNzTmFtZT0iYmVhdXR5LXNoZWV0Ij4KKyAgICAgIHsvKiBBIFNIRUVULCBOT1QgQSBDQVJEIFdJVEggQU4gRU1PSkkgT04gSVQuIFRoaXMgaXMgdGhlIG9uZSB0aGluZyBvbiB0aGUKKyAgICAgICAgICBwYWdlIHNvbWVib2R5IGNvbWVzIGJhY2sgRk9SLCBhbmQgaXQgd2FzIHRoZSBsYXN0IG9iamVjdCBzdGlsbCB3ZWFyaW5nCisgICAgICAgICAgdGhlIGNpdHkncyBvcmRpbmFyeSBpZGlvbSDigJQgYSByb3VuZGVkIHdoaXRlIHRpbGUgaGVhZGVkIPCfk4ggaW4gdGhlCisgICAgICAgICAgbWlkZGxlIG9mIGEgc2V0IG9mIHByaW50cy4gU2FtZSBwYXBlciBhcyBldmVyeXRoaW5nIGVsc2Ugbm93LCBhbmQgdGhlCisgICAgICAgICAgaGVhZGVyIGlzIHRoZSBwbGF0ZSdzIG93biBydWxlLiAqL30KKyAgICAgIDxkaXYgY2xhc3NOYW1lPSJiZWF1dHktcnVsZSI+CisgICAgICAgIDxzcGFuPlByb2dyZXNzIHRpbWVsaW5lPC9zcGFuPgorICAgICAgICA8c3BhbiAvPgorICAgICAgICA8c3Bhbj57c29ydGVkLmxlbmd0aH0gY2hlY2staW57c29ydGVkLmxlbmd0aCA9PT0gMSA/ICcnIDogJ3MnfSDCtyByZS11cGxvYWQgd2Vla2x5PC9zcGFuPgogICAgICAgPC9kaXY+CiAgICAgICA8ZGl2IHN0eWxlPXt7IGRpc3BsYXk6ICdmbGV4JywgZ2FwOiAxMCwgb3ZlcmZsb3dYOiAnYXV0bycsIHBhZGRpbmc6ICcxMnB4IDAgNHB4JyB9fT4KICAgICAgICAge3NvcnRlZC5tYXAoKGUpID0+ICgKZGlmZiAtLWdpdCBhL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL3N0eWxlcy9sYXlvdXQuY3NzIGIvdG9nZXRoZXItY2l0eS1yZWFjdC9zcmMvc3R5bGVzL2xheW91dC5jc3MKaW5kZXggYjY2NTdlMy4uMzM5MzFhMiAxMDA2NDQKLS0tIGEvdG9nZXRoZXItY2l0eS1yZWFjdC9zcmMvc3R5bGVzL2xheW91dC5jc3MKKysrIGIvdG9nZXRoZXItY2l0eS1yZWFjdC9zcmMvc3R5bGVzL2xheW91dC5jc3MKQEAgLTc3MCwxNCArNzcwLDI3IEBACiAuYmVhdXR5LWxlYWYgYS50IHsgY29sb3I6IGluaGVyaXQ7IH0KIC5iZWF1dHktbGVhZiAubSB7IGZvbnQtc2l6ZTogMTAuNXB4OyBsZXR0ZXItc3BhY2luZzogLjA5ZW07IHRleHQtdHJhbnNmb3JtOiB1cHBlcmNhc2U7IGNvbG9yOiB2YXIoLS1tdXRlZCk7IG1pbi13aWR0aDogMDsgfQogLmJlYXV0eS1sZWFmIC5zIHsgbWFyZ2luLWxlZnQ6IGF1dG87IGZsZXg6IG5vbmU7IGZvbnQtc2l6ZTogOS41cHg7IGxldHRlci1zcGFjaW5nOiAuMjRlbTsgdGV4dC10cmFuc2Zvcm06IHVwcGVyY2FzZTsgY29sb3I6IHZhcigtLW11dGVkKTsgfQotLyogV2hhdCBhIGxlYWYgb3BlbnMgaXMgQ09OVEVOVCDigJQgcmVhZGluZ3MsIGluZ3JlZGllbnQgbm90ZXMsIGNhdXRpb25zIOKAlCBhbmQKLSAgIGNvbnRlbnQgaXMgcmVhZCBvbiBwYXBlciBpbiB0aGlzIGh1Yiwgbm90IG9mZiB0aGUgd2FsbC4gSXQgZ2V0cyBhIHNoZWV0IG9mCi0gICBpdHMgb3duIHJhdGhlciB0aGFuIHRoZSBwbGF0ZSdzIGZ1bGwgcG9zdGVyIGNocm9tZSwgYmVjYXVzZSBpdCBpcyB0aGUgaW5zaWRlCi0gICBvZiBhbiBpbmRleCBlbnRyeSBhbmQgbm90IGEgZmlmdGggcHJpbnQuICovCisvKiDilIDilIAgVEhFIFNIRUVUIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAorICAgQSBwbGF0ZSB3aXRoIG5vIHBvc3RlciBvbiBpdDogdGhlIHNhbWUgY3JlYW0gcGFwZXIsIHRoZSBzYW1lIGN1dCBlZGdlLCB0aGUKKyAgIHNhbWUgbGlmdCBvZmYgdGhlIHdhbGwsIGFuZCBub25lIG9mIHRoZSBtYXN0aGVhZC4gQ29udGVudCBpcyByZWFkIG9uIHBhcGVyIGluCisgICB0aGlzIGh1YiwgYW5kIHRoZSB0aGluZ3MgdGhhdCBhcmUgbmVpdGhlciBhIGNoYXB0ZXIgbm9yIGFuIGluZGV4IGVudHJ5IOKAlCB3aGF0CisgICBhIGxlYWYgb3BlbnMsIHRoZSBwcm9ncmVzcyBzdHJpcCwgdGhlIGRhdGVkIGhpc3RvcnksIHRoZSBiaW9tYXJrZXIgcGFuZWwg4oCUCisgICBhcmUgcmVhZCBvbiB0aGlzLgorCisgICBJVCBJUyBBIFRISVJEIFNVUkZBQ0UgT04gUFVSUE9TRSBBTkQgVEhFIExBU1QgT05FLiBQbGF0ZSBmb3IgdGhlIGZvdXIKKyAgIGNoYXB0ZXJzIHRoZSBvd25lciBkcmV3LCBsZWFmIGZvciB0aGUgY29udGVudHMgb2Ygb25lLCBzaGVldCBmb3IgZXZlcnl0aGluZworICAgdGhhdCBpcyBzaW1wbHkgY29udGVudC4gQSBmb3VydGggd291bGQgYmUgYSBkZWNpc2lvbiBub2JvZHkgY291bGQgZGVzY3JpYmUuICovCisuYmVhdXR5LXNoZWV0LAogLmJlYXV0eS1sZWFmLW9wZW4gewogICBiYWNrZ3JvdW5kOiB2YXIoLS1jYXJkKTsgYm9yZGVyOiAxcHggc29saWQgdmFyKC0tbGluZSk7IGJvcmRlci1yYWRpdXM6IDJweDsKLSAgYm94LXNoYWRvdzogdmFyKC0tZTEpOyBwYWRkaW5nOiAxNHB4IDE2cHggMTZweDsgbWFyZ2luOiAwIDAgMTZweDsKLX0KKyAgYm94LXNoYWRvdzogdmFyKC0tZTEpOyBwYWRkaW5nOiAxNnB4IDE4cHggMThweDsgbWFyZ2luOiAwIDAgMTRweDsKK30KKy5iZWF1dHktbGVhZi1vcGVuIHsgcGFkZGluZzogMTRweCAxNnB4IDE2cHg7IG1hcmdpbjogMCAwIDE2cHg7IH0KKy8qIEEgc2hlZXQncyBoZWFkZXIgaXMgdGhlIHBsYXRlJ3MgZm9vdCBydWxlLCByZXVzZWQ6IHRoZSBuYW1lIG9uIHRoZSBsZWZ0LCB3aGF0CisgICBpcyBpbiBpdCBvbiB0aGUgcmlnaHQuIE5vdCBhbiBlbW9qaSBhbmQgYSAxNnB4IGhlYWRpbmcg4oCUIHRoYXQgaXMgdGhlIGNpdHkncworICAgb3JkaW5hcnkgY2FyZCBpZGlvbSwgYW5kIG5leHQgdG8gYSBzZXQgb2YgcHJpbnRzIGl0IGlzIHRoZSBvbmUgb2JqZWN0IG9uIHRoZQorICAgcGFnZSB0aGF0IGNhbWUgZnJvbSBzb21ld2hlcmUgZWxzZS4gKi8KKy5iZWF1dHktc2hlZXQgPiAuYmVhdXR5LXJ1bGU6Zmlyc3QtY2hpbGQgeyBwYWRkaW5nLWJvdHRvbTogMTRweDsgfQogLyogT24gYSBwaG9uZSB0aGUgdGhyZWUgY2VsbHMgZG8gbm90IGZpdCBvbiBvbmUgbGluZSwgYW5kIGxldHRpbmcgdGhlbSB3cmFwIGluCiAgICBzb3VyY2Ugb3JkZXIgc3RyYW5kcyAiT3BlbiArIiBvbiBhIGxpbmUgb2YgaXRzIG93biB1bmRlciBhIGhhbGYtZW1wdHkgb25lLgogICAgVGhlIG5hbWUgYW5kIHRoZSB3YXkgaW4gc3RheSB0b2dldGhlciBvbiB0aGUgZmlyc3Qgcm93IOKAlCB0aGV5IGFyZSB0aGUgdHdvCmRpZmYgLS1naXQgYS90b2dldGhlci1jaXR5LXJlYWN0L3NyYy9zdHlsZXMvcmVsaWVmLmNzcyBiL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL3N0eWxlcy9yZWxpZWYuY3NzCmluZGV4IDBhNmRiNzIuLjc1NGI0OTkgMTAwNjQ0Ci0tLSBhL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL3N0eWxlcy9yZWxpZWYuY3NzCisrKyBiL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL3N0eWxlcy9yZWxpZWYuY3NzCkBAIC0yOTg3LDkgKzI5ODcsMTggQEAgdGV4dGFyZWEuZy1maWVsZCB7IHJlc2l6ZTogbm9uZTsgbGluZS1oZWlnaHQ6IDEuNTU7IH0KICAgIGNyZWFtIGNhcmQgcHJpbnRlZCBpbiBuZWFyLXdoaXRlLiBgLmNhcmRgIGNvdmVycyBtb3N0IG9mIHRoZSBhcHBsaWNhdGlvbiwKICAgIHRoZSB0d28gYmVhdXR5IGZhY2VzIGNvdmVyIHRoZSBwbGF0ZXMsIGFuZCB0aGUgbGFzdCB0aHJlZSBhcmUgdGhlIHRoaW5ncwogICAgdGhhdCBvcGVuIE9WRVIgYSBwYWdlIGFuZCB0aGVyZWZvcmUgbmV2ZXIgaW5oZXJpdCBmcm9tIG9uZS4gKi8KKy8qIFRISVMgTElTVCBCVVJORUQgVVMgT05DRSwgVEhFIFdFRUsgSVQgV0FTIFdSSVRURU4uIFRoZSByb3V0aW5lJ3Mgc3RlcCBjYXJkcworICAgYW5kIHRoZSBodWIncyBjcmVhbSBzaGVldHMgd2VyZSBhZGRlZCBhcyBuZXcgY2xhc3NlcyBhbmQgbmVpdGhlciBqb2luZWQgdGhpcworICAgbGlzdCwgc28gYm90aCBpbmhlcml0ZWQgdGhlIHdhbGwncyBuZWFyLXdoaXRlIGluayBvbnRvIGNyZWFtIHBhcGVyIOKAlCBwcm9kdWN0CisgICBuYW1lcyB5b3UgY291bGQgYmFyZWx5IHNlZSwgb3JkZXIgbnVtYmVycyB0aGF0IHZhbmlzaGVkIOKAlCBhbmQgZXZlcnkgbG9jYWwKKyAgIHNjcmVlbnNob3QgbWlzc2VkIGl0IGJlY2F1c2UgdGhlIGhhcm5lc3MgcmVzdG9yZWQgdGhlIGluayBieSBoYW5kLiBUaGUgcnVsZToKKyAgIEFOWSBjbGFzcyBpbiB0aGlzIGh1YiB0aGF0IHBhaW50cyAtLWNhcmQgb3IgLS1wYXBlciBpcyBhIGxpdCBzdXJmYWNlIGFuZCBpdHMKKyAgIG5hbWUgYmVsb25ncyBoZXJlLCB0aGUgc2FtZSBjb21taXQgaXQgaXMgYm9ybi4gVGhlIHRlc3Qgbm93IHJlYWRzIHRoaXMgbGlzdC4gKi8KIFtkYXRhLWh1Yj0iYmVhdXR5Il0gLmNhcmQsCiBbZGF0YS1odWI9ImJlYXV0eSJdIC5iZWF1dHktcGxhdGUsCitbZGF0YS1odWI9ImJlYXV0eSJdIC5iZWF1dHktc2hlZXQsCiBbZGF0YS1odWI9ImJlYXV0eSJdIC5iZWF1dHktbGVhZi1vcGVuLAorW2RhdGEtaHViPSJiZWF1dHkiXSAucm91dGluZS1jYXJkLAogW2RhdGEtaHViPSJiZWF1dHkiXSAubW9kYWwsCiBbZGF0YS1odWI9ImJlYXV0eSJdIC5zaGVldCwKIFtkYXRhLWh1Yj0iYmVhdXR5Il0gLnRjLXNpZGUgewo=
B64EOF
WANT="bf076ff1df668353516c0176c1f36329469c91daf3d374cae93aedf46e38490d"
GOT="$(shasum -a 256 "$PATCH" | awk '{print $1}')"
[ "$GOT" = "$WANT" ] || { echo "!! Patch is corrupt."; echo "   want $WANT"; echo "   got  $GOT"; exit 1; }
echo "== patch verified"
git apply --check -C1 "$PATCH" || { echo "!! Patch does not apply cleanly. Nothing written."; exit 1; }
git apply -C1 "$PATCH"
echo "== applied"

echo "== gates: the web app"
cd together-city-react
npx tsc --noEmit
npx vitest run
node scripts/a11y-audit.mjs
node scripts/motion-ceiling.mjs
node scripts/lint-ceiling.mjs
npx vite build
cd ..

git add -A together-city-react/src
git commit -F - <<'MSG'
The paper under the ink

Three defects visible on the live routine page, and the missing half of an
earlier land script, in one cut — built against this machine's actual tree
rather than the tree the earlier scripts assumed.

── THE GHOST TEXT ──────────────────────────────────────────────────────────────

The gallery wall re-points --ink to a near-white by inheritance, and every lit
surface is supposed to put the paper's near-black back through one list in
relief.css. The routine's step cards and the hub's cream sheets were born after
that list and never joined it, so product names and prices rendered in the
wall's ink on cream paper — nearly invisible — and the order badges vanished
into their own discs.

Every local screenshot missed it, because the harness restored the ink BY HAND
while the shipped stylesheet did not. That is the second time a hand-rolled
harness has vouched for something the real page does differently; the fix for
that half is a test that reads the actual list in relief.css and fails on any
beauty surface class missing from it.

── THE FLOATING CHECKOUT ──────────────────────────────────────────────────────

Off the viewport, phone and desk alike. It was position: sticky with a heavy
shadow, riding up the routine covering the very steps somebody was reading — a
summary of the bag parked across the products they were deciding whether to put
in it. It is the last block of the page now: you reach it by getting to the
end, which is also when you have finished deciding.

This fix had already been written and never landed. land-gallery-wall.sh was
rebuilt twice under one commit name; the copy this machine ran was the first
build, and the rebuilt ones then keyed on the name and exited "nothing to do".
This patch was built from the bytes actually on this machine, staged tonight.

── THE IMAGE SCALE ────────────────────────────────────────────────────────────

The card's well stretched every photograph to 100% of itself, which inflates a
small retailer JPEG into a blur. A shot shows at its natural size now, capped
at the well. And the photography is white-ground cut-outs, so the white melts
into the paper (mix-blend multiply) instead of floating as a rectangle on
cream, with no-case for the same reason the gem sheets wear it — an outline
drawn round a cut-out is an outline round nothing.

── AND THE SHEETS THE FIRST BUILD NEVER CARRIED ───────────────────────────────

The progress timeline, the dated history and the biomarker panel move off the
city's rounded emoji cards onto the hub's cream sheet, and the sheet CSS the
routine page has been referencing since the cards landed actually exists now.

Backend untouched: no route, no schema, no query changed.
MSG

echo "== committed"
cat <<'DONE'

===============================================================
 Landed: The paper under the ink
 Push — Vercel rebuilds. /beauty/routine: dark ink on the cards,
 photographs at their own size, checkout at the end of the page.
===============================================================

DONE
