#!/bin/bash
# land-budget-buys-too.sh — every row of the budget list gets a way in, and it
# is the same door as everywhere else.
#
# WEB APP ONLY (together-city-react). Vercel.
# PRECONDITION: land-gem-checkout.sh.
set -euo pipefail

cd "$(dirname "$0")"
[ -d together-city-chat ] || { echo "!! Run this from the Together-Ai repo root."; exit 1; }

if [ -f .git/index.lock ] && [ ! -s .git/index.lock ]; then
  echo "== clearing a stale empty .git/index.lock"
  rm -f .git/index.lock
fi

NEEDS="One door into the studio"
LOG="$(git log --oneline -40)"
case "$LOG" in
  *"$NEEDS"*) echo "== \"$NEEDS\" is already here. Nothing to do."; exit 0 ;;
esac
case "$LOG" in
  *"A locked commission has to be waiting somewhere"*) ;;
  *) echo "!! Run land-gem-checkout.sh first — this is written against the tree it produces."; exit 1 ;;
esac

ALLOWED='^ M together-city-react/(public/assets/img/(apple-touch-icon-180|tc-icon-1024|tc-icon-192|tc-icon-512|tc-icon-maskable-512)\.png|public/downloads/TogetherCity\.apk)$'
DIRTY="$(git status --porcelain \
  | grep -Ev '^\?\? (land-.*\.sh|push-.*\.sh|.*\.patch)$' \
  | grep -Ev "$ALLOWED" || true)"
if [ -n "$DIRTY" ]; then
  echo "!! The tree carries changes this script did not expect:"; echo "$DIRTY"; exit 1
fi

PATCH="$(mktemp "${TMPDIR:-/tmp}/land.XXXXXX")"
trap 'rm -f "$PATCH"' EXIT
cat <<'B64EOF' | tr -d '\n' | openssl base64 -d -A > "$PATCH"
ZGlmZiAtLWdpdCBhL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL2FwcC9vbmUtc3RvbmUtYW5zd2VyLnRlc3QudHMgYi90b2dldGhlci1jaXR5LXJlYWN0L3NyYy9hcHAvb25lLXN0b25lLWFuc3dlci50ZXN0LnRzCmluZGV4IGRjMTk2YjYuLmZmNmVmMTEgMTAwNjQ0Ci0tLSBhL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL2FwcC9vbmUtc3RvbmUtYW5zd2VyLnRlc3QudHMKKysrIGIvdG9nZXRoZXItY2l0eS1yZWFjdC9zcmMvYXBwL29uZS1zdG9uZS1hbnN3ZXIudGVzdC50cwpAQCAtMjI5LDYgKzIyOSwzMiBAQCBkZXNjcmliZSgndGhlIGdlbXN0b25lIGJ1ZGdldCcsICgpID0+IHsKICAgICBleHBlY3QoZ2VtcykudG9NYXRjaCgvc2hvcnQgb2YgdGhlIGNoZWFwZXN0IHdheSBpbi8pOwogICB9KTsKIAorICBpdCgnc2VuZHMgdGhlIGJ1ZGdldCByb3dzIHRvIHRoZSBzdHVkaW8sIGxpa2UgZXZlcnkgb3RoZXIgYWRkLXRvLWNhcnQnLCAoKSA9PiB7CisgICAgLyoqCisgICAgICogT05FIERPT1IuIE5vdGhpbmcgaW4gdGhpcyBodWIgaXMgZXZlciBsb2NrZWQgd2l0aG91dCBzb21lYm9keSBoYXZpbmcKKyAgICAgKiBjaG9zZW4gaG93IGl0IGlzIHdvcm4g4oCUIGxvY2tpbmcgYSBsb29zZSBzdG9uZSBzdHJhaWdodCBmcm9tIGEgYnVkZ2V0IHJvdworICAgICAqIHdvdWxkIGRlY2lkZSB0aGF0IGZvciB0aGVtLiBBbmQgdGhlcmUgaXMgbm8gImFkZCBhbGwiOiBmb3VyIHN0b25lcyBhcmUKKyAgICAgKiBmb3VyIGNvbW1pc3Npb25zIHdpdGggZm91ciBzZXRzIG9mIGNob2ljZXMgaW4gdGhlbSwgYW5kIGEgYnV0dG9uIHRoYXQKKyAgICAgKiBsb2NrZWQgYWxsIG9mIHRoZW0gd291bGQgaGF2ZSB0byBpbnZlbnQgZXZlcnkgb25lLgorICAgICAqLworICAgIGV4cGVjdChnZW1zKS50b01hdGNoKC9BZGQgdG8gY2FydC8pOworICAgIGV4cGVjdChnZW1zKS5ub3QudG9NYXRjaCgvd29ybjogJ2xvb3NlJywgc2hhcGU6ICdvdmFsJywgZ3JhZGU6IDAvKTsKKyAgICBleHBlY3QoZ2Vtcykubm90LnRvTWF0Y2goL2xvY2tcLm11dGF0ZS8pOworICAgIGV4cGVjdChnZW1zKS50b01hdGNoKC9cJFx7cGlja1wuZ2VtXC5pZFx9XC9kZXNpZ24vKTsKKyAgfSk7CisKKyAgaXQoJ3NheXMgdGhlIGJ1ZGdldCBjb3ZlcnMgc3RvbmVzIGFuZCBub3Qgc2V0dGluZ3MnLCAoKSA9PiB7CisgICAgLy8gQSBidWRnZXQgbGluZSBxdWlldGx5IGV4Y2x1ZGluZyBhIOKCuTU2LDAwMCBzZXR0aW5nIHdvdWxkIGJlIHRoZSB3b3JzdCBraW5kCisgICAgLy8gb2YgYWNjdXJhdGUuCisgICAgZXhwZWN0KGdlbXMpLnRvTWF0Y2goL1N0b25lcyBvbmx5Lyk7CisgICAgZXhwZWN0KGdlbXMpLnRvTWF0Y2goL2FkZHMgYSB3ZWlnaHQgb2YgZ29sZCB0aGF0IGNhbiBjb3N0IG1vcmUgdGhhbiB0aGUgc3RvbmUvKTsKKyAgfSk7CisKKyAgaXQoJ3NheXMgd2hlbiBhIHN0b25lIGlzIGFscmVhZHkgbG9ja2VkIGluc3RlYWQgb2Ygb2ZmZXJpbmcgaXQgdHdpY2UnLCAoKSA9PiB7CisgICAgZXhwZWN0KGdlbXMpLnRvTWF0Y2goL2luQ2FydFwuaGFzLyk7CisgICAgZXhwZWN0KGdlbXMpLnRvTWF0Y2goL0luIGNoZWNrb3V0Lyk7CisgIH0pOworCiAgIGl0KCdkb2VzIG5vdCBzYXZlIHRoZSBudW1iZXInLCAoKSA9PiB7CiAgICAgLy8gVGhlIGJlYXV0eSBodWIncyBidWRnZXQgaXMgYSBzdGFuZGluZyBtb250aGx5IGxpbWl0IHRoZSBlbmdpbmUgcGxhbnMKICAgICAvLyBhZ2FpbnN0LiBUaGlzIGlzIHNvbWVib2R5IG1vdmluZyBhIHNsaWRlciB0byBzZWUgd2hhdCBhIGZpZ3VyZSBidXlzLCBhbmQKZGlmZiAtLWdpdCBhL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL2ZlYXR1cmVzL2FzdHJvbG9neS9wYWdlcy9Bc3Ryb0dlbXN0b25lcy50c3ggYi90b2dldGhlci1jaXR5LXJlYWN0L3NyYy9mZWF0dXJlcy9hc3Ryb2xvZ3kvcGFnZXMvQXN0cm9HZW1zdG9uZXMudHN4CmluZGV4IGViYjhmNjUuLmQ3ZDE5YTkgMTAwNjQ0Ci0tLSBhL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL2ZlYXR1cmVzL2FzdHJvbG9neS9wYWdlcy9Bc3Ryb0dlbXN0b25lcy50c3gKKysrIGIvdG9nZXRoZXItY2l0eS1yZWFjdC9zcmMvZmVhdHVyZXMvYXN0cm9sb2d5L3BhZ2VzL0FzdHJvR2Vtc3RvbmVzLnRzeApAQCAtMSw3ICsxLDcgQEAKIGltcG9ydCB7IHVzZUlkLCB1c2VNZW1vLCB1c2VTdGF0ZSB9IGZyb20gJ3JlYWN0JzsKIGltcG9ydCB7IExpbmsgfSBmcm9tICdyZWFjdC1yb3V0ZXItZG9tJzsKIGltcG9ydCB7IEJ1dHRvbiwgQ2FyZCwgU3Bpbm5lciB9IGZyb20gJ0AvY29tcG9uZW50cy91aSc7Ci1pbXBvcnQgeyB1c2VBc3Ryb0dlbXN0b25lcyB9IGZyb20gJy4uL2hvb2tzJzsKK2ltcG9ydCB7IHVzZUFzdHJvR2Vtc3RvbmVzLCB1c2VHZW1DYXJ0IH0gZnJvbSAnLi4vaG9va3MnOwogaW1wb3J0IHsgQXN0cm9IZWFkZXIsIEFzdHJvVGFicywgTmVlZHNQcm9maWxlQ2FyZCB9IGZyb20gJy4uL3NoYXJlZCc7CiBpbXBvcnQgdHlwZSB7IEdlbUF0V2VpZ2h0LCBHZW1Qcmlvcml0eSwgR2VtUmVjb21tZW5kYXRpb24sIEdlbVJvbGUsIEdlbXN0b25lc1Jlc3BvbnNlIH0gZnJvbSAnLi4vYXBpJzsKIApAQCAtMzQxLDYgKzM0MSwxNyBAQCBmdW5jdGlvbiBTdG9uZVNoZWV0KHsgcmVjIH06IHsgcmVjOiBHZW1SZWNvbW1lbmRhdGlvbiB9KSB7CiAgKiBub3QgZml0LCBhbmQgdGhlbiB0aGUgREVBUkVTVCBzdWJzdGl0dXRlIHRoYXQgZG9lcywgYmVjYXVzZSB3aXRoaW4gdGhlIHNhbWUKICAqIHBsYW5ldCBhIGJldHRlciBzdG9uZSBpcyBhIGJldHRlciBzdG9uZS4KICAqCisgKiBJVCBQUklDRVMgU1RPTkVTIEFORCBOT1RISU5HIEVMU0UsIEFORCBJVCBTQVlTIFNPLiBFdmVyeSBmaWd1cmUgaGVyZSBpcyB0aGUKKyAqIHN0b25lIGFsb25lLCBhdCB0aGUgd2VpZ2h0IHByZXNjcmliZWQgYW5kIHRoZSBwbGFpbmVzdCBncmFkZSBvZiBpdC4gQSByaW5nIG9yCisgKiBhIHBlbmRhbnQgYWRkcyBhIHdlaWdodCBvZiBnb2xkIHRoYXQgY2FuIGNvc3QgbW9yZSB0aGFuIHRoZSBzdG9uZSBkaWQg4oCUIGEKKyAqIGJ1ZGdldCBsaW5lIHF1aWV0bHkgZXhjbHVkaW5nIGEg4oK5NTYsMDAwIHNldHRpbmcgd291bGQgYmUgdGhlIHdvcnN0IGtpbmQgb2YKKyAqIGFjY3VyYXRlIOKAlCBzbyB0aGUgc2V0dGluZyBpcyBwcmljZWQgaW4gdGhlIHN0dWRpbywgd2hlcmUgdGhlIG1vdW50IGFuZCB0aGUKKyAqIHNpemUgdGhhdCBkZWNpZGUgaXQgYXJlIGNob3Nlbi4KKyAqCisgKiBXSElDSCBJUyBBTFNPIFdIRVJFICJBREQgVE8gQ0FSVCIgR09FUyBGUk9NIEhFUkUuIEV2ZXJ5IG9uZSBvZiB0aG9zZSBidXR0b25zCisgKiBpbiB0aGlzIGh1YiBsYW5kcyBpbiB0aGUgc2FtZSBwbGFjZSwgYW5kIG5vdGhpbmcgaXMgZXZlciBsb2NrZWQgd2l0aG91dAorICogc29tZWJvZHkgaGF2aW5nIGNob3NlbiBob3cgaXQgaXMgd29ybi4KKyAqCiAgKiBUSElTIEJVREdFVCBJUyBOT1QgU0FWRUQsIGFuZCB0aGF0IGlzIHRoZSBkaWZmZXJlbmNlIGJldHdlZW4gaXQgYW5kIHRoZQogICogYmVhdXR5IGh1YidzLiBUaGF0IG9uZSBpcyBhIHN0YW5kaW5nIG1vbnRobHkgbGltaXQgdGhlIGVuZ2luZSBwbGFucyBhZ2FpbnN0OwogICogdGhpcyBpcyBzb21lYm9keSBtb3ZpbmcgYSBzbGlkZXIgdG8gc2VlIHdoYXQgYSBudW1iZXIgYnV5cy4gU3RvcmluZyBpdCB3b3VsZApAQCAtMzc3LDYgKzM4OCw5IEBAIGZ1bmN0aW9uIHBsYW5XaXRoaW4ocmVjczogR2VtUmVjb21tZW5kYXRpb25bXSwgYnVkZ2V0SW5yOiBudW1iZXIpOiB7IHBpY2tzOiBBZmZvCiAKIGZ1bmN0aW9uIEJ1ZGdldFBpY2tlcih7IGRhdGEgfTogeyBkYXRhOiBHZW1zdG9uZXNSZXNwb25zZSB9KSB7CiAgIGNvbnN0IHJlY3MgPSBkYXRhLnJlY29tbWVuZGF0aW9uczsKKyAgY29uc3QgY2FydCA9IHVzZUdlbUNhcnQoKTsKKyAgLyoqIEFscmVhZHkgbG9ja2VkLCBzbyBhIHJvdyBjYW4gc2F5IHNvIHJhdGhlciB0aGFuIG9mZmVyaW5nIGl0IHR3aWNlLiAqLworICBjb25zdCBpbkNhcnQgPSBuZXcgU2V0KChjYXJ0LmRhdGE/LmxpbmVzID8/IFtdKS5tYXAoKGwpID0+IGwuZ2VtSWQpKTsKICAgLyoqIFRoZSB3aG9sZSBzZXQgYXQgaXRzIGJlc3Qg4oCUIHRoZSB0b3Agb2YgdGhlIHNsaWRlciwgc28gaXQgYWx3YXlzIHNwYW5zCiAgICAqICAibm90aGluZyIgdG8gImV2ZXJ5dGhpbmcsIGF0IHRoZSBmaW5lc3QgcXVhbGl0eSB0aGlzIHNoZWxmIHNlbGxzIi4gKi8KICAgY29uc3QgY2VpbGluZyA9IHVzZU1lbW8oKCkgPT4gewpAQCAtNDUzLDYgKzQ2NywyMSBAQCBmdW5jdGlvbiBCdWRnZXRQaWNrZXIoeyBkYXRhIH06IHsgZGF0YTogR2Vtc3RvbmVzUmVzcG9uc2UgfSkgewogICAgICAgICAgICAgPHNwYW4gc3R5bGU9e3sgZm9udFNpemU6IDEzLCBmb250V2VpZ2h0OiA3MDAsIG1pbldpZHRoOiA4NCwgdGV4dEFsaWduOiAncmlnaHQnIH19PgogICAgICAgICAgICAgICB7cGljayA/IGBmcm9tICR7cnVwZWVzKHBpY2suZnJvbUluciBhcyBudW1iZXIpfWAgOiAn4oCUJ30KICAgICAgICAgICAgIDwvc3Bhbj4KKyAgICAgICAgICAgIHsvKiBUSEUgU0FNRSBET09SIEFTIEVWRVJZIE9USEVSICJBREQgVE8gQ0FSVCIgSU4gVEhJUyBIVUIsIGFuZAorICAgICAgICAgICAgICAgIHRoYXQgY29uc2lzdGVuY3kgaXMgdGhlIHBvaW50OiBub3RoaW5nIGlzIGV2ZXIgbG9ja2VkIHdpdGhvdXQKKyAgICAgICAgICAgICAgICBzb21lYm9keSBoYXZpbmcgY2hvc2VuIGhvdyBpdCBpcyB3b3JuLiBMb2NraW5nIGEgbG9vc2Ugc3RvbmUKKyAgICAgICAgICAgICAgICBmcm9tIGhlcmUgd291bGQgYmUgcXVpZXRseSBkZWNpZGluZyB0aGF0IGZvciB0aGVtIOKAlCBhbmQgdGhlCisgICAgICAgICAgICAgICAgZmlndXJlIGJlc2lkZSBpdCBpcyB0aGUgTE9PU0UgcHJpY2UsIHNvIGEgcmluZyBib3VnaHQgdGhhdCB3YXkKKyAgICAgICAgICAgICAgICB3b3VsZCBhcnJpdmUgd2l0aCBhIHdlaWdodCBvZiBnb2xkIHRoaXMgc2VjdGlvbiBuZXZlciBzaG93ZWQuICovfQorICAgICAgICAgICAge3BpY2sgJiYgKAorICAgICAgICAgICAgICBpbkNhcnQuaGFzKHBpY2suZ2VtLmlkKQorICAgICAgICAgICAgICAgID8gPHNwYW4gY2xhc3NOYW1lPSJtdXRlZCIgc3R5bGU9e3sgZm9udFNpemU6IDExLjUsIGZvbnRXZWlnaHQ6IDcwMCwgbWluV2lkdGg6IDkyLCB0ZXh0QWxpZ246ICdyaWdodCcgfX0+4pyTIEluIGNoZWNrb3V0PC9zcGFuPgorICAgICAgICAgICAgICAgIDogKAorICAgICAgICAgICAgICAgICAgPExpbmsgdG89e2AvYXN0cm9sb2d5L2dlbXN0b25lcy8ke3BpY2suZ2VtLmlkfS9kZXNpZ25gfT4KKyAgICAgICAgICAgICAgICAgICAgPEJ1dHRvbiB2YXJpYW50PSJsaW5lIiBzaXplPSJzbSI+QWRkIHRvIGNhcnQ8L0J1dHRvbj4KKyAgICAgICAgICAgICAgICAgIDwvTGluaz4KKyAgICAgICAgICAgICAgICApCisgICAgICAgICAgICApfQogICAgICAgICAgIDwvbGk+CiAgICAgICAgICkpfQogICAgICAgPC91bD4KQEAgLTQ2Myw2ICs0OTIsMTcgQEAgZnVuY3Rpb24gQnVkZ2V0UGlja2VyKHsgZGF0YSB9OiB7IGRhdGE6IEdlbXN0b25lc1Jlc3BvbnNlIH0pIHsKICAgICAgICAgPC9zcGFuPgogICAgICAgICA8c3BhbiBzdHlsZT17eyBtYXJnaW5MZWZ0OiAnYXV0bycsIGZvbnRTaXplOiAyMiwgZm9udFdlaWdodDogODAwLCBsZXR0ZXJTcGFjaW5nOiAnLS4wMWVtJyB9fT57cnVwZWVzKHRvdGFsSW5yKX08L3NwYW4+CiAgICAgICA8L2Rpdj4KKworICAgICAgey8qIE5PICJBREQgQUxMIiBCVVRUT04sIGFuZCBpdHMgYWJzZW5jZSBpcyB0aGUgc2FtZSBkZWNpc2lvbi4gRm91ciBzdG9uZXMKKyAgICAgICAgICBhcmUgZm91ciBjb21taXNzaW9ucyB3aXRoIGZvdXIgc2V0cyBvZiBjaG9pY2VzIGluIHRoZW07IG9uZSBidXR0b24KKyAgICAgICAgICB0aGF0IGxvY2tlZCBhbGwgb2YgdGhlbSB3b3VsZCBoYXZlIHRvIGludmVudCBldmVyeSBvbmUgb2YgdGhvc2UuICovfQorICAgICAgeyhjYXJ0LmRhdGE/LmNvdW50ID8/IDApID4gMCAmJiAoCisgICAgICAgIDxkaXYgc3R5bGU9e3sgbWFyZ2luVG9wOiAxNCB9fT4KKyAgICAgICAgICA8TGluayB0bz0iL2FzdHJvbG9neS9nZW0tY2hlY2tvdXQiIHN0eWxlPXt7IGZvbnRTaXplOiAxMi41LCBmb250V2VpZ2h0OiA3MDAgfX0+CisgICAgICAgICAgICBHbyB0byBjaGVja291dCAoe2NhcnQuZGF0YT8uY291bnR9KSDihpIKKyAgICAgICAgICA8L0xpbms+CisgICAgICAgIDwvZGl2PgorICAgICAgKX0KICAgICAgIHtidWRnZXQgLSB0b3RhbEluciA+IDAgJiYgZ290Lmxlbmd0aCA9PT0gcGlja3MubGVuZ3RoICYmICgKICAgICAgICAgPHAgY2xhc3NOYW1lPSJtdXRlZCIgc3R5bGU9e3sgZm9udFNpemU6IDEyLCBsaW5lSGVpZ2h0OiAxLjYsIG1hcmdpbjogJzEwcHggMCAwJyB9fT4KICAgICAgICAgICB7cnVwZWVzKGJ1ZGdldCAtIHRvdGFsSW5yKX0gbGVmdCBvdmVyLiBFdmVyeXRoaW5nIHlvdXIgY2hhcnQgYXNrcyBmb3IgaXMgY292ZXJlZCDigJQgdGhlIHJlc3QKQEAgLTQ3MCw4ICs1MTAsMTEgQEAgZnVuY3Rpb24gQnVkZ2V0UGlja2VyKHsgZGF0YSB9OiB7IGRhdGE6IEdlbXN0b25lc1Jlc3BvbnNlIH0pIHsKICAgICAgICAgPC9wPgogICAgICAgKX0KICAgICAgIDxwIGNsYXNzTmFtZT0ibXV0ZWQiIHN0eWxlPXt7IGZvbnRTaXplOiAxMS41LCBsaW5lSGVpZ2h0OiAxLjYsIG1hcmdpbjogJzEycHggMCAwJyB9fT4KLSAgICAgICAgUHJpY2VzIGFyZSB0aGUgYm90dG9tIG9mIGVhY2ggc3RvbmUmcnNxdW87cyByYW5nZSBhdCB0aGUgd2VpZ2h0IHlvdSBhcmUgcHJlc2NyaWJlZC4gQSBmaW5lcgotICAgICAgICBncmFkZSBvZiB0aGUgc2FtZSBzdG9uZSBjb3N0cyBtb3JlOyB0aGUgc2hlZXRzIGFib3ZlIGdpdmUgYm90aCBlbmRzLgorICAgICAgICBTdG9uZXMgb25seSwgYXQgdGhlIGJvdHRvbSBvZiBlYWNoIG9uZSZyc3F1bztzIHJhbmdlIGFuZCB0aGUgd2VpZ2h0IHlvdSBhcmUgcHJlc2NyaWJlZC4KKyAgICAgICAgU2V0dGluZyBvbmUgYXMgYSByaW5nIG9yIGEgcGVuZGFudCBhZGRzIGEgd2VpZ2h0IG9mIGdvbGQgdGhhdCBjYW4gY29zdCBtb3JlIHRoYW4gdGhlIHN0b25lCisgICAgICAgIGRpZCDigJQgdGhhdCBpcyBwcmljZWQgaW4gdGhlIHN0dWRpbywgd2hlcmUgdGhlIG1vdW50IGFuZCB0aGUgc2l6ZSB0aGF0IGRlY2lkZSBpdCBhcmUgY2hvc2VuLAorICAgICAgICBhbmQgd2hlcmUgdGhlc2UgYnV0dG9ucyB0YWtlIHlvdS4gQSBmaW5lciBncmFkZSBvZiB0aGUgc2FtZSBzdG9uZSBjb3N0cyBtb3JlOyB0aGUgc2hlZXRzCisgICAgICAgIGFib3ZlIGdpdmUgYm90aCBlbmRzLgogICAgICAgPC9wPgogICAgIDwvQ2FyZD4KICAgKTsK
B64EOF
WANT="415f4806076d90dc8f62a71b460be7a4b63be7fb8db1c949563ce7c713682802"
GOT="$(shasum -a 256 "$PATCH" | awk '{print $1}')"
[ "$GOT" = "$WANT" ] || { echo "!! Patch is corrupt."; echo "   want $WANT"; echo "   got  $GOT"; exit 1; }
echo "== patch verified"
git apply --check -C1 "$PATCH" || { echo "!! Patch does not apply cleanly. Nothing written."; exit 1; }
git apply -C1 "$PATCH"
echo "== applied"

echo "== gates: the web app"
cd together-city-react
npx tsc --noEmit
npx vitest run
node scripts/a11y-audit.mjs
node scripts/motion-ceiling.mjs
node scripts/lint-ceiling.mjs
npx vite build
cd ..

git add together-city-react/src/features/astrology together-city-react/src/app/one-stone-answer.test.ts
git commit -F - <<'MSG'
One door into the studio

The budget list worked out what a number buys and then had nothing to do about
it. Every row now carries the same "Add to cart" as the sheets above, and it
goes to the same place — the studio for that stone.

THAT SAMENESS IS THE DECISION. The first version of this locked straight from
the row, and it locked a LOOSE stone, because the figure beside it is the loose
price. Two things wrong with that. It decides how somebody wears their stone
without asking, which is the one question this whole flow exists to ask. And a
ring bought that way would arrive with a weight of gold the budget section never
showed — on a red coral at 18,000, the 22 carat setting is another 56,000.

A row that has already been locked says so instead of offering it again.

NO "ADD ALL" BUTTON, for the same reason. Four stones are four commissions with
four sets of choices in them, and one button that locked all of them would have
to invent every one.

And the section says outright what it is pricing: stones only, at the bottom of
each one's range and the weight the chart prescribes. A budget line quietly
excluding a 56,000 setting would be the worst kind of accurate.
MSG

echo "== committed"
cat <<'DONE'

===============================================================
 Landed: One door into the studio
===============================================================

DONE
