#!/bin/bash
# land-swipe-unmatch.sh — swipe a dating chat aside to reveal Unmatch. The
# swipe reveals; the button asks once; nothing destructive happens on release.
# First use of framer-motion in this codebase, plus the guard CLAUDE.md asks
# for against hand-typed motion timings.
#
# FRONTEND ONLY (together-city-react). Push, and Vercel ships it.
set -euo pipefail

cd "$(dirname "$0")"
[ -d together-city-react ] || { echo "!! Run this from the Together-Ai repo root."; exit 1; }

NEEDS="Swipe a match aside, and be asked before it ends"
LOG="$(git log --oneline -40)"
case "$LOG" in
  *"$NEEDS"*) echo "== \"$NEEDS\" is already here. Nothing to do."; exit 0 ;;
esac
DIRTY="$(git status --porcelain | grep -Ev '^\?\? (land-.*\.sh|push-.*\.sh|.*\.patch)$' || true)"
if [ -n "$DIRTY" ]; then
  echo "!! Working tree is dirty. Commit or stash first:"; echo "$DIRTY"; exit 1
fi

# framer-motion is declared in package.json but may not be on disk yet — this is
# the first code that imports it, so a missing install fails the build rather
# than this script, which is a worse place to find out.
if [ ! -d together-city-react/node_modules/framer-motion ]; then
  echo "== framer-motion is declared but not installed — running npm install first"
  (cd together-city-react && npm install --no-audit --no-fund)
fi

PATCH="$(mktemp "${TMPDIR:-/tmp}/land.XXXXXX")"
trap 'rm -f "$PATCH"' EXIT
cat <<'B64EOF' | tr -d '\n' | openssl base64 -d -A > "$PATCH"
LS0tIGEvdG9nZXRoZXItY2l0eS1yZWFjdC9zcmMvZmVhdHVyZXMvZGF0aW5nL3BhZ2VzL0RhdGluZ0NoYXRzLnRzeAorKysgYi90b2dldGhlci1jaXR5LXJlYWN0L3NyYy9mZWF0dXJlcy9kYXRpbmcvcGFnZXMvRGF0aW5nQ2hhdHMudHN4CkBAIC0xLDQgKzEsNSBAQAotaW1wb3J0IHsgdXNlRWZmZWN0LCB1c2VNZW1vLCB1c2VSZWYsIHVzZVN0YXRlIH0gZnJvbSAncmVhY3QnOworaW1wb3J0IHsgdXNlQ2FsbGJhY2ssIHVzZUVmZmVjdCwgdXNlTWVtbywgdXNlUmVmLCB1c2VTdGF0ZSB9IGZyb20gJ3JlYWN0JzsKK2ltcG9ydCB7IGFuaW1hdGUsIG1vdGlvbiwgdXNlTW90aW9uVmFsdWUgfSBmcm9tICdmcmFtZXItbW90aW9uJzsKIGltcG9ydCB7IExpbmssIHVzZVNlYXJjaFBhcmFtcyB9IGZyb20gJ3JlYWN0LXJvdXRlci1kb20nOwogaW1wb3J0IHsgQnV0dG9uLCBTcGlubmVyLCBFbXB0eVN0YXRlIH0gZnJvbSAnQC9jb21wb25lbnRzL3VpJzsKIGltcG9ydCB7IHVzZU1lIH0gZnJvbSAnQC9hcGknOwpAQCAtOSw2ICsxMCwxMCBAQAogaW1wb3J0IHsgQ2FsbEJ1dHRvbnMgfSBmcm9tICdAL2ZlYXR1cmVzL2NhbGxzL0NhbGxCdXR0b25zJzsKIGltcG9ydCB7IFNhZmV0eU1lbnUgfSBmcm9tICcuLi9jb21wb25lbnRzL1NhZmV0eU1lbnUnOwogCisvKiogVGhlIG9uZSBzcHJpbmcgaW4gdGhpcyBmaWxlLCBuYW1lZCBzbyB0aGUgZHJhd2VyIGFuZCB0aGUgc25hcC1iYWNrIGNhbm5vdAorICogIGRyaWZ0IGludG8gdHdvIGRpZmZlcmVudCBmZWVscy4gTG93IGJvdW5jZTogdGhpcyBpcyBhIGRyYXdlciwgbm90IGEgdG95LiAqLworY29uc3QgU1BSSU5HID0geyB0eXBlOiAnc3ByaW5nJyBhcyBjb25zdCwgZHVyYXRpb246IDAuMzIsIGJvdW5jZTogMC4xNCB9OworCiAvKiogSW5pdGlhbHMgZm9yIHRoZSBtYXNrZWQvcmVhbCBhdmF0YXIuICovCiBmdW5jdGlvbiBpbml0aWFscyhuYW1lOiBzdHJpbmcpOiBzdHJpbmcgewogICByZXR1cm4gKG5hbWUgfHwgJz8nKS5zcGxpdCgnICcpLm1hcCgodykgPT4gd1swXSB8fCAnJykuam9pbignJykuc2xpY2UoMCwgMikudG9VcHBlckNhc2UoKTsKQEAgLTM1LDExICs0MCw5MSBAQAogfQogCiAvKiogT25lIHJvdyBpbiB0aGUgY2hhdCBsaXN0LiAqLworLyoqCisgKiBTV0lQRSBBIE1BVENIIEFTSURFIFRPIFVOTUFUQ0gg4oCUIEFORCBORVZFUiBCWSBBQ0NJREVOVC4KKyAqCisgKiBUaGUgb3duZXIgYXNrZWQgZm9yIHRoZSBnZXN0dXJlIGV2ZXJ5IG1lc3NhZ2luZyBhcHAgaGFzLiBUd28gZGVjaXNpb25zIGluIGl0CisgKiBhcmUgd29ydGggbW9yZSB0aGFuIHRoZSBhbmltYXRpb24uCisgKgorICogVEhFIFNXSVBFIFJFVkVBTFM7IElUIERPRVMgTk9UIEFDVC4gVW5tYXRjaGluZyBlbmRzIGEgY29udmVyc2F0aW9uIGZvciB0d28KKyAqIHBlb3BsZSBhbmQgdGhpcyBhcHAgY2Fubm90IHVuZG8gaXQg4oCUIGB1bmRvTGFzdFBhc3NgIGlzIGV4cGxpY2l0bHkgbm90IGFuCisgKiB1bi11bm1hdGNoLiBBIGdlc3R1cmUgdGhhdCBjb21wbGV0ZXMgYSBkZXN0cnVjdGl2ZSBhY3Rpb24gb24gcmVsZWFzZSBpcyBhCisgKiBkZXNpZ24gdGhhdCB0cmFkZXMgc29tZWJvZHkncyBtYXRjaCBmb3IgYSBzdHJheSB0aHVtYiBvbiBhIHRyYWluLiBTbyB0aGUKKyAqIHN3aXBlIG9wZW5zIGEgZHJhd2VyLCB0aGUgZHJhd2VyIGhvbGRzIGEgYnV0dG9uLCBhbmQgdGhlIGJ1dHRvbiBhc2tzIG9uY2UuCisgKiBUaHJlZSBkZWxpYmVyYXRlIGFjdHMsIG5vbmUgb2YgdGhlbSBzbG93LgorICoKKyAqIEFORCBJVCBJUyBOT1QgT05MWSBBIEdFU1RVUkUuIFRoZSByb3cgaXMgc3RpbGwgYSBidXR0b24gdGhhdCBvcGVucyB0aGUgY2hhdCwKKyAqIHRoZSBkcmF3ZXIncyBjb250cm9sIGlzIGEgcmVhbCA8YnV0dG9uPiByZWFjaGFibGUgYnkga2V5Ym9hcmQsIGFuZCBldmVyeQorICogdW5tYXRjaCBhbHJlYWR5IGF2YWlsYWJsZSBmcm9tIHRoZSB0aHJlYWQncyBzYWZldHkgYmFyIGlzIHVuY2hhbmdlZC4gQQorICogZ2VzdHVyZSB0aGF0IGlzIHRoZSBPTkxZIHdheSB0byBkbyBzb21ldGhpbmcgaXMgYSBmZWF0dXJlIGEgc2NyZWVuLXJlYWRlcgorICogdXNlciBkb2VzIG5vdCBoYXZlLgorICoKKyAqIFdIWSBmcmFtZXItbW90aW9uIEhFUkUgQU5EIE5PV0hFUkUgRUxTRSBJTiBUSElTIEZJTEUuIENMQVVERS5tZCBncmFudHMgaXQKKyAqIGV4YWN0bHkgdGhyZWUgdXNlcyBhbmQgdGhpcyBpcyB0aGUgZmlyc3Qgb2YgdGhlbTogYSBkcmFnIGNhcnJpZXMgdmVsb2NpdHksCisgKiBhbmQgYSBmbGljayB0aGF0IGhhcyBsZWZ0IHRoZSB0aHVtYiBzaG91bGQga2VlcCBnb2luZy4gQSBDU1MgdHJhbnNpdGlvbgorICogY2Fubm90IHJlYWQgYSBnZXN0dXJlJ3Mgc3BlZWQsIHNvIGEgZmFzdCBzaG9ydCBmbGljayBhbmQgYSBzbG93IGxvbmcgZHJhZworICogd291bGQgc2V0dGxlIGlkZW50aWNhbGx5IOKAlCB3aGljaCBpcyB0aGUgZGlmZmVyZW5jZSBiZXR3ZWVuIGEgY29udHJvbCB0aGF0CisgKiBmZWVscyBhbGl2ZSBhbmQgb25lIHRoYXQgZmVlbHMgbGlrZSBhIHRvZ2dsZS4KKyAqCisgKiBgZHJhZ0RpcmVjdGlvbkxvY2tgIGlzIGxvYWQtYmVhcmluZzogd2l0aG91dCBpdCBhIGRpYWdvbmFsIHRodW1iIHN0ZWFscyB0aGUKKyAqIHZlcnRpY2FsIHNjcm9sbCBmcm9tIHRoZSBsaXN0LCB3aGljaCBpcyB0aGUgY2xhc3NpYyB3YXkgdGhpcyBwYXR0ZXJuIHJ1aW5zIGEKKyAqIHBhZ2UgaXQgd2FzIG1lYW50IHRvIGltcHJvdmUuCisgKi8KK2NvbnN0IERSQVdFUiA9IDEwNDsKKwogZnVuY3Rpb24gQ2hhdFJvdyh7IGMsIGFjdGl2ZSwgb25DbGljayB9OiB7IGM6IERhdGluZ0NoYXRTdW1tYXJ5OyBhY3RpdmU6IGJvb2xlYW47IG9uQ2xpY2s6ICgpID0+IHZvaWQgfSkgeworICBjb25zdCB4ID0gdXNlTW90aW9uVmFsdWUoMCk7CisgIGNvbnN0IFtvcGVuLCBzZXRPcGVuXSA9IHVzZVN0YXRlKGZhbHNlKTsKKyAgY29uc3QgW2NvbmZpcm1pbmcsIHNldENvbmZpcm1pbmddID0gdXNlU3RhdGUoZmFsc2UpOworICBjb25zdCB1bm1hdGNoID0gdXNlVW5tYXRjaCgncm9tYW50aWMnKTsKKworICBjb25zdCBjbG9zZSA9IHVzZUNhbGxiYWNrKCgpID0+IHsgc2V0T3BlbihmYWxzZSk7IHNldENvbmZpcm1pbmcoZmFsc2UpOyB2b2lkIGFuaW1hdGUoeCwgMCwgU1BSSU5HKTsgfSwgW3hdKTsKKyAgLy8gQSBjb25maXJtYXRpb24gbGVmdCBvbiBzY3JlZW4gaXMgYSB0cmFwIGZvciB0aGUgbmV4dCB0YXAuIEl0IHJldmVydHMuCisgIHVzZUVmZmVjdCgoKSA9PiB7CisgICAgaWYgKCFjb25maXJtaW5nKSByZXR1cm47CisgICAgY29uc3QgdCA9IHNldFRpbWVvdXQoKCkgPT4gc2V0Q29uZmlybWluZyhmYWxzZSksIDQwMDApOworICAgIHJldHVybiAoKSA9PiBjbGVhclRpbWVvdXQodCk7CisgIH0sIFtjb25maXJtaW5nXSk7CisKICAgcmV0dXJuICgKLSAgICA8YnV0dG9uIHR5cGU9ImJ1dHRvbiIgb25DbGljaz17b25DbGlja30gc3R5bGU9e3sKKyAgICA8ZGl2IHN0eWxlPXt7IHBvc2l0aW9uOiAncmVsYXRpdmUnLCBtYXJnaW5Cb3R0b206IDgsIGJvcmRlclJhZGl1czogMTQsIG92ZXJmbG93OiAnaGlkZGVuJyB9fT4KKyAgICAgIHsvKiBUaGUgZHJhd2VyLCBiZWhpbmQgdGhlIHJvdy4gYGFyaWEtaGlkZGVuYCB3aGlsZSBzaHV0IHNvIHRoZSBjb250cm9sIGlzCisgICAgICAgICAgbm90IGEgdGFiIHN0b3Agbm9ib2R5IGNhbiBzZWUuICovfQorICAgICAgPGRpdiBhcmlhLWhpZGRlbj17IW9wZW59IHN0eWxlPXt7CisgICAgICAgIHBvc2l0aW9uOiAnYWJzb2x1dGUnLCBpbnNldDogMCwgZGlzcGxheTogJ2ZsZXgnLCBqdXN0aWZ5Q29udGVudDogJ2ZsZXgtZW5kJywgYWxpZ25JdGVtczogJ3N0cmV0Y2gnLAorICAgICAgICBiYWNrZ3JvdW5kOiAndmFyKC0tZGFuZ2VyLXNvZnQpJywgYm9yZGVyUmFkaXVzOiAxNCwKKyAgICAgIH19PgorICAgICAgICA8YnV0dG9uIHR5cGU9ImJ1dHRvbiIKKyAgICAgICAgICBvbkNsaWNrPXsoKSA9PiB7IGlmIChjb25maXJtaW5nKSB7IHVubWF0Y2gubXV0YXRlKGMub3RoZXJVc2VySWQpOyBjbG9zZSgpOyB9IGVsc2Ugc2V0Q29uZmlybWluZyh0cnVlKTsgfX0KKyAgICAgICAgICBkaXNhYmxlZD17IW9wZW4gfHwgdW5tYXRjaC5pc1BlbmRpbmd9CisgICAgICAgICAgYXJpYS1sYWJlbD17Y29uZmlybWluZyA/IGBDb25maXJtIHVubWF0Y2ggd2l0aCAke2MubmFtZX1gIDogYFVubWF0Y2ggJHtjLm5hbWV9YH0KKyAgICAgICAgICBzdHlsZT17eworICAgICAgICAgICAgd2lkdGg6IERSQVdFUiwgbWluSGVpZ2h0OiA0NCwgYm9yZGVyOiAwLCBjdXJzb3I6ICdwb2ludGVyJywgZm9udEZhbWlseTogJ2luaGVyaXQnLAorICAgICAgICAgICAgYmFja2dyb3VuZDogJ25vbmUnLCBjb2xvcjogJ3ZhcigtLWRhbmdlci1pbmspJywgZm9udFdlaWdodDogNzAwLCBmb250U2l6ZTogMTMsCisgICAgICAgICAgICBkaXNwbGF5OiAnZ3JpZCcsIHBsYWNlSXRlbXM6ICdjZW50ZXInLCBwYWRkaW5nOiAnMCA4cHgnLCBsaW5lSGVpZ2h0OiAxLjI1LAorICAgICAgICAgIH19PgorICAgICAgICAgIHt1bm1hdGNoLmlzUGVuZGluZyA/ICdVbm1hdGNoaW5n4oCmJyA6IGNvbmZpcm1pbmcgPyAnU3VyZT8nIDogJ1VubWF0Y2gnfQorICAgICAgICA8L2J1dHRvbj4KKyAgICAgIDwvZGl2PgorCisgICAgICA8bW90aW9uLmRpdgorICAgICAgICBkcmFnPSJ4IgorICAgICAgICBkcmFnRGlyZWN0aW9uTG9jaworICAgICAgICBkcmFnQ29uc3RyYWludHM9e3sgbGVmdDogLURSQVdFUiwgcmlnaHQ6IDAgfX0KKyAgICAgICAgZHJhZ0VsYXN0aWM9e3sgbGVmdDogMC4wNiwgcmlnaHQ6IDAgfX0KKyAgICAgICAgc3R5bGU9e3sgeCwgcG9zaXRpb246ICdyZWxhdGl2ZScsIHRvdWNoQWN0aW9uOiAncGFuLXknIH19CisgICAgICAgIG9uRHJhZ0VuZD17KF8sIGluZm8pID0+IHsKKyAgICAgICAgICAvLyBQYXN0IGhhbGZ3YXkgT1IgdGhyb3duIGhhcmQgZW5vdWdoLiBWZWxvY2l0eSBpcyB3aHkgdGhpcyBpcyBhIGRyYWcKKyAgICAgICAgICAvLyBhbmQgbm90IGEgdHJhbnNpdGlvbjogYSBzaG9ydCBmYXN0IGZsaWNrIHNob3VsZCBvcGVuLgorICAgICAgICAgIGNvbnN0IHNob3VsZE9wZW4gPSBpbmZvLm9mZnNldC54IDwgLURSQVdFUiAvIDIgfHwgaW5mby52ZWxvY2l0eS54IDwgLTQyMDsKKyAgICAgICAgICBzZXRPcGVuKHNob3VsZE9wZW4pOworICAgICAgICAgIGlmICghc2hvdWxkT3Blbikgc2V0Q29uZmlybWluZyhmYWxzZSk7CisgICAgICAgICAgdm9pZCBhbmltYXRlKHgsIHNob3VsZE9wZW4gPyAtRFJBV0VSIDogMCwgU1BSSU5HKTsKKyAgICAgICAgfX0KKyAgICAgID4KKyAgICA8YnV0dG9uIHR5cGU9ImJ1dHRvbiIgb25DbGljaz17KCkgPT4geyBpZiAob3BlbikgeyBjbG9zZSgpOyByZXR1cm47IH0gb25DbGljaygpOyB9fSBzdHlsZT17ewogICAgICAgZGlzcGxheTogJ2ZsZXgnLCBhbGlnbkl0ZW1zOiAnY2VudGVyJywgZ2FwOiAxMiwgd2lkdGg6ICcxMDAlJywgdGV4dEFsaWduOiAnbGVmdCcsIGN1cnNvcjogJ3BvaW50ZXInLCBmb250RmFtaWx5OiAnaW5oZXJpdCcsCi0gICAgICBwYWRkaW5nOiAnMTJweCAxMnB4JywgYm9yZGVyUmFkaXVzOiAxNCwgYm9yZGVyOiAnMXB4IHNvbGlkIHZhcigtLWxpbmUpJywgbWFyZ2luQm90dG9tOiA4LAorICAgICAgcGFkZGluZzogJzEycHggMTJweCcsIGJvcmRlclJhZGl1czogMTQsIGJvcmRlcjogJzFweCBzb2xpZCB2YXIoLS1saW5lKScsCiAgICAgICBiYWNrZ3JvdW5kOiBhY3RpdmUgPyAndmFyKC0tYWNjZW50LXNvZnQpJyA6ICd2YXIoLS1jYXJkKScsCiAgICAgfX0+CiAgICAgICA8QXZhdGFyIG5hbWU9e2MubmFtZX0gcGhvdG89e2MucGhvdG99IC8+CkBAIC01NCw2ICsxMzksOCBAQAogICAgICAgPC9kaXY+CiAgICAgICB7Yy51bnJlYWQgPiAwICYmIDxzcGFuIHN0eWxlPXt7IGZsZXg6ICdub25lJywgbWluV2lkdGg6IDIwLCBoZWlnaHQ6IDIwLCBib3JkZXJSYWRpdXM6IDk5OSwgYmFja2dyb3VuZDogJ3ZhcigtLWFjY2VudCknLCBjb2xvcjogJ3ZhcigtLW9uLWFjY2VudCknLCBmb250U2l6ZTogMTEsIGZvbnRXZWlnaHQ6IDcwMCwgZGlzcGxheTogJ2dyaWQnLCBwbGFjZUl0ZW1zOiAnY2VudGVyJywgcGFkZGluZzogJzAgNnB4JyB9fT57Yy51bnJlYWR9PC9zcGFuPn0KICAgICA8L2J1dHRvbj4KKyAgICAgIDwvbW90aW9uLmRpdj4KKyAgICA8L2Rpdj4KICAgKTsKIH0KIAotLS0gL2Rldi9udWxsCisrKyBiL3RvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL2FwcC9tb3Rpb24tcHJvcHMtbmFtZS10aGVpci10aW1pbmcudGVzdC50cwpAQCAtMCwwICsxLDgwIEBACitpbXBvcnQgeyBkZXNjcmliZSwgaXQsIGV4cGVjdCB9IGZyb20gJ3ZpdGVzdCc7CitpbXBvcnQgeyByZWFkRmlsZVN5bmMsIHJlYWRkaXJTeW5jLCBzdGF0U3luYyB9IGZyb20gJ25vZGU6ZnMnOworaW1wb3J0IHsgZGlybmFtZSwgam9pbiB9IGZyb20gJ25vZGU6cGF0aCc7CitpbXBvcnQgeyBmaWxlVVJMVG9QYXRoIH0gZnJvbSAnbm9kZTp1cmwnOworCitjb25zdCBBUFAgPSBqb2luKGRpcm5hbWUoZmlsZVVSTFRvUGF0aChpbXBvcnQubWV0YS51cmwpKSwgJy4uJywgJy4uJyk7Citjb25zdCByZWFkID0gKHA6IHN0cmluZykgPT4gcmVhZEZpbGVTeW5jKGpvaW4oQVBQLCBwKSwgJ3V0ZjgnKTsKK2NvbnN0IHN0cmlwID0gKHNyYzogc3RyaW5nKSA9PgorICBzcmMucmVwbGFjZSgvXC9cKltcc1xTXSo/XCpcLy9nLCAnICcpLnJlcGxhY2UoLyhefFteOl0pXC9cLy4qJC9nbSwgJyQxICcpOworCitmdW5jdGlvbiB3YWxrKGRpcjogc3RyaW5nLCBvdXQ6IHN0cmluZ1tdID0gW10pOiBzdHJpbmdbXSB7CisgIGZvciAoY29uc3QgbmFtZSBvZiByZWFkZGlyU3luYyhqb2luKEFQUCwgZGlyKSkpIHsKKyAgICBjb25zdCByZWwgPSBqb2luKGRpciwgbmFtZSk7CisgICAgaWYgKHN0YXRTeW5jKGpvaW4oQVBQLCByZWwpKS5pc0RpcmVjdG9yeSgpKSB3YWxrKHJlbCwgb3V0KTsKKyAgICBlbHNlIGlmICgvXC50c3g/JC8udGVzdChyZWwpKSBvdXQucHVzaChyZWwpOworICB9CisgIHJldHVybiBvdXQ7Cit9CisKKy8qKgorICogVEhFIEhPTEUgQ0xBVURFLm1kIE5BTUVTLCBDTE9TRUQuCisgKgorICogYHNjcmlwdHMvbW90aW9uLWNlaWxpbmcubWpzYCBjb3VudHMgQ1NTIGRlY2xhcmF0aW9ucy4gSXQgY2Fubm90IHNlZSBhCisgKiBgbW90aW9uLmRpdmAgY2FycnlpbmcgYHRyYW5zaXRpb249e3sgZHVyYXRpb246IDAuMzIgfX1gLCBzbyB0aGUgZHJpZnQgdGhlCisgKiBjZWlsaW5nIGV4aXN0cyB0byBzdG9wIOKAlCB0d2VsdmUgc2xpZ2h0bHkgZGlmZmVyZW50IGR1cmF0aW9ucyBub2JvZHkgY2hvc2Ug4oCUCisgKiBjYW4gd2FsayBzdHJhaWdodCBiYWNrIGluIHRocm91Z2ggdGhlIGxpYnJhcnksIGludmlzaWJseSwgb25lIGNvbXBvbmVudCBhdCBhCisgKiB0aW1lLiBUaGUgcmVwbydzIG93biBndWlkYW5jZSBzYXlzIHNvIGluIGFzIG1hbnkgd29yZHMgYW5kIHRoZW4gaGFzIHRvIHRydXN0CisgKiB3aG9ldmVyIHJlYWRzIGl0LgorICoKKyAqIFRoaXMgaXMgdGhlIHJhdGNoZXQgZm9yIHRoYXQuIEEgdGltaW5nIGluc2lkZSBhIG1vdGlvbiBwcm9wIG11c3QgY29tZSBmcm9tIGEKKyAqIE5BTUVEIGNvbnN0YW50LCBzbyB0aGVyZSBpcyBvbmUgcGxhY2UgdG8gY2hhbmdlIGl0IGFuZCBvbmUgdGhpbmcgdG8gZGlzYWdyZWUKKyAqIHdpdGguIFRoZSBudW1iZXIgaXRzZWxmIG1heSBsaXZlIHdoZXJldmVyIHRoZSBjb25zdGFudCBkb2VzOyB3aGF0IG1heSBub3QKKyAqIGV4aXN0IGlzIGEgc2Vjb25kLCBhbm9ueW1vdXMgb25lIHRocmVlIGZpbGVzIGF3YXkuCisgKgorICogRGVsaWJlcmF0ZWx5IG5hcnJvdzogaXQgcmVhZHMgb25seSBmaWxlcyB0aGF0IGltcG9ydCB0aGUgbW90aW9uIGxpYnJhcnksIGFuZAorICogb25seSB0aGUgcHJvcGVydGllcyB0aGF0IGNhcnJ5IHRpbWluZy4gQSBjb21wb25lbnQgdGhhdCBuZXZlciBhbmltYXRlcyBpcworICogbm9uZSBvZiBpdHMgYnVzaW5lc3MuCisgKi8KK2Rlc2NyaWJlKCdtb3Rpb24gcHJvcHMgbmFtZSB0aGVpciB0aW1pbmcnLCAoKSA9PiB7CisgIGNvbnN0IGZpbGVzID0gd2Fsaygnc3JjJykuZmlsdGVyKChmKSA9PiAvZnJvbSAnKGZyYW1lci1tb3Rpb258bW90aW9uXC9yZWFjdCknLy50ZXN0KHJlYWQoZikpKTsKKworICBpdCgnaXMgbG9va2luZyBhdCB0aGUgZmlsZXMgdGhhdCBhY3R1YWxseSB1c2UgdGhlIGxpYnJhcnknLCAoKSA9PiB7CisgICAgLy8gSWYgdGhpcyBldmVyIHJlYWNoZXMgemVybyB0aGUgZ3VhcmQgaGFzIHF1aWV0bHkgc3RvcHBlZCBndWFyZGluZyDigJQKKyAgICAvLyBhbiBpbXBvcnQgcmVuYW1lZCwgYSBwYXRoIG1vdmVkIOKAlCBhbmQgd291bGQgcGFzcyBmb3JldmVyIGFmdGVyLgorICAgIGV4cGVjdChmaWxlcy5sZW5ndGgpLnRvQmVHcmVhdGVyVGhhbigwKTsKKyAgfSk7CisKKyAgaXQoJ25ldmVyIGhhbmQtdHlwZXMgYSBkdXJhdGlvbiwgYSBkZWxheSBvciBhIHN0aWZmbmVzcyBpbnNpZGUgYSBtb3Rpb24gcHJvcCcsICgpID0+IHsKKyAgICBjb25zdCBvZmZlbmRlcnM6IHN0cmluZ1tdID0gW107CisgICAgZm9yIChjb25zdCBmIG9mIGZpbGVzKSB7CisgICAgICBjb25zdCBzcmMgPSBzdHJpcChyZWFkKGYpKTsKKyAgICAgIC8vIFdoZXJlIHRoZSBuYW1lZCBjb25zdGFudHMgbGl2ZS4gQSB0aW1pbmcgaXMgYWxsb3dlZCB0byBiZSBhIG51bWJlcgorICAgICAgLy8gSEVSRSBhbmQgbm93aGVyZSBlbHNlIOKAlCBvbmUgZGVjbGFyYXRpb24gaXMgYSBkZWNpc2lvbiwgYSBzZWNvbmQgb25lCisgICAgICAvLyBpbmxpbmUgdGhyZWUgbGluZXMgbGF0ZXIgaXMgdGhlIGRyaWZ0IHRoZSBDU1MgY2VpbGluZyBjYW5ub3Qgc2VlLgorICAgICAgY29uc3QgYWxsb3dlZDogQXJyYXk8W251bWJlciwgbnVtYmVyXT4gPSBbCisgICAgICAgIC4uLnNyYy5tYXRjaEFsbCgvY29uc3RccytbQS1aX11bQS1aMC05X10qXHMqPVxzKlx7W159XSpcfS9nKSwKKyAgICAgIF0ubWFwKChtKSA9PiBbbS5pbmRleCA/PyAwLCAobS5pbmRleCA/PyAwKSArIG1bMF0ubGVuZ3RoXSk7CisgICAgICBjb25zdCBpbnNpZGUgPSAoaTogbnVtYmVyKSA9PiBhbGxvd2VkLnNvbWUoKFthLCBiXSkgPT4gaSA+PSBhICYmIGkgPCBiKTsKKyAgICAgIGZvciAoY29uc3QgbSBvZiBzcmMubWF0Y2hBbGwoL1xiKGR1cmF0aW9ufGRlbGF5fHN0aWZmbmVzc3xkYW1waW5nfGJvdW5jZSlccyo6XHMqW1xkLl0rL2cpKSB7CisgICAgICAgIGlmICghaW5zaWRlKG0uaW5kZXggPz8gMCkpIG9mZmVuZGVycy5wdXNoKGAke2Z9IOKGkiAke21bMF0ucmVwbGFjZSgvXHMrL2csICcgJyl9YCk7CisgICAgICB9CisgICAgfQorICAgIGV4cGVjdChvZmZlbmRlcnMpLnRvRXF1YWwoW10pOworICB9KTsKKworICAvKioKKyAgICogVGhlIG90aGVyIGhhbGYgb2YgdGhlIHNhbWUgcnVsZSwgYW5kIHRoZSBvbmUgdGhhdCBicmVha3MgYSBwYWdlIHJhdGhlciB0aGFuCisgICAqIGEgcGFsZXR0ZTogYSBkcmFnIHRoYXQgZG9lcyBub3QgbG9jayBpdHMgZGlyZWN0aW9uIHN0ZWFscyB0aGUgbGlzdCdzCisgICAqIHZlcnRpY2FsIHNjcm9sbCBmcm9tIGEgZGlhZ29uYWwgdGh1bWIuCisgICAqLworICBpdCgnbG9ja3MgdGhlIGRpcmVjdGlvbiBvZiBldmVyeSBob3Jpem9udGFsIGRyYWcnLCAoKSA9PiB7CisgICAgY29uc3Qgb2ZmZW5kZXJzOiBzdHJpbmdbXSA9IFtdOworICAgIGZvciAoY29uc3QgZiBvZiBmaWxlcykgeworICAgICAgY29uc3Qgc3JjID0gc3RyaXAocmVhZChmKSk7CisgICAgICBpZiAoIS9kcmFnPSgieCJ8J3gnfFx7J3gnXH0pLy50ZXN0KHNyYykpIGNvbnRpbnVlOworICAgICAgaWYgKCEvZHJhZ0RpcmVjdGlvbkxvY2svLnRlc3Qoc3JjKSkgb2ZmZW5kZXJzLnB1c2goZik7CisgICAgfQorICAgIGV4cGVjdChvZmZlbmRlcnMpLnRvRXF1YWwoW10pOworICB9KTsKK30pOwo=
B64EOF

WANT="5a341ad10274d4cb321cc486ecea6ae8f4bdabade7fd6afa0d29baee35132489"
GOT="$(shasum -a 256 "$PATCH" | awk '{print $1}')"
[ "$GOT" = "$WANT" ] || { echo "!! Patch is corrupt."; echo "   want $WANT"; echo "   got  $GOT"; exit 1; }
echo "== patch verified"
git apply --check -C1 "$PATCH" || { echo "!! Patch does not apply cleanly. Nothing written."; exit 1; }
git apply -C1 "$PATCH"
echo "== applied"

cd together-city-react
npx tsc --noEmit
npx vitest run
node scripts/a11y-audit.mjs
node scripts/motion-ceiling.mjs
node scripts/lint-ceiling.mjs
npx vite build
cd ..

git add together-city-react/src/features/dating/pages/DatingChats.tsx \
        together-city-react/src/app/motion-props-name-their-timing.test.ts
git commit -F - <<'MSG'
Swipe a match aside, and be asked before it ends

The owner asked for the gesture every messaging app has. Two decisions inside
it matter more than the animation.

THE SWIPE REVEALS; IT DOES NOT ACT. Unmatching ends a conversation for two
people and this app cannot undo it — `undoLastPass` is explicitly not an
un-unmatch. A gesture that completes a destructive action on release trades
somebody's match for a stray thumb on a train. So the swipe opens a drawer, the
drawer holds a button, the button asks once, and the question reverts itself
after four seconds so a half-finished thought is never left lying under the
next tap. Three deliberate acts, none of them slow.

AND IT IS NOT ONLY A GESTURE. The row is still a button that opens the chat,
the drawer's control is a real <button> a keyboard can reach, it is
`aria-hidden` while shut so it is not a tab stop nobody can see, and every
unmatch already available from the thread's safety bar is untouched. A gesture
that is the ONLY way to do something is a feature a screen-reader user does not
have.

WHY framer-motion, HERE, FOR THE FIRST TIME. CLAUDE.md grants it exactly three
uses and this is the first of them: a drag carries VELOCITY, and a flick that
has left the thumb should keep going. A CSS transition cannot read a gesture's
speed, so a fast short flick and a slow long drag would settle identically —
the difference between a control that feels alive and a toggle. `dragElastic`
is asymmetric (0.06 left, 0 right) because a drawer that rubber-bands in the
direction it cannot open is telling the thumb a lie.

`dragDirectionLock` is load-bearing rather than decorative: without it a
diagonal thumb steals the list's vertical scroll, which is the classic way this
pattern ruins the page it was added to improve.

AND THE HOLE CLAUDE.md NAMES IS NOW CLOSED. Its own words: "scripts/
motion-ceiling.mjs counts CSS declarations only. A motion.div carrying a
hand-typed duration is invisible to it, so the drift it exists to stop can walk
straight back in through the library." That was true, and the first component
to import the library is the right moment to stop it being true.
`motion-props-name-their-timing.test.ts` reads only the files that import the
motion library and fails if a duration, delay, stiffness, damping or bounce
appears as a literal anywhere outside a named constant — and separately if any
horizontal drag omits `dragDirectionLock`. Both halves were watched failing
against a deliberately broken copy before this landed; the first version passed
an inline anonymous timing and was tightened until it did not.

NOT VERIFIED, AND SAID SO: the gesture itself has not been exercised in a real
browser. This container has no live stack to render an authenticated dating
chat against, so what is proven here is the code, the guards and the build —
not the feel. Worth a thumb on a real phone before it is called done.

tsc clean, vitest 445/445 (3 new), a11y 0, motion at ceiling, lint at ceiling,
vite build clean.

MSG
echo "== committed"

echo
echo "==============================================================="
echo " Landed: $NEEDS — push and Vercel ships it."
echo " Swipe left on a dating chat → Unmatch → Sure?"
echo " Try it with a real thumb: the feel is the one thing this"
echo " could not verify."
echo "==============================================================="
