#!/bin/bash
# land-pressed-wordmark.sh — the header wordmark becomes white pressed plastic
# (the owner's 3D reference), drawn in CSS so it embosses on paper and lights
# from the front in the two dark rooms.
#
# FRONTEND ONLY (together-city-react). Push, and Vercel ships it.
set -euo pipefail

cd "$(dirname "$0")"
[ -d together-city-react ] || { echo "!! Run this from the Together-Ai repo root."; exit 1; }

LOG="$(git log --oneline -40)"
MARK="Every room, one lamp"
case "$LOG" in
  *"$MARK"*) ;;
  *) echo "!! This patch applies on top of \"$MARK\" — run land-every-room-one-lamp.sh first."; exit 1 ;;
esac
NEEDS="The wordmark is pressed, not printed"
case "$LOG" in
  *"$NEEDS"*) echo "== \"$NEEDS\" is already here. Nothing to do."; exit 0 ;;
esac
DIRTY="$(git status --porcelain | grep -Ev '^\?\? (land-.*\.sh|push-.*\.sh|.*\.patch)$' || true)"
if [ -n "$DIRTY" ]; then
  echo "!! Working tree is dirty. Commit or stash first:"; echo "$DIRTY"; exit 1
fi

PATCH="$(mktemp "${TMPDIR:-/tmp}/wm.XXXXXX")"
trap 'rm -f "$PATCH"' EXIT
cat <<'B64EOF' | tr -d '\n' | openssl base64 -d -A > "$PATCH"
RnJvbSBkMDRlOWQ3NDkzNGZiZWQ3OTRjZDIxMDlkNTNmMTFmNDE0YjcyN2Q4IE1vbiBTZXAgMTcgMDA6MDA6MDAgMjAwMQpGcm9tOiBDbGF1ZGUgPG5vcmVwbHlAYW50aHJvcGljLmNvbT4KRGF0ZTogU3VuLCA5IEF1ZyAyMDI2IDExOjQ2OjIwICswMDAwClN1YmplY3Q6IFtQQVRDSF0gVGhlIHdvcmRtYXJrIGlzIHByZXNzZWQsIG5vdCBwcmludGVkCk1JTUUtVmVyc2lvbjogMS4wCkNvbnRlbnQtVHlwZTogdGV4dC9wbGFpbjsgY2hhcnNldD1VVEYtOApDb250ZW50LVRyYW5zZmVyLUVuY29kaW5nOiA4Yml0CgpUaGUgb3duZXIncyByZWZlcmVuY2U6ICJ0b2dldGhlciBjaXR5IiBhcyB3aGl0ZSBwbGFzdGljLCBsb3dlcmNhc2UgYW5kCnJvdW5kZWQsIGxpdCBmcm9tIGFib3ZlIGFuZCBjYXN0aW5nIGludG8gdGhlIHBhZ2UuIEl0IGlzIGRyYXduIGluIENTUwpyYXRoZXIgdGhhbiBzaGlwcGVkIGFzIHRoZSByZW5kZXJlZCBpbWFnZSwgZm9yIHRocmVlIHJlYXNvbnMgdGhhdCBhbGwKYml0ZSBhdCAzNHB4OgoKQSBQTkcgT0YgV0hJVEUtT04tV0hJVEUgSVMgQSBSRUNUQU5HTEUuIFRoZSByZWZlcmVuY2UncyBlbnRpcmUgZWZmZWN0IGlzCml0cyBzaGFkaW5nLCBhbmQgYSBmbGF0IGFzc2V0IGJha2VzIHRoYXQgc2hhZGluZyBhdCBvbmUgc2l6ZSwgb25lIGxpZ2h0CmFuZ2xlIGFuZCBvbmUgZ3JvdW5kLiBUd28gcm9vbXMgaW4gdGhpcyBjaXR5IGFyZSBuZWFyLWJsYWNrOyB0aGUgc2FtZQpmaWxlIGNhbm5vdCBiZSBlbWJvc3NlZCBJTlRPIHBhcGVyIG9uIHR3ZW50eS1mb3VyIHNjcmVlbnMgYW5kIGxpdCBmcm9tCmluIGZyb250IG9uIHR3by4gVGV4dCBjYW4sIGFuZCBkb2VzIOKAlCB0aGUgZGFyayBodWJzIGdldCB0aGUgc2FtZSBzaWduIGFzCndoaXRlIHBsYXN0aWMgaW4gYSBkYXJrIHJvb20sIGl0cyBzaGFkb3cgZmFsbGluZyBhd2F5IGZyb20gaXQgaW5zdGVhZCBvZgp1bmRlciBpdC4KCkFORCBJVCBTVEFZUyBURVhULiBTZWxlY3RhYmxlLCBzY2FsaW5nIHdpdGggdGhlIHJlYWRlcidzIG93biBmb250IHNpemUsCm5vIDJ4IG9yIDN4IGFzc2V0LCBhbmQgYSBzY3JlZW4gcmVhZGVyIGdldHMgYSB3b3JkIHJhdGhlciB0aGFuIGFuIGFsdAphdHRyaWJ1dGUgc3RhbmRpbmcgaW4gZm9yIG9uZS4KClRIRSBMRVRURVJGT1JNUyBBUkUgVEhFIENJVFknUyBPV04uIFRoZSByZWZlcmVuY2UgaXMgc2V0IGluIGEgcm91bmRlZApnZW9tZXRyaWMgYW5kIGFkZGluZyBpdCB3b3VsZCBiZSBhIHNlY29uZCB0eXBlZmFjZSwgd2hpY2ggZmFpbHMgdGhlCm9uZS1mYW1pbHkgcnVsZSBvbiBzaWdodC4gV2hhdCBhY3R1YWxseSBjYXJyaWVzIHRoZSBjaGFyYWN0ZXIgaXMgdGhlCmxvd2VyY2FzZSwgdGhlIHdlaWdodCBhbmQgdGhlIHRyYWNraW5nLgoKQVQgMTdweCBUSEUgUE9TVEVSJ1MgU0hBRElORyBIQVMgVE8gU0hSSU5LIFdJVEggSVQuIFRoZSBmaXJzdCBwYXNzCmNhcnJpZWQgdGhlIHJlZmVyZW5jZSdzIGZ1bGwgc3RhY2sg4oCUIGZvdXIgYmx1cnMgb3V0IHRvIDE0cHgg4oCUIGFuZCBhdApoZWFkZXIgc2l6ZSB0aGF0IGlzIG5vdCBkZXB0aCwgaXQgaXMgYSBzbXVkZ2U6IHRoZSBsZXR0ZXJmb3JtcyBtZXJnZWQKYW5kICJjaXR5IiByZW5kZXJlZCBhcyAib2x0eSIuIEEgcHJlc3NlZCB0b3AgZWRnZSwgYSBoYXJkIDFweCB1bmRlcmxpbmUKYW5kIG9uZSBzaG9ydCBkcm9wIGlzIHdoYXQgc3Vydml2ZXMgdGhlIHNjYWxlLCBhbmQgdGhlIHRyYWNraW5nIG9wZW5zCmJhY2sgdXAsIGJlY2F1c2UgaGVhdnkgc2hhZGluZyBuZWVkcyBhaXIgYmV0d2VlbiBsZXR0ZXJzIHRoYXQgYSBmbGF0CndvcmRtYXJrIGRvZXMgbm90LiBDYXVnaHQgYnkgY3JvcHBpbmcgdGhlIG1hcmsgYXQgM3ggYW5kIGxvb2tpbmcgYXQgaXQsCndoaWNoIGlzIHRoZSBvbmx5IHdheSB0aGlzIGNsYXNzIG9mIHRoaW5nIGlzIGV2ZXIgY2F1Z2h0LgoKQSBMT0dPVFlQRSBJUyBFWEVNUFQgRlJPTSBDT05UUkFTVCBhbmQgdGhpcyBvbmUgc3BlbmRzIHRoZSBleGVtcHRpb24Ka25vd2luZ2x5OiB3aGl0ZSBvbiB3aGl0ZSByZWFkcyBieSBpdHMgc2hhZG93IGFsb25lLiBBY2NlcHRhYmxlIGZvciBhCm1hcmsgc3RhbmRpbmcgYmVzaWRlIGl0cyBvd24gYmxhY2sgZ2x5cGggYW5kIG5vd2hlcmUgZWxzZSBpbiB0aGUKYXBwbGljYXRpb247IGl0IHdvdWxkIG5vdCBiZSBhY2NlcHRhYmxlIGZvciBhIHdvcmQgYW55Ym9keSBoYXMgdG8gcmVhZC4KCkNvLUF1dGhvcmVkLUJ5OiBDbGF1ZGUgRmFibGUgNSA8bm9yZXBseUBhbnRocm9waWMuY29tPgpDbGF1ZGUtU2Vzc2lvbjogaHR0cHM6Ly9jbGF1ZGUuYWkvY29kZS9zZXNzaW9uXzAxOXFTUkV5em82OWhCN2oxcnluMjZTQgotLS0KIHRvZ2V0aGVyLWNpdHktcmVhY3Qvc3JjL3N0eWxlcy9yZWxpZWYuY3NzIHwgNDkgKysrKysrKysrKysrKysrKysrKysrKy0KIDEgZmlsZSBjaGFuZ2VkLCA0OCBpbnNlcnRpb25zKCspLCAxIGRlbGV0aW9uKC0pCgpkaWZmIC0tZ2l0IGEvdG9nZXRoZXItY2l0eS1yZWFjdC9zcmMvc3R5bGVzL3JlbGllZi5jc3MgYi90b2dldGhlci1jaXR5LXJlYWN0L3NyYy9zdHlsZXMvcmVsaWVmLmNzcwppbmRleCAxZmM1NDMwLi44NTRiMzQwIDEwMDY0NAotLS0gYS90b2dldGhlci1jaXR5LXJlYWN0L3NyYy9zdHlsZXMvcmVsaWVmLmNzcworKysgYi90b2dldGhlci1jaXR5LXJlYWN0L3NyYy9zdHlsZXMvcmVsaWVmLmNzcwpAQCAtNjE0LDcgKzYxNCw1NCBAQCBpbnB1dFthcmlhLWludmFsaWQ9InRydWUiXSwgdGV4dGFyZWFbYXJpYS1pbnZhbGlkPSJ0cnVlIl0sIC50Yy1maWVsZFtkYXRhLWludmFsaQogCiAudGMtYWN0aW9uYmFyLCAudGMtYWN0aW9ucyB7IGdhcDogOHB4OyB9CiAKLS50Yy1sb2dvIC53b3JkIHsgY29sb3I6IHZhcigtLWluayk7IGZvbnQtd2VpZ2h0OiA3MDA7IGxldHRlci1zcGFjaW5nOiAtLjAzZW07IH0KKy8qIOKUgOKUgCBUSEUgV09SRE1BUksgSVMgUFJFU1NFRCwgTk9UIFBSSU5URUQg4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSACisgICBUaGUgb3duZXIncyByZWZlcmVuY2U6ICJ0b2dldGhlciBjaXR5IiBhcyB3aGl0ZSBwbGFzdGljLCBsb3dlcmNhc2UgYW5kCisgICByb3VuZGVkLCBsaXQgZnJvbSBhYm92ZSBhbmQgY2FzdGluZyBpbnRvIHRoZSBwYWdlLiBJdCBpcyBkcmF3biBoZXJlIHJhdGhlcgorICAgdGhhbiBzaGlwcGVkIGFzIGFuIGltYWdlLCBmb3IgdGhyZWUgcmVhc29ucyB0aGF0IGFsbCBtYXR0ZXIgYXQgMzRweDoKKworICAgICBBIFBORyBPRiBXSElURS1PTi1XSElURSBJUyBBIFJFQ1RBTkdMRS4gVGhlIHJlZmVyZW5jZSdzIHdob2xlIGVmZmVjdCBpcworICAgICBpdHMgc2hhZGluZywgYW5kIGEgZmxhdCBhc3NldCBjYXJyaWVzIHRoYXQgc2hhZGluZyBiYWtlZCBhdCBvbmUgc2l6ZSwgb25lCisgICAgIGxpZ2h0IGFuZ2xlIGFuZCBvbmUgZ3JvdW5kLiBUd28gaHVicyBpbiB0aGlzIGNpdHkgYXJlIG5lYXItYmxhY2s7IHRoZQorICAgICBzYW1lIGZpbGUgY2Fubm90IGJlIGVtYm9zc2VkIGludG8gcGFwZXIgb24gdHdlbnR5LWZvdXIgc2NyZWVucyBhbmQgbGl0CisgICAgIGZyb20gYmVoaW5kIG9uIHR3by4gVGV4dCBjYW4uCisKKyAgICAgQU5EIElUIElTIFNUSUxMIFRFWFQuIEl0IHN0YXlzIHNlbGVjdGFibGUsIGl0IHNjYWxlcyB3aXRoIHRoZSB1c2VyJ3MgZm9udAorICAgICBzaXplLCBpdCBuZWVkcyBubyAyeCBhbmQgbm8gM3gsIGFuZCBhIHNjcmVlbiByZWFkZXIgZ2V0cyBhIHdvcmQgcmF0aGVyCisgICAgIHRoYW4gYW4gYWx0IGF0dHJpYnV0ZSBzdGFuZGluZyBpbiBmb3Igb25lLgorCisgICBUSEUgTEVUVEVSRk9STVMgQVJFIFRIRSBDSVRZJ1MgT1dOLiBUaGUgcmVmZXJlbmNlIGlzIHNldCBpbiBhIHJvdW5kZWQKKyAgIGdlb21ldHJpYzsgYWRkaW5nIGl0IHdvdWxkIGJlIGEgc2Vjb25kIHR5cGVmYWNlIGFuZCBmYWlscyB0aGUgb25lLWZhbWlseQorICAgcnVsZSBvbiBzaWdodC4gV2hhdCBjYXJyaWVzIHRoZSBjaGFyYWN0ZXIgaXMgdGhlIExPV0VSQ0FTRSwgdGhlIHdlaWdodCBhbmQKKyAgIHRoZSB0aWdodCB0cmFja2luZyDigJQgd2hpY2ggaXMgbW9zdCBvZiBpdCDigJQgcGx1cyB0aGUgbGlnaHQuCisKKyAgIEEgTE9HT1RZUEUgSVMgRVhFTVBUIEZST00gQ09OVFJBU1QsIGFuZCB0aGlzIG9uZSB1c2VzIHRoZSBleGVtcHRpb24KKyAgIGtub3dpbmdseTogd2hpdGUgb24gd2hpdGUgcmVhZHMgYnkgaXRzIHNoYWRvdyBhbG9uZS4gVGhhdCBpcyBhY2NlcHRhYmxlCisgICBmb3IgYSBtYXJrIHNpdHRpbmcgYmVzaWRlIGl0cyBvd24gYmxhY2sgZ2x5cGggYW5kIG5vd2hlcmUgZWxzZSBpbiB0aGUKKyAgIGFwcGxpY2F0aW9uOyBpdCB3b3VsZCBub3QgYmUgYWNjZXB0YWJsZSBmb3IgYSB3b3JkIGFueWJvZHkgaGFzIHRvIHJlYWQuICovCisudGMtbG9nbyAud29yZCB7CisgIGNvbG9yOiByZ2JhKDI1NSwyNTUsMjU1LDEpOworICAvKiBBVCAxN3B4IFRIRSBSRUZFUkVOQ0UnUyBTSEFESU5HIEhBUyBUTyBTSFJJTksgV0lUSCBJVC4gVGhlIGZpcnN0IHBhc3MKKyAgICAgY2FycmllZCB0aGUgcG9zdGVyJ3MgZnVsbCBzdGFjayDigJQgZm91ciBibHVycyBvdXQgdG8gMTRweCDigJQgYW5kIGF0IGhlYWRlcgorICAgICBzaXplIHRoYXQgaXMgbm90IGRlcHRoLCBpdCBpcyBhIHNtdWRnZTogdGhlIGxldHRlcnMgbWVyZ2VkIGFuZCAiY2l0eSIKKyAgICAgcmVhZCBhcyAib2x0eSIuIEEgcHJlc3NlZCBlZGdlIGFuZCBvbmUgc2hvcnQgZHJvcCBpcyBhbGwgdGhhdCBzdXJ2aXZlcworICAgICB0aGUgc2NhbGUsIGFuZCB0cmFja2luZyBvcGVucyBiYWNrIHVwIGJlY2F1c2UgaGVhdnkgc2hhZGluZyBuZWVkcyBhaXIKKyAgICAgYmV0d2VlbiBsZXR0ZXJmb3JtcyB0aGF0IGEgZmxhdCB3b3JkbWFyayBkb2VzIG5vdC4gKi8KKyAgZm9udC13ZWlnaHQ6IDc1MDsKKyAgZm9udC1zaXplOiAxN3B4OworICBsZXR0ZXItc3BhY2luZzogLS4wMDhlbTsKKyAgdGV4dC10cmFuc2Zvcm06IGxvd2VyY2FzZTsKKyAgdGV4dC1zaGFkb3c6CisgICAgMCAtMC41cHggMCByZ2JhKDI1NSwyNTUsMjU1LDEpLAorICAgIDAgMXB4IDAuNXB4IHJnYmEoMjAsMjIsMjUsLjQyKSwKKyAgICAwIDJweCA0cHggcmdiYSgyMCwyMiwyNSwuMTgpOworfQorLyogSW4gYSBkYXJrIHJvb20gdGhlcmUgaXMgbm8gcGFwZXIgdG8gcHJlc3MgaW50bywgc28gdGhlIHNpZ24gc3RvcHMgYmVpbmcKKyAgIGVtYm9zc2VkIGFuZCBiZWNvbWVzIHdoYXQgaXQgd291bGQgYWN0dWFsbHkgYmU6IHdoaXRlIHBsYXN0aWMsIGxpdCwgd2l0aAorICAgaXRzIHNoYWRvdyBmYWxsaW5nIGF3YXkgZnJvbSBpdC4gKi8KK1tkYXRhLWh1Yj0iYXN0cm9sb2d5Il0gLnRjLWxvZ28gLndvcmQsCitbZGF0YS1odWI9ImVudGVydGFpbm1lbnQiXSAudGMtbG9nbyAud29yZCB7CisgIHRleHQtc2hhZG93OiAwIDFweCAwIHJnYmEoMCwwLDAsLjU1KSwgMCAzcHggMTBweCByZ2JhKDAsMCwwLC42MCk7Cit9CiAvKiBUSEUgTUFSSyBJUyBBUlRXT1JLLCBOT1QgQSBLRVkuIEl0IHNpdHMgb24gdGhlIG9uZSBmbGF0IHN1cmZhY2UgaW4gdGhlCiAgICBhcHBsaWNhdGlvbiwgc28gYSByYWlzZWQgdGlsZSBiZWhpbmQgaXQgd2FzIGEgYnV0dG9uIG5vYm9keSBjYW4gcHJlc3Mg4oCUCiAgICBhbmQgaXQgYm94ZWQgYSBsb2dvIHRoYXQgYWxyZWFkeSBoYXMgaXRzIG93biBzaGFwZS4gRmxhdCwgbGlrZSB0aGUgYmFyLiAqLwotLSAKMi40My4wCgo=
B64EOF

WANT="1595097994cf4bdd193bc92e15fdf3056ee91be5198e44a7f01fbf8c16a8b784"
GOT="$(shasum -a 256 "$PATCH" | awk '{print $1}')"
[ "$GOT" = "$WANT" ] || { echo "!! Patch is corrupt."; echo "   want $WANT"; echo "   got  $GOT"; exit 1; }
echo "== patch verified"
git apply --check -C1 "$PATCH" || { echo "!! Patch does not apply cleanly. Nothing written."; exit 1; }
git am --keep-cr -C1 < "$PATCH"
echo "== committed"

cd together-city-react
npx tsc --noEmit
npx vitest run
npx eslint src || true
node scripts/lint-ceiling.mjs
node scripts/dead-export-audit.mjs
node scripts/motion-ceiling.mjs
node scripts/a11y-audit.mjs
node scripts/nav-audit.mjs
npx vite build
cd ..

echo
echo "==============================================================="
echo " Landed: $NEEDS — push and Vercel ships it."
echo "==============================================================="
