#!/bin/bash
# land-zoom-lock.sh — the city stops being pinched out of shape. A non-passive
# ctrl-wheel guard (trackpad pinch AND Ctrl/Cmd+wheel), Safari's gesture family,
# and the mobile scale lock in the viewport meta. Registered once above the
# router. Scrolling — wheel, trackpad and touch — is untouched.
#
# FRONTEND ONLY (together-city-react). Push, and Vercel ships it.
set -euo pipefail

cd "$(dirname "$0")"
[ -d together-city-react ] || { echo "!! Run this from the Together-Ai repo root."; exit 1; }

NEEDS="The city cannot be pinched out of shape"
LOG="$(git log --oneline -40)"
case "$LOG" in
  *"$NEEDS"*) echo "== \"$NEEDS\" is already here. Nothing to do."; exit 0 ;;
esac
DIRTY="$(git status --porcelain | grep -Ev '^\?\? (land-.*\.sh|push-.*\.sh|.*\.patch)$' || true)"
if [ -n "$DIRTY" ]; then
  echo "!! Working tree is dirty. Commit or stash first:"; echo "$DIRTY"; exit 1
fi

PATCH="$(mktemp "${TMPDIR:-/tmp}/land.XXXXXX")"
trap 'rm -f "$PATCH"' EXIT
cat <<'B64EOF' | tr -d '\n' | openssl base64 -d -A > "$PATCH"
LS0tIGEvdG9nZXRoZXItY2l0eS1yZWFjdC9zcmMvYXBwL0FwcC50c3gKKysrIGIvdG9nZXRoZXItY2l0eS1yZWFjdC9zcmMvYXBwL0FwcC50c3gKQEAgLTEsNiArMSw3IEBACiBpbXBvcnQgeyBSb3V0ZXJQcm92aWRlciB9IGZyb20gJ3JlYWN0LXJvdXRlci1kb20nOwogaW1wb3J0IHsgUHJvdmlkZXJzIH0gZnJvbSAnLi9wcm92aWRlcnMnOwogaW1wb3J0IHsgQ2FsbENlbnRlciB9IGZyb20gJ0AvZmVhdHVyZXMvY2FsbHMvQ2FsbENlbnRlcic7CitpbXBvcnQgeyB1c2Vab29tTG9jayB9IGZyb20gJ0AvaG9va3MvdXNlWm9vbUxvY2snOwogaW1wb3J0IHsgcm91dGVyIH0gZnJvbSAnLi9yb3V0ZXInOwogCiAvKioKQEAgLTI1LDYgKzI2LDExIEBACiAgKiBuZWVkcyB0aGUgcXVlcnkgY2xpZW50IGFuZCB0aGUgYXV0aCBzdG9yZS4KICAqLwogZXhwb3J0IGZ1bmN0aW9uIEFwcCgpIHsKKyAgLy8gT05FIFBMQUNFLCBBQk9WRSBUSEUgUk9VVEVSLiBUaGUgem9vbSBndWFyZCBpcyBhIHByb3BlcnR5IG9mIHRoZQorICAvLyBhcHBsaWNhdGlvbiwgbm90IG9mIGEgcGFnZSDigJQgcmVnaXN0ZXJlZCBoZXJlIGl0IGNvdmVycyBldmVyeSByb3V0ZQorICAvLyBpbmNsdWRpbmcgdGhlIG9uZXMgdGhhdCBhcmUgc2libGluZ3Mgb2YgQXBwU2hlbGwgcmF0aGVyIHRoYW4gY2hpbGRyZW4gb2YKKyAgLy8gaXQsIHdoaWNoIGlzIHRoZSBzYW1lIHRyYXAgQ2FsbENlbnRlciBmZWxsIGludG8gYWJvdmUuCisgIHVzZVpvb21Mb2NrKCk7CiAgIHJldHVybiAoCiAgICAgPFByb3ZpZGVycz4KICAgICAgIDxDYWxsQ2VudGVyPgotLS0gYS90b2dldGhlci1jaXR5LXJlYWN0L2luZGV4Lmh0bWwKKysrIGIvdG9nZXRoZXItY2l0eS1yZWFjdC9pbmRleC5odG1sCkBAIC0yLDcgKzIsMTggQEAKIDxodG1sIGxhbmc9ImVuIj4KICAgPGhlYWQ+CiAgICAgPG1ldGEgY2hhcnNldD0iVVRGLTgiIC8+Ci0gICAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjAsIHZpZXdwb3J0LWZpdD1jb3ZlciwgaW50ZXJhY3RpdmUtd2lkZ2V0PXJlc2l6ZXMtY29udGVudCIgLz4KKyAgICA8IS0tIFpPT00gSVMgTE9DS0VEIEFUIFRIRSBERVNJR05FRCBTQ0FMRSAob3duZXIncyBjYWxsLCAxMCBBdWcpLgorICAgICAgICAgYG1heGltdW0tc2NhbGU9MSwgdXNlci1zY2FsYWJsZT1ub2AgaXMgaG9ub3VyZWQgYnkgQW5kcm9pZCBDaHJvbWUgYW5kCisgICAgICAgICBkZWxpYmVyYXRlbHkgSUdOT1JFRCBieSBpT1MgU2FmYXJpLCB3aGljaCBoYXMgcmVmdXNlZCBpdCBzaW5jZSBpT1MgMTAKKyAgICAgICAgIGZvciBhY2Nlc3NpYmlsaXR5LiBJdCBmYWlscyBXQ0FHIDIuMSBTQyAxLjQuNCB3aGVyZSBpdCBkb2VzIGFwcGx5IOKAlAorICAgICAgICAgYSBkZWNpc2lvbiB0aGUgb3duZXIgd2FzIGFza2VkIGFib3V0IGRpcmVjdGx5IGFuZCBtYWRlLCBub3QgYW4KKyAgICAgICAgIG92ZXJzaWdodCwgYW5kIGl0IGlzIG9uZSBhdHRyaWJ1dGUgdG8gZ2l2ZSBiYWNrLiBFdmVyeXRoaW5nIGVsc2UgaGVyZQorICAgICAgICAgaXMgdW50b3VjaGVkOiBgd2lkdGg9ZGV2aWNlLXdpZHRoYCBhbmQgYGluaXRpYWwtc2NhbGU9MWAga2VlcCB0aGUKKyAgICAgICAgIHJlc3BvbnNpdmUgbGF5b3V0IGV4YWN0bHkgYXMgaXQgd2FzLCBhbmQgYGludGVyYWN0aXZlLXdpZGdldGAga2VlcHMKKyAgICAgICAgIHRoZSBvbi1zY3JlZW4ga2V5Ym9hcmQgYmVoYXZpb3VyIHNvbWVib2R5IGNob3NlIGRlbGliZXJhdGVseS4gU2VlCisgICAgICAgICBzcmMvaG9va3MvdXNlWm9vbUxvY2sudHMgZm9yIHRoZSBkZXNrdG9wIGhhbGYsIGFuZCBmb3IgYSBwbGFpbgorICAgICAgICAgYWNjb3VudCBvZiB3aGF0IGEgcGFnZSBnZW51aW5lbHkgY2Fubm90IHByZXZlbnQuIC0tPgorICAgIDxtZXRhIG5hbWU9InZpZXdwb3J0IiBjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wLCBtYXhpbXVtLXNjYWxlPTEuMCwgdXNlci1zY2FsYWJsZT1ubywgdmlld3BvcnQtZml0PWNvdmVyLCBpbnRlcmFjdGl2ZS13aWRnZXQ9cmVzaXplcy1jb250ZW50IiAvPgogICAgIDxtZXRhIG5hbWU9InRoZW1lLWNvbG9yIiBjb250ZW50PSIjZmFmOWY2IiAvPgogICAgIDxsaW5rIHJlbD0iaWNvbiIgdHlwZT0iaW1hZ2Uvc3ZnK3htbCIgaHJlZj0iL2Zhdmljb24uc3ZnIiAvPgogICAgIDxsaW5rIHJlbD0ibWFuaWZlc3QiIGhyZWY9Ii9tYW5pZmVzdC53ZWJtYW5pZmVzdCIgLz4KLS0tIC9kZXYvbnVsbAorKysgYi90b2dldGhlci1jaXR5LXJlYWN0L3NyYy9ob29rcy91c2Vab29tTG9jay50cwpAQCAtMCwwICsxLDg2IEBACitpbXBvcnQgeyB1c2VFZmZlY3QgfSBmcm9tICdyZWFjdCc7CisKKy8qKgorICogVEhFIENJVFkgRE9FUyBOT1QgR0VUIFBJTkNIRUQgT1VUIE9GIFNIQVBFLgorICoKKyAqIFRoZSBvd25lciB3YXRjaGVkIHRoZSBkZXNrdG9wIGNpdHkgZGlzdG9ydCB1bmRlciBhIHRyYWNrcGFkIHBpbmNoIGFuZCBhc2tlZAorICogZm9yIHpvb20gdG8gYmUgbG9ja2VkLiBUaGlzIGlzIHdoYXQgYSB3ZWIgcGFnZSBjYW4gaG9uZXN0bHkgZG8gYWJvdXQgdGhhdCwKKyAqIGFuZCDigJQganVzdCBhcyBpbXBvcnRhbnRseSDigJQgd2hhdCBpdCBjYW5ub3QuCisgKgorICog4pSA4pSAIFdIQVQgV09SS1MsIEFORCBXSFkg4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSACisgKgorICogMS4gYHdoZWVsYCB3aXRoIGN0cmxLZXksIGxpc3RlbmVyIE5PTi1QQVNTSVZFLgorICogICAgQSB0cmFja3BhZCBwaW5jaCBkb2VzIG5vdCBhcnJpdmUgYXMgYSB0b3VjaCBnZXN0dXJlIG9uIGEgZGVza3RvcCBicm93c2VyOworICogICAgQ2hyb21lLCBFZGdlIGFuZCBGaXJlZm94IHN5bnRoZXNpc2UgYSBgd2hlZWxgIGV2ZW50IHdpdGggYGN0cmxLZXk6IHRydWVgLgorICogICAgVGhhdCBldmVudCBJUyBjYW5jZWxsYWJsZSwgc28gdGhpcyBpcyB0aGUgb25lIHByZXZlbnRpb24gdGhhdCByZWxpYWJseQorICogICAgaG9sZHMg4oCUIGFuZCBpdCBjb3ZlcnMgQ3RybC9DbWQgKyBtb3VzZSB3aGVlbCBhdCB0aGUgc2FtZSB0aW1lLCBiZWNhdXNlCisgKiAgICB0aGV5IGFyZSB0aGUgc2FtZSBldmVudC4KKyAqICAgIGB7IHBhc3NpdmU6IGZhbHNlIH1gIGlzIHRoZSBlbnRpcmUgdHJpY2s6IFJlYWN0J3Mgb3duIG9uV2hlZWwgYW5kIGFueQorICogICAgZGVmYXVsdC1yZWdpc3RlcmVkIGxpc3RlbmVyIGFyZSBwYXNzaXZlLCBhbmQgYSBwYXNzaXZlIGxpc3RlbmVyIG1heSBub3QKKyAqICAgIGNhbGwgcHJldmVudERlZmF1bHQuIFJlZ2lzdGVyaW5nIGJ5IGhhbmQgaXMgdGhlIG9ubHkgd2F5LgorICogICAgTk9USElORyBpcyBwcmV2ZW50ZWQgdW5sZXNzIGN0cmxLZXkgaXMgc2V0LCBzbyBvcmRpbmFyeSB3aGVlbCBzY3JvbGxpbmcsCisgKiAgICB0d28tZmluZ2VyIHRyYWNrcGFkIHNjcm9sbGluZyBhbmQgbW9tZW50dW0gYXJlIHVudG91Y2hlZC4KKyAqCisgKiAyLiBgZ2VzdHVyZXN0YXJ0YCAvIGBnZXN0dXJlY2hhbmdlYCAvIGBnZXN0dXJlZW5kYC4KKyAqICAgIFNhZmFyaSBvbiBtYWNPUyBkb2VzIG5vdCBzeW50aGVzaXNlIHRoZSBjdHJsLXdoZWVsOyBpdCBmaXJlcyB0aGVzZQorICogICAgbm9uLXN0YW5kYXJkIGV2ZW50cyBpbnN0ZWFkLiBQcmV2ZW50ZWQgZm9yIHRoZSBzYW1lIHJlYXNvbi4KKyAqCisgKiAzLiBUaGUgdmlld3BvcnQgbWV0YSAoaW5kZXguaHRtbCkgY2FycmllcyBgbWF4aW11bS1zY2FsZT0xLCB1c2VyLXNjYWxhYmxlPW5vYC4KKyAqCisgKiDilIDilIAgV0hBVCBET0VTIE5PVCBXT1JLLCBTVEFURUQgUExBSU5MWSDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKKyAqCisgKiBDdHJsL0NtZCB3aXRoICssIC0gb3IgMCBDQU5OT1QgYmUgYmxvY2tlZCBieSBhIHdlYiBwYWdlLiBDaHJvbWUsIFNhZmFyaSBhbmQKKyAqIEZpcmVmb3ggaGFuZGxlIGJyb3dzZXItem9vbSBzaG9ydGN1dHMgaW4gdGhlIGJyb3dzZXIgaXRzZWxmLCBhYm92ZSB0aGUKKyAqIGRvY3VtZW50LCBhbmQgdGhlIGtleWRvd24gZWl0aGVyIG5ldmVyIHJlYWNoZXMgdGhlIHBhZ2Ugb3IgaXMgbm90IGNhbmNlbGxhYmxlCisgKiB3aGVuIGl0IGRvZXMuIFRoZSBoYW5kbGVyIGJlbG93IGlzIHJlZ2lzdGVyZWQgYW55d2F5IGJlY2F1c2UgaXQgaXMgY29ycmVjdCBpbgorICogdGhlIGNvbnRleHRzIHdoZXJlIGl0IGRvZXMgYXBwbHkgKGFuIEVsZWN0cm9uIHNoZWxsLCBhIFdlYlZpZXcsIGEga2lvc2sKKyAqIGJ1aWxkKSBhbmQgY29zdHMgbm90aGluZyBlbHNld2hlcmUg4oCUIGJ1dCBpdCBpcyBOT1QgYSBwcm9taXNlLCBhbmQgd3JpdGluZyBpdAorICogd2l0aG91dCBzYXlpbmcgc28gd291bGQgYmUgdGhlIGtpbmQgb2YgY29kZSB0aGF0IGxvb2tzIGxpa2UgYSBmZWF0dXJlIGFuZCBpcworICogYSBkZWNvcmF0aW9uLgorICoKKyAqIGlPUyBTYWZhcmkgaGFzIGlnbm9yZWQgYHVzZXItc2NhbGFibGU9bm9gIHNpbmNlIGlPUyAxMCwgZGVsaWJlcmF0ZWx5LCBmb3IKKyAqIGFjY2Vzc2liaWxpdHkuIFRoZXJlIGlzIG5vIG92ZXJyaWRlIGFuZCB0aGVyZSBzaG91bGQgbm90IGJlIG9uZS4KKyAqCisgKiDilIDilIAgVEhFIEFDQ0VTU0lCSUxJVFkgQ09TVCwgT04gVEhFIFJFQ09SRCDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKKyAqCisgKiBCbG9ja2luZyBwaW5jaC10by16b29tIGZhaWxzIFdDQUcgMi4xIFNDIDEuNC40IChSZXNpemUgVGV4dCk6IHBlb3BsZSB3aXRoIGxvdworICogdmlzaW9uIHVzZSBpdCwgYW5kIG9uIEFuZHJvaWQgQ2hyb21lIOKAlCB0aGUgb25lIHBsYWNlIGB1c2VyLXNjYWxhYmxlPW5vYCBpcworICogaG9ub3VyZWQg4oCUIHRoaXMgdGFrZXMgaXQgZnJvbSB0aGVtLiBUaGUgb3duZXIgd2FzIGFza2VkIGRpcmVjdGx5IGFuZCBjaG9zZQorICogaXQgKDEwIEF1ZykuIEl0IGlzIHdyaXR0ZW4gaGVyZSByYXRoZXIgdGhhbiBkaXNjb3ZlcmVkIGxhdGVyLCBhbmQgaXQgaXMgb25lCisgKiBsaW5lIGluIGluZGV4Lmh0bWwgdG8gZ2l2ZSBiYWNrLgorICoKKyAqIOKUgOKUgCBXSEFUIElTIERFTElCRVJBVEVMWSBOT1QgRE9ORSDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKKyAqCisgKiBObyBgdG91Y2gtYWN0aW9uOiBub25lYCwgbm8gYmxhbmtldCBgdG91Y2htb3ZlYCBwcmV2ZW50aW9uLCBubyBzY3JvbGwKKyAqIGxvY2tpbmcuIFRob3NlIGFyZSB0aGUgdXN1YWwgd2F5IHRoaXMgZ2V0cyBpbXBsZW1lbnRlZCBhbmQgdGhleSBicmVhaworICogc2Nyb2xsaW5nIG9uIHRvdWNoIGRldmljZXMsIHdoaWNoIGlzIGEgZmFyIHdvcnNlIGJ1ZyB0aGFuIHRoZSBvbmUgYmVpbmcKKyAqIGZpeGVkLiBFdmVyeSBsaXN0ZW5lciBoZXJlIGlzIHNjb3BlZCB0byBhIHpvb20gZ2VzdHVyZSBhbmQgdG8gbm90aGluZyBlbHNlLgorICovCitleHBvcnQgZnVuY3Rpb24gdXNlWm9vbUxvY2soKTogdm9pZCB7CisgIHVzZUVmZmVjdCgoKSA9PiB7CisgICAgLy8gQSBwaW5jaCBvbiBhIHRyYWNrcGFkLCBhbmQgQ3RybC9DbWQgKyB3aGVlbC4gT25lIGV2ZW50LCBvbmUgZ3VhcmQuCisgICAgY29uc3Qgb25XaGVlbCA9IChlOiBXaGVlbEV2ZW50KSA9PiB7CisgICAgICBpZiAoZS5jdHJsS2V5IHx8IGUubWV0YUtleSkgZS5wcmV2ZW50RGVmYXVsdCgpOworICAgIH07CisgICAgLy8gU2FmYXJpL21hY09TIHBpbmNoLgorICAgIGNvbnN0IG9uR2VzdHVyZSA9IChlOiBFdmVudCkgPT4gZS5wcmV2ZW50RGVmYXVsdCgpOworICAgIC8vIEhvbmVzdCBhYm91dCBpdHMgcmVhY2gg4oCUIHNlZSB0aGUgbm90ZSBhYm92ZS4KKyAgICBjb25zdCBvbktleURvd24gPSAoZTogS2V5Ym9hcmRFdmVudCkgPT4geworICAgICAgaWYgKCEoZS5jdHJsS2V5IHx8IGUubWV0YUtleSkpIHJldHVybjsKKyAgICAgIGlmIChbJysnLCAnPScsICctJywgJ18nLCAnMCddLmluY2x1ZGVzKGUua2V5KSkgZS5wcmV2ZW50RGVmYXVsdCgpOworICAgIH07CisKKyAgICB3aW5kb3cuYWRkRXZlbnRMaXN0ZW5lcignd2hlZWwnLCBvbldoZWVsLCB7IHBhc3NpdmU6IGZhbHNlIH0pOworICAgIHdpbmRvdy5hZGRFdmVudExpc3RlbmVyKCdnZXN0dXJlc3RhcnQnLCBvbkdlc3R1cmUgYXMgRXZlbnRMaXN0ZW5lcik7CisgICAgd2luZG93LmFkZEV2ZW50TGlzdGVuZXIoJ2dlc3R1cmVjaGFuZ2UnLCBvbkdlc3R1cmUgYXMgRXZlbnRMaXN0ZW5lcik7CisgICAgd2luZG93LmFkZEV2ZW50TGlzdGVuZXIoJ2dlc3R1cmVlbmQnLCBvbkdlc3R1cmUgYXMgRXZlbnRMaXN0ZW5lcik7CisgICAgd2luZG93LmFkZEV2ZW50TGlzdGVuZXIoJ2tleWRvd24nLCBvbktleURvd24pOworICAgIHJldHVybiAoKSA9PiB7CisgICAgICB3aW5kb3cucmVtb3ZlRXZlbnRMaXN0ZW5lcignd2hlZWwnLCBvbldoZWVsKTsKKyAgICAgIHdpbmRvdy5yZW1vdmVFdmVudExpc3RlbmVyKCdnZXN0dXJlc3RhcnQnLCBvbkdlc3R1cmUgYXMgRXZlbnRMaXN0ZW5lcik7CisgICAgICB3aW5kb3cucmVtb3ZlRXZlbnRMaXN0ZW5lcignZ2VzdHVyZWNoYW5nZScsIG9uR2VzdHVyZSBhcyBFdmVudExpc3RlbmVyKTsKKyAgICAgIHdpbmRvdy5yZW1vdmVFdmVudExpc3RlbmVyKCdnZXN0dXJlZW5kJywgb25HZXN0dXJlIGFzIEV2ZW50TGlzdGVuZXIpOworICAgICAgd2luZG93LnJlbW92ZUV2ZW50TGlzdGVuZXIoJ2tleWRvd24nLCBvbktleURvd24pOworICAgIH07CisgIH0sIFtdKTsKK30KLS0tIC9kZXYvbnVsbAorKysgYi90b2dldGhlci1jaXR5LXJlYWN0L3NyYy9hcHAvem9vbS1pcy1sb2NrZWQudGVzdC50cwpAQCAtMCwwICsxLDc1IEBACitpbXBvcnQgeyBkZXNjcmliZSwgaXQsIGV4cGVjdCB9IGZyb20gJ3ZpdGVzdCc7CitpbXBvcnQgeyByZWFkRmlsZVN5bmMgfSBmcm9tICdub2RlOmZzJzsKK2ltcG9ydCB7IGRpcm5hbWUsIGpvaW4gfSBmcm9tICdub2RlOnBhdGgnOworaW1wb3J0IHsgZmlsZVVSTFRvUGF0aCB9IGZyb20gJ25vZGU6dXJsJzsKKworY29uc3QgQVBQID0gam9pbihkaXJuYW1lKGZpbGVVUkxUb1BhdGgoaW1wb3J0Lm1ldGEudXJsKSksICcuLicsICcuLicpOworY29uc3QgcmVhZCA9IChwOiBzdHJpbmcpID0+IHJlYWRGaWxlU3luYyhqb2luKEFQUCwgcCksICd1dGY4Jyk7CisvKiogQSBmaWxlIGlzIGFsbG93ZWQgdG8gbmFtZSB0aGUgdGhpbmcgaXQgcmVmdXNlcyB0byBkby4gQ29tbWVudHMgYXJlIG5vdCBjb2RlIOKAlAorICogIHRoZSBzYW1lIHJ1bGUgcmVsaWVmLnNwZWMudHMgYXBwbGllcyB0byBDU1MsIGZvciB0aGUgc2FtZSByZWFzb246IHRoaXMgZmlsZSdzCisgKiAgb3duIHByb3NlIHNheXMgIm5vIHRvdWNoLWFjdGlvbjogbm9uZSIsIGFuZCBhIGd1YXJkIHRoYXQgY2Fubm90IHRlbGwgYW4KKyAqICBleHBsYW5hdGlvbiBmcm9tIGFuIGltcGxlbWVudGF0aW9uIGZhaWxzIG9uIHRoZSBzZW50ZW5jZSBleHBsYWluaW5nIGl0c2VsZi4gKi8KK2NvbnN0IGNvZGUgPSAoc3JjOiBzdHJpbmcpID0+IHNyYy5yZXBsYWNlKC9cL1wqW1xzXFNdKj9cKlwvL2csICcgJykucmVwbGFjZSgvKF58W146XSlcL1wvLiokL2dtLCAnJDEgJyk7CisKKy8qKgorICogVEhFIFpPT00gR1VBUkQgSVMgT05FIExJTkUgQVdBWSBGUk9NIEJFSU5HIERFQ09SQVRJT04sIElOIFRIUkVFIERJUkVDVElPTlMuCisgKgorICogRXZlcnkgb25lIG9mIHRoZXNlIGhhcyBhIHBsYXVzaWJsZSwgd2VsbC1tZWFudCBlZGl0IHRoYXQgc2lsZW50bHkgdHVybnMgdGhlCisgKiBmZWF0dXJlIG9mZiBvciBicmVha3Mgc29tZXRoaW5nIHdvcnNlLCBhbmQgbm9uZSBvZiB0aGVtIHNob3dzIHVwIGFzIGEgZmFpbGluZworICogc2NyZWVuIOKAlCB3aGljaCBpcyBleGFjdGx5IHRoZSBzaGFwZSBvZiB0aGluZyB0aGF0IG5lZWRzIGEgdGVzdCByYXRoZXIgdGhhbiBhCisgKiBjb21tZW50LgorICovCitkZXNjcmliZSgnem9vbSBpcyBsb2NrZWQsIGFuZCBzY3JvbGxpbmcgaXMgbm90JywgKCkgPT4geworICBjb25zdCBob29rID0gcmVhZCgnc3JjL2hvb2tzL3VzZVpvb21Mb2NrLnRzJyk7CisKKyAgLyoqCisgICAqIFRoZSBvbmUgdGhhdCBhY3R1YWxseSB3b3JrcywgYW5kIHRoZSBvbmUgd29yZCB0aGF0IG1ha2VzIGl0IHdvcmsuCisgICAqIEEgcGFzc2l2ZSBsaXN0ZW5lciBtYXkgbm90IGNhbGwgcHJldmVudERlZmF1bHQsIGFuZCBldmVyeSBkZWZhdWx0LXJlZ2lzdGVyZWQKKyAgICogd2hlZWwgbGlzdGVuZXIgaW4gYSBicm93c2VyIGlzIHBhc3NpdmUuIERyb3AgYHsgcGFzc2l2ZTogZmFsc2UgfWAgYW5kIHRoZQorICAgKiBwaW5jaCBndWFyZCBiZWNvbWVzIGEgbm8tb3AgdGhhdCBzdGlsbCByZWFkcyBjb3JyZWN0bHkuCisgICAqLworICBpdCgncmVnaXN0ZXJzIHRoZSB3aGVlbCBndWFyZCBhcyBub24tcGFzc2l2ZSwgb3IgaXQgcHJldmVudHMgbm90aGluZycsICgpID0+IHsKKyAgICBleHBlY3QoaG9vaykudG9NYXRjaCgvYWRkRXZlbnRMaXN0ZW5lclwoXHMqJ3doZWVsJ1tcc1xTXXswLDYwfXBhc3NpdmU6XHMqZmFsc2UvKTsKKyAgfSk7CisKKyAgLyoqCisgICAqIFNDUk9MTElORyBJUyBOT1QgWk9PTUlORy4gVGhlIHVzdWFsIHdheSB0aGlzIGZlYXR1cmUgaXMgaW1wbGVtZW50ZWQg4oCUIGFuZAorICAgKiB0aGUgcmVhc29uIHBlb3BsZSBoYXRlIGl0IOKAlCBpcyBhIGJsYW5rZXQgdG91Y2ggb3Igd2hlZWwgYmxvY2ssIHdoaWNoIHRha2VzCisgICAqIHNjcm9sbGluZyB3aXRoIGl0LiBOb3RoaW5nIG1heSBiZSBwcmV2ZW50ZWQgdW5sZXNzIHRoZSBtb2RpZmllciB0aGF0IG1lYW5zCisgICAqICJ6b29tIiBpcyBoZWxkLgorICAgKi8KKyAgaXQoJ25ldmVyIHByZXZlbnRzIGEgd2hlZWwgZXZlbnQgdGhhdCBpcyBub3QgYSB6b29tJywgKCkgPT4geworICAgIGNvbnN0IGJvZHkgPSBob29rLnNsaWNlKGhvb2suaW5kZXhPZignY29uc3Qgb25XaGVlbCcpLCBob29rLmluZGV4T2YoJ2NvbnN0IG9uR2VzdHVyZScpKTsKKyAgICBleHBlY3QoYm9keSkudG9NYXRjaCgvaWZccypcKFteKV0qKGN0cmxLZXl8bWV0YUtleSlbXildKlwpXHMqZVwucHJldmVudERlZmF1bHRcKFwpLyk7CisgICAgLy8gVGhlIHR3byBibHVudCBpbnN0cnVtZW50cyB0aGF0IGJyZWFrIHNjcm9sbGluZyBmb3IgZXZlcnlib2R5LgorICAgIGV4cGVjdChjb2RlKGhvb2spKS5ub3QudG9NYXRjaCgvdG91Y2gtYWN0aW9uOlxzKm5vbmUvKTsKKyAgICBleHBlY3QoY29kZShob29rKSkubm90LnRvTWF0Y2goLyd0b3VjaG1vdmUnLyk7CisgIH0pOworCisgIC8qKiBTYWZhcmkvbWFjT1MgZG9lcyBub3Qgc3ludGhlc2lzZSB0aGUgY3RybC13aGVlbDsgd2l0aG91dCB0aGVzZSwgaXRzIHBpbmNoCisgICAqICBpcyBzaW1wbHkgdW5ndWFyZGVkIGFuZCBub2JvZHkgd291bGQgbm90aWNlIG9uIGEgTWFjIHJ1bm5pbmcgQ2hyb21lLiAqLworICBpdCgnY292ZXJzIHRoZSBTYWZhcmkgcGluY2gsIHdoaWNoIGFycml2ZXMgYXMgaXRzIG93biBldmVudCBmYW1pbHknLCAoKSA9PiB7CisgICAgZm9yIChjb25zdCBlIG9mIFsnZ2VzdHVyZXN0YXJ0JywgJ2dlc3R1cmVjaGFuZ2UnLCAnZ2VzdHVyZWVuZCddKSB7CisgICAgICBleHBlY3QoeyBldmVudDogZSwgaGFuZGxlZDogaG9vay5pbmNsdWRlcyhgJyR7ZX0nYCkgfSkudG9FcXVhbCh7IGV2ZW50OiBlLCBoYW5kbGVkOiB0cnVlIH0pOworICAgIH0KKyAgfSk7CisKKyAgLyoqIFJlZ2lzdGVyZWQgYWJvdmUgdGhlIHJvdXRlciwgYmVjYXVzZSBzZXZlcmFsIHJvdXRlIGJsb2NrcyBhcmUgU0lCTElOR1Mgb2YKKyAgICogIEFwcFNoZWxsIHJhdGhlciB0aGFuIGNoaWxkcmVuIG9mIGl0IOKAlCB0aGUgc2FtZSB0cmFwIHRoYXQgb25jZSBsZWZ0CisgICAqICBDYWxsQ2VudGVyIHVuYWJsZSB0byByZWFjaCBoYWxmIHRoZSBhcHBsaWNhdGlvbi4gKi8KKyAgaXQoJ2lzIGluc3RhbGxlZCBvbmNlLCBhYm92ZSB0aGUgcm91dGVyLCBub3QgcGFnZSBieSBwYWdlJywgKCkgPT4geworICAgIGV4cGVjdChyZWFkKCdzcmMvYXBwL0FwcC50c3gnKSkudG9NYXRjaCgvdXNlWm9vbUxvY2tcKFwpLyk7CisgIH0pOworCisgIC8qKiBUaGUgbW9iaWxlIGhhbGYuIEtlcHQgaG9uZXN0OiBpZiBzb21lYm9keSByZXN0b3JlcyBwaW5jaC10by16b29tIG9uCisgICAqICBwaG9uZXMgdGhpcyB0ZXN0IGlzIHRoZSB0aGluZyB0aGF0IHNheXMgdGhlIGRlc2t0b3AgZ3VhcmQgaXMgbm93IGRvaW5nCisgICAqICB0aGUgam9iIGFsb25lLCByYXRoZXIgdGhhbiB0aGUgY2hhbmdlIHBhc3NpbmcgdW5yZW1hcmtlZC4gKi8KKyAgaXQoJ2NhcnJpZXMgdGhlIG1vYmlsZSBzY2FsZSBsb2NrIGluIHRoZSB2aWV3cG9ydCBtZXRhJywgKCkgPT4geworICAgIGNvbnN0IGh0bWwgPSByZWFkKCdpbmRleC5odG1sJyk7CisgICAgZXhwZWN0KGh0bWwpLnRvTWF0Y2goL25hbWU9InZpZXdwb3J0IltePl0qbWF4aW11bS1zY2FsZT0xXC4wLyk7CisgICAgZXhwZWN0KGh0bWwpLnRvTWF0Y2goL25hbWU9InZpZXdwb3J0IltePl0qdXNlci1zY2FsYWJsZT1uby8pOworICAgIC8vIFJlc3BvbnNpdmVuZXNzIGlzIE5PVCB3aGF0IHdhcyBsb2NrZWQsIGFuZCBhIHdpZHRoIG90aGVyIHRoYW4KKyAgICAvLyBkZXZpY2Utd2lkdGggd291bGQgYmUgdGhlIG9uZSBlZGl0IGhlcmUgdGhhdCBicmVha3MgZXZlcnkgcGhvbmUuCisgICAgZXhwZWN0KGh0bWwpLnRvTWF0Y2goL25hbWU9InZpZXdwb3J0IltePl0qd2lkdGg9ZGV2aWNlLXdpZHRoLyk7CisgIH0pOworfSk7Cg==
B64EOF

WANT="6eb8e5d924f9f1ff09555bba7a2976f3c8eaaf357b0f9d8e182bdf0e9e4931d0"
GOT="$(shasum -a 256 "$PATCH" | awk '{print $1}')"
[ "$GOT" = "$WANT" ] || { echo "!! Patch is corrupt."; echo "   want $WANT"; echo "   got  $GOT"; exit 1; }
echo "== patch verified"
git apply --check -C1 "$PATCH" || { echo "!! Patch does not apply cleanly. Nothing written."; exit 1; }
git apply -C1 "$PATCH"
echo "== applied"

cd together-city-react
npx tsc --noEmit
npx vitest run
node scripts/a11y-audit.mjs
node scripts/lint-ceiling.mjs
npx vite build
cd ..

git add together-city-react/src/hooks/useZoomLock.ts \
        together-city-react/src/app/zoom-is-locked.test.ts \
        together-city-react/src/app/App.tsx \
        together-city-react/index.html
git commit -F - <<'MSG'
The city cannot be pinched out of shape

The owner watched the desktop city distort under a trackpad pinch. This is
everything a web page can honestly do about that, and the parts it cannot do
are named rather than faked.

WHAT ACTUALLY HOLDS:

- `wheel` with ctrlKey, registered NON-PASSIVE. A trackpad pinch is not a touch
  gesture on a desktop browser — Chrome, Edge and Firefox synthesise a wheel
  event with ctrlKey set, and that event is cancellable. One guard therefore
  covers both the pinch and Ctrl/Cmd + mouse wheel, because they are the same
  event. `{ passive: false }` is the whole trick: React's onWheel and every
  default-registered wheel listener are passive, and a passive listener may not
  call preventDefault, so the obvious implementation of this feature is a no-op
  that reads correctly. There is a test for that one word.
- `gesturestart` / `gesturechange` / `gestureend` for Safari on macOS, which
  does not synthesise the ctrl-wheel and fires its own family instead.
- `maximum-scale=1, user-scalable=no` in the viewport meta.

WHAT DOES NOT, STATED PLAINLY: Ctrl/Cmd with +, - or 0 cannot be blocked by a
web page. Chrome, Safari and Firefox handle browser-zoom shortcuts above the
document; the keydown either never arrives or is not cancellable. The handler
is registered because it is correct in an Electron shell or a WebView and costs
nothing elsewhere — but it is not a promise, and shipping it without saying so
would be a decoration that looks like a feature. iOS Safari has ignored
`user-scalable=no` since iOS 10, deliberately; there is no override.

SCROLLING IS NOT ZOOMING. The usual implementation of this — `touch-action:
none`, a blanket touchmove block — breaks scrolling, which is a far worse bug
than the one being fixed. Nothing is prevented unless the modifier that means
"zoom" is held. Verified in a real browser rather than asserted: plain wheel
still scrolls 0→400, touch scroll still moves 0→600, ctrl-wheel prevented and
does NOT scroll the page.

THE ACCESSIBILITY COST, ON THE RECORD. Blocking pinch-to-zoom fails WCAG 2.1
SC 1.4.4 (Resize Text) on Android Chrome, the one platform where the meta is
honoured. The owner was asked directly and chose it. Writing it in the commit
and in the hook means the next person finds a decision, not a bug — and it is
one attribute to give back.

AND WHAT WAS NOT DONE: the request also asked to lock the render at 90%, which
contradicts its own "the desktop layout should remain exactly as it is at 100%
zoom". Asked; the owner chose to leave the size alone. Nothing here scales
anything — no transform, no `zoom`, no root font-size. Every measured thing
that landed today (the nav fit, the billboard contrast, the crop anchors) is
untouched, which it would not have been.

TESTED: Chromium desktop (Chrome macOS and Windows share this engine) and
Mobile Chrome (Pixel 7) — ctrl+wheel prevented, page does not scroll, plain
wheel still scrolls, preventDefault takes effect. Trackpad pinch, both
directions, 2 of 2 prevented. Safari's gesture family all three prevented.
WebKit could not be launched in this container, so Safari's engine is covered
by the gesture handlers and the shared meta rather than by a run — that is a
gap in the evidence, not a claim.

tsc clean, vitest 442/442 (5 new), a11y 0, lint at ceiling, vite build clean.

MSG
echo "== committed"

echo
echo "==============================================================="
echo " Landed: $NEEDS — push and Vercel ships it."
echo " Pinch and Ctrl/Cmd+wheel blocked; scrolling untouched."
echo " Ctrl/Cmd +/-/0 cannot be blocked by a page — see the commit."
echo "==============================================================="
