/**
 * A QR encoder, because the alternative was a dependency for one square.
 *
 * The citizen card is a picture somebody sends to a friend who is NOT in
 * Together City. A handle on a picture is not clickable, so the card carries a
 * QR and a plain URL; that is the whole reason the code exists.
 *
 * WHY NOT `npm i qrcode`. This repo has thirteen runtime dependencies and adds
 * them deliberately — framer-motion was argued for in CLAUDE.md before it
 * landed. A QR encoder is a well-specified, finite, testable thing: byte mode,
 * one error-correction level, six versions. It is about two hundred lines and
 * it never needs updating, where a dependency is a supply chain, a bundle
 * cost, and a thing to upgrade forever.
 *
 * AND IT IS CHECKED AGAINST A REFERENCE IMPLEMENTATION, not against my
 * reading of the spec: `src/app/qr-matches-a-reference-encoder.test.ts`
 * compares the matrices this produces to ones generated by the Python
 * `qrcode` library, byte for byte, for URLs of several lengths. A
 * hand-written encoder nobody decoded is a picture of a QR code.
 *
 * SCOPE, deliberately small:
 *   - byte mode only (a URL is bytes)
 *   - error correction level M (~15%), the usual choice for print
 *   - versions 1–6, which hold 106 bytes. A profile URL is about thirty.
 *     Stopping at 6 means no version-information block, which is a whole
 *     second BCH code and a whole second thing to get wrong.
 */

/** Byte-mode capacity at level M, versions 1–6. */
const CAPACITY = [14, 26, 42, 62, 84, 106];

/** Level M, versions 1–6: [ec codewords per block, block sizes in data codewords]. */
const BLOCKS: Array<{ ec: number; groups: number[] }> = [
  { ec: 10, groups: [16] },
  { ec: 16, groups: [28] },
  { ec: 26, groups: [44] },
  { ec: 18, groups: [32, 32] },
  { ec: 24, groups: [43, 43] },
  { ec: 16, groups: [27, 27, 27, 27] },
];

/** Alignment-pattern centres per version. Version 1 has none. */
const ALIGN: number[][] = [[], [6, 18], [6, 22], [6, 26], [6, 30], [6, 34]];

/* ── GF(256), primitive polynomial 0x11d ──────────────────────────────── */
const EXP = new Uint8Array(512);
const LOG = new Uint8Array(256);
(() => {
  let x = 1;
  for (let i = 0; i < 255; i += 1) {
    EXP[i] = x; LOG[x] = i;
    x <<= 1;
    if (x & 0x100) x ^= 0x11d;
  }
  for (let i = 255; i < 512; i += 1) EXP[i] = EXP[i - 255];
})();
const mul = (a: number, b: number) => (a === 0 || b === 0 ? 0 : EXP[LOG[a] + LOG[b]]);

/** The generator polynomial for `n` error-correction codewords. */
function generator(n: number): number[] {
  let g = [1];
  for (let i = 0; i < n; i += 1) {
    const next = new Array<number>(g.length + 1).fill(0);
    for (let j = 0; j < g.length; j += 1) {
      next[j] ^= mul(g[j], 1);
      next[j + 1] ^= mul(g[j], EXP[i]);
    }
    g = next;
  }
  return g;
}

function ecFor(data: number[], n: number): number[] {
  const g = generator(n);
  const rem = new Array<number>(n).fill(0);
  for (const d of data) {
    const factor = d ^ rem[0];
    rem.shift(); rem.push(0);
    for (let i = 0; i < n; i += 1) rem[i] ^= mul(g[i + 1], factor);
  }
  return rem;
}

/* ── the matrix ───────────────────────────────────────────────────────── */

type Grid = { size: number; mod: Int8Array; fixed: Uint8Array };
const at = (g: Grid, r: number, c: number) => g.mod[r * g.size + c];
const put = (g: Grid, r: number, c: number, v: number, fixed = true) => {
  g.mod[r * g.size + c] = v;
  if (fixed) g.fixed[r * g.size + c] = 1;
};

function frame(version: number): Grid {
  const size = version * 4 + 17;
  const g: Grid = { size, mod: new Int8Array(size * size).fill(0), fixed: new Uint8Array(size * size) };

  const finder = (r0: number, c0: number) => {
    for (let r = -1; r <= 7; r += 1) {
      for (let c = -1; c <= 7; c += 1) {
        const rr = r0 + r, cc = c0 + c;
        if (rr < 0 || cc < 0 || rr >= size || cc >= size) continue;
        const on = (r >= 0 && r <= 6 && (c === 0 || c === 6))
          || (c >= 0 && c <= 6 && (r === 0 || r === 6))
          || (r >= 2 && r <= 4 && c >= 2 && c <= 4);
        put(g, rr, cc, on ? 1 : 0);
      }
    }
  };
  finder(0, 0); finder(0, size - 7); finder(size - 7, 0);

  for (let i = 8; i < size - 8; i += 1) {
    const on = i % 2 === 0 ? 1 : 0;
    put(g, 6, i, on); put(g, i, 6, on);
  }

  for (const r of ALIGN[version - 1]) {
    for (const c of ALIGN[version - 1]) {
      /* Alignment patterns never sit on a finder. */
      if ((r <= 8 && c <= 8) || (r <= 8 && c >= size - 9) || (r >= size - 9 && c <= 8)) continue;
      for (let dr = -2; dr <= 2; dr += 1) {
        for (let dc = -2; dc <= 2; dc += 1) {
          const on = Math.max(Math.abs(dr), Math.abs(dc)) !== 1 ? 1 : 0;
          put(g, r + dr, c + dc, on);
        }
      }
    }
  }

  /* The dark module, and the two format-information strips reserved. */
  put(g, size - 8, 8, 1);
  for (let i = 0; i < 9; i += 1) {
    if (i !== 6) { put(g, 8, i, 0); put(g, i, 8, 0); }
  }
  for (let i = 0; i < 8; i += 1) {
    put(g, 8, size - 1 - i, 0);
    if (i < 7) put(g, size - 1 - i, 8, 0);
  }
  return g;
}

const MASKS: Array<(r: number, c: number) => boolean> = [
  (r, c) => (r + c) % 2 === 0,
  (r) => r % 2 === 0,
  (_r, c) => c % 3 === 0,
  (r, c) => (r + c) % 3 === 0,
  (r, c) => (Math.floor(r / 2) + Math.floor(c / 3)) % 2 === 0,
  (r, c) => ((r * c) % 2) + ((r * c) % 3) === 0,
  (r, c) => (((r * c) % 2) + ((r * c) % 3)) % 2 === 0,
  (r, c) => (((r + c) % 2) + ((r * c) % 3)) % 2 === 0,
];

/** The four penalty rules, applied to a fully masked matrix. */
function penalty(g: Grid): number {
  const { size } = g;
  let score = 0;

  const run = (get: (i: number, j: number) => number) => {
    for (let i = 0; i < size; i += 1) {
      let last = -1, len = 0;
      for (let j = 0; j < size; j += 1) {
        const v = get(i, j);
        if (v === last) { len += 1; } else { if (len >= 5) score += len - 2; last = v; len = 1; }
      }
      if (len >= 5) score += len - 2;
    }
  };
  run((i, j) => at(g, i, j));
  run((i, j) => at(g, j, i));

  for (let r = 0; r < size - 1; r += 1) {
    for (let c = 0; c < size - 1; c += 1) {
      const v = at(g, r, c);
      if (v === at(g, r, c + 1) && v === at(g, r + 1, c) && v === at(g, r + 1, c + 1)) score += 3;
    }
  }

  const PAT = [1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0];
  const hasAt = (get: (k: number) => number, start: number) => {
    for (let k = 0; k < 11; k += 1) if (get(start + k) !== PAT[k]) return false;
    return true;
  };
  const hasRev = (get: (k: number) => number, start: number) => {
    for (let k = 0; k < 11; k += 1) if (get(start + k) !== PAT[10 - k]) return false;
    return true;
  };
  for (let i = 0; i < size; i += 1) {
    for (let j = 0; j <= size - 11; j += 1) {
      if (hasAt((k) => at(g, i, k), j) || hasRev((k) => at(g, i, k), j)) score += 40;
      if (hasAt((k) => at(g, k, i), j) || hasRev((k) => at(g, k, i), j)) score += 40;
    }
  }

  let dark = 0;
  for (let i = 0; i < size * size; i += 1) if (g.mod[i]) dark += 1;
  score += Math.floor(Math.abs((dark * 100) / (size * size) - 50) / 5) * 10;
  return score;
}

/** BCH(15,5) format information for level M and a mask. */
function formatBits(mask: number): number {
  const data = (0b00 << 3) | mask;           /* level M is 00 */
  let rem = data << 10;
  for (let i = 14; i >= 10; i -= 1) if (rem & (1 << i)) rem ^= 0b10100110111 << (i - 10);
  return ((data << 10) | rem) ^ 0b101010000010010;
}

/**
 * Encode `text` as a QR matrix of 0/1 rows.
 *
 * Throws if the text does not fit in version 6 at level M — 106 bytes. A
 * silent truncation would produce a code that scans and goes somewhere else,
 * which is worse than no code at all.
 */
export function qrMatrix(text: string, forceMask?: number): number[][] {
  const bytes = [...new TextEncoder().encode(text)];
  const version = CAPACITY.findIndex((cap) => bytes.length <= cap) + 1;
  if (version === 0) throw new Error(`QR: ${bytes.length} bytes exceeds the 106 this encoder supports`);

  const { ec, groups } = BLOCKS[version - 1];
  const totalData = groups.reduce((a, b) => a + b, 0);

  /* ── the bitstream ── */
  const bits: number[] = [];
  const push = (value: number, len: number) => {
    for (let i = len - 1; i >= 0; i -= 1) bits.push((value >> i) & 1);
  };
  push(0b0100, 4);                 /* byte mode */
  push(bytes.length, 8);           /* 8-bit count field for versions 1–9 */
  for (const b of bytes) push(b, 8);
  for (let i = 0; i < 4 && bits.length < totalData * 8; i += 1) bits.push(0);
  while (bits.length % 8 !== 0) bits.push(0);

  const codewords: number[] = [];
  for (let i = 0; i < bits.length; i += 8) {
    codewords.push(bits.slice(i, i + 8).reduce((a, b) => (a << 1) | b, 0));
  }
  for (let i = 0; codewords.length < totalData; i += 1) codewords.push(i % 2 === 0 ? 0xec : 0x11);

  /* ── blocks, error correction, interleave ── */
  const dataBlocks: number[][] = [];
  const ecBlocks: number[][] = [];
  let cursor = 0;
  for (const n of groups) {
    const block = codewords.slice(cursor, cursor + n);
    cursor += n;
    dataBlocks.push(block);
    ecBlocks.push(ecFor(block, ec));
  }
  const stream: number[] = [];
  for (let i = 0; i < Math.max(...groups); i += 1) {
    for (const b of dataBlocks) if (i < b.length) stream.push(b[i]);
  }
  for (let i = 0; i < ec; i += 1) for (const b of ecBlocks) stream.push(b[i]);

  /* ── placement, zigzag from the bottom right ── */
  const base = frame(version);
  const size = base.size;
  const dataBits: number[] = [];
  for (const cw of stream) for (let i = 7; i >= 0; i -= 1) dataBits.push((cw >> i) & 1);

  let bit = 0;
  let up = true;
  for (let right = size - 1; right >= 1; right -= 2) {
    /* THE SHIFT IS PERMANENT ONCE PAST THE TIMING COLUMN, not a single
       skip. Written `right === 6` the pairs came out (5,4) then (4,3) — the
       same column twice — and every module left of the timing line was
       placed wrong. `right <= 6` shifts all of the remaining pairs by one,
       which is what the zigzag actually does. */
    const col = right <= 6 ? right - 1 : right;
    for (let step = 0; step < size; step += 1) {
      const r = up ? size - 1 - step : step;
      for (const c of [col, col - 1]) {
        if (base.fixed[r * size + c]) continue;
        base.mod[r * size + c] = bit < dataBits.length ? dataBits[bit] : 0;
        bit += 1;
      }
    }
    up = !up;
  }

  /* ── mask, by penalty ── */
  let best = 0, bestScore = Infinity, bestGrid: Grid | null = null;
  for (let m = 0; m < 8; m += 1) {
    if (forceMask !== undefined && m !== forceMask) continue;
    const g: Grid = { size, mod: base.mod.slice(), fixed: base.fixed };
    for (let r = 0; r < size; r += 1) {
      for (let c = 0; c < size; c += 1) {
        if (!g.fixed[r * size + c] && MASKS[m](r, c)) g.mod[r * size + c] ^= 1;
      }
    }
    writeFormat(g, m);
    const s = penalty(g);
    if (s < bestScore) { bestScore = s; best = m; bestGrid = g; }
  }
  void best;

  const out: number[][] = [];
  for (let r = 0; r < size; r += 1) {
    out.push(Array.from(bestGrid!.mod.subarray(r * size, r * size + size)));
  }
  return out;
}

function writeFormat(g: Grid, mask: number) {
  const bitsVal = formatBits(mask);
  const { size } = g;
  /* MSB FIRST. The fifteen positions below take the format string in the
     order it is written — (8,0) holds bit 14, not bit 0. Reading it the other
     way round leaves eleven of fifteen bits right, which looks like a
     placement bug and is not one. */
  const read = (i: number) => (bitsVal >> (14 - i)) & 1;
  for (let i = 0; i <= 5; i += 1) g.mod[8 * size + i] = read(i);
  g.mod[8 * size + 7] = read(6);
  g.mod[8 * size + 8] = read(7);
  g.mod[7 * size + 8] = read(8);
  for (let i = 9; i <= 14; i += 1) g.mod[(14 - i) * size + 8] = read(i);

  /* THE SECOND COPY SPLITS 7 / 8, NOT 8 / 7. Seven modules run up the column
     beside the bottom-left finder, the dark module sits above them, and the
     remaining EIGHT run along row 8 on the right. Splitting it the other way
     puts every bit of the second copy one place out — which is exactly the
     ~30-module difference the reference comparison showed while the data
     region already matched perfectly. */
  for (let i = 0; i <= 6; i += 1) g.mod[(size - 1 - i) * size + 8] = read(i);
  for (let i = 7; i <= 14; i += 1) g.mod[8 * size + (size - 15 + i)] = read(i);
  g.mod[(size - 8) * size + 8] = 1;
}
