import { SUPPLEMENTS } from './knowledge';

/**
 * THE SHELF — 43 PRODUCTS ACTUALLY SOLD IN INDIA.
 *
 * Every row below was read off the same evidence review the knowledge base
 * came from ("Supplements, Honestly", August 2026), out of its "Available in
 * India" tables: a brand, the strength printed on the label, the price at the
 * retailer on the day the review was compiled, and the link to buy it.
 *
 * THE ONE INVARIANT. `supplement` on every row is an id that exists in
 * `knowledge.ts`, and the spec asserts it. A product this city can show but
 * cannot say the evidence for is a product this city has no business showing —
 * the shelf and the plan resolve to the same file or the shelf is just a
 * catalogue with a health page bolted on. That rule cost one real product: the
 * review lists a Carbamide Forte probiotic, and probiotics have no entry in
 * the knowledge base (the review covers them only in its "named strains for
 * named problems" note), so it is not here.
 *
 * TOGETHER CITY DOES NOT TAKE THE MONEY. `url` goes to the retailer's own
 * page — Tata 1mg, HealthKart, Nutrabay, the brand's own store — and that is
 * the whole checkout. There is no cart on this side, no margin, no affiliate
 * parameter appended to any link in this file. The plan page's argument was
 * that the moment a refusal costs revenue the refusals get quieter, and the
 * cheapest way to keep that true is to never be in the transaction. It is
 * also why 12 of these rows sit under supplements the engine REFUSES: the
 * shelf shows them with the refusal attached rather than hiding them, because
 * somebody who is going to buy a multivitamin anyway should meet the 78-trial
 * null before the checkout page and not after it.
 *
 * PRICES GO STALE. `price` is a string with its unit attached ("₹649 / 30
 * strips") and never a number pretending to be current — `priceFrom` exists
 * only to sort the grid. The screen says when the review was compiled.
 *
 * `pack` and `colour` are the review's own drawn renderings of the dosage
 * format — a strip, a blister, a tub — so the grid can draw every product
 * itself and owe nothing to a retailer's CDN. `image` is the photo where the
 * retailer publishes one; a screen may use it, and must survive it failing.
 */

export type PackShape =
  | 'strip' | 'blister' | 'sachet' | 'syrup' | 'jar' | 'pouch' | 'tub'
  | 'bottle-tab' | 'bottle-cap' | 'bottle-soft';

export interface Product {
  id: string;
  /** An id in SUPPLEMENTS. Enforced by the spec, not by convention. */
  supplement: string;
  brand: string;
  name: string;
  /** What the label says is in it, in the review's words. */
  strength?: string;
  /** With its unit attached, as read on the day of the review. */
  price?: string;
  /** For sorting only. Never shown as a price. */
  priceFrom?: number;
  /**
   * THE TILL PRICE, IN WHOLE RUPEES, and the only number the wallet is ever
   * charged. Present ONLY where the review recorded one unambiguous price for
   * one pack: a range ("₹379–₹999 for 100–400 g") is three products wearing
   * one row, and "Stock intermittent" is not a price at all. Three of the 43
   * have no `priceInr` and cannot be bought here — the card says so rather
   * than guessing at the middle of a range and charging it.
   *
   * The city's till is in whole rupees, as every other hub's is. Two of these
   * were recorded in paise (₹34.60, ₹23.90) and round to the nearest rupee;
   * the card prints both the till price and the recorded label, so the
   * rounding is visible rather than quiet.
   */
  priceInr?: number;
  /** The review's own notes on the product — certification, or a warning. */
  tags: string[];
  /** Prescription-only in India. */
  rx: boolean;
  pack: PackShape;
  colour: string;
  retailer: string;
  url: string;
  image?: string;
}

export const PRODUCTS: Product[] = [
  {
    id: "wellbeing-nutrition-melts-plant-based-d3-k2-oral-strips",
    supplement: "vitamin-d3",
    brand: "Wellbeing Nutrition",
    name: "Melts Plant-Based D3 + K2 oral strips",
    strength: "600 IU D3 (lichen) + MK-7",
    price: "₹649 / 30 strips",
    priceFrom: 649,
    priceInr: 649,
    tags: ["Vegan", "Vitashine"],
    rx: false,
    pack: "strip",
    colour: "#eda100",
    retailer: "Wellbeing Nutrition",
    url: "https://wellbeingnutrition.com/products/melts-plant-based-d3k2-oral-strips",
    image: "https://wellbeingnutrition.com/cdn/shop/files/IMG1_a5772f05-a142-4bb2-a56d-57a7a53f4ed4.webp",
  },
  {
    id: "carbamide-forte-vitamin-d3-k2-mk-7-lichen-source",
    supplement: "vitamin-d3",
    brand: "Carbamide Forte",
    name: "Vitamin D3 + K2 MK-7, lichen source",
    strength: "Labelled 100% RDA",
    price: "₹449 / 120 tablets",
    priceFrom: 449,
    priceInr: 449,
    tags: ["Vegetarian"],
    rx: false,
    pack: "bottle-tab",
    colour: "#eda100",
    retailer: "Carbamide Forte",
    url: "https://mycf.in/products/vitamin-d3-k2-mk7-plant-based-veg-vitamin-d-supplements-lichen-source-with-vitamin-k2-mk7-menaquinone-120-veg-tablets",
    image: "https://mycf.in/cdn/shop/files/1_7_c48e4ac8-7f9c-4b32-b9cd-6eab503772bb.jpg?v=1782214947",
  },
  {
    id: "cadila-calcirol-60k-sachet",
    supplement: "vitamin-d3",
    brand: "Cadila",
    name: "Calcirol 60K sachet",
    strength: "60,000 IU per 1 g sachet",
    price: "₹34.60 / sachet",
    priceFrom: 34.6,
    priceInr: 35,
    tags: ["Repletion only"],
    rx: false,
    pack: "sachet",
    colour: "#eb6834",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/calcirol-60k-iu-cholecalciferol-sachet-for-bone-health-otc111246",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/90c75e6999a84b09aafbb3b72bf18306.jpg",
  },
  {
    id: "alkem-uprise-d3-60k-capsule",
    supplement: "vitamin-d3",
    brand: "Alkem",
    name: "Uprise-D3 60K capsule",
    strength: "60,000 IU",
    price: "₹362 / 12 capsules",
    priceFrom: 362,
    priceInr: 362,
    tags: ["Prescription"],
    rx: true,
    pack: "blister",
    colour: "#eb6834",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/drugs/uprise-d3-60k-capsule-918999",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/213c2782b4a849b4b6796140a7109a7e.jpg",
  },
  {
    id: "arachitol-nano-60k-oral-solution",
    supplement: "vitamin-d3",
    brand: "Arachitol",
    name: "Nano 60K oral solution",
    strength: "60,000 IU per 5 ml",
    price: "₹466 / 4 × 5 ml",
    priceFrom: 466,
    priceInr: 466,
    tags: ["Repletion only"],
    rx: false,
    pack: "syrup",
    colour: "#eda100",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/arachitol-nano-bottle-60k-iu-vitamin-d3-oral-solution-5ml-each-bone-joint-and-muscle-care-otc323191",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/a0ecb279e17c4693ab01a15ac9258939.jpg",
  },
  {
    id: "torrent-shelcal-500",
    supplement: "vitamin-d3",
    brand: "Torrent",
    name: "Shelcal 500",
    strength: "500 mg elemental Ca + 250 IU D3",
    price: "₹356 / 40 tablets",
    priceFrom: 356,
    priceInr: 356,
    tags: ["Calcium too"],
    rx: false,
    pack: "bottle-tab",
    colour: "#2a78d6",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/shelcal-500-calcium-vitamin-d3-tablet-for-bones-joints-muscles-care-supports-immunity-daily-mineral-blend-otc899888",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/1779525d42b24909b3bcf9ebeb41916a.jpg",
  },
  {
    id: "mankind-nurokind-od-mecobalamin",
    supplement: "vitamin-b12",
    brand: "Mankind",
    name: "Nurokind-OD mecobalamin",
    strength: "1,500 mcg methylcobalamin",
    price: "₹193 / 20 tablets",
    priceFrom: 193,
    priceInr: 193,
    tags: ["Prescription"],
    rx: true,
    pack: "blister",
    colour: "#e87ba4",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/nurokind-od-tablet-otc188384",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/cropped/jlrbqfgc5sumqeknr8ip.jpg",
  },
  {
    id: "p-g-health-neurobion-forte",
    supplement: "vitamin-b12",
    brand: "P&G Health",
    name: "Neurobion Forte",
    strength: "B12 15 mcg + full B-complex",
    price: "₹47.53 / 30 tablets",
    priceFrom: 47.53,
    priceInr: 48,
    tags: ["Cyanocobalamin"],
    rx: false,
    pack: "blister",
    colour: "#e34948",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/neurobion-forte-tablet-relief-from-tingling-numbness-weakness-otc356742",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/593a0c88615240df932e1ea50b4f3937.jpg",
  },
  {
    id: "pfizer-becosules",
    supplement: "vitamin-b12",
    brand: "Pfizer",
    name: "Becosules",
    strength: "B12 15 mcg + folic acid 1.5 mg + C",
    price: "₹62.37 / 20 capsules",
    priceFrom: 62.37,
    priceInr: 62,
    tags: ["B-complex"],
    rx: false,
    pack: "blister",
    colour: "#eda100",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/becosules-capsule-with-b-complex-vitamin-c-for-mouth-ulcers-otc114687",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/69e588a556b54334af736fc860e1e057.jpg",
  },
  {
    id: "wellbeing-nutrition-melts-b12-folate-oral-strips",
    supplement: "vitamin-b12",
    brand: "Wellbeing Nutrition",
    name: "Melts B12 + folate oral strips",
    strength: "B12 + methylfolate + Brahmi",
    price: "₹649 / 30 strips",
    priceFrom: 649,
    priceInr: 649,
    tags: ["Check label dose"],
    rx: false,
    pack: "strip",
    colour: "#e87ba4",
    retailer: "Wellbeing Nutrition",
    url: "https://wellbeingnutrition.com/products/melts-vitamin-b12-1500mcg-folate-brahmi-curcumin-oral-strips",
    image: "https://wellbeingnutrition.com/cdn/shop/files/IMG1_5c890ae4-aa74-4869-a1f4-09a13fd305ff.jpg?v=1759311653",
  },
  {
    id: "neuherbs-deep-sea-fish-oil-2500-mg-lemon",
    supplement: "omega-3",
    brand: "Neuherbs",
    name: "Deep Sea Fish Oil 2500 mg (Lemon)",
    strength: "892 mg EPA + 594 mg DHA per 2 caps",
    price: "₹749 / 60 softgels",
    priceFrom: 749,
    priceInr: 749,
    tags: ["Highest EPA/DHA found", "Heavy-metal tested"],
    rx: false,
    pack: "bottle-soft",
    colour: "#1baf7a",
    retailer: "Neuherbs",
    url: "https://neuherbs.com/products/deep-sea-fish-oil-capsules-omega-3-2500-mg-lemon",
    image: "https://neuherbs.com/cdn/shop/files/deep_sea_fish_oil_1.png?v=1756897940",
  },
  {
    id: "unived-ovegha-vegan-algal-omega-3",
    supplement: "omega-3",
    brand: "Unived",
    name: "Ovegha vegan algal omega-3",
    strength: "500 mg DHA per 2 caps (no EPA)",
    price: "₹1,350 / 60 capsules",
    priceFrom: 1350,
    priceInr: 1350,
    tags: ["Vegan", "Published CoA"],
    rx: false,
    pack: "bottle-soft",
    colour: "#008300",
    retailer: "Unived",
    url: "https://unived.com/products/ovegha",
    image: "https://unived.com/cdn/shop/files/UNIVED-WELLNESS-OVEGHA-60-VEGAN-OMEGA-3-DHA-60-CAPS_2026_FRONT.jpg?v=1785219191",
  },
  {
    id: "hk-vitals-fish-oil-1000-mg",
    supplement: "omega-3",
    brand: "HK Vitals",
    name: "Fish Oil 1000 mg",
    strength: "180 mg EPA + 120 mg DHA per cap",
    price: "₹359 / 60 capsules",
    priceFrom: 359,
    priceInr: 359,
    tags: ["Low concentration"],
    rx: false,
    pack: "bottle-soft",
    colour: "#2a78d6",
    retailer: "HealthKart",
    url: "https://www.healthkart.com/sv/healthkart-hk-vitals-fish-oil-1000mg-with-180mg-epa-and-120mg-dha/SP-43252",
    image: "https://img4.hkrtcdn.com/44058/prd_4405791-HealthKart-HK-Vitals-Fish-Oil-1000mg-with-180mg-EPA-and-120mg-DHA-60-capsules_o.jpg",
  },
  {
    id: "setu-deep-sea-omega-3-1000-mg",
    supplement: "omega-3",
    brand: "Setu",
    name: "Deep Sea Omega-3 1000 mg",
    strength: "EPA/DHA split not stated on label",
    price: "₹641 / 2 × 60 capsules",
    priceFrom: 641,
    priceInr: 641,
    tags: ["Verify dose"],
    rx: false,
    pack: "bottle-soft",
    colour: "#4a3aa7",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/setu-deep-sea-omega-3-fish-oil-1000mg-capsule-for-brain-heart-joints-60-each-otc897610",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/32678f3a563a4f46a2e149b79f819a3a.jpg",
  },
  {
    id: "nutrabay-pure-creatine-monohydrate-micronised",
    supplement: "creatine",
    brand: "Nutrabay",
    name: "Pure Creatine Monohydrate, micronised",
    strength: "3 g creatine per 3.1 g serving",
    price: "₹379–₹999 (100–400 g)",
    priceFrom: 379,
    tags: ["Trustified tested"],
    rx: false,
    pack: "pouch",
    colour: "#4a3aa7",
    retailer: "Nutrabay",
    url: "https://nutrabay.com/product/nutrabay-micronised-creatine-monohydrate/",
    image: "https://cdn2.nutrabay.com/uploads/product/images/featured_image-NB-NUT-1009-PA-1778572817-800x800.webp",
  },
  {
    id: "nutrabay-creapeak-creapure-alzchem-germany",
    supplement: "creatine",
    brand: "Nutrabay",
    name: "CreaPeak — Creapure (AlzChem, Germany)",
    strength: "3 g per serving, 99.9% pure",
    price: "Stock intermittent",
    tags: ["Creapure"],
    rx: false,
    pack: "pouch",
    colour: "#2a78d6",
    retailer: "Nutrabay",
    url: "https://nutrabay.com/product/nutrabay-creapeak/",
    image: "https://cdn2.nutrabay.com/uploads/product/images/featured_image-NB-NUT-1084-PA-800x800.webp",
  },
  {
    id: "muscleblaze-creatine-monohydrate-creamp",
    supplement: "creatine",
    brand: "MuscleBlaze",
    name: "Creatine Monohydrate CreAMP",
    strength: "3 g per 3.1 g serving, 80 servings",
    price: "₹999 / 250 g",
    priceFrom: 999,
    priceInr: 999,
    tags: ["No 3rd-party cert"],
    rx: false,
    pack: "tub",
    colour: "#e34948",
    retailer: "HealthKart",
    url: "https://www.healthkart.com/sv/muscleblaze-creatine-monohydrate-creamp/SP-8688",
    image: "https://img4.hkrtcdn.com/39960/prd_3995919_o.jpg",
  },
  {
    id: "dabur-sat-isabgol-psyllium-husk-powder",
    supplement: "psyllium",
    brand: "Dabur",
    name: "Sat Isabgol psyllium husk powder",
    strength: "~10 g/day target dose",
    price: "₹320 / 180 g",
    priceFrom: 320,
    priceInr: 320,
    tags: ["Category default"],
    rx: false,
    pack: "jar",
    colour: "#008300",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/dabur-sat-isabgol-psyllium-husk-eases-constipation-powder-otc884517",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/3dcb91f0e59c496aa7eab860cde8de03.jpg",
  },
  {
    id: "muscleblaze-biozyme-performance-whey",
    supplement: "protein",
    brand: "MuscleBlaze",
    name: "Biozyme Performance Whey",
    strength: "25 g protein, 5.51 g BCAA per serving",
    price: "₹7,799 / 2 kg",
    priceFrom: 7799,
    priceInr: 7799,
    tags: ["Informed Choice", "Labdoor", "Trustified Gold"],
    rx: false,
    pack: "tub",
    colour: "#e34948",
    retailer: "HealthKart",
    url: "https://www.healthkart.com/sv/muscleblaze-biozyme-performance-whey/SP-84971",
    image: "https://img2.hkrtcdn.com/cdn-cgi/image/width=500,height=500,dpr=1/41388/prd_4138721-MuscleBlaze-Biozyme-Performance-Whey-4.4-lb-Rich-Chocolate_o.jpg",
  },
  {
    id: "myprotein-india-impact-whey-isolate",
    supplement: "protein",
    brand: "Myprotein India",
    name: "Impact Whey Isolate",
    strength: ">90% protein, 1% fat",
    price: "₹1,999 / 250 g",
    priceFrom: 1999,
    priceInr: 1999,
    tags: ["Informed Choice", "Informed Protein"],
    rx: false,
    pack: "pouch",
    colour: "#2a78d6",
    retailer: "Myprotein India",
    url: "https://www.myprotein.co.in/sports-nutrition/impact-whey-isolate/11654647.html",
    image: "https://static.thcdn.com/productimg/original/11730723-1385214944777127.jpg",
  },
  {
    id: "optimum-nutrition-gold-standard-100-whey",
    supplement: "protein",
    brand: "Optimum Nutrition",
    name: "Gold Standard 100% Whey",
    strength: "24 g protein, 5.5 g BCAA",
    price: "₹2,309 / 1 lb",
    priceFrom: 2309,
    priceInr: 2309,
    tags: ["ISO 22000"],
    rx: false,
    pack: "tub",
    colour: "#eda100",
    retailer: "HealthKart",
    url: "https://www.healthkart.com/sv/on-optimum-nutrition-gold-standard-100-whey-protein/SP-9558",
    image: "https://img6.hkrtcdn.com/41385/prd_4138435-ON-Optimum-Nutrition-Gold-Standard-100-Whey-Protein-1-lb-Double-Rich-Chocolate_c_l.jpg",
  },
  {
    id: "oziva-organic-plant-protein-quinoa",
    supplement: "protein",
    brand: "OZiva",
    name: "Organic Plant Protein + Quinoa",
    strength: "Pea + brown rice + quinoa blend",
    price: "₹1,299 / 500 g",
    priceFrom: 1299,
    priceInr: 1299,
    tags: ["Vegan blend"],
    rx: false,
    pack: "pouch",
    colour: "#008300",
    retailer: "OZiva",
    url: "https://www.oziva.in/products/oziva-organic-plant-protein-for-everyday-fitness-lactose-free-cholesterol-free-soy-free-sugar-free",
    image: "https://cdn.shopify.com/s/files/1/2393/2199/files/Oppu_500g_800X800.jpg",
  },
  {
    id: "nutrabay-gold-tri-blend-whey",
    supplement: "protein",
    brand: "Nutrabay",
    name: "Gold Tri-Blend Whey",
    strength: "25 g protein per 33 g scoop",
    price: "Stock intermittent",
    tags: ["No 3rd-party cert"],
    rx: false,
    pack: "tub",
    colour: "#4a3aa7",
    retailer: "Nutrabay",
    url: "https://nutrabay.com/product/nutrabay-gold-tri-blend-whey-protein/",
    image: "https://cdn.nutrabay.com/wp-content/uploads/2023/11/NB-NUT-1014-06-01-800x800.jpg",
  },
  {
    id: "carbamide-forte-chelated-magnesium-glycinate",
    supplement: "magnesium",
    brand: "Carbamide Forte",
    name: "Chelated Magnesium Glycinate",
    strength: "440 mg elemental Mg per 2 tablets",
    price: "₹415 / 60 tablets",
    priceFrom: 415,
    priceInr: 415,
    tags: ["Glycinate", "GMP"],
    rx: false,
    pack: "bottle-tab",
    colour: "#4a3aa7",
    retailer: "Carbamide Forte",
    url: "https://mycf.in/products/carbamide-forte-chelated-magnesium-glycinate-2408mg-per-serving-supplement-60-veg-tablets",
    image: "https://mycf.in/cdn/shop/files/1_8_1.jpg?v=1782216152",
  },
  {
    id: "boldfit-magnesium-340-mg-tablet",
    supplement: "magnesium",
    brand: "Boldfit",
    name: "Magnesium 340 mg tablet",
    strength: "340 mg elemental — as OXIDE",
    price: "₹338 / 60 tablets",
    priceFrom: 338,
    priceInr: 338,
    tags: ["Oxide — poorly absorbed"],
    rx: false,
    pack: "bottle-tab",
    colour: "#898781",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/boldfit-magnesium-340mg-tablet-otc648895",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/zqbxp12ss68qfba5q4am.jpg",
  },
  {
    id: "hk-vitals-chelated-iron-ferrous-bisglycinate",
    supplement: "iron",
    brand: "HK Vitals",
    name: "Chelated Iron+ (ferrous bisglycinate)",
    strength: "29 mg elemental + folic acid + zinc",
    price: "₹379 / 60 capsules",
    priceFrom: 379,
    priceInr: 379,
    tags: ["Bisglycinate", "Gentler GI"],
    rx: false,
    pack: "bottle-cap",
    colour: "#e34948",
    retailer: "HealthKart",
    url: "https://www.healthkart.com/sv/healthkart-hk-vitals-chelated-iron-plus/SP-74249",
    image: "https://img6.hkrtcdn.com/cdn-cgi/image/width=500,height=500,dpr=1/41804/prd_4180345-HealthKart-HK-Vitals-Chelated-Iron--60-capsules_o.jpg",
  },
  {
    id: "carbamide-forte-chelated-iron-with-vitamin-c",
    supplement: "iron",
    brand: "Carbamide Forte",
    name: "Chelated Iron with Vitamin C",
    strength: "Bisglycinate + carbonyl iron + C + B12",
    price: "₹375 / 60 tablets",
    priceFrom: 375,
    priceInr: 375,
    tags: ["Elemental mg not stated"],
    rx: false,
    pack: "bottle-tab",
    colour: "#eb6834",
    retailer: "Carbamide Forte",
    url: "https://mycf.in/products/carbamide-forte-chelated-iron-tablets-for-women-men-with-vitamin-c-folic-acid-zinc-b12-supplement-60-veg-tablets",
    image: "https://mycf.in/cdn/shop/files/ferronoz_60_hero_image.jpg?v=1775200110",
  },
  {
    id: "p-g-health-livogen-z",
    supplement: "iron",
    brand: "P&G Health",
    name: "Livogen Z",
    strength: "50 mg elemental + folic acid + zinc",
    price: "₹98 / 15 tablets",
    priceFrom: 98,
    priceInr: 98,
    tags: ["Pharma dose"],
    rx: false,
    pack: "blister",
    colour: "#e34948",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/livogen-z-management-of-iron-deficiency-anemia-otc135128",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/c856c6f7515f472fb2fc4076a3d79444.jpg",
  },
  {
    id: "pfizer-autrin-hematinic",
    supplement: "iron",
    brand: "Pfizer",
    name: "Autrin hematinic",
    strength: "98.6 mg elemental + B12 + folic acid",
    price: "₹179 / 30 capsules",
    priceFrom: 179,
    priceInr: 179,
    tags: ["High dose"],
    rx: false,
    pack: "blister",
    colour: "#4a3aa7",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/autrin-capsule-otc63464",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/cropped/mxhzf22n3efxnjzvz9qh.jpg",
  },
  {
    id: "wardex-dexorange-syrup",
    supplement: "iron",
    brand: "Wardex",
    name: "Dexorange syrup",
    strength: "32.8 mg elemental per 15 ml + B12",
    price: "₹198 / 200 ml",
    priceFrom: 198,
    priceInr: 198,
    tags: ["Liquid"],
    rx: false,
    pack: "syrup",
    colour: "#e34948",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/dexorange-hematinic-syrup-with-iron-folic-acid-vitamin-b12-otc135509",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/0f87429517dc400289696733b3b0efec.jpg",
  },
  {
    id: "truebasics-ashwagandha-with-ksm-66",
    supplement: "ashwagandha",
    brand: "TrueBasics",
    name: "Ashwagandha with KSM-66",
    strength: "600 mg KSM-66 per capsule",
    price: "₹929 / 60 capsules",
    priceFrom: 929,
    priceInr: 929,
    tags: ["KSM-66"],
    rx: false,
    pack: "bottle-cap",
    colour: "#eb6834",
    retailer: "HealthKart",
    url: "https://www.healthkart.com/sv/truebasics-ashwagandha-with-600-mg-of-ksm-66/SP-65413",
    image: "https://img6.hkrtcdn.com/32578/prd_3257785-TrueBasics-Ashwagandha-with-600-mg-of-KSM66-60-capsules_c_l.jpg",
  },
  {
    id: "himalaya-ashwagandha-tablet",
    supplement: "ashwagandha",
    brand: "Himalaya",
    name: "Ashwagandha tablet",
    strength: "250 mg extract per tablet",
    price: "₹229 / 60 tablets",
    priceFrom: 229,
    priceInr: 229,
    tags: ["Cycle it"],
    rx: false,
    pack: "bottle-tab",
    colour: "#008300",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/himalaya-wellness-himalaya-ashwagandha-tablet-stress-relief-supplement-rejuvenates-mind-body-otc322760",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/fcbb06a94a934e2d96e4fc4418e8038e.jpg",
  },
  {
    id: "dabur-ashwagandha-churna",
    supplement: "ashwagandha",
    brand: "Dabur",
    name: "Ashwagandha churna",
    strength: "Traditional loose powder",
    price: "₹170 / 100 g",
    priceFrom: 170,
    priceInr: 170,
    tags: ["Unstandardised"],
    rx: false,
    pack: "jar",
    colour: "#eda100",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/dabur-ashwagandha-churna-promotes-vitality-strength-otc347676",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/8eaae5d54b1d49008b37f20fdf8962a6.jpg",
  },
  {
    id: "wellbeing-nutrition-melts-restful-sleep",
    supplement: "melatonin",
    brand: "Wellbeing Nutrition",
    name: "Melts Restful Sleep",
    strength: "Melatonin 10 mg + Suntheanine 30 mg",
    price: "₹599 / 30 strips",
    priceFrom: 599,
    priceInr: 599,
    tags: ["10 mg is above the 4 mg optimum"],
    rx: false,
    pack: "strip",
    colour: "#4a3aa7",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/wellbeing-nutrition-melts-into-a-restful-sleep-melatonin-10mg-oral-thin-strip-calming-chamomile-lavender-otc865862",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/7b4b6680159b4421a3ec758f323d6c2a.jpg",
  },
  {
    id: "carbamide-forte-coenzyme-q10-300-mg-selenium",
    supplement: "coq10",
    brand: "Carbamide Forte",
    name: "Coenzyme Q10 300 mg + Selenium",
    strength: "300 mg CoQ10 + 40 mcg selenium",
    price: "₹849 / 30 capsules",
    priceFrom: 849,
    priceInr: 849,
    tags: ["ISO 22000", "HACCP"],
    rx: false,
    pack: "bottle-soft",
    colour: "#eda100",
    retailer: "Carbamide Forte",
    url: "https://mycf.in/products/carbamide-forte-coenzyme-q10-coq10-300mg-with-selenium-40mcg-supports-heart-health-and-vascular-health-100-vegetarian-30-capsules",
    image: "https://mycf.in/cdn/shop/files/CopyofB0FGCQVX3G.MAIN.jpg?v=1752564955",
  },
  {
    id: "nutrabay-curcumin-piperine",
    supplement: "curcumin",
    brand: "Nutrabay",
    name: "Curcumin + Piperine",
    strength: "95% curcuminoids + piperine",
    price: "₹648 / 60 capsules",
    priceFrom: 648,
    priceInr: 648,
    tags: ["Generic, not C3 Complex"],
    rx: false,
    pack: "bottle-cap",
    colour: "#eda100",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/nutrabay-wellness-curcumin-piperine-capsule-otc629101",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/87f42488a9de46fbb06af56bfbf4a1f7.jpg",
  },
  {
    id: "apex-labs-zincovit",
    supplement: "zinc",
    brand: "Apex Labs",
    name: "Zincovit",
    strength: "Zinc 17 mg + multivitamin",
    price: "₹104 / 15 tablets",
    priceFrom: 104,
    priceInr: 104,
    tags: ["India default"],
    rx: false,
    pack: "blister",
    colour: "#eb6834",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/zincovit-tablet-with-multivitamin-multimineral-grape-seed-extract-otc111998",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/874c73ab2b3747f68d49263ab2c475ca.jpg",
  },
  {
    id: "abbott-limcee-vitamin-c-chewable",
    supplement: "vitamin-c",
    brand: "Abbott",
    name: "Limcee vitamin C chewable",
    strength: "500 mg",
    price: "₹23.90 / 15 tablets",
    priceFrom: 23.9,
    priceInr: 24,
    tags: ["Above saturation"],
    rx: false,
    pack: "blister",
    colour: "#eda100",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/limcee-vitamin-c-chewable-tablet-flavour-orange-otc173959",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/pharmacy-production-rxs%2F1738667483_crop_38.png",
  },
  {
    id: "amway-nutrilite-daily-multivitamin",
    supplement: "multivitamin",
    brand: "Amway",
    name: "Nutrilite Daily multivitamin",
    strength: "13 vitamins + 11 minerals",
    price: "₹1,289 / 60 tablets",
    priceFrom: 1289,
    priceInr: 1289,
    tags: ["Premium end"],
    rx: false,
    pack: "bottle-tab",
    colour: "#008300",
    retailer: "Amway",
    url: "https://www.amway.in/nutrilite-daily/p/313505ID",
    image: "https://media.amway.in/sys-master/images/h48/h13/9201501798430/EIA.w800.h800.313505ID_Daily-601.png",
  },
  {
    id: "hk-vitals-multivitamin-with-zinc-c",
    supplement: "multivitamin",
    brand: "HK Vitals",
    name: "Multivitamin with Zinc & C",
    strength: "Zinc 5.49 mg + taurine + ginseng",
    price: "₹399 / 60 tablets",
    priceFrom: 399,
    priceInr: 399,
    tags: ["Insurance, not medicine"],
    rx: false,
    pack: "bottle-tab",
    colour: "#2a78d6",
    retailer: "HealthKart",
    url: "https://www.healthkart.com/sv/healthkart-hk-vitals-multivitamin-with-multimineral/SP-39873",
    image: "https://img8.hkrtcdn.com/40247/prd_4024697-HealthKart-HK-Vitals-Multivitamin-with-Zinc-Vitamin-C-60-tablets-Unflavoured_c_l.jpg",
  },
  {
    id: "sun-pharma-revital-h",
    supplement: "multivitamin",
    brand: "Sun Pharma",
    name: "Revital H",
    strength: "Ginseng 212.5 mg + 10 vitamins",
    price: "₹315 / 30 capsules",
    priceFrom: 315,
    priceInr: 315,
    tags: ["Energy claims unsupported"],
    rx: false,
    pack: "bottle-soft",
    colour: "#e34948",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/revital-h-men-multivitamin-with-calcium-zinc-ginseng-for-immunity-strong-bones-energy-otc66303",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/7c0c52f301584f3697ad1d3095cd5e21.jpg",
  },
  {
    id: "wellbeing-nutrition-marine-collagen-type-i-iii",
    supplement: "collagen",
    brand: "Wellbeing Nutrition",
    name: "Marine Collagen Type I & III",
    strength: "8 g peptides per serving",
    price: "₹1,619 / 200 g",
    priceFrom: 1619,
    priceInr: 1619,
    tags: ["Weak evidence"],
    rx: false,
    pack: "jar",
    colour: "#e87ba4",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/wellbeing-nutrition-marine-collagen-type-i-iii-8000mg-for-skin-hair-nails-bones-joints-unflavoured-otc679753",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/12c4498dd39445e28c47e186aab1b7c3.jpg",
  },
  {
    id: "hk-vitals-zinc-complex",
    supplement: "zinc",
    brand: "HK Vitals",
    name: "Zinc Complex",
    strength: "Zinc form and elemental mg not stated",
    price: "₹399 / 60 tablets",
    priceFrom: 399,
    priceInr: 399,
    tags: ["Label unclear"],
    rx: false,
    pack: "bottle-tab",
    colour: "#898781",
    retailer: "HealthKart",
    url: "https://www.healthkart.com/sv/healthkart-hk-vitals-zinc-complex/SP-88771",
    image: "https://img4.hkrtcdn.com/39197/prd_3919673-HealthKart-HK-Vitals-Zinc-Complex-60-tablets_c_l.jpg",
  },
];

/**
 * CAN THIS CITY SELL IT?
 *
 * Two ways to be un-sellable and they are not the same absence, which is why
 * a screen must be able to tell them apart:
 *
 *   NO TILL PRICE — the review recorded a range or no stock, so there is no
 *   single number to charge. Three products. Nothing to do but say so.
 *
 *   PRESCRIPTION ONLY — there IS a price and the product is real, and a shop
 *   that put it in a basket beside a tub of whey would be selling a licensed
 *   drug on a fitness page. Two products. They keep their card, their evidence
 *   and their price, and their button goes to the prescriptions hub instead of
 *   to a checkout.
 *
 * Stated as a function rather than as a `sellable: true` column because a flag
 * in the data can be edited by whoever adds the next row, and this cannot.
 */
export const sellable = (p: Product): boolean => typeof p.priceInr === 'number' && !p.rx;

/** Every product for one supplement, cheapest-known first, prescription last.
 *  A product with no readable price sorts to the end rather than to zero. */
export function productsFor(supplement: string): Product[] {
  return PRODUCTS.filter((p) => p.supplement === supplement).sort(
    (a, b) =>
      Number(a.rx) - Number(b.rx) ||
      (a.priceFrom ?? Number.MAX_SAFE_INTEGER) - (b.priceFrom ?? Number.MAX_SAFE_INTEGER),
  );
}

/** The supplement ids the shelf can actually sell something for. Three entries
 *  in the knowledge base — folate, L-theanine and standalone K2 — have no
 *  product row, and the store says "nothing verified in India" rather than
 *  inventing one. */
export const STOCKED: string[] = SUPPLEMENTS.map((s) => s.id).filter((id) =>
  PRODUCTS.some((p) => p.supplement === id),
);

/** The review's shelves, in the order a person shops them rather than the
 *  order the evidence was written in. */
export const AISLES: Array<{ id: string; title: string; blurb: string; supplements: string[] }> = [
  { id: 'india', title: 'The Indian shortlist', blurb: 'The four the base rates in this country actually argue for.',
    supplements: ['vitamin-d3', 'vitamin-b12', 'omega-3', 'psyllium'] },
  { id: 'training', title: 'Training and protein', blurb: 'The two with the most replicated evidence in sport.',
    supplements: ['creatine', 'protein'] },
  { id: 'heart', title: 'Heart and cholesterol', blurb: 'Psyllium is the best evidence-to-cost ratio on the whole list.',
    supplements: ['psyllium', 'omega-3', 'magnesium', 'coq10'] },
  { id: 'sleep', title: 'Sleep and stress', blurb: 'Small, real effects — and one product dosed above its own optimum.',
    supplements: ['melatonin', 'magnesium', 'ashwagandha'] },
  { id: 'clinical', title: 'Test before you buy', blurb: 'A blood test belongs before the first dose of these, not after.',
    supplements: ['iron', 'vitamin-d3', 'vitamin-b12'] },
  { id: 'popular', title: 'Popular, and worth reading first', blurb: 'India buys these in volume. The evidence review does not.',
    supplements: ['multivitamin', 'collagen', 'curcumin', 'vitamin-c', 'zinc'] },
];
