import { SUPPLEMENTS } from './knowledge';

/**
 * THE SHELF — 103 PRODUCTS ACTUALLY SOLD IN INDIA.
 *
 * Every row below was read off the same evidence review the knowledge base
 * came from ("Supplements, Honestly", August 2026), out of its "Available in
 * India" tables: a brand, the strength printed on the label, the price at the
 * retailer on the day the review was compiled, and the link to buy it.
 *
 * THE ONE INVARIANT. `supplement` on every row is an id that exists in
 * `knowledge.ts`, and the spec asserts it. A product this city can show but
 * cannot say the evidence for is a product this city has no business showing —
 * the shelf and the plan resolve to the same file or the shelf is just a
 * catalogue with a health page bolted on. That rule cost one real product: the
 * review lists a Carbamide Forte probiotic, and probiotics have no entry in
 * the knowledge base (the review covers them only in its "named strains for
 * named problems" note), so it is not here.
 *
 * TOGETHER CITY DOES NOT TAKE THE MONEY. `url` goes to the retailer's own
 * page — Tata 1mg, HealthKart, Nutrabay, the brand's own store — and that is
 * the whole checkout. There is no cart on this side, no margin, no affiliate
 * parameter appended to any link in this file. The plan page's argument was
 * that the moment a refusal costs revenue the refusals get quieter, and the
 * cheapest way to keep that true is to never be in the transaction. It is
 * also why 12 of these rows sit under supplements the engine REFUSES: the
 * shelf shows them with the refusal attached rather than hiding them, because
 * somebody who is going to buy a multivitamin anyway should meet the 78-trial
 * null before the checkout page and not after it.
 *
 * PRICES GO STALE. `price` is a string with its unit attached ("₹649 / 30
 * strips") and never a number pretending to be current — `priceFrom` exists
 * only to sort the grid. The screen says when the review was compiled.
 *
 * `pack` and `colour` are the review's own drawn renderings of the dosage
 * format — a strip, a blister, a tub — so the grid can draw every product
 * itself and owe nothing to a retailer's CDN. `image` is the photo where the
 * retailer publishes one; a screen may use it, and must survive it failing.
 *
 * ── 23 AUGUST 2026. SIXTY MORE ROWS, FROM THE OPEN-MARKET SURVEY. ──────────
 *
 * The first 43 came out of the evidence review's own "Available in India"
 * tables. These 60 come out of a second, wider pass ("The Verified Shelf",
 * 131 products priced at their sellers on 22 August 2026) — brands the review
 * never reached: Nakpro, Avvatar, AS-IT-IS, Isopure, Cellucor, Plix, Fast&Up,
 * Neuherbs, Zeroharm, Swisse, Centrum and the rest.
 *
 * THE INVARIANT HELD, AND IT COST 45 PRODUCTS. The survey carries whole
 * categories this city has no evidence row for — every pre-workout, every
 * probiotic, every BCAA/EAA, shilajit, biotin, joint blends, digestive
 * enzymes, vitamin E, evening primrose. Each is a real product that really
 * sells in India, and each is one this city could show and could not cite,
 * so none of them is here. Adding a `knowledge.ts` row is how they get onto
 * the shelf. Adding a `products.ts` row is not.
 *
 * TWELVE MORE WERE DROPPED FOR PRICE. The survey recorded no single
 * unambiguous ₹ figure for them — out of stock at every seller, or a spread
 * across flavours. The three long-standing no-price rows keep their card and
 * their sentence; these twelve simply never arrive.
 *
 * FOURTEEN WERE ALREADY HERE, under another retailer's wording — matched on
 * the product page, not the name, so "Melts Plant-Based D3 + K2 oral strips"
 * and "Melts Plant-Based Vitamin D3 + K2 Oral Strips" did not become two
 * bottles of the same thing.
 *
 * `image` on every new row is the photograph on the seller's OWN page as the
 * survey found it — the brand's store where there is one, the retailer's CDN
 * otherwise. Nothing is hosted here, and the drawn `pack` still stands behind
 * every one of them, because a hotlink is a thing that goes away.
 *
 * `tags` carry the survey's judgement forward rather than laundering it: the
 * price band it put the product in, "Partly verified" where it could not
 * confirm every field, and its data flags in its own words — "Composition
 * unverified", "Inflated MRP", "Out of stock at review". A shelf that prints
 * only the flattering fields is an advert.
 */

export type PackShape =
  | 'strip' | 'blister' | 'sachet' | 'syrup' | 'jar' | 'pouch' | 'tub'
  | 'bottle-tab' | 'bottle-cap' | 'bottle-soft';

export interface Product {
  id: string;
  /** An id in SUPPLEMENTS. Enforced by the spec, not by convention. */
  supplement: string;
  brand: string;
  name: string;
  /** What the label says is in it, in the review's words. */
  strength?: string;
  /** With its unit attached, as read on the day of the review. */
  price?: string;
  /** For sorting only. Never shown as a price. */
  priceFrom?: number;
  /**
   * THE TILL PRICE, IN WHOLE RUPEES, and the only number the wallet is ever
   * charged. Present ONLY where the review recorded one unambiguous price for
   * one pack: a range ("₹379–₹999 for 100–400 g") is three products wearing
   * one row, and "Stock intermittent" is not a price at all. Three of the 103
   * have no `priceInr` and cannot be bought here — the card says so rather
   * than guessing at the middle of a range and charging it.
   *
   * The city's till is in whole rupees, as every other hub's is. Two of these
   * were recorded in paise (₹34.60, ₹23.90) and round to the nearest rupee;
   * the card prints both the till price and the recorded label, so the
   * rounding is visible rather than quiet.
   */
  priceInr?: number;
  /** The review's own notes on the product — certification, or a warning. */
  tags: string[];
  /** Prescription-only in India. */
  rx: boolean;
  pack: PackShape;
  colour: string;
  retailer: string;
  url: string;
  image?: string;
}

export const PRODUCTS: Product[] = [
  {
    id: "wellbeing-nutrition-melts-plant-based-d3-k2-oral-strips",
    supplement: "vitamin-d3",
    brand: "Wellbeing Nutrition",
    name: "Melts Plant-Based D3 + K2 oral strips",
    strength: "600 IU D3 (lichen) + MK-7",
    price: "₹649 / 30 strips",
    priceFrom: 649,
    priceInr: 649,
    tags: ["Vegan", "Vitashine"],
    rx: false,
    pack: "strip",
    colour: "#eda100",
    retailer: "Wellbeing Nutrition",
    url: "https://wellbeingnutrition.com/products/melts-plant-based-d3k2-oral-strips",
    image: "https://wellbeingnutrition.com/cdn/shop/files/IMG1_a5772f05-a142-4bb2-a56d-57a7a53f4ed4.webp",
  },
  {
    id: "carbamide-forte-vitamin-d3-k2-mk-7-lichen-source",
    supplement: "vitamin-d3",
    brand: "Carbamide Forte",
    name: "Vitamin D3 + K2 MK-7, lichen source",
    strength: "Labelled 100% RDA",
    price: "₹449 / 120 tablets",
    priceFrom: 449,
    priceInr: 449,
    tags: ["Vegetarian"],
    rx: false,
    pack: "bottle-tab",
    colour: "#eda100",
    retailer: "Carbamide Forte",
    url: "https://mycf.in/products/vitamin-d3-k2-mk7-plant-based-veg-vitamin-d-supplements-lichen-source-with-vitamin-k2-mk7-menaquinone-120-veg-tablets",
    image: "https://mycf.in/cdn/shop/files/1_7_c48e4ac8-7f9c-4b32-b9cd-6eab503772bb.jpg?v=1782214947",
  },
  {
    id: "cadila-calcirol-60k-sachet",
    supplement: "vitamin-d3",
    brand: "Cadila",
    name: "Calcirol 60K sachet",
    strength: "60,000 IU per 1 g sachet",
    price: "₹34.60 / sachet",
    priceFrom: 34.6,
    priceInr: 35,
    tags: ["Repletion only"],
    rx: false,
    pack: "sachet",
    colour: "#eb6834",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/calcirol-60k-iu-cholecalciferol-sachet-for-bone-health-otc111246",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/90c75e6999a84b09aafbb3b72bf18306.jpg",
  },
  {
    id: "alkem-uprise-d3-60k-capsule",
    supplement: "vitamin-d3",
    brand: "Alkem",
    name: "Uprise-D3 60K capsule",
    strength: "60,000 IU",
    price: "₹362 / 12 capsules",
    priceFrom: 362,
    priceInr: 362,
    tags: ["Prescription"],
    rx: true,
    pack: "blister",
    colour: "#eb6834",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/drugs/uprise-d3-60k-capsule-918999",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/213c2782b4a849b4b6796140a7109a7e.jpg",
  },
  {
    id: "arachitol-nano-60k-oral-solution",
    supplement: "vitamin-d3",
    brand: "Arachitol",
    name: "Nano 60K oral solution",
    strength: "60,000 IU per 5 ml",
    price: "₹466 / 4 × 5 ml",
    priceFrom: 466,
    priceInr: 466,
    tags: ["Repletion only"],
    rx: false,
    pack: "syrup",
    colour: "#eda100",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/arachitol-nano-bottle-60k-iu-vitamin-d3-oral-solution-5ml-each-bone-joint-and-muscle-care-otc323191",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/a0ecb279e17c4693ab01a15ac9258939.jpg",
  },
  {
    id: "torrent-shelcal-500",
    supplement: "vitamin-d3",
    brand: "Torrent",
    name: "Shelcal 500",
    strength: "500 mg elemental Ca + 250 IU D3",
    price: "₹356 / 40 tablets",
    priceFrom: 356,
    priceInr: 356,
    tags: ["Calcium too"],
    rx: false,
    pack: "bottle-tab",
    colour: "#2a78d6",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/shelcal-500-calcium-vitamin-d3-tablet-for-bones-joints-muscles-care-supports-immunity-daily-mineral-blend-otc899888",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/1779525d42b24909b3bcf9ebeb41916a.jpg",
  },
  {
    id: "mankind-nurokind-od-mecobalamin",
    supplement: "vitamin-b12",
    brand: "Mankind",
    name: "Nurokind-OD mecobalamin",
    strength: "1,500 mcg methylcobalamin",
    price: "₹193 / 20 tablets",
    priceFrom: 193,
    priceInr: 193,
    tags: ["Prescription"],
    rx: true,
    pack: "blister",
    colour: "#e87ba4",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/nurokind-od-tablet-otc188384",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/cropped/jlrbqfgc5sumqeknr8ip.jpg",
  },
  {
    id: "p-g-health-neurobion-forte",
    supplement: "vitamin-b12",
    brand: "P&G Health",
    name: "Neurobion Forte",
    strength: "B12 15 mcg + full B-complex",
    price: "₹47.53 / 30 tablets",
    priceFrom: 47.53,
    priceInr: 48,
    tags: ["Cyanocobalamin"],
    rx: false,
    pack: "blister",
    colour: "#e34948",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/neurobion-forte-tablet-relief-from-tingling-numbness-weakness-otc356742",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/593a0c88615240df932e1ea50b4f3937.jpg",
  },
  {
    id: "pfizer-becosules",
    supplement: "vitamin-b12",
    brand: "Pfizer",
    name: "Becosules",
    strength: "B12 15 mcg + folic acid 1.5 mg + C",
    price: "₹62.37 / 20 capsules",
    priceFrom: 62.37,
    priceInr: 62,
    tags: ["B-complex"],
    rx: false,
    pack: "blister",
    colour: "#eda100",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/becosules-capsule-with-b-complex-vitamin-c-for-mouth-ulcers-otc114687",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/69e588a556b54334af736fc860e1e057.jpg",
  },
  {
    id: "wellbeing-nutrition-melts-b12-folate-oral-strips",
    supplement: "vitamin-b12",
    brand: "Wellbeing Nutrition",
    name: "Melts B12 + folate oral strips",
    strength: "B12 + methylfolate + Brahmi",
    price: "₹649 / 30 strips",
    priceFrom: 649,
    priceInr: 649,
    tags: ["Check label dose"],
    rx: false,
    pack: "strip",
    colour: "#e87ba4",
    retailer: "Wellbeing Nutrition",
    url: "https://wellbeingnutrition.com/products/melts-vitamin-b12-1500mcg-folate-brahmi-curcumin-oral-strips",
    image: "https://wellbeingnutrition.com/cdn/shop/files/IMG1_5c890ae4-aa74-4869-a1f4-09a13fd305ff.jpg?v=1759311653",
  },
  {
    id: "neuherbs-deep-sea-fish-oil-2500-mg-lemon",
    supplement: "omega-3",
    brand: "Neuherbs",
    name: "Deep Sea Fish Oil 2500 mg (Lemon)",
    strength: "892 mg EPA + 594 mg DHA per 2 caps",
    price: "₹749 / 60 softgels",
    priceFrom: 749,
    priceInr: 749,
    tags: ["Highest EPA/DHA found", "Heavy-metal tested"],
    rx: false,
    pack: "bottle-soft",
    colour: "#1baf7a",
    retailer: "Neuherbs",
    url: "https://neuherbs.com/products/deep-sea-fish-oil-capsules-omega-3-2500-mg-lemon",
    image: "https://neuherbs.com/cdn/shop/files/deep_sea_fish_oil_1.png?v=1756897940",
  },
  {
    id: "unived-ovegha-vegan-algal-omega-3",
    supplement: "omega-3",
    brand: "Unived",
    name: "Ovegha vegan algal omega-3",
    strength: "500 mg DHA per 2 caps (no EPA)",
    price: "₹1,350 / 60 capsules",
    priceFrom: 1350,
    priceInr: 1350,
    tags: ["Vegan", "Published CoA"],
    rx: false,
    pack: "bottle-soft",
    colour: "#008300",
    retailer: "Unived",
    url: "https://unived.com/products/ovegha",
    image: "https://unived.com/cdn/shop/files/UNIVED-WELLNESS-OVEGHA-60-VEGAN-OMEGA-3-DHA-60-CAPS_2026_FRONT.jpg?v=1785219191",
  },
  {
    id: "hk-vitals-fish-oil-1000-mg",
    supplement: "omega-3",
    brand: "HK Vitals",
    name: "Fish Oil 1000 mg",
    strength: "180 mg EPA + 120 mg DHA per cap",
    price: "₹359 / 60 capsules",
    priceFrom: 359,
    priceInr: 359,
    tags: ["Low concentration"],
    rx: false,
    pack: "bottle-soft",
    colour: "#2a78d6",
    retailer: "HealthKart",
    url: "https://www.healthkart.com/sv/healthkart-hk-vitals-fish-oil-1000mg-with-180mg-epa-and-120mg-dha/SP-43252",
    image: "https://img4.hkrtcdn.com/44058/prd_4405791-HealthKart-HK-Vitals-Fish-Oil-1000mg-with-180mg-EPA-and-120mg-DHA-60-capsules_o.jpg",
  },
  {
    id: "setu-deep-sea-omega-3-1000-mg",
    supplement: "omega-3",
    brand: "Setu",
    name: "Deep Sea Omega-3 1000 mg",
    strength: "EPA/DHA split not stated on label",
    price: "₹641 / 2 × 60 capsules",
    priceFrom: 641,
    priceInr: 641,
    tags: ["Verify dose"],
    rx: false,
    pack: "bottle-soft",
    colour: "#4a3aa7",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/setu-deep-sea-omega-3-fish-oil-1000mg-capsule-for-brain-heart-joints-60-each-otc897610",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/32678f3a563a4f46a2e149b79f819a3a.jpg",
  },
  {
    id: "nutrabay-pure-creatine-monohydrate-micronised",
    supplement: "creatine",
    brand: "Nutrabay",
    name: "Pure Creatine Monohydrate, micronised",
    strength: "3 g creatine per 3.1 g serving",
    price: "₹379–₹999 (100–400 g)",
    priceFrom: 379,
    tags: ["Trustified tested"],
    rx: false,
    pack: "pouch",
    colour: "#4a3aa7",
    retailer: "Nutrabay",
    url: "https://nutrabay.com/product/nutrabay-micronised-creatine-monohydrate/",
    image: "https://cdn2.nutrabay.com/uploads/product/images/featured_image-NB-NUT-1009-PA-1778572817-800x800.webp",
  },
  {
    id: "nutrabay-creapeak-creapure-alzchem-germany",
    supplement: "creatine",
    brand: "Nutrabay",
    name: "CreaPeak — Creapure (AlzChem, Germany)",
    strength: "3 g per serving, 99.9% pure",
    price: "Stock intermittent",
    tags: ["Creapure"],
    rx: false,
    pack: "pouch",
    colour: "#2a78d6",
    retailer: "Nutrabay",
    url: "https://nutrabay.com/product/nutrabay-creapeak/",
    image: "https://cdn2.nutrabay.com/uploads/product/images/featured_image-NB-NUT-1084-PA-800x800.webp",
  },
  {
    id: "muscleblaze-creatine-monohydrate-creamp",
    supplement: "creatine",
    brand: "MuscleBlaze",
    name: "Creatine Monohydrate CreAMP",
    strength: "3 g per 3.1 g serving, 80 servings",
    price: "₹999 / 250 g",
    priceFrom: 999,
    priceInr: 999,
    tags: ["No 3rd-party cert"],
    rx: false,
    pack: "tub",
    colour: "#e34948",
    retailer: "HealthKart",
    url: "https://www.healthkart.com/sv/muscleblaze-creatine-monohydrate-creamp/SP-8688",
    image: "https://img4.hkrtcdn.com/39960/prd_3995919_o.jpg",
  },
  {
    id: "dabur-sat-isabgol-psyllium-husk-powder",
    supplement: "psyllium",
    brand: "Dabur",
    name: "Sat Isabgol psyllium husk powder",
    strength: "~10 g/day target dose",
    price: "₹320 / 180 g",
    priceFrom: 320,
    priceInr: 320,
    tags: ["Category default"],
    rx: false,
    pack: "jar",
    colour: "#008300",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/dabur-sat-isabgol-psyllium-husk-eases-constipation-powder-otc884517",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/3dcb91f0e59c496aa7eab860cde8de03.jpg",
  },
  {
    id: "muscleblaze-biozyme-performance-whey",
    supplement: "protein",
    brand: "MuscleBlaze",
    name: "Biozyme Performance Whey",
    strength: "25 g protein, 5.51 g BCAA per serving",
    price: "₹7,799 / 2 kg",
    priceFrom: 7799,
    priceInr: 7799,
    tags: ["Informed Choice", "Labdoor", "Trustified Gold"],
    rx: false,
    pack: "tub",
    colour: "#e34948",
    retailer: "HealthKart",
    url: "https://www.healthkart.com/sv/muscleblaze-biozyme-performance-whey/SP-84971",
    image: "https://img2.hkrtcdn.com/cdn-cgi/image/width=500,height=500,dpr=1/41388/prd_4138721-MuscleBlaze-Biozyme-Performance-Whey-4.4-lb-Rich-Chocolate_o.jpg",
  },
  {
    id: "myprotein-india-impact-whey-isolate",
    supplement: "protein",
    brand: "Myprotein India",
    name: "Impact Whey Isolate",
    strength: ">90% protein, 1% fat",
    price: "₹1,999 / 250 g",
    priceFrom: 1999,
    priceInr: 1999,
    tags: ["Informed Choice", "Informed Protein"],
    rx: false,
    pack: "pouch",
    colour: "#2a78d6",
    retailer: "Myprotein India",
    url: "https://www.myprotein.co.in/sports-nutrition/impact-whey-isolate/11654647.html",
    image: "https://static.thcdn.com/productimg/original/11730723-1385214944777127.jpg",
  },
  {
    id: "optimum-nutrition-gold-standard-100-whey",
    supplement: "protein",
    brand: "Optimum Nutrition",
    name: "Gold Standard 100% Whey",
    strength: "24 g protein, 5.5 g BCAA",
    price: "₹2,309 / 1 lb",
    priceFrom: 2309,
    priceInr: 2309,
    tags: ["ISO 22000"],
    rx: false,
    pack: "tub",
    colour: "#eda100",
    retailer: "HealthKart",
    url: "https://www.healthkart.com/sv/on-optimum-nutrition-gold-standard-100-whey-protein/SP-9558",
    image: "https://img6.hkrtcdn.com/41385/prd_4138435-ON-Optimum-Nutrition-Gold-Standard-100-Whey-Protein-1-lb-Double-Rich-Chocolate_c_l.jpg",
  },
  {
    id: "oziva-organic-plant-protein-quinoa",
    supplement: "protein",
    brand: "OZiva",
    name: "Organic Plant Protein + Quinoa",
    strength: "Pea + brown rice + quinoa blend",
    price: "₹1,299 / 500 g",
    priceFrom: 1299,
    priceInr: 1299,
    tags: ["Vegan blend"],
    rx: false,
    pack: "pouch",
    colour: "#008300",
    retailer: "OZiva",
    url: "https://www.oziva.in/products/oziva-organic-plant-protein-for-everyday-fitness-lactose-free-cholesterol-free-soy-free-sugar-free",
    image: "https://cdn.shopify.com/s/files/1/2393/2199/files/Oppu_500g_800X800.jpg",
  },
  {
    id: "nutrabay-gold-tri-blend-whey",
    supplement: "protein",
    brand: "Nutrabay",
    name: "Gold Tri-Blend Whey",
    strength: "25 g protein per 33 g scoop",
    price: "Stock intermittent",
    tags: ["No 3rd-party cert"],
    rx: false,
    pack: "tub",
    colour: "#4a3aa7",
    retailer: "Nutrabay",
    url: "https://nutrabay.com/product/nutrabay-gold-tri-blend-whey-protein/",
    image: "https://cdn.nutrabay.com/wp-content/uploads/2023/11/NB-NUT-1014-06-01-800x800.jpg",
  },
  {
    id: "carbamide-forte-chelated-magnesium-glycinate",
    supplement: "magnesium",
    brand: "Carbamide Forte",
    name: "Chelated Magnesium Glycinate",
    strength: "440 mg elemental Mg per 2 tablets",
    price: "₹415 / 60 tablets",
    priceFrom: 415,
    priceInr: 415,
    tags: ["Glycinate", "GMP"],
    rx: false,
    pack: "bottle-tab",
    colour: "#4a3aa7",
    retailer: "Carbamide Forte",
    url: "https://mycf.in/products/carbamide-forte-chelated-magnesium-glycinate-2408mg-per-serving-supplement-60-veg-tablets",
    image: "https://mycf.in/cdn/shop/files/1_8_1.jpg?v=1782216152",
  },
  {
    id: "boldfit-magnesium-340-mg-tablet",
    supplement: "magnesium",
    brand: "Boldfit",
    name: "Magnesium 340 mg tablet",
    strength: "340 mg elemental — as OXIDE",
    price: "₹338 / 60 tablets",
    priceFrom: 338,
    priceInr: 338,
    tags: ["Oxide — poorly absorbed"],
    rx: false,
    pack: "bottle-tab",
    colour: "#898781",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/boldfit-magnesium-340mg-tablet-otc648895",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/zqbxp12ss68qfba5q4am.jpg",
  },
  {
    id: "hk-vitals-chelated-iron-ferrous-bisglycinate",
    supplement: "iron",
    brand: "HK Vitals",
    name: "Chelated Iron+ (ferrous bisglycinate)",
    strength: "29 mg elemental + folic acid + zinc",
    price: "₹379 / 60 capsules",
    priceFrom: 379,
    priceInr: 379,
    tags: ["Bisglycinate", "Gentler GI"],
    rx: false,
    pack: "bottle-cap",
    colour: "#e34948",
    retailer: "HealthKart",
    url: "https://www.healthkart.com/sv/healthkart-hk-vitals-chelated-iron-plus/SP-74249",
    image: "https://img6.hkrtcdn.com/cdn-cgi/image/width=500,height=500,dpr=1/41804/prd_4180345-HealthKart-HK-Vitals-Chelated-Iron--60-capsules_o.jpg",
  },
  {
    id: "carbamide-forte-chelated-iron-with-vitamin-c",
    supplement: "iron",
    brand: "Carbamide Forte",
    name: "Chelated Iron with Vitamin C",
    strength: "Bisglycinate + carbonyl iron + C + B12",
    price: "₹375 / 60 tablets",
    priceFrom: 375,
    priceInr: 375,
    tags: ["Elemental mg not stated"],
    rx: false,
    pack: "bottle-tab",
    colour: "#eb6834",
    retailer: "Carbamide Forte",
    url: "https://mycf.in/products/carbamide-forte-chelated-iron-tablets-for-women-men-with-vitamin-c-folic-acid-zinc-b12-supplement-60-veg-tablets",
    image: "https://mycf.in/cdn/shop/files/ferronoz_60_hero_image.jpg?v=1775200110",
  },
  {
    id: "p-g-health-livogen-z",
    supplement: "iron",
    brand: "P&G Health",
    name: "Livogen Z",
    strength: "50 mg elemental + folic acid + zinc",
    price: "₹98 / 15 tablets",
    priceFrom: 98,
    priceInr: 98,
    tags: ["Pharma dose"],
    rx: false,
    pack: "blister",
    colour: "#e34948",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/livogen-z-management-of-iron-deficiency-anemia-otc135128",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/c856c6f7515f472fb2fc4076a3d79444.jpg",
  },
  {
    id: "pfizer-autrin-hematinic",
    supplement: "iron",
    brand: "Pfizer",
    name: "Autrin hematinic",
    strength: "98.6 mg elemental + B12 + folic acid",
    price: "₹179 / 30 capsules",
    priceFrom: 179,
    priceInr: 179,
    tags: ["High dose"],
    rx: false,
    pack: "blister",
    colour: "#4a3aa7",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/autrin-capsule-otc63464",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/cropped/mxhzf22n3efxnjzvz9qh.jpg",
  },
  {
    id: "wardex-dexorange-syrup",
    supplement: "iron",
    brand: "Wardex",
    name: "Dexorange syrup",
    strength: "32.8 mg elemental per 15 ml + B12",
    price: "₹198 / 200 ml",
    priceFrom: 198,
    priceInr: 198,
    tags: ["Liquid"],
    rx: false,
    pack: "syrup",
    colour: "#e34948",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/dexorange-hematinic-syrup-with-iron-folic-acid-vitamin-b12-otc135509",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/0f87429517dc400289696733b3b0efec.jpg",
  },
  {
    id: "truebasics-ashwagandha-with-ksm-66",
    supplement: "ashwagandha",
    brand: "TrueBasics",
    name: "Ashwagandha with KSM-66",
    strength: "600 mg KSM-66 per capsule",
    price: "₹929 / 60 capsules",
    priceFrom: 929,
    priceInr: 929,
    tags: ["KSM-66"],
    rx: false,
    pack: "bottle-cap",
    colour: "#eb6834",
    retailer: "HealthKart",
    url: "https://www.healthkart.com/sv/truebasics-ashwagandha-with-600-mg-of-ksm-66/SP-65413",
    image: "https://img6.hkrtcdn.com/32578/prd_3257785-TrueBasics-Ashwagandha-with-600-mg-of-KSM66-60-capsules_c_l.jpg",
  },
  {
    id: "himalaya-ashwagandha-tablet",
    supplement: "ashwagandha",
    brand: "Himalaya",
    name: "Ashwagandha tablet",
    strength: "250 mg extract per tablet",
    price: "₹229 / 60 tablets",
    priceFrom: 229,
    priceInr: 229,
    tags: ["Cycle it"],
    rx: false,
    pack: "bottle-tab",
    colour: "#008300",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/himalaya-wellness-himalaya-ashwagandha-tablet-stress-relief-supplement-rejuvenates-mind-body-otc322760",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/fcbb06a94a934e2d96e4fc4418e8038e.jpg",
  },
  {
    id: "dabur-ashwagandha-churna",
    supplement: "ashwagandha",
    brand: "Dabur",
    name: "Ashwagandha churna",
    strength: "Traditional loose powder",
    price: "₹170 / 100 g",
    priceFrom: 170,
    priceInr: 170,
    tags: ["Unstandardised"],
    rx: false,
    pack: "jar",
    colour: "#eda100",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/dabur-ashwagandha-churna-promotes-vitality-strength-otc347676",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/8eaae5d54b1d49008b37f20fdf8962a6.jpg",
  },
  {
    id: "wellbeing-nutrition-melts-restful-sleep",
    supplement: "melatonin",
    brand: "Wellbeing Nutrition",
    name: "Melts Restful Sleep",
    strength: "Melatonin 10 mg + Suntheanine 30 mg",
    price: "₹599 / 30 strips",
    priceFrom: 599,
    priceInr: 599,
    tags: ["10 mg is above the 4 mg optimum"],
    rx: false,
    pack: "strip",
    colour: "#4a3aa7",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/wellbeing-nutrition-melts-into-a-restful-sleep-melatonin-10mg-oral-thin-strip-calming-chamomile-lavender-otc865862",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/7b4b6680159b4421a3ec758f323d6c2a.jpg",
  },
  {
    id: "carbamide-forte-coenzyme-q10-300-mg-selenium",
    supplement: "coq10",
    brand: "Carbamide Forte",
    name: "Coenzyme Q10 300 mg + Selenium",
    strength: "300 mg CoQ10 + 40 mcg selenium",
    price: "₹849 / 30 capsules",
    priceFrom: 849,
    priceInr: 849,
    tags: ["ISO 22000", "HACCP"],
    rx: false,
    pack: "bottle-soft",
    colour: "#eda100",
    retailer: "Carbamide Forte",
    url: "https://mycf.in/products/carbamide-forte-coenzyme-q10-coq10-300mg-with-selenium-40mcg-supports-heart-health-and-vascular-health-100-vegetarian-30-capsules",
    image: "https://mycf.in/cdn/shop/files/CopyofB0FGCQVX3G.MAIN.jpg?v=1752564955",
  },
  {
    id: "nutrabay-curcumin-piperine",
    supplement: "curcumin",
    brand: "Nutrabay",
    name: "Curcumin + Piperine",
    strength: "95% curcuminoids + piperine",
    price: "₹648 / 60 capsules",
    priceFrom: 648,
    priceInr: 648,
    tags: ["Generic, not C3 Complex"],
    rx: false,
    pack: "bottle-cap",
    colour: "#eda100",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/nutrabay-wellness-curcumin-piperine-capsule-otc629101",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/87f42488a9de46fbb06af56bfbf4a1f7.jpg",
  },
  {
    id: "apex-labs-zincovit",
    supplement: "zinc",
    brand: "Apex Labs",
    name: "Zincovit",
    strength: "Zinc 17 mg + multivitamin",
    price: "₹104 / 15 tablets",
    priceFrom: 104,
    priceInr: 104,
    tags: ["India default"],
    rx: false,
    pack: "blister",
    colour: "#eb6834",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/zincovit-tablet-with-multivitamin-multimineral-grape-seed-extract-otc111998",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/874c73ab2b3747f68d49263ab2c475ca.jpg",
  },
  {
    id: "abbott-limcee-vitamin-c-chewable",
    supplement: "vitamin-c",
    brand: "Abbott",
    name: "Limcee vitamin C chewable",
    strength: "500 mg",
    price: "₹23.90 / 15 tablets",
    priceFrom: 23.9,
    priceInr: 24,
    tags: ["Above saturation"],
    rx: false,
    pack: "blister",
    colour: "#eda100",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/limcee-vitamin-c-chewable-tablet-flavour-orange-otc173959",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/pharmacy-production-rxs%2F1738667483_crop_38.png",
  },
  {
    id: "amway-nutrilite-daily-multivitamin",
    supplement: "multivitamin",
    brand: "Amway",
    name: "Nutrilite Daily multivitamin",
    strength: "13 vitamins + 11 minerals",
    price: "₹1,289 / 60 tablets",
    priceFrom: 1289,
    priceInr: 1289,
    tags: ["Premium end"],
    rx: false,
    pack: "bottle-tab",
    colour: "#008300",
    retailer: "Amway",
    url: "https://www.amway.in/nutrilite-daily/p/313505ID",
    image: "https://media.amway.in/sys-master/images/h48/h13/9201501798430/EIA.w800.h800.313505ID_Daily-601.png",
  },
  {
    id: "hk-vitals-multivitamin-with-zinc-c",
    supplement: "multivitamin",
    brand: "HK Vitals",
    name: "Multivitamin with Zinc & C",
    strength: "Zinc 5.49 mg + taurine + ginseng",
    price: "₹399 / 60 tablets",
    priceFrom: 399,
    priceInr: 399,
    tags: ["Insurance, not medicine"],
    rx: false,
    pack: "bottle-tab",
    colour: "#2a78d6",
    retailer: "HealthKart",
    url: "https://www.healthkart.com/sv/healthkart-hk-vitals-multivitamin-with-multimineral/SP-39873",
    image: "https://img8.hkrtcdn.com/40247/prd_4024697-HealthKart-HK-Vitals-Multivitamin-with-Zinc-Vitamin-C-60-tablets-Unflavoured_c_l.jpg",
  },
  {
    id: "sun-pharma-revital-h",
    supplement: "multivitamin",
    brand: "Sun Pharma",
    name: "Revital H",
    strength: "Ginseng 212.5 mg + 10 vitamins",
    price: "₹315 / 30 capsules",
    priceFrom: 315,
    priceInr: 315,
    tags: ["Energy claims unsupported"],
    rx: false,
    pack: "bottle-soft",
    colour: "#e34948",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/revital-h-men-multivitamin-with-calcium-zinc-ginseng-for-immunity-strong-bones-energy-otc66303",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/7c0c52f301584f3697ad1d3095cd5e21.jpg",
  },
  {
    id: "wellbeing-nutrition-marine-collagen-type-i-iii",
    supplement: "collagen",
    brand: "Wellbeing Nutrition",
    name: "Marine Collagen Type I & III",
    strength: "8 g peptides per serving",
    price: "₹1,619 / 200 g",
    priceFrom: 1619,
    priceInr: 1619,
    tags: ["Weak evidence"],
    rx: false,
    pack: "jar",
    colour: "#e87ba4",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/wellbeing-nutrition-marine-collagen-type-i-iii-8000mg-for-skin-hair-nails-bones-joints-unflavoured-otc679753",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/12c4498dd39445e28c47e186aab1b7c3.jpg",
  },
  {
    id: "hk-vitals-zinc-complex",
    supplement: "zinc",
    brand: "HK Vitals",
    name: "Zinc Complex",
    strength: "Zinc form and elemental mg not stated",
    price: "₹399 / 60 tablets",
    priceFrom: 399,
    priceInr: 399,
    tags: ["Label unclear"],
    rx: false,
    pack: "bottle-tab",
    colour: "#898781",
    retailer: "HealthKart",
    url: "https://www.healthkart.com/sv/healthkart-hk-vitals-zinc-complex/SP-88771",
    image: "https://img4.hkrtcdn.com/39197/prd_3919673-HealthKart-HK-Vitals-Zinc-Complex-60-tablets_c_l.jpg",
  },
  {
    id: "hkvitals-vitamin-d3-600iu",
    supplement: "vitamin-d3",
    brand: "HK Vitals",
    name: "Vitamin D3 600 IU Softgels",
    strength: "600 IU vitamin D3 per capsule",
    price: "₹389 / 60 softgels",
    priceFrom: 389,
    priceInr: 389,
    tags: ["Third-party tested", "Value"],
    rx: false,
    pack: "bottle-soft",
    colour: "#eda100",
    retailer: "HK Vitals",
    url: "https://www.hkvitals.com/products/vitamin-d3",
    image: "https://img2.hkrtcdn.com/35037/prd_3503641-HK-Vitals-Vitamin-D3-by-HealthKart-60-capsules_o.jpg",
  },
  {
    id: "swisse-calcium-vitamin-d",
    supplement: "vitamin-d3",
    brand: "Swisse",
    name: "Ultiboost Calcium + Vitamin D",
    strength: "317 mg calcium + 252 IU vitamin D3 per tablet",
    price: "₹1,020 / 90 tablets",
    priceFrom: 1020,
    priceInr: 1020,
    tags: ["Premium", "Price varies by seller"],
    rx: false,
    pack: "bottle-tab",
    colour: "#2a78d6",
    retailer: "Apollo Pharmacy",
    url: "https://www.apollopharmacy.in/otc/swisse-ultiboost-calcium-vitamin-d-tab-90-s",
    image: "https://images.apollo247.in/pub/media/catalog/product/S/W/SWI0171_1-AUG23_1.jpg",
  },
  {
    id: "zeroharm-holistic-calcium",
    supplement: "vitamin-d3",
    brand: "Zeroharm",
    name: "Holistic Calcium with D3 & K2-7",
    strength: "Per tablet: calcium 150 mg; D3 7.5 mcg; K2-7 27.5 mcg; magnesium 26 mg; phosphorus 41 mg",
    price: "₹699 / 60 tablets",
    priceFrom: 699,
    priceInr: 699,
    tags: ["Vegetarian", "High performance", "Inflated MRP"],
    rx: false,
    pack: "bottle-tab",
    colour: "#eda100",
    retailer: "Zeroharm",
    url: "https://www.zeroharm.in/products/holistic-calcium-tablets",
    image: "https://www.zeroharm.in/cdn/shop/files/CALCIUM_for_website-01.jpg?v=1766163690",
  },
  {
    id: "carbamide-forte-b12",
    supplement: "vitamin-b12",
    brand: "Carbamide Forte",
    name: "Methylcobalamin B12 1500 mcg",
    strength: "1500 mcg methylcobalamin per tablet",
    price: "₹774 / 90 tablets",
    priceFrom: 774,
    priceInr: 774,
    tags: ["Vegan", "Premium", "Single nutrient"],
    rx: false,
    pack: "bottle-tab",
    colour: "#e34948",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/carbamide-forte-methylcobalamin-vitamin-b12-1500mcg-tablet-for-stomach-care-otc690461",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/d2a5bd5fc3d546988d5aacf44b836efc.jpg",
  },
  {
    id: "gnc-triple-strength-fish-oil",
    supplement: "omega-3",
    brand: "GNC",
    name: "Triple Strength Fish Oil 1500 mg",
    strength: "1500 mg fish oil with 900 mg combined EPA+DHA; individual split not stated",
    price: "₹850 / 60 softgels",
    priceFrom: 850,
    priceInr: 850,
    tags: ["Budget", "Price varies by seller"],
    rx: false,
    pack: "bottle-soft",
    colour: "#4a3aa7",
    retailer: "Nutrabay",
    url: "https://nutrabay.com/product/gnc-triple-strength-fish-oil-softgels/?pId=6416665&vId=6423647",
    image: "https://cdn.nutrabay.com/wp-content/uploads/2021/04/NB-GNC-1061-03-01-340x340.jpg",
  },
  {
    id: "naturaltein-vegan-omega3",
    supplement: "omega-3",
    brand: "Naturaltein",
    name: "Algae Source Vegan Omega 3 500 mg",
    strength: "500 mg omega-3 per 2-softgel serving; DHA/EPA split not stated",
    price: "₹989 / 60 softgels",
    priceFrom: 989,
    priceInr: 989,
    tags: ["Vegan", "High performance", "Partly verified", "Inflated MRP"],
    rx: false,
    pack: "bottle-soft",
    colour: "#1baf7a",
    retailer: "Nutrabay",
    url: "https://nutrabay.com/product/naturaltein-algae-source-ultimate-vegan-omega-3-500mg/?pId=3535537&vId=8233834",
    image: "https://cdn2.nutrabay.com/uploads/product/featured_image/product-4281-featured_image-Naturaltein_Algae_Source_Ultimate_Vegan_Omega_3_500mg.jpg",
  },
  {
    id: "neuherbs-flaxseed-oil",
    supplement: "omega-3",
    brand: "Neuherbs",
    name: "Flaxseed Oil 1000 mg with Omega 3-6-9",
    strength: "Per 2 softgels: omega-3 (ALA) 500 mg, omega-6 134 mg, omega-9 187 mg",
    price: "₹499 / 60 softgels",
    priceFrom: 499,
    priceInr: 499,
    tags: ["Vegan", "Value"],
    rx: false,
    pack: "bottle-soft",
    colour: "#2a78d6",
    retailer: "Neuherbs",
    url: "https://neuherbs.com/products/omega-flaxseed-oil",
    image: "https://neuherbs.com/cdn/shop/files/Flaxseed_oil_capsule_1.webp?v=1772175772",
  },
  {
    id: "neuherbs-gold-fish-oil",
    supplement: "omega-3",
    brand: "Neuherbs",
    name: "Gold Deep-Sea Fish Oil Omega-3",
    strength: "Per 2 softgels: 1800 mg fish oil, EPA 1080 mg, DHA 720 mg",
    price: "₹1,299 / 60 softgels",
    priceFrom: 1299,
    priceInr: 1299,
    tags: ["Third-party tested", "High performance", "Price varies by seller"],
    rx: false,
    pack: "bottle-soft",
    colour: "#2a78d6",
    retailer: "Nutrabay",
    url: "https://neuherbs.com/products/gold-deep-sea-fish-oil-omega-3",
    image: "https://neuherbs.com/cdn/shop/files/Gold_deep_sea_fish_oil_capsule_1.webp?v=1776076367",
  },
  {
    id: "wow-omega3-1300",
    supplement: "omega-3",
    brand: "WOW Life Science",
    name: "Omega-3 1300 mg Softgels",
    strength: "1300 mg fish oil per capsule; EPA/DHA split not stated",
    price: "₹719 / 60 softgels",
    priceFrom: 719,
    priceInr: 719,
    tags: ["Premium", "Partly verified", "EPA/DHA split not stated"],
    rx: false,
    pack: "bottle-soft",
    colour: "#008300",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/wow-life-science-omega-3-1300-mg-epa-dha-softgel-capsule-for-healthy-heart-eyes-joints-otc411356",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/9debbba19e15458ab68c0ac36cb38f37.jpg",
  },
  {
    id: "wellbeing-slow-omega3-3x",
    supplement: "omega-3",
    brand: "Wellbeing Nutrition",
    name: "Slow Triple Strength Omega-3 with Curcumin",
    strength: "Per 2 softgels: 1500 mg fish oil, EPA 612 mg, DHA 408 mg",
    price: "₹949 / 60 softgels",
    priceFrom: 949,
    priceInr: 949,
    tags: ["Premium"],
    rx: false,
    pack: "bottle-soft",
    colour: "#1baf7a",
    retailer: "Apollo Pharmacy",
    url: "https://www.apollopharmacy.in/otc/wellbeing-nutrition-slow-virgin-omega-3-cap-60-s",
    image: "https://images.apollo247.in/pub/media/catalog/product/w/e/wel0348_1_1_.jpg",
  },
  {
    id: "asitis-creatine-monohydrate",
    supplement: "creatine",
    brand: "AS-IT-IS Nutrition",
    name: "ONE Creatine Monohydrate",
    strength: "Creatine Monohydrate",
    price: "₹525 / 250 g",
    priceFrom: 525,
    priceInr: 525,
    tags: ["Vegetarian", "Third-party tested", "Partly verified"],
    rx: false,
    pack: "tub",
    colour: "#4a3aa7",
    retailer: "Nutrabay",
    url: "https://asitisnutrition.com/products/pure-creatine-monohydrate-powder",
    image: "https://asitisnutrition.com/cdn/shop/files/AS-IT-IS_One_Creatine_RPD_100g_front-min_1_af50ae47-5137-4792-893e-797e4a30d8b2.jpg?v=1771217123",
  },
  {
    id: "athlab-creapower-creapure",
    supplement: "creatine",
    brand: "Athlab",
    name: "CreaPower Creatine Monohydrate (Creapure)",
    strength: "Creapure Creatine Monohydrate (Alzchem, Germany)",
    price: "₹799 / 250 g",
    priceFrom: 799,
    priceInr: 799,
    tags: ["Vegetarian", "Value", "Partly verified", "Out of stock at review"],
    rx: false,
    pack: "tub",
    colour: "#4a3aa7",
    retailer: "Nutrabay",
    url: "https://nutrabay.com/product/athlab-creapower-creapure-creatine-monohydrate/?pId=4208554&vId=3768627",
    image: "https://cdn.nutrabay.com/wp-content/uploads/2023/12/NB-ATH-1006-01-01-340x340.jpg",
  },
  {
    id: "bigmuscles-creatine",
    supplement: "creatine",
    brand: "BigMuscles Nutrition",
    name: "BigMuscles Creatine",
    strength: "Micronised Creatine Monohydrate, ProHydrolase protease enzyme",
    price: "₹229 / 33 servings",
    priceFrom: 229,
    priceInr: 229,
    tags: ["Vegetarian", "Budget", "Partly verified"],
    rx: false,
    pack: "tub",
    colour: "#e34948",
    retailer: "Nutrabay",
    url: "https://nutrabay.com/product/big-muscles-creatine/?pId=7368815&vId=1295563",
    image: "https://cdn2.nutrabay.com/uploads/product/images/featured_image-NB-BGM-1015-PA-400x400.webp",
  },
  {
    id: "gnc-creatine-electrolytes",
    supplement: "creatine",
    brand: "GNC",
    name: "Pro Performance Creatine + Electrolytes",
    strength: "Creatine Monohydrate 3 g, Sodium 118 mg, Potassium 106 mg",
    price: "₹549 / 100 g",
    priceFrom: 549,
    priceInr: 549,
    tags: ["High performance", "Partly verified"],
    rx: false,
    pack: "tub",
    colour: "#2a78d6",
    retailer: "Guardian (GNC India)",
    url: "https://www.guardian.in/products/creatine-electrolytes",
    image: "https://www.guardian.in/cdn/shop/files/100_3.png?v=1750770123",
  },
  {
    id: "gnc-creatine-monohydrate",
    supplement: "creatine",
    brand: "GNC",
    name: "Pro Performance Creatine Monohydrate 3000 mg",
    strength: "Creatine Monohydrate 3 g",
    price: "₹518 / 100 g",
    priceFrom: 518,
    priceInr: 518,
    tags: ["Vegetarian", "Premium"],
    rx: false,
    pack: "tub",
    colour: "#2a78d6",
    retailer: "Nutrabay",
    url: "https://nutrabay.com/product/gnc-creatine-monohydrate-250g/?pId=5371058&vId=6002107",
    image: "https://cdn2.nutrabay.com/uploads/product/featured_image/product-2595-featured_image-GNC_Creatine_Monohydrate.jpg",
  },
  {
    id: "nakpro-creatine-monohydrate",
    supplement: "creatine",
    brand: "Nakpro",
    name: "Micronized Creatine Monohydrate",
    strength: "Creatine Monohydrate (micronised)",
    price: "₹493 / 250 g",
    priceFrom: 493,
    priceInr: 493,
    tags: ["Vegetarian", "Partly verified"],
    rx: false,
    pack: "tub",
    colour: "#e34948",
    retailer: "Nutrabay",
    url: "https://nutrabay.com/product/nakpro-micronized-creatine-monohydrate/",
    image: "https://cdn.nutrabay.com/wp-content/uploads/2023/10/NB-NAK-1021-02-01-800x800.jpg",
  },
  {
    id: "on-micronized-creatine",
    supplement: "creatine",
    brand: "Optimum Nutrition",
    name: "Micronized Creatine Monohydrate",
    strength: "Creatine Monohydrate",
    price: "₹529 / 100 g",
    priceFrom: 529,
    priceInr: 529,
    tags: ["Third-party tested", "Value", "Partly verified", "Creapure claim unconfirmed"],
    rx: false,
    pack: "tub",
    colour: "#4a3aa7",
    retailer: "Nutrabay",
    url: "https://nutrabay.com/product/optimum-nutrition-on-micro-creatine-powder-2/?pId=4322003&vId=1375346",
    image: "https://cdn2.nutrabay.com/uploads/product/images/featured_image-NB-OPT-1012-PA-1772085018-400x400.webp",
  },
  {
    id: "wellcore-creatine-monohydrate",
    supplement: "creatine",
    brand: "Wellcore",
    name: "Micronised Creatine Monohydrate",
    strength: "Creatine Monohydrate (micronised)",
    price: "₹529 / 100 g",
    priceFrom: 529,
    priceInr: 529,
    tags: ["Vegetarian", "Premium", "Partly verified"],
    rx: false,
    pack: "tub",
    colour: "#2a78d6",
    retailer: "Nutrabay",
    url: "https://nutrabay.com/product/wellcore-wellversed-micronised-creatine-monohydrate/?pId=8318359&vId=2181561",
    image: "https://cdn2.nutrabay.com/uploads/product/featured_image/product-106-featured_image-Wellversed_Wellcore__Micronised_Creatine_Monohydrate.jpg",
  },
  {
    id: "organic-india-psyllium",
    supplement: "psyllium",
    brand: "Organic India",
    name: "Psyllium Whole Husk",
    strength: "Certified organic psyllium whole husk",
    price: "₹260 / 100 g",
    priceFrom: 260,
    priceInr: 260,
    tags: ["Partly verified", "Certifier unnamed"],
    rx: false,
    pack: "tub",
    colour: "#008300",
    retailer: "Giri",
    url: "https://giri.in/products/organic-india-whole-husk-psyllium-100-gms",
    image: "https://giri.in/cdn/shop/files/802529_Organic_India_Whole_Husk_Psyllium_100g_1_41facd4e-38fc-4ba3-b205-2c583e3eb8d9_1200x1200.webp?v=1715426313",
  },
  {
    id: "avvatar-whey-protein",
    supplement: "protein",
    brand: "Avvatar",
    name: "Avvatar Whey Protein",
    price: "₹3,899 / 1000 g",
    priceFrom: 3899,
    priceInr: 3899,
    tags: ["Vegetarian", "Premium"],
    rx: false,
    pack: "tub",
    colour: "#eda100",
    retailer: "Avvatar",
    url: "https://www.avvatarindia.com/categories/whey-protein",
    image: "https://www.avvatarindia.com/images/product_images/1697552095_FOP.jpg",
  },
  {
    id: "boldfit-vegan-plant-protein",
    supplement: "protein",
    brand: "Boldfit",
    name: "Vegan Plant Protein",
    price: "₹1,747 / 1000 g",
    priceFrom: 1747,
    priceInr: 1747,
    tags: ["Vegan", "Budget", "Partly verified", "Composition unverified"],
    rx: false,
    pack: "tub",
    colour: "#eda100",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/boldfit-vegan-protein-chocolate-otc648881",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/acuiy5nhemf2ztvkosle.jpg?dpr=3&format=auto&h=320&w=412",
  },
  {
    id: "cure-by-design-hemp-protein",
    supplement: "protein",
    brand: "Cure By Design",
    name: "Hemp Protein Powder",
    price: "₹500 / 250 g",
    priceFrom: 500,
    priceInr: 500,
    tags: ["Vegan", "Value", "Partly verified", "Composition unverified"],
    rx: false,
    pack: "tub",
    colour: "#008300",
    retailer: "Cure By Design",
    url: "https://curebydesign.in/product/hemp-protein-powder/",
    image: "https://curebydesign.in/wp-content/uploads/2024/02/PROTEIN_500.jpg",
  },
  {
    id: "fastandup-plant-protein",
    supplement: "protein",
    brand: "Fast&Up",
    name: "Plant Protein (Pea Isolate + Brown Rice)",
    price: "₹831 / 500 g",
    priceFrom: 831,
    priceInr: 831,
    tags: ["Vegan", "Third-party tested", "Budget"],
    rx: false,
    pack: "tub",
    colour: "#008300",
    retailer: "Fast&Up",
    url: "https://in.fastandup.com/products/plant-protein-rich-chocolate-1kg",
    image: "https://in.fastandup.com/cdn/shop/files/1_efcf69ac-ad36-4c67-abd1-414928ac114d.jpg?v=1780922094",
  },
  {
    id: "gnc-amp-gold-whey",
    supplement: "protein",
    brand: "GNC",
    name: "AMP Gold Series 100% Whey Protein Advanced",
    price: "₹5,749 / 907 g",
    priceFrom: 5749,
    priceInr: 5749,
    tags: ["Vegetarian", "Third-party tested", "High performance"],
    rx: false,
    pack: "tub",
    colour: "#008300",
    retailer: "Guardian (GNC India)",
    url: "https://www.guardian.in/products/gnc-amp-gold-series-100-whey-protein-advanced",
    image: "https://www.guardian.in/cdn/shop/files/Artboard1_9806cb3c-ac68-4bce-a287-85c37c1acaef.jpg?v=1734090960&width=2048",
  },
  {
    id: "isopure-low-carb-isolate",
    supplement: "protein",
    brand: "Isopure",
    name: "Low Carb 100% Whey Protein Isolate",
    price: "₹2,919 / 500 g",
    priceFrom: 2919,
    priceInr: 2919,
    tags: ["Vegetarian", "High performance"],
    rx: false,
    pack: "tub",
    colour: "#eda100",
    retailer: "Nutrabay",
    url: "https://nutrabay.com/product/natures-best-isopure-low-carb/?pId=1899939&vId=5870113",
    image: "https://cdn2.nutrabay.com/uploads/product/images/featured_image-NB-ISO-1002-PA-1768484418-400x400.webp",
  },
  {
    id: "muscle-asylum-premium-whey",
    supplement: "protein",
    brand: "Muscle Asylum",
    name: "Premium Whey Protein",
    price: "₹1,233 / 1000 g",
    priceFrom: 1233,
    priceInr: 1233,
    tags: ["Vegetarian", "Budget", "Deep discount off MRP"],
    rx: false,
    pack: "tub",
    colour: "#4a3aa7",
    retailer: "Muscle Asylum",
    url: "https://muscleasylum.in/products/whey-protein",
    image: "https://muscleasylum.in/cdn/shop/files/Chocolate_bag_2.png?v=1783935393",
  },
  {
    id: "muscleblaze-raw-whey-concentrate",
    supplement: "protein",
    brand: "MuscleBlaze",
    name: "100% Clean Raw Whey Protein Concentrate",
    price: "₹3,499 / 1000 g",
    priceFrom: 3499,
    priceInr: 3499,
    tags: ["Vegetarian", "High performance", "Partly verified", "Composition unverified"],
    rx: false,
    pack: "tub",
    colour: "#008300",
    retailer: "MuscleBlaze",
    url: "https://www.muscleblaze.com/categories/proteins?navKey=CL-1703",
    image: "https://img8.hkrtcdn.com/cdn-cgi/image/width=172,height=172,dpr=1/39954/prd_3995367-MuscleBlaze-Raw-Whey-Protein-80-4.4-lb-Unflavoured_o.jpg",
  },
  {
    id: "muscleblaze-micellar-casein",
    supplement: "protein",
    brand: "MuscleBlaze",
    name: "100% Micellar Casein",
    price: "₹2,929 / 1000 g",
    priceFrom: 2929,
    priceInr: 2929,
    tags: ["Vegetarian", "Value"],
    rx: false,
    pack: "tub",
    colour: "#e34948",
    retailer: "MuscleBlaze",
    url: "https://www.muscleblaze.com/sv/muscleblaze-100-micellar-casein/SP-38554",
    image: "https://img8.hkrtcdn.com/39694/prd_3969387-MuscleBlaze-100-Micellar-Casein-2.2-lb-Chocolate_o.jpg",
  },
  {
    id: "muscleblaze-biozyme-iso-zero",
    supplement: "protein",
    brand: "MuscleBlaze",
    name: "Biozyme Iso-Zero",
    price: "₹4,999 / 1000 g",
    priceFrom: 4999,
    priceInr: 4999,
    tags: ["Vegetarian", "High performance"],
    rx: false,
    pack: "tub",
    colour: "#2a78d6",
    retailer: "MuscleBlaze",
    url: "https://www.muscleblaze.com/sv/muscleblaze-biozyme-iso-zero/SP-45405?navKey=VRNT-89957",
    image: "https://img8.hkrtcdn.com/40660/prd_4065947-MuscleBlaze-Biozyme-IsoZero-2.2-lb-Low-Carb-Ice-Cream-Chocolate_o.jpg",
  },
  {
    id: "muscleblaze-fuel-one-true-whey-isolate",
    supplement: "protein",
    brand: "MuscleBlaze",
    name: "MB Fuel One True Whey Isolate",
    price: "₹1,499 / 1000 g",
    priceFrom: 1499,
    priceInr: 1499,
    tags: ["Vegetarian", "Budget", "Out of stock at review"],
    rx: false,
    pack: "tub",
    colour: "#4a3aa7",
    retailer: "MuscleBlaze",
    url: "https://www.muscleblaze.com/sv/mb-fuel-one-true-whey-isolate/SP-76595",
    image: "https://img4.hkrtcdn.com/12021/prd_1202063-MB-Fuel-One-True-Whey-Isolate-2.2-lb-Unflavoured_o.jpg",
  },
  {
    id: "muscleblaze-plant-protein",
    supplement: "protein",
    brand: "MuscleBlaze",
    name: "MuscleBlaze Plant Protein",
    price: "₹2,129 / 1000 g",
    priceFrom: 2129,
    priceInr: 2129,
    tags: ["Vegan", "Value"],
    rx: false,
    pack: "tub",
    colour: "#2a78d6",
    retailer: "MuscleBlaze",
    url: "https://www.muscleblaze.com/sv/muscleblaze-plant-protein/SP-103284",
    image: "https://img2.hkrtcdn.com/31085/prd_3108491-MuscleBlaze-Plant-Protein-Rich-Chocolate-2.2-lb_o.jpg",
  },
  {
    id: "myprotein-clear-whey-isolate",
    supplement: "protein",
    brand: "Myprotein",
    name: "Clear Whey Isolate",
    price: "₹2,499 / 312 g",
    priceFrom: 2499,
    priceInr: 2499,
    tags: ["Vegetarian", "High performance"],
    rx: false,
    pack: "tub",
    colour: "#008300",
    retailer: "Myprotein",
    url: "https://www.myprotein.co.in/p/sports-nutrition/clear-whey-isolate/12299009/",
    image: "https://static.thcdn.com/productimg/original/16302004-5475289103796196.jpg",
  },
  {
    id: "nakpro-platinum-isolate",
    supplement: "protein",
    brand: "Nakpro",
    name: "Platinum Raw Whey Protein Isolate",
    price: "₹2,224 / 1000 g",
    priceFrom: 2224,
    priceInr: 2224,
    tags: ["Vegetarian", "Third-party tested", "Budget", "Partly verified"],
    rx: false,
    pack: "tub",
    colour: "#2a78d6",
    retailer: "Nakpro",
    url: "https://nakpro.com/collections/whey-protein-powder",
    image: "https://nakpro.com/cdn/shop/files/01_unflavoured_45b05573-b1c6-455f-95f6-beb948734420.jpg?v=1779173840&width=1080",
  },
  {
    id: "nakpro-whey-hydro",
    supplement: "protein",
    brand: "Nakpro",
    name: "Whey Hydro (Hydrolysate)",
    price: "₹2,949 / 1000 g",
    priceFrom: 2949,
    priceInr: 2949,
    tags: ["Vegetarian", "Premium", "Partly verified", "Composition unverified"],
    rx: false,
    pack: "tub",
    colour: "#e34948",
    retailer: "Nakpro",
    url: "https://nakpro.com/collections/whey-protein-powder",
    image: "https://nakpro.com/cdn/shop/files/01_malaikulfi_03e617c0-ecdd-4c6a-85c0-a5b0beb617d8.jpg?v=1777034087&width=1080",
  },
  {
    id: "naturaltein-whey-isolate",
    supplement: "protein",
    brand: "Naturaltein",
    name: "Natural Whey Protein Isolate",
    price: "₹5,599 / 1000 g",
    priceFrom: 5599,
    priceInr: 5599,
    tags: ["Vegetarian", "Premium", "Partly verified", "Sources disagree on composition"],
    rx: false,
    pack: "tub",
    colour: "#e34948",
    retailer: "Nutrabay",
    url: "https://nutrabay.com/product/naturaltein-whey-protein-isolate/?pId=6227949&vId=9690484",
    image: "https://cdn.nutrabay.com/wp-content/uploads/2023/11/NB-NTR-1000-01-01-340x340.jpg",
  },
  {
    id: "nutrabay-gold-pea-protein",
    supplement: "protein",
    brand: "Nutrabay",
    name: "Nutrabay Gold Pea Protein",
    price: "₹69 / 40 g",
    priceFrom: 69,
    priceInr: 69,
    tags: ["Vegan", "Budget"],
    rx: false,
    pack: "tub",
    colour: "#e34948",
    retailer: "Nutrabay",
    url: "https://nutrabay.com/product/nutrabay-gold-hydrolyzed-pea-protein/?pId=3302532&vId=8317633",
    image: "https://cdn2.nutrabay.com/uploads/product/images/featured_image-NB-NUT-1102-PA-1771418717-400x400.webp",
  },
  {
    id: "nutrabay-soy-protein-isolate",
    supplement: "protein",
    brand: "Nutrabay",
    name: "Pure Soy Protein Isolate",
    price: "₹1,099 / 1000 g",
    priceFrom: 1099,
    priceInr: 1099,
    tags: ["Vegan", "Budget"],
    rx: false,
    pack: "tub",
    colour: "#4a3aa7",
    retailer: "Nutrabay",
    url: "https://nutrabay.com/product/nutrabay-pure-100-soy-protein-isolate/?pId=4186049&vId=1886437",
    image: "https://cdn2.nutrabay.com/uploads/product/images/featured_image-NB-NUT-1047-PA-400x400.webp",
  },
  {
    id: "oziva-bioactive-plant-protein",
    supplement: "protein",
    brand: "OZiva",
    name: "Bioactive Plant Protein",
    price: "₹1,359 / 500 g",
    priceFrom: 1359,
    priceInr: 1359,
    tags: ["Vegan", "Budget"],
    rx: false,
    pack: "tub",
    colour: "#2a78d6",
    retailer: "OZiva",
    url: "https://www.oziva.in/products/oziva-bioactive-plant-protein-with-25g-vegan-protein-5-5-bcaas-100-rda-vitamins-minerals-ayurvedic-herbs-for-better-endurance-stamina-muscle-recovery-1-kg",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/3ace32f8f4bb48108aff40c98ca85fa6.jpg?dpr=3&format=auto&h=320&w=412",
  },
  {
    id: "one-good-plant-protein",
    supplement: "protein",
    brand: "One Good (Nourish You)",
    name: "One Good Plant Protein",
    price: "₹1,299 / 500 g",
    priceFrom: 1299,
    priceInr: 1299,
    tags: ["Vegetarian", "Premium"],
    rx: false,
    pack: "tub",
    colour: "#eda100",
    retailer: "Nourish You",
    url: "https://nourishyou.in/collections/plant-protein-powder",
    image: "https://nourishyou.in/cdn/shop/files/VanillaD2CListingImages_FOP_73171487-fc50-4893-9891-c41c81f3c200_1200x1200.png?v=1763632568",
  },
  {
    id: "on-performance-whey",
    supplement: "protein",
    brand: "Optimum Nutrition",
    name: "Performance Whey",
    price: "₹2,149 / 500 g",
    priceFrom: 2149,
    priceInr: 2149,
    tags: ["Vegetarian", "High performance", "Partly verified", "Composition unverified"],
    rx: false,
    pack: "tub",
    colour: "#4a3aa7",
    retailer: "Optimum Nutrition",
    url: "https://www.optimumnutrition.co.in/collections/whey-protein",
    image: "https://www.optimumnutrition.co.in/cdn/shop/files/748927071320_1_5ed99bc6-4ee5-4524-b46c-558db6c88dd4.jpg?v=1756964077&width=533",
  },
  {
    id: "plix-evolve-protein",
    supplement: "protein",
    brand: "Plix",
    name: "Evolve Plant Protein Shake",
    price: "₹2,266 / 1000 g",
    priceFrom: 2266,
    priceInr: 2266,
    tags: ["Vegetarian", "Value", "Price varies by seller"],
    rx: false,
    pack: "tub",
    colour: "#4a3aa7",
    retailer: "Tata 1mg",
    url: "https://www.plixlife.com/collection/proteins/227",
    image: "https://plixlifefc-media.farziengineer.co/__sized__/products/14-e47e986f3a9f43a9a65208a94425ab30-thumbnail-255x255-70.jpg",
  },
  {
    id: "plix-super-strength-protein",
    supplement: "protein",
    brand: "Plix",
    name: "Super Strength Plant Protein",
    price: "₹1,125 / 500 g",
    priceFrom: 1125,
    priceInr: 1125,
    tags: ["Vegan", "Value", "Partly verified", "Sources disagree on composition"],
    rx: false,
    pack: "tub",
    colour: "#e34948",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/plix-super-strength-plant-protein-powder-raw-chocolate-otc675363",
    image: "https://d2zrb39teys09q.cloudfront.net/products/otc/DR280322/DR280322_12.jpg",
  },
  {
    id: "whole-truth-whey-isolate",
    supplement: "protein",
    brand: "The Whole Truth",
    name: "Whey Protein Isolate (Unflavoured)",
    price: "₹4,215 / 1000 g",
    priceFrom: 4215,
    priceInr: 4215,
    tags: ["Vegetarian", "Premium", "Partly verified", "Out of stock at review"],
    rx: false,
    pack: "tub",
    colour: "#2a78d6",
    retailer: "Nutrabay",
    url: "https://nutrabay.com/product/the-whole-truth-whey-protein-isolate/?pId=9568984&vId=3039905",
    image: "https://cdn2.nutrabay.com/uploads/product/featured_image/product-3611-featured_image-The_Whole_Truth_Whey_Protein_Isolate.jpg",
  },
  {
    id: "ultimate-nutrition-prostar-whey",
    supplement: "protein",
    brand: "Ultimate Nutrition",
    name: "Prostar 100% Whey Protein",
    price: "₹8,699 / 2390 g",
    priceFrom: 8699,
    priceInr: 8699,
    tags: ["Vegetarian", "Premium", "Partly verified"],
    rx: false,
    pack: "tub",
    colour: "#eda100",
    retailer: "Nutrabay",
    url: "https://nutrabay.com/product/ultimate-nutrition-prostar-100-whey-protein/",
    image: "https://cdn.nutrabay.com/wp-content/uploads/2017/11/NB-ULT-1000-02-01-800x800.jpg",
  },
  {
    id: "wellbeing-superfood-plant-protein",
    supplement: "protein",
    brand: "Wellbeing Nutrition",
    name: "Superfood Plant Protein",
    price: "₹1,439 / 500 g",
    priceFrom: 1439,
    priceInr: 1439,
    tags: ["Vegan", "Premium", "Partly verified", "Composition unverified"],
    rx: false,
    pack: "tub",
    colour: "#2a78d6",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/wellbeing-nutrition-superfood-plant-protein-for-muscle-growth-metabolism-flavour-belgian-dark-chocolate-otc755212",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/ae8cba71b0cf48f8b252b5e165b6b9e7.jpg?dpr=3&format=auto&h=320&w=412",
  },
  {
    id: "himalayan-organics-magnesium-glycinate",
    supplement: "magnesium",
    brand: "Himalayan Organics",
    name: "Chelated Magnesium Glycinate",
    strength: "2000 mg magnesium glycinate per serving, providing 440 mg elemental magnesium",
    price: "₹699 / 120 capsules",
    priceFrom: 699,
    priceInr: 699,
    tags: ["Vegetarian", "Elemental dose stated", "High dose — human review", "Inflated MRP"],
    rx: false,
    pack: "bottle-cap",
    colour: "#4a3aa7",
    retailer: "Himalayan Organics",
    url: "https://www.thehimalayanorganics.in/products/himalayan-organics-highly-absorbable-magnesium-glycinate-support-overall-nerve-and-muscle-health-strong-bones-for-men-women-120-vegetable-capsules",
    image: "https://www.thehimalayanorganics.in/cdn/shop/files/Artboard1.jpg?v=1748254982",
  },
  {
    id: "carbamide-forte-zinc-picolinate",
    supplement: "zinc",
    brand: "Carbamide Forte",
    name: "Zinc Picolinate with Vitamin C",
    strength: "Zinc picolinate 85 mg + vitamin C 40 mg per tablet; elemental zinc not stated",
    price: "₹599 / 120 tablets",
    priceFrom: 599,
    priceInr: 599,
    tags: ["Vegetarian", "Budget", "Compound weight, not elemental", "Single nutrient"],
    rx: false,
    pack: "bottle-tab",
    colour: "#898781",
    retailer: "Carbamide Forte",
    url: "https://mycf.in/products/zinc-picolinate-with-vitamin-c-120-tablets",
    image: "https://mycf.in/cdn/shop/files/71zh4J8He4L._SL1500__1.jpg?v=1769759193",
  },
  {
    id: "boldfit-vitamin-c-complex",
    supplement: "vitamin-c",
    brand: "Boldfit",
    name: "Vitamin C Complex 1000 mg with Amla & Zinc",
    strength: "1000 mg vitamin C per tablet; zinc and amla amounts not stated",
    price: "₹267 / 60 tablets",
    priceFrom: 267,
    priceInr: 267,
    tags: ["Budget", "Partly verified", "Deep discount off MRP", "Single nutrient"],
    rx: false,
    pack: "bottle-tab",
    colour: "#eda100",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/boldfit-vitamin-c-complex-1000mg-tablet-otc633746",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/ftbs3tnjvvbqywd92dym.jpg?dpr=3&format=auto&h=320&w=412",
  },
  {
    id: "carbamide-forte-amla-vitamin-c",
    supplement: "vitamin-c",
    brand: "Carbamide Forte",
    name: "Natural Vitamin C from Amla with Zinc",
    strength: "Vitamin C 1000 mg per serving from amla extract; zinc amount not stated",
    price: "₹599 / 120 tablets",
    priceFrom: 599,
    priceInr: 599,
    tags: ["Vegetarian", "Budget", "Zinc amount not stated", "Single nutrient"],
    rx: false,
    pack: "bottle-tab",
    colour: "#eda100",
    retailer: "Carbamide Forte",
    url: "https://mycf.in/products/carbamide-forte-natural-vitamin-c-1000mg-amla-extract-with-zinc-for-immunity-skincare-120-veg-tablets",
    image: "https://mycf.in/cdn/shop/files/1_37.png?v=1782214409",
  },
  {
    id: "baidyanath-ashwagandha-churna",
    supplement: "ashwagandha",
    brand: "Baidyanath",
    name: "Ashwagandha Churna",
    strength: "1–2 teaspoons (3–6 g) as directed",
    price: "₹155 / 100 g",
    priceFrom: 155,
    priceInr: 155,
    tags: ["Herbal caveat"],
    rx: false,
    pack: "tub",
    colour: "#eda100",
    retailer: "Baidyanath",
    url: "https://www.baidyanath.com/products/ashwagandha-churna",
    image: "https://www.baidyanath.com/cdn/shop/files/Ashwagandha_Churna.jpg?v=1771969932&width=2048",
  },
  {
    id: "organic-india-ashwagandha",
    supplement: "ashwagandha",
    brand: "Organic India",
    name: "Ashwagandha Capsules",
    strength: "Whole ashwagandha root",
    price: "₹198 / 60 capsules",
    priceFrom: 198,
    priceInr: 198,
    tags: ["Vegetarian", "Budget", "Herbal caveat"],
    rx: false,
    pack: "bottle-cap",
    colour: "#eb6834",
    retailer: "Organic India",
    url: "https://organicindia.com/products/ashwagandha-capsules",
    image: "https://organicindia.com/cdn/shop/files/AshwagandhaFront.png?v=1765865177",
  },
  {
    id: "wellbeing-melts-ashwagandha",
    supplement: "ashwagandha",
    brand: "Wellbeing Nutrition",
    name: "Melts Pure Ashwagandha (KSM-66)",
    strength: "KSM-66 standardised to 5% withanolides",
    price: "₹649 / 30 strips",
    priceFrom: 649,
    priceInr: 649,
    tags: ["Vegan", "High performance", "Herbal caveat"],
    rx: false,
    pack: "strip",
    colour: "#008300",
    retailer: "Wellbeing Nutrition",
    url: "https://wellbeingnutrition.com/products/melts-ashwagandha",
    image: "https://wellbeingnutrition.com/cdn/shop/files/IMG1_72d7dce2-9a97-4a3e-8161-1ff360bcee0a.jpg?v=1759310852",
  },
  {
    id: "himalaya-turmeric-gummies",
    supplement: "curcumin",
    brand: "Himalaya",
    name: "Healthy Turmeric Gummies",
    strength: "Turmeric rhizome extract containing 95% curcuminoids",
    price: "₹378 / 30 gummies",
    priceFrom: 378,
    priceInr: 378,
    tags: ["Vegan", "Value", "Curcuminoid mg not stated", "Herbal caveat"],
    rx: false,
    pack: "jar",
    colour: "#eda100",
    retailer: "Himalaya",
    url: "https://himalayawellness.in/products/himalaya-healthy-turmeric-gummies",
    image: "https://himalayawellness.in/cdn/shop/files/TURMERIC-GUMMIES-30s-FRONT-INDIA-13463-F39-FV-Large.jpg?v=1716176249",
  },
  {
    id: "carbamide-forte-marine-collagen",
    supplement: "collagen",
    brand: "Carbamide Forte",
    name: "Marine Collagen + Hyaluronic Acid Tablets",
    strength: "Marine collagen 3000 mg per serving",
    price: "₹699 / 90 tablets",
    priceFrom: 699,
    priceInr: 699,
    tags: ["Budget"],
    rx: false,
    pack: "bottle-tab",
    colour: "#e87ba4",
    retailer: "Carbamide Forte",
    url: "https://mycf.in/products/carbamide-forte-hydrolyzed-marine-collagen-peptides-3000mg-with-biotin-hyaluronic-acid-collagen-type-1-powder-90-tablets",
    image: "https://mycf.in/cdn/shop/files/B09C8JXNCV.MAIN.jpg?v=1767787784",
  },
  {
    id: "hkvitals-skin-radiance-collagen",
    supplement: "collagen",
    brand: "HK Vitals",
    name: "Skin Radiance Marine Collagen",
    strength: "Marine collagen peptides 5 g and vitamin C 40 mg per serving",
    price: "₹519 / 100 g",
    priceFrom: 519,
    priceInr: 519,
    tags: ["Price varies by flavour"],
    rx: false,
    pack: "tub",
    colour: "#e87ba4",
    retailer: "HK Vitals",
    url: "https://www.hkvitals.com/sv/hk-vitals-skin-radiance-collagen/SP-99764",
    image: "https://img6.hkrtcdn.com/45530/prd_4552965-HK-Vitals-Skin-Radiance-Collagen-Marine-Collagen-200-g-Orange_o.jpg",
  },
  {
    id: "oziva-plant-collagen-builder",
    supplement: "collagen",
    brand: "OZiva",
    name: "Plant Based Collagen Builder",
    strength: "Plant-based collagen builder blend, Vitamin C, Biotin",
    price: "₹929 / 200 g",
    priceFrom: 929,
    priceInr: 929,
    tags: ["Vegetarian", "High performance", "Partly verified"],
    rx: false,
    pack: "tub",
    colour: "#e87ba4",
    retailer: "OZiva",
    url: "https://www.oziva.in/products/plant-based-collagen",
    image: "https://cdn.shopify.com/s/files/1/2393/2199/files/Collagen_classic_gluta_combos2_800X800.jpg",
  },
  {
    id: "wellbeing-beauty-collagen",
    supplement: "collagen",
    brand: "Wellbeing Nutrition",
    name: "Beauty Collagen",
    strength: "Nano-hydrolysed peptides stated as under 1000 Daltons",
    price: "₹1,939 / 250 g",
    priceFrom: 1939,
    priceInr: 1939,
    tags: ["Third-party tested"],
    rx: false,
    pack: "tub",
    colour: "#e87ba4",
    retailer: "Wellbeing Nutrition",
    url: "https://wellbeingnutrition.com/products/beauty-collagen-strawberry-watermelon-flavor",
    image: "https://wellbeingnutrition.com/cdn/shop/files/BEAUTY_SW_P-1.jpg?v=1754641430",
  },
  {
    id: "centrum-men-multivitamin",
    supplement: "multivitamin",
    brand: "Centrum",
    name: "Multivitamin for Men (23 Vitamins & Minerals)",
    strength: "Per tablet: A 800 mcg; C 80 mg; D2 600 IU; E 5 mg; Calcium 250 mg; Zinc 11 mg; Iron 3.7 mg; Grape Seed 100 mg",
    price: "₹437 / 30 tablets",
    priceFrom: 437,
    priceInr: 437,
    tags: ["Vegetarian", "High performance"],
    rx: false,
    pack: "bottle-tab",
    colour: "#2a78d6",
    retailer: "Tata 1mg",
    url: "https://www.1mg.com/otc/centrum-men-vegetarian-tablets-for-muscles-heart-immunity-world-s-no.1-multivitamin-nutrition-formula-otc772915",
    image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/52f577535f5d4fedbff7d95a54ea69a5.jpg",
  },
  {
    id: "hkvitals-multivitamin-50plus",
    supplement: "multivitamin",
    brand: "HK Vitals",
    name: "Multivitamin Adults 50+",
    price: "₹329 / 30 tablets",
    priceFrom: 329,
    priceInr: 329,
    tags: ["Partly verified"],
    rx: false,
    pack: "bottle-tab",
    colour: "#008300",
    retailer: "HK Vitals",
    url: "https://www.hkvitals.com/sv/hk-vitals-multivitamin-adults-50plus/SP-135855",
    image: "https://img2.hkrtcdn.com/39876/prd_3987531-HK-Vitals-Multivitamin-Adults-50-Unflavoured-30-tablets_o.jpg",
  },
  {
    id: "himalayan-organics-cal-mag-zinc",
    supplement: "multivitamin",
    brand: "Himalayan Organics",
    name: "Calcium Magnesium Zinc D3, B12 & K2",
    strength: "Calcium, Magnesium, Zinc",
    price: "₹524 / 60 tablets",
    priceFrom: 524,
    priceInr: 524,
    tags: ["Vegetarian", "Value", "Partly verified"],
    rx: false,
    pack: "bottle-tab",
    colour: "#e34948",
    retailer: "Nutrabay",
    url: "https://nutrabay.com/product/himalayan-organics-calcium-magnesium-zinc-vitamin-d3-b12/?pId=1662646&vId=1551602",
    image: "https://cdn2.nutrabay.com/uploads/product/featured_image/product-1180-featured_image-Vlado's_Himalayan_Organics_Calcium_Magnesium_Zinc_D3_B12__K2.jpg",
  },
];

/**
 * CAN THIS CITY SELL IT?
 *
 * Two ways to be un-sellable and they are not the same absence, which is why
 * a screen must be able to tell them apart:
 *
 *   NO TILL PRICE — the review recorded a range or no stock, so there is no
 *   single number to charge. Three products. Nothing to do but say so.
 *
 *   PRESCRIPTION ONLY — there IS a price and the product is real, and a shop
 *   that put it in a basket beside a tub of whey would be selling a licensed
 *   drug on a fitness page. Two products. They keep their card, their evidence
 *   and their price, and their button goes to the prescriptions hub instead of
 *   to a checkout.
 *
 * Stated as a function rather than as a `sellable: true` column because a flag
 * in the data can be edited by whoever adds the next row, and this cannot.
 */
export const sellable = (p: Product): boolean => typeof p.priceInr === 'number' && !p.rx;

/** Every product for one supplement, cheapest-known first, prescription last.
 *  A product with no readable price sorts to the end rather than to zero. */
export function productsFor(supplement: string): Product[] {
  return PRODUCTS.filter((p) => p.supplement === supplement).sort(
    (a, b) =>
      Number(a.rx) - Number(b.rx) ||
      (a.priceFrom ?? Number.MAX_SAFE_INTEGER) - (b.priceFrom ?? Number.MAX_SAFE_INTEGER),
  );
}

/** The supplement ids the shelf can actually sell something for. Three entries
 *  in the knowledge base — folate, L-theanine and standalone K2 — have no
 *  product row, and the store says "nothing verified in India" rather than
 *  inventing one. */
export const STOCKED: string[] = SUPPLEMENTS.map((s) => s.id).filter((id) =>
  PRODUCTS.some((p) => p.supplement === id),
);

/** The review's shelves, in the order a person shops them rather than the
 *  order the evidence was written in. */
export const AISLES: Array<{ id: string; title: string; blurb: string; supplements: string[] }> = [
  { id: 'india', title: 'The Indian shortlist', blurb: 'The four the base rates in this country actually argue for.',
    supplements: ['vitamin-d3', 'vitamin-b12', 'omega-3', 'psyllium'] },
  { id: 'training', title: 'Training and protein', blurb: 'The two with the most replicated evidence in sport.',
    supplements: ['creatine', 'protein'] },
  { id: 'heart', title: 'Heart and cholesterol', blurb: 'Psyllium is the best evidence-to-cost ratio on the whole list.',
    supplements: ['psyllium', 'omega-3', 'magnesium', 'coq10'] },
  { id: 'sleep', title: 'Sleep and stress', blurb: 'Small, real effects — and one product dosed above its own optimum.',
    supplements: ['melatonin', 'magnesium', 'ashwagandha'] },
  { id: 'clinical', title: 'Test before you buy', blurb: 'A blood test belongs before the first dose of these, not after.',
    supplements: ['iron', 'vitamin-d3', 'vitamin-b12'] },
  { id: 'popular', title: 'Popular, and worth reading first', blurb: 'India buys these in volume. The evidence review does not.',
    supplements: ['multivitamin', 'collagen', 'curcumin', 'vitamin-c', 'zinc'] },
];
