/**
 * ── SEED THE CITY'S GROCERY CATALOGUE ───────────────────────────────────────
 *
 *     DATABASE_URL="<the Postgres service's DATABASE_PUBLIC_URL>" \
 *       npx ts-node prisma/seed-grocery-catalogue.ts
 *
 * Reads prisma/data/grocery-catalogue.json — which is GENERATED by
 * scripts/gen-grocery-catalogue.mjs and must not be hand-edited — and upserts
 * every row into GroceryProduct.
 *
 * IDEMPOTENT BY (sourceKey, sourceRef), which is the unique key on the table.
 * Re-running after a refresh of the extracts updates the rows that changed and
 * leaves the rest alone; it does NOT delete rows that have left the source,
 * because a shopkeeper's menu line may already point at one, and unpicking
 * somebody's shelf item is not a seed script's decision to make. Retiring a
 * product is a deliberate act with a SET NULL behind it.
 *
 * RAW SQL RATHER THAN THE PRISMA CLIENT, for the reason recorded at the
 * `catalogue` accessor in local-services.service.ts: the client in this working
 * tree predates the table, because `prisma generate` has to reach
 * binaries.prisma.sh. Raw SQL is parameterised and needs no generated types, so
 * this script runs correctly before the first regenerate as well as after it.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { PrismaClient } from '@prisma/client';

interface Row {
  aisle: string;
  brand: string | null;
  name: string;
  pack: string | null;
  gtin: string | null;
  imageUrl: string | null;
  loose: boolean;
  sourceKey: string;
  sourceRef: string;
  searchText: string;
}

async function main() {
  const file = join(__dirname, 'data', 'grocery-catalogue.json');
  const rows = JSON.parse(readFileSync(file, 'utf8')) as Row[];
  if (!Array.isArray(rows) || rows.length === 0) throw new Error('empty catalogue file');

  const prisma = new PrismaClient();
  let written = 0;
  try {
    for (const r of rows) {
      /* A row with no source cannot be written. The column is NOT NULL, so the
         database would refuse it anyway — this refuses it here, with a sentence
         somebody can read, because the invariant is the point of the table. */
      if (!r.sourceKey || !r.sourceRef) throw new Error(`row without a source: ${r.name}`);
      await prisma.$executeRaw`
        INSERT INTO "GroceryProduct"
          ("id", "aisle", "brand", "name", "pack", "gtin", "imageUrl", "loose",
           "sourceKey", "sourceRef", "searchText", "createdAt", "updatedAt")
        VALUES
          (${randomUUID()}, ${r.aisle}, ${r.brand}, ${r.name}, ${r.pack}, ${r.gtin},
           ${r.imageUrl}, ${r.loose}, ${r.sourceKey}, ${r.sourceRef}, ${r.searchText},
           NOW(), NOW())
        ON CONFLICT ("sourceKey", "sourceRef") DO UPDATE SET
          "aisle" = EXCLUDED."aisle",
          "brand" = EXCLUDED."brand",
          "name" = EXCLUDED."name",
          "pack" = EXCLUDED."pack",
          "gtin" = EXCLUDED."gtin",
          "imageUrl" = EXCLUDED."imageUrl",
          "loose" = EXCLUDED."loose",
          "searchText" = EXCLUDED."searchText",
          "updatedAt" = NOW()
      `;
      written++;
    }
  } finally {
    await prisma.$disconnect();
  }
  console.log(`grocery catalogue: ${written} products upserted`);
}

main().catch((e) => { console.error(e); process.exit(1); });
