import { existsSync, readdirSync } from 'fs';
import { join } from 'path';
import { RECIPE_IMAGE_NOS, recipeImageUrl } from './recipe-image-set';

/**
 * The list and the files agree.
 *
 * recipeImageUrl returns a path only for numbers in RECIPE_IMAGE_NOS, so the
 * app never emits a broken tile — but that guarantee is only as good as the
 * list, and the list is auto-generated by hand. Add photos and forget to
 * regenerate and recipes that HAVE a picture show a placeholder. Regenerate
 * against a directory that has lost a file and every tile in that range 404s.
 *
 * Both directions are checked because they fail differently and only one of
 * them is visible: a missing claim is a dull tile nobody reports, a false claim
 * is a broken image on a page somebody screenshots.
 */
const IMAGES = join(__dirname, '..', '..', '..', 'together-city-react', 'public', 'recipe-images');

describe('the recipe image set', () => {
  // The web app is a sibling package; skip rather than fail if only the API
  // has been checked out, so this cannot become the reason a build is red.
  const present = existsSync(IMAGES);
  const onDisk = present
    ? new Set(readdirSync(IMAGES).filter((f) => f.endsWith('.webp')).map((f) => Number(f.slice(0, -5))))
    : new Set<number>();

  (present ? it : it.skip)('claims every photo that exists', () => {
    const unclaimed = [...onDisk].filter((n) => !RECIPE_IMAGE_NOS.has(n)).sort((a, b) => a - b);
    expect({ count: unclaimed.length, examples: unclaimed.slice(0, 10) })
      .toEqual({ count: 0, examples: [] });
  });

  (present ? it : it.skip)('claims no photo that does not', () => {
    const missing = [...RECIPE_IMAGE_NOS].filter((n) => !onDisk.has(n)).sort((a, b) => a - b);
    expect({ count: missing.length, examples: missing.slice(0, 10) })
      .toEqual({ count: 0, examples: [] });
  });

  it('answers with a path only for a number it has', () => {
    const known = [...RECIPE_IMAGE_NOS][0];
    expect(recipeImageUrl(known)).toBe(`/recipe-images/${known}.webp`);
    expect(recipeImageUrl(999999)).toBeNull();
    expect(recipeImageUrl(null)).toBeNull();
    expect(recipeImageUrl(undefined)).toBeNull();
  });
});
