/**
 * WHAT EVERY NUMBER MEANS (owner, 16 Sep: "investors should understand
 * exactly what every number means"). One sentence each, shown in the (i)
 * beside the number and in the Definitions section. The rules themselves live
 * in together-city-chat/src/insights/insights.config.ts; docs/insights.md
 * says the same at length.
 */
export const DEFINITIONS = {
  members: 'Accounts that exist and have not been closed, at the end of today. The change compares with the same count at the start of the window.',
  newMembers: 'Accounts created in the window, whether or not they were closed later.',
  stillMembers: 'Of the accounts created in the window, those not closed since.',
  activeToday: 'Distinct members who used the signed-in app today (India time), or created anything in one of the eight systems today.',
  activeWeek: 'Distinct members active on any of the last 7 days, as defined for "Active today".',
  activeMonth: 'Distinct members active on any of the last 30 days, as defined for "Active today".',
  growthRate: 'Change in City members over the window, as a percentage of the members at its start.',
  d7: 'Of members old enough to have had it, the share active again 7 to 13 days after the day they joined.',
  d1: 'Of members at least 2 days old, the share active again the day after they joined.',
  d14: 'Of members old enough to have had it, the share active again 14 to 20 days after joining.',
  d30: 'Of members old enough to have had it, the share active again 30 to 36 days after joining.',
  session: 'Average time the app was on screen, per member per active day. The app sends a beat every 30 seconds while it is visible and signed in; each beat counts at most a minute and a day at most 24 hours.',
  depth: 'For members active in the window: how many of the eight systems (City Assistant, Hair & Skin, Fitness, Nutrition, Medical Records, Find Love, Astrology, Pets) each one used.',
  aiUsers: 'Distinct members who sent the City Assistant at least one message in the window.',
  aiCost: 'Rupees spent on AI models in the window: the tokens of every call × the rate set for its model. If any model used has no rate, no cost is shown rather than a low one.',
  aiCostPerUser: 'AI cost in the window divided by the members who talked to the City Assistant.',
  aiMonthly: 'AI cost in the window, per day, × 30 — the pace of this window, not a forecast.',
  aiLatency: 'Time from sending a call to an AI model to its answer, successful calls only: the median and the slowest 5%.',
  aiFailures: 'Calls to an AI model that ended in an error — a timeout, a rate limit, an overload, a server error — as a share of all calls. The member gets the app’s own fallback answer when this happens.',
  paying: 'Members paying Together City real money. None yet: no payment partner is live.',
  growth: 'City members at the end of each day. Marks are real milestones — the first member, member 10, 25, 50, 100 …',
  activation: 'Of members who joined in the window, the share who used at least two of the eight systems within their first seven days. The rule can be changed in one place.',
  retained: 'Activated members who joined at least 14 days ago and were active in the last 7 days.',
  stage_visitors: 'Browsers that opened togethercity.app for the first time in the window. Bots and link previews are not counted.',
  stage_signups: 'Accounts created in the window.',
  stage_members: 'Of those, accounts not closed since.',
  stage_activated: 'Of those, members who used at least two systems in their first seven days.',
  stage_weekly: 'Of those, members active in the last 7 days.',
  stage_retained: 'Of those, members who joined at least 14 days ago.',
  stage_paying: 'Of those, members paying real money. Not yet possible: no payment partner is live.',
  systemUsers: 'Distinct members who used the system in the window — by opening it signed in, or by creating a record in it.',
  interactions: 'Records members created in the system in the window: assistant messages, analyses and orders, workouts, meal plans and journal entries, medical records and prescriptions, Find Love actions, astrology questions and readings, pets and pet photos.',
  activeDays: 'Average number of distinct days each active member was active in the window.',
  aiPerMember: 'Messages members sent the City Assistant, per member who sent any.',
  messages: 'Person-to-person chat messages sent in the window. Their content is never read here.',
  returning: 'Members active in the window who had also been active on some earlier day.',
  conversations: 'A member talking to the City Assistant in one room on one day counts as one conversation.',
  aiMessages: 'Messages members sent the City Assistant in the window.',
  avgConversation: 'Member messages per conversation.',
  continuation: 'Share of conversations in which the member wrote more than once.',
  aiReturning: 'Members who talked to the City Assistant on more than one day in the window.',
  aiCalls: 'Calls the server made to an AI model, from the per-call ledger, when that ledger is recording.',
  tokens: 'Tokens sent to and received from AI models, from the per-call ledger.',
  mrr: 'Monthly recurring revenue: real money from active subscriptions. Not yet monetised.',
  arr: 'MRR × 12. Not yet monetised.',
  conversion: 'Share of members who moved from free to paid. Not yet monetised.',
  arpu: 'Revenue per member. Not yet monetised.',
  cac: 'Acquisition spend per new member. Spend is not recorded here.',
  ltv: 'Expected revenue per member over their life. Needs revenue and churn.',
  margin: 'Revenue minus the cost of serving it (AI, hosting), as a share of revenue.',
  age: 'From the date of birth members gave in their profile, in bands. Members under 18 cannot join.',
  uptime: 'How long this server process has been running without restarting.',
  uptimeDeploys: 'Share of the window (since uptime started being recorded) when at least one API server was running. Each server writes a beat every minute; a gap longer than that is downtime, whether a crash, a deploy or the platform.',
  deploys: 'Distinct versions of the API started in the window, and how many times a server started in all (a restart without a new version counts only in the second).',
  crashFree: 'Share of app openings in the window that ended without a crash — a screen that fell over or an uncaught error. Counted on the web and inside the phone apps; a stale page after a deploy that reloads itself is not a crash.',
  success: 'Share of API requests in the last 24 hours that did not end in a server error (5xx).',
  latency: 'Time the server took to answer API requests in the last 24 hours: the median and the slowest 5%.',
  failed: 'API requests in the last 24 hours that ended in a server error.',
  database: 'Whether the database answered a simple question just now, and how long it took.',
} as const;
