import type { BeautyProduct } from './beauty-engine';

/**
 * The shelf — 62 real products sold in India, with the price, the ingredients
 * and the page they can be bought from.
 *
 * WHAT THIS REPLACED. Thirteen products under one invented house brand,
 * "Together Beauty Labs", written to exercise the recommender. They did that
 * job and they could not do the next one: a citizen who is told to use a
 * Ceramide Barrier Cream cannot go and buy a Ceramide Barrier Cream. Every row
 * here is a product with a brand, a real price in rupees, and a link to where
 * it is sold.
 *
 * IT IS GENERATED FROM THE OWNER'S DATA SHEET, AND EDITED BY HAND AFTERWARDS IS
 * A MISTAKE. The sheet carries brand, name, price, tier, skin/hair type, key
 * ingredients, benefits, a photograph and a product page. Five fields the
 * ENGINE needs are not in it and are derived here — `usage`, `suitableSkin`,
 * `profileKeys`, `tags` and the display `category` — so the next sheet should
 * be re-run through the same derivation rather than diffed against this file.
 *
 * THE FOUR DERIVATIONS, BECAUSE THEY ARE JUDGEMENTS AND NOT FACTS:
 *
 *   `usage` comes from the category, then two overrides: a retinoid is Night
 *   whatever else it is, and vitamin C is Morning, because that is where its
 *   antioxidant protection has something to do. Shampoo, conditioner and hair
 *   oil are Weekly — they are wash-day items, and the routine's weekly band is
 *   named for both.
 *
 *   `suitableSkin` gates matching HARD: a product whose list excludes you is
 *   never recommended, at any score. So only FACE products are gated at all —
 *   a shampoo that suited people with oily FACES would be a bug wearing a data
 *   field — "all skin types" anywhere in the sheet's own wording means `all`,
 *   ranges like "dry to normal" expand, and three of the four base types is
 *   treated as universal, because at that point the list is excluding one type
 *   by accident rather than on purpose.
 *
 *   `profileKeys` are the assessment reading keys this product answers, matched
 *   on ingredients and benefits, then filtered by group: a face product cannot
 *   claim `scalp`, a hair product cannot claim `acne`. Body products are
 *   allowed only hydration, texture and redness. Where nothing matched, the
 *   category supplies one key rather than leaving the product unmatchable —
 *   a product with no keys can never be recommended to anybody, which is a
 *   silent way to delete it.
 *
 *   `tags` are the biomarker refinement and only ever add to an existing
 *   profile match. Hair tags are refused to non-hair products (caffeine in a
 *   face cream was being read as hair density) and `spf` only to a sunscreen.
 *
 * THE PHOTOGRAPHS ARE HOTLINKED to the retailers' own CDNs, which is how the
 * sheet supplies them, and every row carries TWO — a primary and an alternate
 * from a different retailer. That is not belt and braces: a hotlinked image is
 * the one field here guaranteed to rot, and a shelf of broken frames reads as a
 * broken shop rather than a missing picture. The screens try the first, fall to
 * the second, and end at a category mark, which is a real answer rather than a
 * grey box with a torn corner in it.
 */
export const BEAUTY_PRODUCTS: BeautyProduct[] = [
  // ── Skincare ─────────────────────────────────────────────────────────────
  { id: 'bp_minimalist_salicylic_acid_lha_2_cleanser', name: 'Minimalist Salicylic Acid + LHA 2% Cleanser (100 ml)', brand: 'Minimalist', category: 'Cleanser', group: 'Skincare',
    priceInr: 284, tier: 'Budget', usage: 'Morning & Night',
    tags: [], profileKeys: ['acne', 'oil', 'texture'], suitableSkin: ['oily'],
    actives: ['Salicylic Acid', 'LHA (Capryloyl Salicylic Acid)', 'Zinc'], keyIngredient: 'Salicylic Acid',
    blurb: 'Gently exfoliates inside pores to reduce excess sebum, blackheads and breakouts without stripping the skin. Sulphate-free daily cleanser for acne-prone skin.',
    image: 'https://beminimalist.co/cdn/shop/files/SalicylicCleanserNew.jpg?v=1756796206',
    imageAlt: 'https://images-static.nykaa.com/media/catalog/product/3/9/394e9c5MINIM00000019_a.jpg',
    productUrl: 'https://beminimalist.co/products/salicylic-lha-2-cleanser' },
  { id: 'bp_cetaphil_gentle_skin_cleanser', name: 'Cetaphil Gentle Skin Cleanser (125 ml)', brand: 'Cetaphil', category: 'Cleanser', group: 'Skincare',
    priceInr: 459, tier: 'Budget', usage: 'Morning & Night',
    tags: ['barrier', 'hydration', 'brightening', 'soothing'], profileKeys: ['hydration', 'redness', 'pigmentation'], suitableSkin: ['dry', 'normal', 'sensitive'],
    actives: ['Niacinamide', 'Panthenol (Vitamin B5)', 'Glycerin'], keyIngredient: 'Niacinamide',
    blurb: 'Soap-free, non-irritating creamy cleanser that removes dirt and impurities while protecting the skin barrier. Dermatologist-recommended for dry and sensitive skin.',
    image: 'https://images-static.nykaa.com/media/catalog/product/4/f/4fdcde1NYCETA0000010_j1.jpg',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/1049039/x9z34V4KZ_-1049039_1.jpg',
    productUrl: 'https://www.nykaa.com/cetaphil-cleansing-lotion/p/22032' },
  { id: 'bp_cerave_foaming_cleanser_for_oily_skin', name: 'CeraVe Foaming Cleanser for Oily Skin (88 ml)', brand: 'CeraVe', category: 'Cleanser', group: 'Skincare',
    priceInr: 559, tier: 'Mid-range', usage: 'Morning & Night',
    tags: ['barrier', 'hydration', 'brightening'], profileKeys: ['oil', 'hydration', 'redness', 'pigmentation'], suitableSkin: ['combination', 'oily'],
    actives: ['Ceramides', 'Hyaluronic Acid', 'Niacinamide'], keyIngredient: 'Ceramides',
    blurb: 'Gel-based foaming cleanser that removes excess oil and impurities while maintaining the skin barrier with three essential ceramides. Non-comedogenic and fragrance-free.',
    image: 'https://images-static.nykaa.com/media/catalog/product/d/a/da25edbCERAV00000010_1.jpg',
    imageAlt: 'https://www.clinikally.com/cdn/shop/files/1_cc5f035a-0f00-4e4b-8c96-29a302454bbf.jpg?v=1766491485',
    productUrl: 'https://www.nykaa.com/cerave-foaming-cleanser-face-wash-for-oily-skin-with-hyaluronic-acid-ceramides-niacinamide/p/13169474' },
  { id: 'bp_forest_essentials_delicate_facial_cleanser_m', name: 'Forest Essentials Delicate Facial Cleanser Mashobra Honey, Lemon & Rosewater (130 ml)', brand: 'Forest Essentials', category: 'Cleanser', group: 'Skincare',
    priceInr: 1295, tier: 'Mid-range', usage: 'Morning & Night',
    tags: ['hydration'], profileKeys: ['hydration'], suitableSkin: ['all'],
    actives: ['Mashobra Honey', 'Lemon Peel', 'Rosewater'], keyIngredient: 'Mashobra Honey',
    blurb: 'Luxurious Ayurvedic soap-free cleanser that gently lifts away impurities while honey and rosewater keep skin soft, hydrated and glowing.',
    image: 'https://images-static.nykaa.com/media/catalog/product/a/0/a0cf873FORES00000046_1.jpg',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/1105616/YAuUG_yKLF-1105616_1.jpg',
    productUrl: 'https://www.nykaa.com/forest-essentials-delicate-facial-cleanser-mashobra-honey-lemon-rosewater-config/p/304705' },
  { id: 'bp_kiehl_s_calendula_deep_cleansing_foaming_fac', name: 'Kiehl\'s Calendula Deep Cleansing Foaming Face Wash (230 ml)', brand: 'Kiehl\'s', category: 'Cleanser', group: 'Skincare',
    priceInr: 3200, tier: 'Premium', usage: 'Morning & Night',
    tags: ['hydration', 'soothing'], profileKeys: ['oil', 'hydration', 'redness'], suitableSkin: ['all'],
    actives: ['Calendula Extract', 'Calendula Petals', 'Glycerin'], keyIngredient: 'Calendula Extract',
    blurb: 'Iconic soap-free foaming wash that deeply cleanses and refreshes while calendula soothes and balances normal-to-oily skin without over-drying.',
    image: 'https://images-static.nykaa.com/media/catalog/product/7/2/726a4db3605970630881_1.jpg',
    imageAlt: 'https://www.kiehls.com/dw/image/v2/AAFM_PRD/on/demandware.static/-/Sites-kiehls-master-catalog/default/dwec16edef/nextgen/skin-care/face-cleansers/calendula/calendula-deep-cleansing-foaming-face-wash/kiehls-face-cleanser-calendula-deep-cleansing-foaming-f',
    productUrl: 'https://www.nykaa.com/kiehl-s-calendula-deep-cleansing-foaming-face-wash/p/26486' },
  { id: 'bp_minimalist_vitamin_b5_10_moisturizer', name: 'Minimalist Vitamin B5 10% Moisturizer (50 g)', brand: 'Minimalist', category: 'Moisturiser', group: 'Skincare',
    priceInr: 349, tier: 'Budget', usage: 'Morning & Night',
    tags: ['barrier', 'hydration', 'soothing'], profileKeys: ['hydration', 'redness'], suitableSkin: ['dry', 'sensitive'],
    actives: ['Vitamin B5 (Panthenol) 10%', 'Hyaluronic Acid', 'Centella Asiatica'], keyIngredient: 'Vitamin B5 (Panthenol) 10%',
    blurb: 'Lightweight oil-free gel moisturizer that deeply hydrates, calms irritation and repairs a damaged skin barrier. Fragrance-free and non-comedogenic.',
    image: 'https://images-static.nykaa.com/media/catalog/product/3/9/394e9c5MINIM00000036_a.jpg',
    imageAlt: 'https://beminimalist.co/cdn/shop/products/B5Moisturizer1200-2-min.png?v=1756800645',
    productUrl: 'https://www.nykaa.com/minimalist-vitamin-b5-10percent-moisturizer/p/18876941' },
  { id: 'bp_plum_green_tea_oil_free_moisturizer', name: 'Plum Green Tea Oil-Free Moisturizer (50 ml)', brand: 'Plum', category: 'Moisturiser', group: 'Skincare',
    priceInr: 408, tier: 'Budget', usage: 'Morning & Night',
    tags: ['hydration', 'antioxidant'], profileKeys: ['acne', 'oil', 'hydration', 'texture'], suitableSkin: ['oily'],
    actives: ['Green Tea Extract', 'Glycolic Acid', 'Vitamin E'], keyIngredient: 'Green Tea Extract',
    blurb: 'Non-comedogenic gel moisturizer that hydrates without greasiness while green tea antioxidants help control oil and prevent breakouts.',
    image: 'https://plumgoodness.com/cdn/shop/files/Listing_1st_Tile_GTOFM_1001x1001_px_b3122998-de05-4161-9645-057264e3eaa2.webp?v=1782458593&width=1024',
    imageAlt: 'https://images-static.nykaa.com/media/catalog/product/f/d/fdd18dfPLUMX00000055_1.jpg',
    productUrl: 'https://plumgoodness.com/products/green-tea-oil-free-moisturizer-for-oily-skin' },
  { id: 'bp_cetaphil_moisturising_cream', name: 'Cetaphil Moisturising Cream (100 g)', brand: 'Cetaphil', category: 'Moisturiser', group: 'Skincare',
    priceInr: 899, tier: 'Mid-range', usage: 'Morning & Night',
    tags: ['barrier', 'hydration', 'soothing'], profileKeys: ['hydration', 'redness'], suitableSkin: ['dry', 'sensitive'],
    actives: ['Glycerin', 'Petrolatum', 'Sweet Almond Oil'], keyIngredient: 'Glycerin',
    blurb: 'Rich, non-greasy cream that provides intense, long-lasting hydration and restores the skin\'s moisture barrier. Fragrance-free and dermatologist-recommended for sensitive skin.',
    image: 'https://images-static.nykaa.com/media/catalog/product/9/e/9ed9f93NYCETA0000005_1.jpg',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/XIyXRvfrCH-1191539_1.jpg',
    productUrl: 'https://www.nykaa.com/cetaphil-moisturising-cream/p/392483' },
  { id: 'bp_neutrogena_hydro_boost_hyaluronic_acid_water', name: 'Neutrogena Hydro Boost Hyaluronic Acid Water Gel (50 g)', brand: 'Neutrogena', category: 'Moisturiser', group: 'Skincare',
    priceInr: 1190, tier: 'Mid-range', usage: 'Morning & Night',
    tags: ['hydration'], profileKeys: ['oil', 'hydration', 'texture'], suitableSkin: ['all'],
    actives: ['Hyaluronic Acid', 'Glycerin', 'Olive Extract'], keyIngredient: 'Hyaluronic Acid',
    blurb: 'Ultra-light water-gel that delivers up to 72 hours of hydration and locks in moisture without clogging pores. Absorbs instantly with a fresh, non-sticky finish.',
    image: 'https://images-static.nykaa.com/media/catalog/product/0/6/06a74df4891080614470_s1.jpg',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/Vr4UdKyqV-1103737_1.jpg',
    productUrl: 'https://www.nykaa.com/neutrogena-hydro-boost-water-gel/p/875156' },
  { id: 'bp_clinique_moisture_surge_100h_auto_replenishi', name: 'Clinique Moisture Surge 100H Auto-Replenishing Hydrator (30 ml)', brand: 'Clinique', category: 'Moisturiser', group: 'Skincare',
    priceInr: 2250, tier: 'Premium', usage: 'Morning & Night',
    tags: ['hydration', 'soothing'], profileKeys: ['hydration'], suitableSkin: ['all'],
    actives: ['Aloe Bio-Ferment', 'Hyaluronic Acid', 'Caffeine'], keyIngredient: 'Aloe Bio-Ferment',
    blurb: 'Oil-free gel-cream that delivers 100 hours of continuous hydration and helps skin create its own internal water source for a plump, dewy look. Allergy tested and fragrance-free.',
    image: 'https://images-static.nykaa.com/media/catalog/product/7/e/7e9c340CLINI00000002_n1.jpg',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/resize-w:540/wpWIOoM5-g-1067204_1.jpg',
    productUrl: 'https://www.nykaa.com/clinique-moisture-surge-100h-auto-replenishing-hydrator/p/1129289' },
  { id: 'bp_the_derma_co_2_salicylic_acid_face_serum', name: 'The Derma Co 2% Salicylic Acid Face Serum (30 ml)', brand: 'The Derma Co', category: 'Serum', group: 'Skincare',
    priceInr: 483, tier: 'Budget', usage: 'Morning & Night',
    tags: [], profileKeys: ['acne', 'oil', 'texture'], suitableSkin: ['oily'],
    actives: ['Salicylic Acid 2%', 'Zinc', 'Witch Hazel'], keyIngredient: 'Salicylic Acid 2%',
    blurb: 'Targets active acne, blackheads and acne marks by exfoliating within pores and controlling oil. Lightweight daily-use serum for breakout-prone skin.',
    image: 'https://images-static.nykaa.com/media/catalog/product/0/6/062d8aeTHEDE00000026_01.jpg',
    imageAlt: 'https://thedermaco.com/cdn/shop/files/2_PDP_516d5d09-bf60-4181-9611-34bbcb9c4e81.jpg?v=1782729928',
    productUrl: 'https://www.nykaa.com/the-derma-co-2-salicylic-acid-serum-for-acne-acne-marks/p/1172651' },
  { id: 'bp_minimalist_niacinamide_10_face_serum', name: 'Minimalist Niacinamide 10% Face Serum (30 ml)', brand: 'Minimalist', category: 'Serum', group: 'Skincare',
    priceInr: 569, tier: 'Mid-range', usage: 'Morning & Night',
    tags: ['brightening'], profileKeys: ['acne', 'oil', 'pigmentation', 'texture'], suitableSkin: ['combination', 'oily'],
    actives: ['Niacinamide 10%', 'Zinc PCA', 'Matmarine'], keyIngredient: 'Niacinamide 10%',
    blurb: 'Reduces blemishes, acne marks and enlarged pores while balancing sebum production for clearer, more even-toned skin. Fragrance-free and lightweight.',
    image: 'https://beminimalist.co/cdn/shop/files/Nia10New.png?v=1721398127',
    imageAlt: 'https://images-static.nykaa.com/media/catalog/product/3/9/394e9c5MINIM00000001_a.jpg',
    productUrl: 'https://beminimalist.co/products/niacinamide-10-with-matmarine' },
  { id: 'bp_the_ordinary_niacinamide_10_zinc_1', name: 'The Ordinary Niacinamide 10% + Zinc 1% (30 ml)', brand: 'The Ordinary', category: 'Serum', group: 'Skincare',
    priceInr: 600, tier: 'Mid-range', usage: 'Morning & Night',
    tags: ['brightening'], profileKeys: ['acne', 'oil', 'pigmentation', 'texture'], suitableSkin: ['combination', 'oily'],
    actives: ['Niacinamide 10%', 'Zinc PCA 1%'], keyIngredient: 'Niacinamide 10%',
    blurb: 'Cult-favourite high-strength serum that visibly reduces blemishes, congestion and shine while refining skin texture over time.',
    image: 'https://images-static.nykaa.com/media/catalog/product/8/8/88a48a1THECI00000026_1.jpg',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/1154593/ilW0Oe-6EW-1154593_1.jpg',
    productUrl: 'https://www.nykaa.com/the-ordinary-niacinamide-10percent-zinc-1percent/p/15707745' },
  { id: 'bp_plum_15_vitamin_c_face_serum_with_mandarin', name: 'Plum 15% Vitamin C Face Serum with Mandarin (30 ml)', brand: 'Plum', category: 'Serum', group: 'Skincare',
    priceInr: 790, tier: 'Mid-range', usage: 'Morning',
    tags: ['brightening', 'antioxidant'], profileKeys: ['pigmentation'], suitableSkin: ['all'],
    actives: ['15% Ethyl Ascorbic Acid (Vitamin C)', 'Mandarin Extract', 'Kakadu Plum'], keyIngredient: '15% Ethyl Ascorbic Acid (Vitamin C)',
    blurb: 'Brightens dull skin, fades dark spots and hyperpigmentation, and boosts glow with a stable, fast-absorbing form of vitamin C. Fragrance-free and vegan.',
    image: 'https://plumgoodness.com/cdn/shop/files/Listing_1st_Tile_Vit_C_15_Serum_30ml_1001x1001_px.webp?v=1776943410&width=1024',
    imageAlt: 'https://images-static.nykaa.com/media/catalog/product/b/0/b0b3422PLUMX00000068_1.jpg',
    productUrl: 'https://plumgoodness.com/products/vitamin-c-face-serum' },
  { id: 'bp_estee_lauder_advanced_night_repair_synchroni', name: 'Estée Lauder Advanced Night Repair Synchronized Multi-Recovery Complex Serum (20 ml)', brand: 'Estée Lauder', category: 'Serum', group: 'Skincare',
    priceInr: 4500, tier: 'Premium', usage: 'Night',
    tags: ['hydration', 'collagen'], profileKeys: ['hydration', 'wrinkles', 'texture'], suitableSkin: ['all'],
    actives: ['Tripeptide-32', 'Hyaluronic Acid', 'Bifida Ferment Lysate'], keyIngredient: 'Tripeptide-32',
    blurb: 'Legendary overnight repair serum that reduces the look of fine lines and wrinkles, boosts radiance and strengthens skin\'s natural renewal for firmer, smoother skin.',
    image: 'https://images-static.nykaa.com/media/catalog/product/3/1/31ae905887167485495_1x.jpg',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/1021661/eyYbpuXo8x-1021661_1.jpg',
    productUrl: 'https://www.nykaa.com/estee-lauder-advanced-night-repair-synchronized-multi-recovery-complex/p/833283' },
  { id: 'bp_minimalist_light_fluid_spf_50_pa_sunscreen', name: 'Minimalist Light Fluid SPF 50 PA++++ Sunscreen (50 ml)', brand: 'Minimalist', category: 'Sunscreen', group: 'Skincare',
    priceInr: 474, tier: 'Budget', usage: 'Morning',
    tags: ['antioxidant', 'spf'], profileKeys: ['oil', 'pigmentation'], suitableSkin: ['all'],
    actives: ['Hybrid UV Filters (broad spectrum)', 'Vitamin A (Retinyl Palmitate)', 'Vitamin E'], keyIngredient: 'Hybrid UV Filters (broad spectrum)',
    blurb: 'Ultra-light, no-white-cast fluid sunscreen with SPF 50 PA++++ broad-spectrum protection; water and sweat resistant with a non-greasy finish.',
    image: 'https://beminimalist.co/cdn/shop/files/Artboard_1_1.jpg?v=1783323907',
    imageAlt: 'https://images-static.nykaa.com/media/catalog/product/0/1/014ba2cMINIM00000164_1.jpg',
    productUrl: 'https://beminimalist.co/products/light-fluid-spf-50-sunscreen' },
  { id: 'bp_dot_key_vitamin_c_e_super_bright_sunscreen_s', name: 'Dot & Key Vitamin C + E Super Bright Sunscreen SPF 50+ PA++++ (50 g)', brand: 'Dot & Key', category: 'Sunscreen', group: 'Skincare',
    priceInr: 445, tier: 'Budget', usage: 'Morning',
    tags: ['brightening', 'antioxidant', 'spf'], profileKeys: ['pigmentation'], suitableSkin: ['normal'],
    actives: ['Vitamin C', 'Vitamin E', 'New-age UV filters'], keyIngredient: 'Vitamin C',
    blurb: 'Water-light fluid sunscreen that pairs SPF 50+ PA++++ protection with vitamins C and E to boost glow and fade dullness, leaving no white cast.',
    image: 'https://images-static.nykaa.com/media/catalog/product/2/5/252f4d6DOTKE00000213_n1.jpg',
    imageAlt: 'https://www.dotandkey.com/cdn/shop/files/VitaminCSunscreenListing1_24ade7b6-5667-43a8-8cbf-a750fae616a4.jpg?v=1784638633',
    productUrl: 'https://www.nykaa.com/dot-key-vitamin-c-e-super-bright-sunscreen-spf-50-pa/p/8380668' },
  { id: 'bp_cetaphil_sun_spf_50_light_gel', name: 'Cetaphil Sun SPF 50+ Light Gel (50 ml)', brand: 'Cetaphil', category: 'Sunscreen', group: 'Skincare',
    priceInr: 1299, tier: 'Mid-range', usage: 'Morning',
    tags: ['hydration', 'antioxidant', 'soothing', 'spf'], profileKeys: ['hydration', 'redness', 'pigmentation'], suitableSkin: ['dry', 'sensitive'],
    actives: ['Advanced UVA/UVB filters (Tinosorb)', 'Vitamin E', 'Glycerin'], keyIngredient: 'Advanced UVA/UVB filters (Tinosorb)',
    blurb: 'Gentle, water-resistant SPF 50+ gel formulated for sensitive skin; hydrates while providing high broad-spectrum sun protection without irritation.',
    image: 'https://images-static.nykaa.com/media/catalog/product/5/a/5a763ae7612076600645_1.jpg',
    imageAlt: 'https://www.clinikally.com/cdn/shop/products/Cetaphilsunspf50.jpg?v=1670247389',
    productUrl: 'https://www.nykaa.com/cetaphil-sun-spf-50-gel/p/930182' },
  { id: 'bp_la_roche_posay_anthelios_uvmune_400_invisibl', name: 'La Roche-Posay Anthelios UVMune 400 Invisible Fluid SPF 50+ (50 ml)', brand: 'La Roche-Posay', category: 'Sunscreen', group: 'Skincare',
    priceInr: 1399, tier: 'Mid-range', usage: 'Morning',
    tags: ['soothing', 'spf'], profileKeys: ['redness', 'pigmentation'], suitableSkin: ['all'],
    actives: ['Mexoryl 400 (ultra-long UVA filter)', 'Netlock technology', 'Thermal Spring Water'], keyIngredient: 'Mexoryl 400 (ultra-long UVA filter)',
    blurb: 'Dermatologist-favourite ultra-light fluid with breakthrough Mexoryl 400 filter protecting against the deepest UVA rays; invisible finish, ideal for sensitive skin.',
    image: 'https://www.clinikally.com/cdn/shop/files/5_12ed73cf-ba90-4af1-94bc-0f10c8bb6e9a.jpg?v=1771062870',
    imageAlt: 'https://images-static.nykaa.com/media/catalog/product/0/e/0e3730dLAROC00000002_r1.jpg',
    productUrl: 'https://www.clinikally.com/products/la-roche-posay-anthelios-uvmune-400-invisible-fluid-sunscreen-spf-50-pa' },
  { id: 'bp_kiehl_s_ultra_light_daily_uv_defense_spf_50', name: 'Kiehl\'s Ultra-Light Daily UV Defense SPF 50 PA++++ Sunscreen (60 ml)', brand: 'Kiehl\'s', category: 'Sunscreen', group: 'Skincare',
    priceInr: 5500, tier: 'Premium', usage: 'Morning',
    tags: ['antioxidant', 'spf'], profileKeys: ['oil', 'pigmentation'], suitableSkin: ['all'],
    actives: ['Broad-spectrum UVA/UVB filters', 'Vitamin E', 'Anti-pollution actives'], keyIngredient: 'Broad-spectrum UVA/UVB filters',
    blurb: 'Featherweight, non-greasy daily sunscreen offering SPF 50 PA++++ protection plus a defense against pollution-induced damage; leaves a fresh, invisible finish.',
    image: 'https://images-static.nykaa.com/media/catalog/product/b/b/bb4e187KIEHL00000035_1.jpg',
    imageAlt: 'https://www.kiehls.in/cdn/shop/files/bb4e1873605971613401_1.jpg?v=1774092304',
    productUrl: 'https://www.nykaa.com/kiehl-s-ultra-light-daily-uv-defense-spf-50-pa-with-anti-pollution/p/361232' },
  { id: 'bp_minimalist_polyhydroxy_acid_3_face_toner', name: 'Minimalist Polyhydroxy Acid (PHA) 3% Face Toner (150 ml)', brand: 'Minimalist', category: 'Toner', group: 'Skincare',
    priceInr: 379, tier: 'Budget', usage: 'Morning & Night',
    tags: ['hydration', 'soothing'], profileKeys: ['hydration', 'redness', 'texture'], suitableSkin: ['all'],
    actives: ['PHA (Gluconolactone) 3%', 'Prebiotic complex', 'Hyaluronic Acid'], keyIngredient: 'PHA (Gluconolactone) 3%',
    blurb: 'Alcohol-free exfoliating toner that gently tightens pores, rebalances the microbiome and hydrates — mild enough for sensitive skin.',
    image: 'https://beminimalist.co/cdn/shop/files/PHANew.jpg?v=1721379191',
    imageAlt: 'https://images-static.nykaa.com/media/catalog/product/a/1/a11fc14MINIM00000014_1.jpg',
    productUrl: 'https://beminimalist.co/products/pha-3-biotic-toner' },
  { id: 'bp_plum_green_tea_alcohol_free_pore_tightening', name: 'Plum Green Tea Alcohol-Free Pore Tightening Face Toner (200 ml)', brand: 'Plum', category: 'Toner', group: 'Skincare',
    priceInr: 369, tier: 'Budget', usage: 'Morning & Night',
    tags: ['hydration', 'antioxidant', 'soothing'], profileKeys: ['acne', 'oil', 'hydration', 'texture'], suitableSkin: ['oily'],
    actives: ['Green Tea Extract', 'Glycolic Acid', 'Aloe Juice'], keyIngredient: 'Green Tea Extract',
    blurb: 'Alcohol-free toner that tightens pores, controls oil and helps prevent breakouts while lightly hydrating the skin.',
    image: 'https://plumgoodness.com/cdn/shop/files/Listing_1st_Tile_GT_Toner_200ml_1001x1001_px_c93eaf1e-d084-4779-bce8-6a976cadbed7.webp?v=1782212495&width=1024',
    imageAlt: 'https://images-static.nykaa.com/media/catalog/product/b/0/b00850c737534800058_1.jpg',
    productUrl: 'https://plumgoodness.com/products/green-tea-alcohol-free-toner' },
  { id: 'bp_forest_essentials_facial_tonic_mist_pure_ros', name: 'Forest Essentials Facial Tonic Mist Pure Rosewater (130 ml)', brand: 'Forest Essentials', category: 'Toner', group: 'Skincare',
    priceInr: 1350, tier: 'Mid-range', usage: 'Morning & Night',
    tags: ['hydration'], profileKeys: ['hydration', 'texture'], suitableSkin: ['all'],
    actives: ['Steam-distilled Pure Rosewater (Kannauj roses)'], keyIngredient: 'Steam-distilled Pure Rosewater (Kannauj roses)',
    blurb: 'Luxurious Ayurvedic rosewater mist that hydrates, minimises the look of pores and refreshes skin any time of day; also preps skin for serums and moisturizers.',
    image: 'https://images-static.nykaa.com/media/catalog/product/5/8/58768b08904153391751_1u.jpg',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/_Q2LbLI4q5-1105613_1.jpg',
    productUrl: 'https://www.nykaa.com/forest-essentials-facial-tonic-mist-pure-rosewater-config/p/255101' },
  { id: 'bp_klairs_supple_preparation_unscented_toner', name: 'Klairs Supple Preparation Unscented Toner (180 ml)', brand: 'Klairs', category: 'Toner', group: 'Skincare',
    priceInr: 1430, tier: 'Mid-range', usage: 'Morning & Night',
    tags: ['barrier', 'hydration', 'soothing'], profileKeys: ['hydration', 'redness'], suitableSkin: ['dry', 'sensitive'],
    actives: ['Hyaluronic Acid', 'Centella Asiatica', 'Beta-Glucan'], keyIngredient: 'Hyaluronic Acid',
    blurb: 'Bestselling Korean hydrating toner that restores pH balance, deeply hydrates and calms reactive skin — completely fragrance-free.',
    image: 'https://images-static.nykaa.com/media/catalog/product/9/2/9213df48809115029119_1.jpg',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/dear-klairs/1023419/0/4k5xznb4qN-fn_BdCpAKR-AqSa-IqErO-1023419_1.jpg',
    productUrl: 'https://www.nykaa.com/klairs-supple-preparation-unscented-toner/p/906437' },
  { id: 'bp_pixi_glow_tonic_exfoliating_toner', name: 'PIXI Glow Tonic Exfoliating Toner (100 ml)', brand: 'PIXI', category: 'Toner', group: 'Skincare',
    priceInr: 1590, tier: 'Premium', usage: 'Morning & Night',
    tags: ['hydration', 'soothing'], profileKeys: ['hydration', 'redness', 'texture'], suitableSkin: ['all'],
    actives: ['Glycolic Acid 5%', 'Aloe Vera', 'Ginseng'], keyIngredient: 'Glycolic Acid 5%',
    blurb: 'Iconic exfoliating toner that sweeps away dead cells to reveal brighter, smoother, glowing skin while aloe soothes and hydrates.',
    image: 'https://images-static.nykaa.com/media/catalog/product/a/5/a5fe676885190821020b_b1.jpg',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/1140357/LCjyqhiYvis-1140357_1.jpg',
    productUrl: 'https://www.nykaa.com/pixi-glow-tonic/p/762184' },
  { id: 'bp_garnier_bright_complete_vitamin_c_serum_shee', name: 'Garnier Bright Complete Vitamin C Serum Sheet Mask (28 g)', brand: 'Garnier', category: 'Face mask', group: 'Skincare',
    priceInr: 115, tier: 'Budget', usage: 'Weekly',
    tags: ['hydration', 'brightening', 'antioxidant'], profileKeys: ['hydration', 'pigmentation'], suitableSkin: ['all'],
    actives: ['Vitamin C', 'Serum essence', 'Hydrating polymers'], keyIngredient: 'Vitamin C',
    blurb: 'Single-use serum-soaked sheet mask that instantly brightens, hydrates and reduces the look of spots in 15 minutes.',
    image: 'https://images-static.nykaa.com/media/catalog/product/5/1/51716e46970175253959_1.jpg',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/1002675/UAUDE9l6g-1002675_1.jpg',
    productUrl: 'https://www.nykaa.com/garnier-skin-naturals-hydra-bomb-serum-mask/p/306996' },
  { id: 'bp_plum_green_tea_clear_face_mask', name: 'Plum Green Tea Clear Face Mask (60 g)', brand: 'Plum', category: 'Face mask', group: 'Skincare',
    priceInr: 490, tier: 'Budget', usage: 'Weekly',
    tags: ['antioxidant'], profileKeys: ['acne', 'oil', 'texture'], suitableSkin: ['oily'],
    actives: ['Green Tea Extract', 'Kaolin Clay', 'Glycolic Acid'], keyIngredient: 'Green Tea Extract',
    blurb: 'Clay mask that unclogs pores, absorbs excess oil and helps clear and prevent acne, leaving skin fresh and mattified.',
    image: 'https://plumgoodness.com/cdn/shop/files/Listing_1st_Tile_GT_Face_Mask_60g_1001x1001_px.webp?v=1777978257&width=1024',
    imageAlt: 'https://images-static.nykaa.com/media/catalog/product/0/c/0cd5722737534800072z_1.jpg',
    productUrl: 'https://plumgoodness.com/products/green-tea-clear-face-mask' },
  { id: 'bp_mamaearth_ubtan_detan_face_pack_with_saffron', name: 'Mamaearth Ubtan Detan Face Pack with Saffron & Turmeric (200 g)', brand: 'Mamaearth', category: 'Face mask', group: 'Skincare',
    priceInr: 499, tier: 'Budget', usage: 'Weekly',
    tags: ['brightening'], profileKeys: ['pigmentation'], suitableSkin: ['all'],
    actives: ['Turmeric', 'Saffron', 'Fuller\'s Earth (Multani Mitti)'], keyIngredient: 'Turmeric',
    blurb: 'Ubtan-inspired face pack that visibly reduces tan, brightens and adds glow using traditional Indian ingredients; free of parabens and sulphates.',
    image: 'https://images-static.nykaa.com/media/catalog/product/f/e/fe7b5a8MAMAE00001154_x1.jpg',
    imageAlt: 'https://mamaearth.in/cdn/shop/files/1_222.jpg?v=1777975472',
    productUrl: 'https://www.nykaa.com/mamaearth-ubtan-detan-face-pack/p/19536959' },
  { id: 'bp_innisfree_super_volcanic_pore_clay_mask_2x', name: 'Innisfree Super Volcanic Pore Clay Mask 2X (100 ml)', brand: 'Innisfree', category: 'Face mask', group: 'Skincare',
    priceInr: 1100, tier: 'Mid-range', usage: 'Weekly',
    tags: [], profileKeys: ['acne', 'oil', 'texture'], suitableSkin: ['combination', 'oily'],
    actives: ['Jeju Super Volcanic Clusters', 'AHA', 'Walnut Shell Powder'], keyIngredient: 'Jeju Super Volcanic Clusters',
    blurb: 'K-beauty bestselling wash-off clay mask that deep-cleans pores, absorbs excess sebum, removes blackheads and gently exfoliates for smoother skin.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/a/9/a96a0408809560262871a_1.jpg',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/BHtyVIqtk-1013269_1.jpg',
    productUrl: 'https://www.nykaa.com/innisfree-pore-clearing-clay-mask-2x-with-volcanic-clusters/p/21530716' },
  { id: 'bp_kiehl_s_turmeric_cranberry_seed_energizing_r', name: 'Kiehl\'s Turmeric & Cranberry Seed Energizing Radiance Masque (100 ml)', brand: 'Kiehl\'s', category: 'Face mask', group: 'Skincare',
    priceInr: 4800, tier: 'Premium', usage: 'Weekly',
    tags: ['brightening'], profileKeys: ['pigmentation', 'texture'], suitableSkin: ['normal'],
    actives: ['Turmeric Extract', 'Cranberry Seeds', 'Cranberry Extract'], keyIngredient: 'Turmeric Extract',
    blurb: 'Energizing wash-off masque that brightens dull, tired skin and gently exfoliates with crushed cranberry seeds for an instant healthy-looking glow.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/b/b/bb4e1873605971354960_1.jpg',
    imageAlt: 'https://www.kiehls.in/cdn/shop/files/bb4e1873605971354960_1.jpg?v=1774092297&width=1024',
    productUrl: 'https://www.nykaa.com/kiehl-s-turmeric-cranberry-seed-energizing-radiance-masque/p/38817' },
  { id: 'bp_bioderma_sensibio_h2o_micellar_water', name: 'Bioderma Sensibio H2O Micellar Water (500 ml)', brand: 'Bioderma', category: 'Cleanser', group: 'Skincare',
    priceInr: 1275, tier: 'Mid-range', usage: 'Morning & Night',
    tags: ['barrier', 'soothing'], profileKeys: ['redness'], suitableSkin: ['all'],
    actives: ['Micellar technology', 'Cucumber Extract', 'Mannitol', 'Xylitol'], keyIngredient: 'Micellar technology',
    blurb: 'Iconic no-rinse micellar water that gently cleanses and removes makeup while respecting the skin barrier. Soothes reactive skin; fragrance- and alcohol-free.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/7/c/7c9d1b23401345935571_1.jpg',
    imageAlt: 'https://www.clinikally.com/cdn/shop/files/BiodermaSensibioH2OMicellarWaterMakeupRemover1.jpg?v=1765265499',
    productUrl: 'https://www.nykaa.com/bioderma-sensibio-h2o/p/9739' },
  { id: 'bp_avene_thermal_spring_water_face_mist', name: 'Avène Thermal Spring Water Face Mist (150 ml)', brand: 'Avène', category: 'Toner', group: 'Skincare',
    priceInr: 1450, tier: 'Mid-range', usage: 'Morning & Night',
    tags: ['soothing'], profileKeys: ['redness'], suitableSkin: ['all'],
    actives: ['Avène Thermal Spring Water (silicates, trace minerals)'], keyIngredient: 'Avène Thermal Spring Water (silicates, trace minerals)',
    blurb: 'Soothing anti-irritant thermal water mist bottled sterile at source. Calms redness, sunburn and post-procedure irritation while refreshing the skin.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/d/9/d919497N_3282779O35576_0.jpg',
    imageAlt: 'https://www.clinikally.com/cdn/shop/files/21_0fb0e29b-9787-42fa-9855-70f4cf46e6e2.jpg?v=1707383356',
    productUrl: 'https://www.nykaa.com/avene-thermal-spring-water/p/10777' },
  { id: 'bp_avene_skin_recovery_cream', name: 'Avène Skin Recovery Cream (50 ml)', brand: 'Avène', category: 'Moisturiser', group: 'Skincare',
    priceInr: 1369, tier: 'Mid-range', usage: 'Morning & Night',
    tags: ['barrier', 'hydration', 'soothing'], profileKeys: ['hydration', 'redness'], suitableSkin: ['all'],
    actives: ['Avène Thermal Spring Water', 'Squalane', 'Glycerin', 'Serine'], keyIngredient: 'Avène Thermal Spring Water',
    blurb: 'Minimalist-formula moisturizer for hypersensitive skin that soothes discomfort and restores the barrier. Free from preservatives, parabens, fragrance and alcohol.',
    image: 'https://images.apollo247.in/pub/media/catalog/product/A/V/AVE0053_1_2.jpg',
    imageAlt: 'https://media6.ppl-media.com/static/img/product/85773/avene-skin-recovery-cream-intolerant-pack-of-2_1_display_1408800851_dcf7f3e2.jpg',
    productUrl: 'https://www.apollopharmacy.in/otc/avene-skin-recovery-cream-50ml' },
  { id: 'bp_la_roche_posay_cicaplast_baume_b5_soothing_b', name: 'La Roche-Posay Cicaplast Baume B5+ Soothing Balm (40 ml)', brand: 'La Roche-Posay', category: 'Moisturiser', group: 'Skincare',
    priceInr: 1150, tier: 'Mid-range', usage: 'Morning & Night',
    tags: ['barrier', 'hydration', 'soothing'], profileKeys: ['hydration', 'redness'], suitableSkin: ['all'],
    actives: ['Panthenol 5%', 'Madecassoside', 'Shea Butter', 'Zinc + Manganese Gluconate'], keyIngredient: 'Panthenol 5%',
    blurb: 'Multi-purpose soothing balm that repairs and comforts dry, irritated and sensitised skin on face and body while supporting barrier recovery.',
    image: 'https://www.clinikally.com/cdn/shop/files/1_c6afd01a-6de0-43ab-88b7-168bb1a0be12.jpg?v=1771063797',
    imageAlt: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/0/e/0e3730dLAROC00000004_r1.jpg',
    productUrl: 'https://www.clinikally.com/products/la-roche-posay-cicaplast-baume-b5-soothing-balm' },
  { id: 'bp_minimalist_retinol_0_3_coenzyme_q10_face_ser', name: 'Minimalist Retinol 0.3% + Coenzyme Q10 Face Serum (10 ml)', brand: 'Minimalist', category: 'Serum', group: 'Skincare',
    priceInr: 249, tier: 'Budget', usage: 'Night',
    tags: ['hydration', 'collagen'], profileKeys: ['hydration', 'redness', 'wrinkles'], suitableSkin: ['all'],
    actives: ['Retinol 0.3%', 'Coenzyme Q10', 'Bakuchiol 1%', 'Squalane'], keyIngredient: 'Retinol 0.3%',
    blurb: 'Beginner-friendly retinol serum that boosts cell turnover to reduce fine lines and wrinkles. Q10, bakuchiol and squalane offset irritation and support elasticity.',
    image: 'https://beminimalist.co/cdn/shop/files/Reti3New.png?v=1721398129',
    imageAlt: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/3/9/394e9c5MINIM00000017_a.jpg',
    productUrl: 'https://beminimalist.co/products/retinol-0-3-q10' },
  { id: 'bp_the_derma_co_0_3_retinol_face_serum', name: 'The Derma Co 0.3% Retinol Face Serum (30 ml)', brand: 'The Derma Co', category: 'Serum', group: 'Skincare',
    priceInr: 671, tier: 'Mid-range', usage: 'Night',
    tags: ['brightening', 'antioxidant', 'collagen'], profileKeys: ['oil', 'pigmentation', 'wrinkles'], suitableSkin: ['all'],
    actives: ['Retinol 0.3%', 'Vitamin C (THD Ascorbate)', 'Physalis Angulata Extract'], keyIngredient: 'Retinol 0.3%',
    blurb: 'Night serum that accelerates healthy cell turnover to fade fine lines, wrinkles and dark spots, with a vitamin C derivative for added radiance.',
    image: 'https://thedermaco.com/cdn/shop/files/0.3__retinol_serum.jpg?v=1758286519',
    imageAlt: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/7/1/71646b5THEDE00000028.jpg',
    productUrl: 'https://thedermaco.com/products/0-3-retinol-serum' },
  { id: 'bp_olay_regenerist_retinol24_night_moisturiser', name: 'Olay Regenerist Retinol24 Night Moisturiser (50 g)', brand: 'Olay', category: 'Moisturiser', group: 'Skincare',
    priceInr: 1899, tier: 'Premium', usage: 'Night',
    tags: ['hydration', 'brightening', 'collagen'], profileKeys: ['hydration', 'redness', 'pigmentation', 'wrinkles', 'texture'], suitableSkin: ['all'],
    actives: ['Retinyl Propionate + Retinol complex', 'Niacinamide', 'Amino-Peptides'], keyIngredient: 'Retinyl Propionate + Retinol complex',
    blurb: 'Fragrance-free night cream delivering 24-hour hydration while its retinoid complex smooths fine lines, refines texture and brightens tone with minimal irritation.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/5/f/5fc040e4902430917964_o1.jpg',
    imageAlt: 'https://media6.ppl-media.com/tr:h-750,w-750,c-at_max,dpr-2,q-40/static/img/product/221169/olay-night-cream-regenerist-retinol-24-moisturiser-50-g_1_display_1748596578_8823ea45.jpg',
    productUrl: 'https://www.nykaa.com/olay-night-cream-regenerist-retinol-24-moisturiser-50gm/p/946344' },
  { id: 'bp_kiehl_s_micro_dose_anti_aging_retinol_serum', name: 'Kiehl\'s Micro-Dose Anti-Aging Retinol Serum with Ceramides & Peptide (30 ml)', brand: 'Kiehl\'s', category: 'Serum', group: 'Skincare',
    priceInr: 6500, tier: 'Premium', usage: 'Night',
    tags: ['barrier', 'collagen', 'soothing'], profileKeys: ['hydration', 'redness', 'pigmentation', 'wrinkles'], suitableSkin: ['all'],
    actives: ['Pure Retinol (micro-dose)', 'Ceramides', 'Peptide'], keyIngredient: 'Pure Retinol (micro-dose)',
    blurb: 'Daily micro-dose of pure retinol that firms skin, reduces wrinkles and evens tone with minimal redness or peeling; ceramides reinforce the barrier for nightly use.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/8/2/823d6613605972610010_1.jpg',
    imageAlt: 'https://www.kiehls.in/cdn/shop/files/823d6613605972610010_1.jpg?v=1774092296',
    productUrl: 'https://www.nykaa.com/kiehl-s-micro-dose-anti-aging-retinol-serum/p/20652396' },
  // ── Hair Care ─────────────────────────────────────────────────────────────
  { id: 'bp_head_shoulders_cool_menthol_anti_dandruff_sh', name: 'Head & Shoulders Cool Menthol Anti-Dandruff Shampoo (340 ml)', brand: 'Head & Shoulders', category: 'Shampoo', group: 'Hair Care',
    priceInr: 355, tier: 'Budget', usage: 'Weekly',
    tags: ['scalp'], profileKeys: ['scalp'], suitableSkin: ['all'],
    actives: ['Zinc Pyrithione (ZPT)', 'Menthol'], keyIngredient: 'Zinc Pyrithione (ZPT)',
    blurb: 'Clinically proven anti-dandruff formula that removes flakes and relieves scalp itch, with a cooling menthol sensation that refreshes oily, irritated scalps.',
    image: 'https://www.bbassets.com/media/uploads/p/s/212701_8-head-shoulders-anti-dandruff-shampoo-cool-menthol.jpg',
    imageAlt: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/2/5/251949f4902430774529_1.jpg',
    productUrl: 'https://www.bigbasket.com/pd/212701/head-shoulders-anti-dandruff-shampoo-cool-menthol-340-ml/' },
  { id: 'bp_indulekha_bringha_anti_hairfall_shampoo', name: 'Indulekha Bringha Anti-Hairfall Shampoo (340 ml)', brand: 'Indulekha', category: 'Shampoo', group: 'Hair Care',
    priceInr: 304, tier: 'Budget', usage: 'Weekly',
    tags: ['hair-density'], profileKeys: ['damage', 'density'], suitableSkin: ['all'],
    actives: ['Bringharaj extract', 'Amla', 'Shikakai'], keyIngredient: 'Bringharaj extract',
    blurb: 'Ayurvedic hair-fall control shampoo with bringharaj, amla and shikakai that strengthens roots and reduces breakage for both men and women.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/4/a/4ab9d018901030731006_j1.jpg',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/1013589/9ULAf_4Ih-1013589_1.jpg',
    productUrl: 'https://www.nykaa.com/indulekha-bringha-hair-anti-hairfall-shampoo/p/218594' },
  { id: 'bp_l_oreal_professionnel_serie_expert_absolut_r', name: 'L\'Oréal Professionnel Serie Expert Absolut Repair Shampoo (300 ml)', brand: 'L\'Oréal Professionnel', category: 'Shampoo', group: 'Hair Care',
    priceInr: 675, tier: 'Mid-range', usage: 'Weekly',
    tags: [], profileKeys: ['damage'], suitableSkin: ['all'],
    actives: ['Gold Quinoa', 'Wheat Protein', 'Omega-9'], keyIngredient: 'Gold Quinoa',
    blurb: 'Salon-grade resurfacing shampoo that cleanses while repairing dry, damaged fibre, leaving hair stronger, smoother and shinier.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/1/9/19b782bNYLOPROF00002_1.jpg',
    imageAlt: 'https://media6.ppl-media.com/tr:h-750,w-750,c-at_max,dpr-2,q-40/static/img/product/418772/l-oreal-professionnel-absolut-repair-lipidium-shampoo-300-ml-11-35-20-11_1_display_1775801316_a6a5b702.jpg',
    productUrl: 'https://www.nykaa.com/l-oreal-professionnel-absolut-repair-lipidium-shampoo/p/18402' },
  { id: 'bp_kerastase_specifique_divalent_balancing_sham', name: 'Kérastase Spécifique Divalent Balancing Shampoo (250 ml)', brand: 'Kérastase', category: 'Shampoo', group: 'Hair Care',
    priceInr: 2900, tier: 'Premium', usage: 'Weekly',
    tags: ['hydration', 'scalp'], profileKeys: ['scalp'], suitableSkin: ['all'],
    actives: ['Amino acids', 'Glycerin', 'Vitamin B6'], keyIngredient: 'Amino acids',
    blurb: 'Luxury balancing shampoo that regulates excess sebum at the roots while hydrating lengths, ideal for oily scalps with dry ends.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/2/0/20f29e3KERAS00000023_1.jpg',
    imageAlt: 'https://media6.ppl-media.com/tr:h-750,w-750,c-at_max,dpr-2,q-40/static/img/product/71687/kerastase-specifique-bain-divalent-shampoo-250-ml_1_display_1408797987_af81c0ff.jpg',
    productUrl: 'https://www.nykaa.com/kerastase-specifique-divalent-shampoo-for-oily-scalp-dry-ends/p/17272475' },
  { id: 'bp_dove_intense_repair_conditioner', name: 'Dove Intense Repair Conditioner (335 ml)', brand: 'Dove', category: 'Conditioner', group: 'Hair Care',
    priceInr: 389, tier: 'Budget', usage: 'Weekly',
    tags: [], profileKeys: ['damage'], suitableSkin: ['all'],
    actives: ['Keratin Actives', 'Fiber Actives'], keyIngredient: 'Keratin Actives',
    blurb: 'Daily conditioner with keratin actives that penetrates strands to smoothen and strengthen damaged hair, reducing breakage and roughness.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/e/5/e5e22b38901030810435_1.jpg',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/1013828/SEJFgGoY65-1013828_1.jpg',
    productUrl: 'https://www.nykaa.com/dove-damage-solutions-intense-repair-conditioner-10229/p/10229' },
  { id: 'bp_tresemme_keratin_smooth_anti_frizz_condition', name: 'TRESemmé Keratin Smooth Anti-Frizz Conditioner (335 ml)', brand: 'TRESemmé', category: 'Conditioner', group: 'Hair Care',
    priceInr: 350, tier: 'Budget', usage: 'Weekly',
    tags: [], profileKeys: ['damage'], suitableSkin: ['all'],
    actives: ['Keratin', 'Argan Oil'], keyIngredient: 'Keratin',
    blurb: 'Salon-inspired anti-frizz conditioner that infuses keratin and argan oil to tame frizz and leave hair sleek, smooth and manageable.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/e/d/edf5a118901030751677_1.jpg',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/cjqTGizBM7-1013634_1.jpg',
    productUrl: 'https://www.nykaa.com/tresemme-keratin-smoothwith-argan-oil-conditioner/p/208993' },
  { id: 'bp_wella_professionals_invigo_color_brilliance', name: 'Wella Professionals Invigo Color Brilliance Conditioner (200 ml)', brand: 'Wella Professionals', category: 'Conditioner', group: 'Hair Care',
    priceInr: 808, tier: 'Mid-range', usage: 'Weekly',
    tags: ['antioxidant'], profileKeys: ['damage'], suitableSkin: ['all'],
    actives: ['Lime Caviar extract', 'Copper encapsulation complex', 'Vitamin E'], keyIngredient: 'Lime Caviar extract',
    blurb: 'Professional color-care conditioner that locks in color vibrancy and adds silky shine to colour-treated fine-to-normal hair.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/1/d/1d899558005610639093_11n.jpg',
    imageAlt: 'https://media6.ppl-media.com/tr:h-750,w-750,c-at_max,dpr-2,q-40/static/img/product/361395/wella-professionals-invigo-color-brilliance-conditioner-for-coarse-hair-200-ml_1_display_1610972588_90c1f8ae.jpg',
    productUrl: 'https://www.nykaa.com/wella-professionals-invigo-color-brilliance-conditioner-for-fine-normal-hair/p/415926' },
  { id: 'bp_moroccanoil_hydrating_conditioner', name: 'Moroccanoil Hydrating Conditioner (250 ml)', brand: 'Moroccanoil', category: 'Conditioner', group: 'Hair Care',
    priceInr: 2860, tier: 'Premium', usage: 'Weekly',
    tags: ['hydration'], profileKeys: ['damage'], suitableSkin: ['all'],
    actives: ['Argan Oil', 'Vitamin A + E', 'Red Algae'], keyIngredient: 'Argan Oil',
    blurb: 'Argan oil-infused daily conditioner that deeply hydrates and detangles, restoring softness and shine to all hair types.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/a/7/a7f9cef290011521837_1711231.jpg',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/1085658/GQHcXJs43-7290011521837_1.jpg',
    productUrl: 'https://www.nykaa.com/moroccanoil-hydrating-conditioner/p/36194' },
  { id: 'bp_parachute_advansed_ayurvedic_coconut_hair_oi', name: 'Parachute Advansed Ayurvedic Coconut Hair Oil (300 ml)', brand: 'Parachute Advansed', category: 'Hair oil', group: 'Hair Care',
    priceInr: 264, tier: 'Budget', usage: 'Weekly',
    tags: ['scalp', 'hair-density'], profileKeys: ['damage', 'density', 'scalp'], suitableSkin: ['all'],
    actives: ['Coconut Oil', 'Neem', 'Bhringraj'], keyIngredient: 'Coconut Oil',
    blurb: 'Ayurvedic coconut oil blend that controls hair fall, reduces dandruff and repairs split ends with regular oiling.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/7/f/7f508aa8901088069816_1.jpg',
    imageAlt: 'https://www.bbassets.com/media/uploads/p/s/20004212_6-parachute-advansed-ayurvedic-coconut-hair-oil.jpg',
    productUrl: 'https://www.nykaa.com/parachute-advansed-ayurvedic-hair-oil/p/31375' },
  { id: 'bp_mamaearth_onion_hair_oil_with_redensyl', name: 'Mamaearth Onion Hair Oil with Redensyl (250 ml)', brand: 'Mamaearth', category: 'Hair oil', group: 'Hair Care',
    priceInr: 419, tier: 'Budget', usage: 'Weekly',
    tags: ['scalp', 'hair-density'], profileKeys: ['density', 'scalp'], suitableSkin: ['all'],
    actives: ['Onion Seed Oil', 'Redensyl', 'Bhringraj Extract', 'Amla Oil'], keyIngredient: 'Onion Seed Oil',
    blurb: 'Toxin-free onion oil with Redensyl that reduces hair fall, boosts new growth and balances the scalp while adding strength and shine.',
    image: 'https://mamaearth.in/cdn/shop/files/onion-oil-250ml__1_1_1.jpg?v=1777974267',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/awN6uaTkQc-1005472_1.jpg',
    productUrl: 'https://mamaearth.in/products/onion-hair-oil-for-hair-regrowth-hair-fall-control-with-redensyl-250ml' },
  { id: 'bp_kama_ayurveda_bringadi_intensive_hair_treatm', name: 'Kama Ayurveda Bringadi Intensive Hair Treatment Oil (100 ml)', brand: 'Kama Ayurveda', category: 'Hair oil', group: 'Hair Care',
    priceInr: 933, tier: 'Mid-range', usage: 'Weekly',
    tags: ['scalp', 'hair-density'], profileKeys: ['density', 'scalp'], suitableSkin: ['all'],
    actives: ['Bhringraj', 'Amla', 'Indigo', 'Sesame Oil'], keyIngredient: 'Bhringraj',
    blurb: 'Classic ayurvedic treatment oil that reduces hair fall and premature greying while deeply nourishing the scalp and conditioning hair.',
    image: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/990464/GuUvXbQtZv-990464_1.jpg',
    imageAlt: 'https://static.kamaayurveda.in/media/catalog/product/0/1/01_bringaras-scalp-_-hair-oil-50ml_1.png',
    productUrl: 'https://www.tirabeauty.com/product/kama-ayurveda-bringadi-intensive-hair-treatment-oil-100ml-g7iku4mwivwt' },
  { id: 'bp_livon_hair_serum_for_smooth_frizz_free_gloss', name: 'Livon Hair Serum for Smooth, Frizz-free & Glossy Hair (100 ml)', brand: 'Livon', category: 'Hair serum', group: 'Hair Care',
    priceInr: 273, tier: 'Budget', usage: 'Night',
    tags: ['antioxidant'], profileKeys: ['damage'], suitableSkin: ['all'],
    actives: ['Moroccan Argan Oil', 'Vitamin E', 'Silicones'], keyIngredient: 'Moroccan Argan Oil',
    blurb: 'India\'s best-selling leave-in serum that instantly detangles and smooths frizz, giving glossy, manageable hair after every wash.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/7/f/7f508aaL_8901088062398_1.jpg',
    imageAlt: 'https://www.bbassets.com/media/uploads/p/s/250998_11-livon-serum-hair-serum.jpg',
    productUrl: 'https://www.nykaa.com/livon-serum/p/28661' },
  { id: 'bp_l_oreal_paris_extraordinary_oil_hair_serum_w', name: 'L\'Oréal Paris Extraordinary Oil Hair Serum with UV Protection (100 ml)', brand: 'L\'Oréal Paris', category: 'Hair serum', group: 'Hair Care',
    priceInr: 620, tier: 'Mid-range', usage: 'Night',
    tags: [], profileKeys: ['damage'], suitableSkin: ['all'],
    actives: ['Blend of 6 flower oils', 'UV filters'], keyIngredient: 'Blend of 6 flower oils',
    blurb: 'Lightweight anti-frizz serum with floral oils that nourishes dry hair, adds mirror-like shine and shields strands from UV and heat damage.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/3/1/31462b56923700970449_v1.jpg',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/tU9PnaKJA-996542_1.jpg',
    productUrl: 'https://www.nykaa.com/l-oreal-paris-elseve-extraordinary-oil-serum/p/1133168' },
  { id: 'bp_olaplex_no_7_bonding_oil', name: 'Olaplex No. 7 Bonding Oil (30 ml)', brand: 'Olaplex', category: 'Hair serum', group: 'Hair Care',
    priceInr: 2950, tier: 'Premium', usage: 'Night',
    tags: [], profileKeys: ['damage'], suitableSkin: ['all'],
    actives: ['Bis-Aminopropyl Diglycol Dimaleate (bond builder)'], keyIngredient: 'Bis-Aminopropyl Diglycol Dimaleate (bond builder)',
    blurb: 'Highly concentrated bonding oil that repairs broken disulfide bonds, dramatically reduces frizz and protects against heat up to 232°C while boosting color vibrancy.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/6/3/638bdceOLAPL00000003_1.jpg',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/bWJs72lNCYC-1110558_1.jpg',
    productUrl: 'https://www.nykaa.com/olaplex-no-7-bonding-oil/p/16830894' },
  { id: 'bp_tresemme_keratin_smooth_deep_smoothing_hair', name: 'TRESemmé Keratin Smooth Deep Smoothing Hair Mask (300 ml)', brand: 'TRESemmé', category: 'Hair mask', group: 'Hair Care',
    priceInr: 450, tier: 'Budget', usage: 'Weekly',
    tags: [], profileKeys: ['damage'], suitableSkin: ['all'],
    actives: ['Keratin', 'Argan Oil'], keyIngredient: 'Keratin',
    blurb: 'Deep-conditioning weekly mask with keratin and argan oil that smooths frizz and leaves hair stronger and salon-smooth.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/4/a/4ab9d018710908693809_j1.jpg',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/vLHzg1Yty-1013642_1.jpg',
    productUrl: 'https://www.nykaa.com/tresemme-keratin-mask-300-ml/p/825658' },
  { id: 'bp_l_oreal_professionnel_vitamino_color_mask_wi', name: 'L\'Oréal Professionnel Vitamino Color Mask with Resveratrol (250 g)', brand: 'L\'Oréal Professionnel', category: 'Hair mask', group: 'Hair Care',
    priceInr: 999, tier: 'Mid-range', usage: 'Weekly',
    tags: ['antioxidant'], profileKeys: ['damage'], suitableSkin: ['all'],
    actives: ['Resveratrol', 'Vitamin E'], keyIngredient: 'Resveratrol',
    blurb: 'Professional color-protection mask with antioxidant resveratrol that preserves color radiance and adds shine to color-treated hair.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/1/9/19b782b8901526401611_1.jpg',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/LQsOkja1Z6-1102995_1.jpg',
    productUrl: 'https://www.nykaa.com/l-oreal-professionnel-vitamino-color-masque/p/10505' },
  { id: 'bp_moroccanoil_intense_hydrating_mask', name: 'Moroccanoil Intense Hydrating Mask (250 ml)', brand: 'Moroccanoil', category: 'Hair mask', group: 'Hair Care',
    priceInr: 3940, tier: 'Premium', usage: 'Weekly',
    tags: ['hydration'], profileKeys: ['damage', 'thickness'], suitableSkin: ['all'],
    actives: ['Argan Oil', 'Nourishing proteins'], keyIngredient: 'Argan Oil',
    blurb: 'Rich argan-oil deep conditioning mask that intensely hydrates dry, thick hair in 5-7 minutes, restoring elasticity, softness and shine.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/a/7/a7f9cef7290011521004_1711231.jpg',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/1085638/zHflz66qt--7290011521004_1.jpg',
    productUrl: 'https://www.nykaa.com/moroccanoil-intance-hydrating-mask-250ml/p/513013' },
  // ── Body Care ─────────────────────────────────────────────────────────────
  { id: 'bp_nivea_nourishing_lotion_body_milk', name: 'NIVEA Nourishing Lotion Body Milk (400 ml)', brand: 'Nivea', category: 'Body lotion', group: 'Body Care',
    priceInr: 473, tier: 'Budget', usage: 'Body',
    tags: ['hydration', 'antioxidant'], profileKeys: ['hydration', 'texture'], suitableSkin: ['all'],
    actives: ['Almond oil', 'Hyaluronic acid', 'Vitamin E', 'Glycerin'], keyIngredient: 'Almond oil',
    blurb: 'Deeply nourishes parched, very dry skin with 72h moisturization. Non-greasy formula that leaves skin soft and smooth.',
    image: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/resize-w:540/1018270/FKuC3hpIpo-1018270-1.jpg',
    imageAlt: 'https://assets.beiersdorf.com/-/media/images/8/c/b/0/c0cbadf7196844ababc82643b8d2a8d5-web_1010x1180_transparent_png.png?mh=1200&mw=1200&ctx=IN',
    productUrl: 'https://www.nivea.in/products/nivea-nourishing-lotion-body-milk-40058087252980213.html' },
  { id: 'bp_cetaphil_moisturising_lotion', name: 'Cetaphil Moisturising Lotion (250 ml)', brand: 'Cetaphil', category: 'Body lotion', group: 'Body Care',
    priceInr: 710, tier: 'Mid-range', usage: 'Body',
    tags: ['hydration', 'antioxidant', 'soothing'], profileKeys: ['hydration', 'redness'], suitableSkin: ['all'],
    actives: ['Glycerin', 'Macadamia nut oil', 'Vitamin E', 'Dimethicone'], keyIngredient: 'Glycerin',
    blurb: 'Dermatologist-recommended lightweight lotion that provides lasting hydration for sensitive skin. Non-comedogenic, fragrance-free and fast-absorbing.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/9/e/9ed9f93NYCETA0000007_1.jpg',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/1059239/4Fw0I9HCFa-1059239-1.jpg',
    productUrl: 'https://www.nykaa.com/cetaphil-moisturising-lotion-for-dry-to-normal-sensitive-skin/p/12999624' },
  { id: 'bp_forest_essentials_ultra_rich_body_milk_india', name: 'Forest Essentials Ultra Rich Body Milk - Indian Rose Absolute (200 ml)', brand: 'Forest Essentials', category: 'Body lotion', group: 'Body Care',
    priceInr: 2095, tier: 'Premium', usage: 'Body',
    tags: [], profileKeys: ['hydration'], suitableSkin: ['all'],
    actives: ['Indian rose absolute', 'Cold-pressed sweet almond oil', 'Wheatgerm oil'], keyIngredient: 'Indian rose absolute',
    blurb: 'Luxurious Ayurvedic body milk that intensely nourishes and softens skin while leaving a delicate rose fragrance. Rich yet quickly absorbed for a silky finish.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/7/7/777dd128904153307608_1.jpg',
    imageAlt: 'https://www.distacart.com/cdn/shop/products/It70949fWV_600x.jpg?v=1613914781',
    productUrl: 'https://www.nykaa.com/forest-essentials-ultra-rich-dazzling-body-lotion-indian-rose-absolute-config/p/304727' },
  { id: 'bp_dove_deeply_nourishing_body_wash', name: 'Dove Deeply Nourishing Body Wash (300 ml)', brand: 'Dove', category: 'Body wash', group: 'Body Care',
    priceInr: 195, tier: 'Budget', usage: 'Body',
    tags: ['hydration'], profileKeys: ['hydration', 'texture'], suitableSkin: ['all'],
    actives: ['Triple Hydration Serum', 'NutriumMoisture technology', 'Glycerin'], keyIngredient: 'Triple Hydration Serum',
    blurb: 'Cleans like soap while moisturising like a cream, giving up to 24 hours of hydration. Leaves dry skin feeling softer and smoother after every shower.',
    image: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/x-M_ABNSeg-1117579_1.jpg',
    imageAlt: 'https://media6.ppl-media.com/tr:h-750,w-750,c-at_max,dpr-2,q-40/static/img/product/413194/dove-deeply-nourishing-body-wash-250-ml-15-56-11-23-65-72_1_display_1753856591_873fa0ef.jpg',
    productUrl: 'https://www.dove-india.com/collections/body-wash-and-shower-gel/products/dove-nourishing-body-wash-with-triple-hydration-serum' },
  { id: 'bp_sebamed_liquid_face_body_wash', name: 'Sebamed Liquid Face & Body Wash (200 ml)', brand: 'Sebamed', category: 'Body wash', group: 'Body Care',
    priceInr: 567, tier: 'Mid-range', usage: 'Body',
    tags: ['barrier', 'soothing'], profileKeys: ['redness'], suitableSkin: ['all'],
    actives: ['Soap-free pH 5.5 formula', 'Amino-acid based cleansers', 'Pentavitin'], keyIngredient: 'Soap-free pH 5.5 formula',
    blurb: 'Soap-free and alkali-free wash at skin-friendly pH 5.5 that protects the skin barrier while cleansing. Ideal for sensitive and problem-prone skin.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/7/0/70cacb6SB_4103040895479_1.jpg',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/21020/VRhWPt-aOt-4103040895479_1.jpg',
    productUrl: 'https://www.nykaa.com/sebamed-liquid-face-body-wash/p/4722' },
  { id: 'bp_l_occitane_almond_softening_shower_oil', name: 'L\'Occitane Almond Softening Shower Oil (250 ml)', brand: 'L\'Occitane', category: 'Body wash', group: 'Body Care',
    priceInr: 2650, tier: 'Premium', usage: 'Body',
    tags: ['barrier'], profileKeys: ['redness'], suitableSkin: ['all'],
    actives: ['Sweet almond oil from Provence', 'Nourishing plant oils'], keyIngredient: 'Sweet almond oil from Provence',
    blurb: 'Oil-to-foam cleanser that transforms into a delicate foam on contact with water, cleansing without stripping the skin\'s natural barrier. Deeply nourishes with a subtle almond scent.',
    image: 'https://in.loccitane.com/cdn/shop/files/29HD250A26_RECT_RVB.png?v=1777278919',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/5t4OwT-tm2-1043261_1.jpg',
    productUrl: 'https://in.loccitane.com/products/almond-shower-oil-nourishes-skin-bestseller' },
  { id: 'bp_mcaffeine_naked_raw_coffee_body_scrub', name: 'mCaffeine Naked & Raw Coffee Body Scrub (100 g)', brand: 'mCaffeine', category: 'Body scrub', group: 'Body Care',
    priceInr: 449, tier: 'Budget', usage: 'Body',
    tags: [], profileKeys: ['texture'], suitableSkin: ['all'],
    actives: ['Pure Arabica coffee', 'Caffeine', 'Coconut oil'], keyIngredient: 'Pure Arabica coffee',
    blurb: 'Removes tan and gently exfoliates dead skin with coffee and coconut oil, polishing rough areas like elbows and knees. Helps prevent ingrown hair.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/1/1/1185643NYKMCF0000002_01.jpg',
    imageAlt: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/959541/9-D_vM7Cyy-959541_1.jpg',
    productUrl: 'https://www.mcaffeine.com/products/naked-raw-coffee-body-scrub-with-coconut' },
  { id: 'bp_plum_bodylovin_vanilla_vibes_sugar_body_scru', name: 'Plum BodyLovin\' Vanilla Vibes Sugar Body Scrub (200 g)', brand: 'Plum', category: 'Body scrub', group: 'Body Care',
    priceInr: 550, tier: 'Mid-range', usage: 'Body',
    tags: ['hydration'], profileKeys: ['hydration', 'texture'], suitableSkin: ['all'],
    actives: ['Sugar crystals', 'Kokum butter', 'Shea butter', 'Vanilla extract'], keyIngredient: 'Sugar crystals',
    blurb: 'Sugar-based scrub that exfoliates dead skin, unclogs pores and removes tan without over-drying. Kokum and shea butters moisturise while leaving a warm vanilla fragrance.',
    image: 'https://plumgoodness.com/cdn/shop/files/2U4A7502.jpg?v=1719216324&width=1024',
    imageAlt: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/7/a/7a5dadf8906118410774_1007231.jpg',
    productUrl: 'https://plumgoodness.com/products/vanilla-vibes-sugar-body-scrub' },
  { id: 'bp_forest_essentials_body_polisher_sandalwood_t', name: 'Forest Essentials Body Polisher Sandalwood & Turmeric (200 g)', brand: 'Forest Essentials', category: 'Body scrub', group: 'Body Care',
    priceInr: 2495, tier: 'Premium', usage: 'Body',
    tags: ['brightening'], profileKeys: ['texture'], suitableSkin: ['all'],
    actives: ['Sandalwood', 'Turmeric', 'Ayurvedic herb infusions'], keyIngredient: 'Sandalwood',
    blurb: 'Traditional Ayurvedic ubtan-style body polisher that exfoliates and brightens while helping remove tan. Leaves skin smooth, radiant and delicately fragranced.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/7/7/77c5e3cFORES00000218_1.jpg',
    imageAlt: 'https://www.distacart.com/cdn/shop/products/0MEoHIfiJB_600x.jpg?v=1755083740',
    productUrl: 'https://www.nykaa.com/forest-essentials-body-polisher-sandalwood-turmeric/p/4226908' },
  { id: 'bp_plum_bodylovin_vanilla_vibes_hand_cream', name: 'Plum BodyLovin\' Vanilla Vibes Hand Cream (30 g)', brand: 'Plum', category: 'Hand cream', group: 'Body Care',
    priceInr: 275, tier: 'Budget', usage: 'Body',
    tags: ['hydration', 'brightening'], profileKeys: ['hydration'], suitableSkin: ['all'],
    actives: ['Shea butter', 'Brazil nut seed oil', 'Sunflower seed oil', 'Niacinamide'], keyIngredient: 'Shea butter',
    blurb: 'Ultra-moisturising yet non-greasy hand cream that absorbs quickly and deeply hydrates. Travel-friendly tube with a warm vanilla fragrance; vegan and cruelty-free.',
    image: 'https://plumgoodness.com/cdn/shop/files/1_2f167742-8608-464c-933a-c1a6f0f13a5b.jpg?v=1745408284&width=1080',
    imageAlt: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/0/d/0d753cfPLUMX00001071n_1.jpg',
    productUrl: 'https://plumgoodness.com/products/vanilla-vibes-hand-cream-by-plum-body-lovin' },
  { id: 'bp_l_occitane_shea_butter_hand_cream', name: 'L\'Occitane Shea Butter Hand Cream (30 ml)', brand: 'L\'Occitane', category: 'Hand cream', group: 'Body Care',
    priceInr: 1050, tier: 'Mid-range', usage: 'Body',
    tags: ['hydration'], profileKeys: ['hydration', 'texture'], suitableSkin: ['all'],
    actives: ['20% organic shea butter', 'Honey', 'Almond extracts', 'Coconut oil'], keyIngredient: '20% organic shea butter',
    blurb: 'Iconic hand cream with 20% organic shea butter that protects, nourishes and moisturises dry hands. Leaves hands soft and smooth with no oily residue.',
    image: 'https://in.loccitane.com/cdn/shop/files/1023PNG-01MA030K26_RECT_RVB.png?v=1767347818',
    imageAlt: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/0/c/0c1f50401MA030K16_r1.jpg',
    productUrl: 'https://in.loccitane.com/products/shea-butter-hand-cream-30ml' },
  { id: 'bp_the_body_shop_hemp_hand_protector', name: 'The Body Shop Hemp Hand Protector (100 ml)', brand: 'The Body Shop', category: 'Hand cream', group: 'Body Care',
    priceInr: 1695, tier: 'Premium', usage: 'Body',
    tags: ['hydration'], profileKeys: ['hydration'], suitableSkin: ['all'],
    actives: ['Cold-pressed hemp seed oil', 'Hydrating emollients'], keyIngredient: 'Cold-pressed hemp seed oil',
    blurb: 'Hard-working 24hr hydration for ultra-dry hands, with nourishment lasting up to 96 hours. Rich but non-greasy cream that leaves hands noticeably softer.',
    image: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/1105380/QjTE_NcbKP-1105380_1.jpg',
    imageAlt: 'https://media.thebodyshop.in/media/catalog/product/1/0/1025247_hemp_hand_protector_30ml_brnz_nw_inaehps050_-_copy_anggfeaej9om0bke.jpg',
    productUrl: 'https://www.thebodyshop.in/hemp-hand-protector-100ml/p/p150002' },
  { id: 'bp_vaseline_lip_tins_rosy_lips', name: 'Vaseline Lip Tins - Rosy Lips (17 g)', brand: 'Vaseline', category: 'Lip balm', group: 'Body Care',
    priceInr: 236, tier: 'Budget', usage: 'Body',
    tags: ['hydration'], profileKeys: ['hydration'], suitableSkin: ['all'],
    actives: ['100% pure petroleum jelly', 'Rose oil', 'Almond oil'], keyIngredient: '100% pure petroleum jelly',
    blurb: 'Locks in moisture to heal dry, chapped lips while adding a subtle rosy tint and sheen. Classic pocket-friendly tin for everyday lip care.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/8/a/8aa8d8fVASEL00000022_1.jpg',
    imageAlt: 'https://media6.ppl-media.com/tr:h-750,w-750,c-at_max,dpr-2,q-40/static/img/product/358648/vaseline-lip-tins-rosy-lips-17-g_5_display_1633331839_6c2eedcd.jpg',
    productUrl: 'https://www.nykaa.com/vaseline-lip-tins-rosy-lips/p/3626137' },
  { id: 'bp_laneige_lip_sleeping_mask_berry', name: 'Laneige Lip Sleeping Mask - Berry (20 g)', brand: 'Laneige', category: 'Lip balm', group: 'Body Care',
    priceInr: 1207, tier: 'Mid-range', usage: 'Body',
    tags: ['hydration', 'brightening', 'antioxidant'], profileKeys: ['hydration', 'texture'], suitableSkin: ['all'],
    actives: ['Berry Fruit Complex', 'Hyaluronic acid', 'Vitamin C'], keyIngredient: 'Berry Fruit Complex',
    blurb: 'Overnight lip mask that melts away dead skin cells and delivers intense moisture while you sleep. Wake up to smooth, supple lips with a sweet berry scent.',
    image: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/7M06p6X0u-1143613_1.jpg',
    imageAlt: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/d/2/d204539LANEI00000343_a1.jpg',
    productUrl: 'https://www.tirabeauty.com/product/laneige-lip-sleeping-mask-berry-20-g-7600099' },
  { id: 'bp_dior_addict_lip_glow_007_raspberry', name: 'Dior Addict Lip Glow - 007 Raspberry (3.2 g)', brand: 'Dior', category: 'Lip balm', group: 'Body Care',
    priceInr: 4500, tier: 'Premium', usage: 'Body',
    tags: ['hydration'], profileKeys: ['hydration'], suitableSkin: ['all'],
    actives: ['Cherry oil', 'Shea butter', '97% natural-origin formula'], keyIngredient: 'Cherry oil',
    blurb: 'Couture colour-reviving lip balm that hydrates for 24 hours and enhances lips\' natural colour with a custom rosy tint. Luxurious care with a glossy, nourished finish.',
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/f/2/f2f7800DIORX00000167_1.jpg',
    imageAlt: 'https://www.dior.com/on/demandware.static/-/Sites-master_dior/default/dwa5ad9ca6/Y0457000/Y0457000_E000000670_E01_GHC.jpg',
    productUrl: 'https://www.nykaa.com/dior-addict-lip-glow/p/2736129' },
];
